<a href="https://colab.research.google.com/github/WardaAli-00/MS-THESIS-/blob/main/THESIS_IMPLEMENTATION_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### (Baseline): Text-Only Claim Verification Pipeline

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
!pip -q install transformers torch scikit-learn pandas tqdm newspaper3k lxml_html_clean google-search-results

  Preparing metadata (setup.py) ... done
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.4/7.4 MB 75.6 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Preparing metadata (setup.py) ... done
  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.1/211.1 kB 23.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 81.5/81.5 kB 9.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 105.9/105.9 kB 12.4 MB/s eta 0:00:00
  Building wheel for tinysegmenter (setup.py) ... done
  Building wheel for google-search-results (setup.py) ... done
  Building wheel for feedfinder2 (setup.py) ... done
  Building wheel for jieba3k (setup.py) ... done
  Building wheel for sgmllib3k (setup.py) ... done

In [3]:
import os
import re
import torch
from newspaper import Article
from serpapi import GoogleSearch
from transformers import pipeline

In [4]:
device_id = 0 if torch.cuda.is_available() else -1
print("device_id:", device_id)

device_id: 0

In [5]:
!pip uninstall -y serpapi google-search-results
!pip install google-search-results==2.4.2

WARNING: Skipping serpapi as it is not installed.
Found existing installation: google_search_results 2.4.2
Uninstalling google_search_results-2.4.2:
  Successfully uninstalled google_search_results-2.4.2
Collecting google-search-results==2.4.2
  Using cached google_search_results-2.4.2-py3-none-any.whl
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from google-search-results==2.4.2) (2.32.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->google-search-results==2.4.2) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->google-search-results==2.4.2) (3.13)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->google-search-results==2.4.2) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->google-search-results==2.4.2) (2026.4.22)
Installing collected packages: google-search-results
Successfully installed google-search-results-2.4.2

In [77]:
SERPAPI_KEY = "a88883d9b8af70f3ba224fa4209127e2eb9fd800e477353f991bc6c425c65c80"

In [78]:
import os
os.environ["SERPAPI_KEY"] = "a88883d9b8af70f3ba224fa4209127e2eb9fd800e477353f991bc6c425c65c80"
SERPAPI_KEY = os.getenv("SERPAPI_KEY")

In [8]:
print("SERPAPI_KEY exists:", bool(SERPAPI_KEY))
print("SERPAPI_KEY length:", len(SERPAPI_KEY) if SERPAPI_KEY else 0)

SERPAPI_KEY exists: True
SERPAPI_KEY length: 64

In [9]:
from serpapi import GoogleSearch

params = {
    "engine": "google",
    "q": "NASA Mars water",
    "api_key": SERPAPI_KEY,
    "num": 2
}
results = GoogleSearch(params).get_dict()
print(results.keys())
print("error:", results.get("error"))
print("organic_results_count:", len(results.get("organic_results", [])))

dict_keys(['error'])
error: Your account has run out of searches.
organic_results_count: 0

In [ ]:
nli = pipeline(
    "text-classification",
    model="typeform/distilbert-base-uncased-mnli",
    return_all_scores=True,
    device=device_id
)

Loading weights:   0%|          | 0/104 [00:00<?, ?it/s]

 RETRIEVAL MODULE

In [ ]:
def is_valid_url(url: str) -> bool:
    bad_ext = (".jpg", ".jpeg", ".png", ".gif", ".webp", ".mp4", ".mp3", ".pdf")
    u = url.lower()
    if u.endswith(bad_ext):
        return False
    if "image" in u:
        return False
    return True

In [ ]:

def fetch_article_text(url: str, min_chars: int = 200, max_chars: int = 1200):
    try:
        article = Article(url)
        article.download()
        article.parse()
        text = " ".join(article.text.split())
        if len(text) < min_chars:
            return None
        return text[:max_chars]
    except Exception:
        return None

In [ ]:
def retrieve_evidence_serpapi(query: str, max_results: int = 5):
    params = {
        "engine": "google",
        "q": query,
        "api_key": SERPAPI_KEY,
        "num": max_results
    }
    results = GoogleSearch(params).get_dict()
    evidence = []
    for r in results.get("organic_results", []):
        url = r.get("link", "")
        snippet = r.get("snippet", "")
        if not url or not is_valid_url(url):
            continue
        text = fetch_article_text(url)
        # fallback to snippet if article extraction fails
        if not text and snippet and len(snippet) > 80:
            text = snippet
        if text:
            evidence.append({"text": text, "url": url})
    return evidence

CLEANING + RANKING

In [ ]:
def is_valid_evidence(text: str) -> bool:
    noise_keywords = [
        "home", "all news", "media inquiries", "campus", "podcasts", "advertisement"
    ]
    t = text.lower()
    if len(text) < 120:
        return False
    if any(k in t for k in noise_keywords):
        return False
    return True

In [ ]:
def deduplicate_evidence(evidence_list):
    seen = set()
    out = []
    for ev in evidence_list:
        key = (ev["url"], ev["text"][:200])
        if key not in seen:
            out.append(ev)
            seen.add(key)
    return out

In [ ]:
def clean_evidence(evidence_list):
    cleaned = []
    for ev in evidence_list:
        text = " ".join(ev["text"].split())
        if is_valid_evidence(text):
            cleaned.append({"text": text, "url": ev["url"]})
    return deduplicate_evidence(cleaned)

In [ ]:
def rank_by_overlap(claim: str, evidence_list):
    claim_words = set(re.findall(r"\w+", claim.lower()))
    scored = []
    for ev in evidence_list:
        ev_words = set(re.findall(r"\w+", ev["text"].lower()))
        overlap = len(claim_words.intersection(ev_words))
        scored.append((overlap, ev))
    scored.sort(key=lambda x: x[0], reverse=True)
    return [ev for _, ev in scored]

REASONING MODULE (NLI)

In [ ]:
 def nli_text_score(claim: str, evidence_list, top_k: int = 2):
    if not evidence_list:
        return {"entail": 0.0, "contra": 0.0, "neutral": 1.0, "used": 0}

    e_sum = c_sum = n_sum = 0.0
    used = 0

    for ev in evidence_list[:top_k]:
        text = ev["text"].strip()
        if len(text) < 20:
            continue

        try:
            out = nli(
                {"text": text[:400], "text_pair": claim},
                top_k=None      # ← this is the key fix
            )

            # Normalise shape
            if isinstance(out, list) and len(out) > 0:
                if isinstance(out[0], list):
                    out = out[0]

            scores = {}
            for d in out:
                if isinstance(d, dict) and "label" in d:
                    scores[d["label"].upper()] = float(d.get("score", 0.0))

            if len(scores) < 2:
                print(f"  ⚠️  Still incomplete NLI output: {scores}")
                continue

            e_sum += scores.get("ENTAILMENT",   0.0)
            c_sum += scores.get("CONTRADICTION", 0.0)
            n_sum += scores.get("NEUTRAL",       0.0)
            used  += 1

            print(f"  NLI: entail={scores.get('ENTAILMENT',0):.3f}  "
                  f"contra={scores.get('CONTRADICTION',0):.3f}  "
                  f"neutral={scores.get('NEUTRAL',0):.3f}")

        except Exception as ex:
            print(f"  NLI ERROR: {ex}")
            continue

    if used == 0:
        return {"entail": 0.0, "contra": 0.0, "neutral": 1.0, "used": 0}

    return {
        "entail":  round(e_sum / used, 4),
        "contra":  round(c_sum / used, 4),
        "neutral": round(n_sum / used, 4),
        "used":    used,
    }

EXPLANATION + CONFIDENCE

In [ ]:
def final_text_label(text_scores, margin=0.03, contra_floor=0.08, entail_floor=0.12):
    e = text_scores["entail"]
    c = text_scores["contra"]
    n = text_scores["neutral"]
    if c >= contra_floor and (c - e) >= margin:
        return "FAKE"
    elif e >= entail_floor and (e - c) >= margin:
        return "REAL"
    else:
        return "MISLEADING"

In [ ]:
def compute_confidence(nli_stats, pred_label):
    if nli_stats["used"] == 0:
        return 0.0

    e = nli_stats["entail"]
    c = nli_stats["contra"]
    n = nli_stats["neutral"]

    if pred_label == "REAL":
        return round(e * 100, 2)
    elif pred_label == "FAKE":
        return round(c * 100, 2)
    else:
        uncertainty = 1 - abs(e - c)
        return round(uncertainty * 100, 2)

In [ ]:
def generate_explanation(claim, evidence_list, label):
    if not evidence_list:
        return "No strong evidence found."
    msg = [f"Claim: {claim}", "", "Top evidence:"]
    for i, ev in enumerate(evidence_list[:2], start=1):
        msg.append(f"{i}. {ev['text'][:180]}...")
        msg.append(f"   Source: {ev['url']}")
    if label == "REAL":
        msg.append("Verdict rationale: Most evidence supports the claim.")
    elif label == "FAKE":
        msg.append("Verdict rationale: Most evidence contradicts the claim.")
    else:
        msg.append("Verdict rationale: Evidence is mixed/insufficient.")
    return "\n".join(msg)

 MAIN PIPELINE (Methodology Core)

In [ ]:
def main_pipeline(claim: str, top_k: int = 2):
    retrieved = retrieve_evidence_serpapi(claim, max_results=6)

    cleaned = clean_evidence(retrieved)
    ranked = rank_by_overlap(claim, cleaned)
    top_evidence = ranked[:top_k]
    nli_stats  = nli_text_score(claim, top_evidence, top_k)
    pred_label = final_text_label(nli_stats)
    confidence = compute_confidence(nli_stats, pred_label)
    explanation = generate_explanation(claim, top_evidence, pred_label)
    return {
        "claim": claim,
        "label": pred_label,
        "confidence": confidence,
        "nli_stats": nli_stats,
        "evidence": top_evidence,
        "explanation": explanation
    }
# quick sanity run
out = main_pipeline("NASA confirms water on Mars")
print(out["label"], out["confidence"])
print(out["explanation"][:500])

MISLEADING 100.0
Claim: NASA confirms water on Mars

Top evidence:
1. These dark, narrow, 100 meter-long streaks called recurring slope lineae flowing downhill on Mars are inferred to have been formed by contemporary flowing water. Recently, planetar...
   Source: https://www.nasa.gov/news-release/nasa-confirms-evidence-that-liquid-water-flows-on-todays-mars/
2. Using seismic activity to probe the interior of Mars, geophysicists have found evidence for a large underground reservoir of liquid water — enough to fi

### V2: MULTIMODAL VISION-RAG PIPELINE (SKELETON)

In [10]:
!pip install -q beautifulsoup4
from bs4 import BeautifulSoup

In [11]:
!pip install -q open_clip_torch sentence-transformers newspaper3k lxml_html_clean

import re
import os
import time
import torch
import requests
from PIL import Image
from io import BytesIO
from newspaper import Article
from serpapi import GoogleSearch
from transformers import pipeline as hf_pipeline
from sentence_transformers import SentenceTransformer
import open_clip

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 31.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.8/44.8 kB 4.7 MB/s eta 0:00:00

NLI model

In [12]:
nli = hf_pipeline(
    "text-classification",
    model="MoritzLaurer/DeBERTa-v3-large-mnli-fever-anli-ling-wanli",
    return_all_scores=True,
    device=device_id,
    truncation=True,
    max_length=512,
)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:93: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

config.json: 0.00B [00:00, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

model.safetensors:   0%|          | 0.00/870M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/394 [00:00<?, ?it/s]

DebertaV2ForSequenceClassification LOAD REPORT from: MoritzLaurer/DeBERTa-v3-large-mnli-fever-anli-ling-wanli
Key                             | Status     |  |
--------------------------------+------------+--+-
deberta.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

tokenizer_config.json:   0%|          | 0.00/395 [00:00<?, ?B/s]

spm.model:   0%|          | 0.00/2.46M [00:00<?, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

added_tokens.json:   0%|          | 0.00/18.0 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/156 [00:00<?, ?B/s]

Sentence Transformer

In [13]:
embed_model = SentenceTransformer("all-MiniLM-L6-v2")

print("Models loaded.")

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

Models loaded.

CLIP model

In [14]:
import open_clip
import torch
from PIL import Image

In [15]:
import torch

device_id = 0 if torch.cuda.is_available() else -1
DEVICE    = "cuda" if torch.cuda.is_available() else "cpu"
HEADERS   = {"User-Agent": "Mozilla/5.0"}

In [16]:
import torch
import open_clip
from PIL import Image

clip_model, _, clip_preprocess = open_clip.create_model_and_transforms(
    "ViT-B-32", pretrained="openai"
)
clip_model = clip_model.to(DEVICE)
clip_tokenizer = open_clip.get_tokenizer("ViT-B-32")

HEADERS = {"User-Agent": "Mozilla/5.0"}

open_clip_model.safetensors:   0%|          | 0.00/605M [00:00<?, ?B/s]

/usr/local/lib/python3.12/dist-packages/open_clip/factory.py:450: UserWarning: QuickGELU mismatch between final model config (quick_gelu=False) and pretrained tag 'openai' (quick_gelu=True).
  warnings.warn(

In [17]:
def compute_clip_score(image: Image.Image, text: str) -> float:
    try:
        image_input = clip_preprocess(image).unsqueeze(0).to(DEVICE)
        text_input  = clip_tokenizer([text]).to(DEVICE)
        with torch.no_grad():
            img_feat = clip_model.encode_image(image_input)
            txt_feat = clip_model.encode_text(text_input)
            img_feat = img_feat / img_feat.norm(dim=-1, keepdim=True)
            txt_feat = txt_feat / txt_feat.norm(dim=-1, keepdim=True)
            score    = (img_feat @ txt_feat.T).item()
        return float((score + 1) / 2)
    except Exception:
        return 0.0

DOMAINS

In [18]:
TRUSTED_DOMAINS = {
    "nasa.gov": 3.0, "nature.com": 3.0, "who.int": 3.0,
    "cdc.gov": 3.0, "nih.gov": 3.0, "sciencedirect.com": 2.8,
    "pubmed.ncbi.nlm.nih.gov": 3.0, "snopes.com": 2.8,
    "politifact.com": 2.8, "factcheck.org": 2.8, "fullfact.org": 2.8,
    "apnews.com": 2.5, "reuters.com": 2.5, "bbc.com": 2.0,
    "bbc.co.uk": 2.0, "nytimes.com": 1.8, "theguardian.com": 1.8,
    "scientificamerican.com": 2.2,
}

FACT_CHECK_DOMAINS = {
    "snopes.com", "politifact.com", "factcheck.org",
    "fullfact.org", "checkyourfact.com", "leadstories.com",
}

NOISE_DOMAINS = {
    "facebook.com", "instagram.com", "tiktok.com",
    "twitter.com", "x.com", "reddit.com",
    "freerepublic.com", "substack.com",
}

SCIENCE_KEYWORDS = {
    "boils", "melts", "freezes", "revolves", "orbits", "speed of light",
    "photosynthesis", "gravity", "electrons", "tectonic", "ozone layer",
    "heart pumps", "blood carries", "bones", "insulin regulates",
    "brain controls", "dna carries", "water cycle",
}

STOPWORDS = {
    "the","a","an","is","are","was","were","of","on","in","at","to",
    "for","and","or","not","do","does","can","it","that","this","be",
    "by","from","with","will","has","have","its","their","about",
    "also","but","so","if","as",
}

In [19]:
def get_domain(url):
    try:    return url.split("/")[2].replace("www.", "")
    except: return ""

Tweet claim cleaner

In [20]:
import re
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

def clean_tweet_claim(claim: str) -> str:
    claim = re.sub(r'http\S+', '', claim)
    claim = re.sub(r'[@#]\w+', '', claim)
    claim = re.sub(r'^RT\s+', '', claim)
    claim = re.sub(r'\s+', ' ', claim).strip()
    return claim if len(claim) > 15 else claim

In [21]:
def get_domain_boost(url: str) -> float:
    try:
        domain = url.split("/")[2].replace("www.", "")
        return TRUSTED_DOMAINS.get(domain, 0.0)
    except Exception:
        return 0.0

In [22]:
def get_domain_for_check(url: str) -> str:
    try:
        domain = url.split("/")[2].replace("www.", "")
        return domain
    except Exception:
        return ""

def is_fact_checker(url: str) -> bool:
    domain = get_domain_for_check(url)
    return domain in FACT_CHECK_DOMAINS

In [23]:
def is_health_fact(query):
    health_kws = {"causes","cancer","risk","disease","infection","bacteria",
                  "virus","vaccine","antibiotic","lung","smoking","alcohol",
                  "sugar","exercise","sleep"}
    return len(health_kws & set(re.findall(r"\w+", query.lower()))) >= 2

Embedding fallback

In [24]:
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

def embedding_stance_fallback(claim, evidence_list):
    if not evidence_list:
        return {"entail": 0.10, "contra": 0.05, "neutral": 0.85, "used": 0}
    claim_emb = embed_model.encode([claim])
    sims = [float(cosine_similarity(claim_emb, embed_model.encode([ev["text"][:300]]))[0][0])
            for ev in evidence_list[:4]]
    avg = float(np.mean(sims)) if sims else 0.5
    if avg > 0.55:   return {"entail": 0.35, "contra": 0.05, "neutral": 0.60, "used": -1}
    elif avg < 0.30: return {"entail": 0.05, "contra": 0.35, "neutral": 0.60, "used": -1}
    else:            return {"entail": 0.20, "contra": 0.15, "neutral": 0.65, "used": -1}

In [53]:
def embedding_stance_fallback(claim: str, evidence_list: list) -> dict:
    if not evidence_list:
        return {"entail": 0.1, "contra": 0.05, "neutral": 0.85, "used": 0}

    claim_emb = embed_model.encode([claim])
    sims = []
    for ev in evidence_list[:4]:
        ev_emb = embed_model.encode([ev["text"][:300]])
        sims.append(float(cosine_similarity(claim_emb, ev_emb)[0][0]))

    avg = float(np.mean(sims)) if sims else 0.5

    # More decisive thresholds
    if avg > 0.55:
        return {"entail": 0.35, "contra": 0.05, "neutral": 0.60, "used": -1}
    elif avg < 0.30:
        return {"entail": 0.05, "contra": 0.35, "neutral": 0.60, "used": -1}
    else:
        return {"entail": 0.20, "contra": 0.15, "neutral": 0.65, "used": -1}

URL filtering

In [26]:
def is_valid_url(url: str) -> bool:
    bad_ext = (".jpg", ".jpeg", ".png", ".gif", ".webp", ".mp4", ".mp3", ".pdf")
    u = url.lower()
    if any(u.endswith(e) for e in bad_ext) or "image" in u:
        return False
    # Block social media — too noisy for NLI
    domain = u.split("/")[2].replace("www.", "") if "/" in u else ""
    if any(nd in domain for nd in NOISE_DOMAINS):
        return False
    return True

In [27]:
def compute_overlap(query, text):
    q = set(re.findall(r"\w+", query.lower()))
    t = set(re.findall(r"\w+", text.lower()))
    return len(q & t) / len(q) if q else 0.0

Safe search

In [28]:
def safe_google_search(params, retries=3, sleep_sec=2):
    for attempt in range(retries):
        try:    return GoogleSearch(params).get_dict()
        except:
            if attempt < retries - 1:
                time.sleep(sleep_sec * (attempt + 1))
    return {}

Article fetch

In [29]:
import requests
from newspaper import Article

def fetch_article_text(url, min_chars=120, max_chars=2500):
    try:
        head = requests.head(url, timeout=4, headers=HEADERS, allow_redirects=True)
        if head.status_code >= 400:
            return ""
        r = requests.get(url, timeout=8, headers=HEADERS)
        if r.status_code != 200:
            return ""
        a = Article(url)
        a.set_html(r.text)
        a.parse()
        text = " ".join(a.text.split())
        if len(text) < min_chars:
            soup = BeautifulSoup(r.text, "html.parser")
            for tag in soup(["script","style","nav","footer","header"]):
                tag.decompose()
            text = " ".join(soup.get_text().split())
        return text[:max_chars] if len(text) >= min_chars else ""
    except:
        return ""

Retrieve text evidence (CORE)

In [81]:
def retrieve_from_query(query: str, max_results: int = 5) -> list:

    params = {
        "engine":  "google",
        "q":       query,
        "api_key": SERPAPI_KEY,
        "num":     max_results,
    }
    res = safe_google_search(params)
    raw = []

    for r in res.get("organic_results", []):
        url     = r.get("link", "")
        snippet = r.get("snippet", "")
        if not url or not is_valid_url(url):
            continue
        if "reddit.com" in url:
            continue
        if any(str(y) in url for y in ["2014", "2015", "2016", "2017", "2018"]):
            continue

        text = fetch_article_text(url)
        if not text:
            text = snippet

        if text and len(text) >= 40:
            low = text.lower()
            if "login" in low or "subscribe" in low:
                continue
            raw.append({"text": text, "url": url, "is_fact_check": is_fact_checker(url)})

    # Score: 50% keyword overlap + 30% length + 20% domain trust
    scored = []
    for ev in raw:
        overlap      = compute_overlap(query, ev["text"])
        domain_boost = get_domain_boost(ev["url"])
        score        = 0.5 * overlap + 0.3 * (len(ev["text"]) / 2500) + 0.2 * domain_boost
        scored.append((score, ev))

    scored.sort(key=lambda x: x[0], reverse=True)
    return [x[1] for x in scored[10:max_results]]

In [58]:
def retrieve_fact_checks(query: str, max_results: int = 3) -> list:
    STOPWORDS = {"the","a","an","is","are","was","were","of","on","in",
                 "at","to","for","and","or","not","do","does","can","it",
                 "that","this","be","by","from","with","will","has","have"}

    content_words = [
        w for w in re.findall(r"\w+", query.lower())
        if w not in STOPWORDS and len(w) > 2
    ]

    # Scale threshold: 2 words in claim → need 2 matches, 4+ words → need 3
    min_matches = 1

    search_terms = " ".join(content_words[:4])
    fc_sites = (
        "site:snopes.com OR site:politifact.com OR "
        "site:factcheck.org OR site:fullfact.org"
    )
    search_q = f"{search_terms} {fc_sites}"

    params = {
        "engine":  "google",
        "q":       search_q,
        "api_key": SERPAPI_KEY,
        "num":     max_results + 4,
    }
    res = safe_google_search(params)
    raw = []

    for r in res.get("organic_results", []):
        url     = r.get("link", "")
        snippet = r.get("snippet", "")
        title   = r.get("title", "")
        if not url or not is_valid_url(url):
            continue

        combined     = (snippet + " " + title).lower()
        combo_words  = set(re.findall(r"\w+", combined))
        matches      = [w for w in content_words if w in combo_words]

        if len(matches) < min_matches:
            print(f"  [FC SKIP] only {len(matches)} matches (need {min_matches}): {url[:60]}")
            continue

        text = fetch_article_text(url, min_chars=80, max_chars=2000)
        if not text:
            text = snippet   # fall back to snippet — better than nothing

        if text and len(text) >= 40:
            raw.append({
                "text":          text,
                "url":           url,
                "is_fact_check": True,
            })

    return raw[:max_results]

In [54]:
def fetch_article_text(url: str, min_chars: int = 120, max_chars: int = 2500) -> str:
    try:

        head = requests.head(url, timeout=4, headers=HEADERS, allow_redirects=True)
        if head.status_code >= 400:
            return ""

        response = requests.get(url, timeout=8, headers=HEADERS)
        if response.status_code != 200:
            return ""

        a = Article(url)
        a.set_html(response.text)
        a.parse()
        text = " ".join(a.text.split())

        if len(text) < min_chars:
            from bs4 import BeautifulSoup
            soup = BeautifulSoup(response.text, "html.parser")
            for tag in soup(["script","style","nav","footer","header"]):
                tag.decompose()
            text = " ".join(soup.get_text().split())

        return text[:max_chars] if len(text) >= min_chars else ""

    except Exception:
        return ""

In [33]:
def build_search_query(claim: str) -> str:
    #  basic tweet cleaning
    text = re.sub(r'http\S+', '', claim)
    text = re.sub(r'[@#]\w+', '', text)
    text = re.sub(r'^RT\s+', '', text)
    text = re.sub(r'\s+', ' ', text).strip()

    #  remove incomplete trailing word
    words = text.split()
    if words and len(words[-1]) < 4:
        words = words[:-1]
    text = ' '.join(words)

    # extract content words
    content = [w for w in re.findall(r'\w+', text.lower())
               if w not in STOPWORDS and len(w) > 3]

    # return best 5-6 word query
    if len(content) >= 4:
        return ' '.join(content[:6])
    return text if len(text) > 15 else claim

In [55]:
SCIENCE_DOMAINS = [
    "cdc.gov", "nih.gov", "who.int", "cancer.org", "cancer.gov",
    "pubmed.ncbi.nlm.nih.gov", "mayoclinic.org", "nhs.uk",
    "nasa.gov", "noaa.gov", "usgs.gov",
]

def is_pure_science(query: str) -> bool:
    q = query.lower()
    return any(kw in q for kw in SCIENCE_KEYWORDS)

def retrieve_all_evidence(query: str, use_fact_checks: bool = True) -> list:
    web_ev = retrieve_from_query(query, max_results=6)

    if not use_fact_checks or is_pure_science(query):
        print(f"  [FC SKIP] Pure science claim — using web evidence only")
        return web_ev

    if is_health_fact(query):
        health_sites = "site:cdc.gov OR site:nih.gov OR site:cancer.org OR site:who.int OR site:mayoclinic.org"
        params = {
            "engine":  "google",
            "q":       f"{query} {health_sites}",
            "api_key": SERPAPI_KEY,
            "num":     3,
        }
        res = safe_google_search(params)
        health_ev = []
        for r in res.get("organic_results", []):
            url     = r.get("link", "")
            snippet = r.get("snippet", "")
            if not url or not is_valid_url(url):
                continue
            text = fetch_article_text(url, min_chars=80, max_chars=2000)
            if not text:
                text = snippet
            if text and len(text) >= 40:
                health_ev.append({
                    "text":          text,
                    "url":           url,
                    "is_fact_check": False,
                    "domain_boost":  3.0,
                })

        seen  = set()
        merged = []
        for ev in health_ev + web_ev:
            if ev["url"] not in seen:
                seen.add(ev["url"])
                merged.append(ev)
        return merged

    fc_ev  = retrieve_fact_checks(query, max_results=3)
    seen   = set()
    merged = []
    for ev in fc_ev + web_ev:
        if ev["url"] not in seen:
            seen.add(ev["url"])
            merged.append(ev)
    return merged

In [34]:
def rank_by_overlap_and_trust(claim: str, evidence_list: list) -> list:
    claim_words = set(claim.lower().split())
    scored = []
    for ev in evidence_list:
        ev_words     = set(ev["text"].lower().split())
        overlap      = len(claim_words & ev_words)
        domain_boost = get_domain_boost(ev["url"])
        fc_bonus     = 2.0 if ev.get("is_fact_check") else 0.0
        score        = overlap + domain_boost + fc_bonus
        scored.append((score, ev))
    scored.sort(key=lambda x: x[0], reverse=True)
    return [x[1] for x in scored]

In [35]:
def deduplicate_evidence(evidence_list: list) -> list:
    seen = set()
    out  = []
    for ev in evidence_list:
        key = (ev["url"], ev["text"][:200])
        if key not in seen:
            seen.add(key)
            out.append(ev)
    return out

CLEANING + SENTENCE SELECTION

In [36]:
def select_best_evidence_passages(claim: str, evidence_list: list, top_k: int = 3) -> list:

    claim_words = set(re.findall(r"\w+", claim.lower()))
    scored      = []

    for ev in evidence_list:
        text        = ev["text"]
        ev_words    = set(re.findall(r"\w+", text.lower()))
        kw_score    = len(claim_words & ev_words)
        trust_score = get_domain_boost(ev["url"])
        fc_bonus    = 3.0 if ev.get("is_fact_check") else 0.0
        total_score = kw_score + trust_score + fc_bonus

        # Truncate to 600 chars at a sentence boundary
        truncated = text[:600]
        last_period = truncated.rfind(".")
        if last_period > 300:
            truncated = truncated[:last_period + 1]

        scored.append((total_score, {
            "text":          truncated,
            "url":           ev["url"],
            "is_fact_check": ev.get("is_fact_check", False),
        }))

    scored.sort(key=lambda x: x[0], reverse=True)
    top = [x[1] for x in scored[:top_k]]

    if not top and evidence_list:
        top = [{"text": ev["text"][:600], "url": ev["url"],
                "is_fact_check": ev.get("is_fact_check", False)}
               for ev in evidence_list[:top_k]]
    return top

In [37]:
def clean_text_evidence(evidence_list: list) -> list:
    return [ev for ev in evidence_list
            if len(" ".join(ev["text"].split())) > 50]

In [38]:
def split_sentences(text: str):
    return [s.strip() for s in re.split(r"(?<=[.!?])\s+", text) if len(s) > 30]

In [ ]:
def select_best_sentences(claim: str, evidence_list, top_k: int = 2):
    claim_words = set(re.findall(r"\w+", claim.lower()))
    scored = []

    for ev in evidence_list:
        text = ev["text"]
        ev_words = set(re.findall(r"\w+", text.lower()))
        score = len(claim_words & ev_words) + get_domain_boost(ev["url"])
        # Keep full passage — NLI needs context, not isolated fragments
        scored.append((score, {"text": text[:500], "url": ev["url"]}))

    scored.sort(key=lambda x: x[0], reverse=True)
    top = [x[1] for x in scored[:top_k]]

    if not top and evidence_list:
        top = [{"text": ev["text"][:500], "url": ev["url"]}
               for ev in evidence_list[:top_k]]
    return top

NLI MODULE

In [39]:
def safe_truncate(text, max_words=200):
    if not text:
        return ""
    return " ".join(text.split()[:max_words])

In [40]:
def fc_article_is_relevant(claim: str, ev: dict, min_shared: int = 2) -> bool:

    claim_words = set(re.findall(r"\w+", claim.lower())) - STOPWORDS
    url_words  = set(re.findall(r"\w+", ev["url"].lower()))
    text_words = set(re.findall(r"\w+", ev["text"][:200].lower()))
    combined   = url_words | text_words

    shared = len(claim_words & combined)
    return shared >= min_shared

In [41]:
def nli_text_score_v2(claim: str, evidence_list: list, top_k: int = 4) -> dict:
    if not evidence_list:
        return {"entail": 0.0, "contra": 0.0, "neutral": 1.0, "used": 0}

    STOPWORDS = {"the","a","an","is","are","was","were","of","on","in",
                 "at","to","for","and","or","not","do","does","can","it",
                 "that","this","be","by","from","with","will","has","have"}
    content_words = set(re.findall(r"\w+", claim.lower())) - STOPWORDS
    min_overlap   = 1 if len(content_words) <= 4 else 2

    e_sum = c_sum = n_sum = weight_sum = 0.0

    for ev in evidence_list[:top_k]:
        text = ev["text"].strip()
        if len(text) < 20:
           continue

        # skip FC articles that are clearly about a different topic
        if ev.get("is_fact_check") and not fc_article_is_relevant(claim, ev):
             print(f"  [FC REJECT] off-topic article: {ev['url'][:60]}")
             continue

        try:
            out = nli({"text": text[:500], "text_pair": claim}, top_k=None)
            if isinstance(out, list) and isinstance(out[0], list):
                out = out[0]
            scores = {}
            for d in out:
                lbl = d["label"].upper()
                if "ENTAIL" in lbl:
                    scores["ENTAILMENT"]    = float(d["score"])
                elif "CONTRADICT" in lbl:
                    scores["CONTRADICTION"] = float(d["score"])
                elif "NEUTRAL" in lbl:
                    scores["NEUTRAL"]       = float(d["score"])
            if len(scores) < 2:
                continue
            w = 3.0 if ev.get("is_fact_check") else 1.0
            MAX_SINGLE = 0.90
            e_sum      += min(scores.get("ENTAILMENT",    0.0), MAX_SINGLE) * w
            c_sum      += min(scores.get("CONTRADICTION", 0.0), MAX_SINGLE) * w
            n_sum      += scores.get("NEUTRAL",       0.0) * w
            weight_sum += w
            print(f"  NLI {'[FC]' if ev.get('is_fact_check') else '    '}: "
                  f"e={scores.get('ENTAILMENT',0):.3f}  "
                  f"c={scores.get('CONTRADICTION',0):.3f}  "
                  f"src={ev['url'][:50]}")
        except Exception as ex:
            print(f"  NLI ERROR: {ex}")

    if weight_sum == 0:
        print("  [FALLBACK] Using embedding similarity")
        return embedding_stance_fallback(claim, evidence_list)

    return {
        "entail":  round(e_sum / weight_sum, 4),
        "contra":  round(c_sum / weight_sum, 4),
        "neutral": round(n_sum / weight_sum, 4),
        "used":    int(weight_sum),
    }

In [42]:
def normalize_nli_scores(scores):
    total = scores["entail"] + scores["contra"] + scores["neutral"]
    if total == 0:
        return scores

    return {
        "entail": scores["entail"] / total,
        "contra": scores["contra"] / total,
        "neutral": scores["neutral"] / total,
        "used": scores["used"]
    }

IMAGE MODULE

In [43]:
def retrieve_image_urls(query, max_results=3):
    params = {
        "engine": "google_images",
        "q": query,
        "api_key": SERPAPI_KEY,
        "num": max_results
    }

    res = GoogleSearch(params).get_dict()

    return [
        r.get("original")
        for r in res.get("images_results", [])
        if r.get("original")
    ]

Load image

In [44]:
def load_image_from_path_or_url(image_input: str, save_dir="/content", timeout=20):
    if image_input is None:
        return None, None, "no_image"
    image_input = str(image_input).strip()
    if image_input.startswith("http://") or image_input.startswith("https://"):
        try:
            r   = requests.get(image_input, timeout=timeout, headers=HEADERS)
            r.raise_for_status()
            img = Image.open(BytesIO(r.content)).convert("RGB")
            img.thumbnail((1024, 1024))
            os.makedirs(save_dir, exist_ok=True)
            local_path = os.path.join(save_dir, "tmp_claim_image.jpg")
            img.save(local_path)
            return img, local_path, "url_ok"
        except Exception as ex:
            return None, None, f"url_failed: {ex}"
    try:
        img = Image.open(image_input).convert("RGB")
        img.thumbnail((1024, 1024))
        return img, image_input, "local_ok"
    except Exception as ex:
        return None, None, f"local_failed: {ex}"

In [45]:
def get_image_for_claim(claim, image_path=None):
    if image_path is not None:
        return image_path

    urls = retrieve_image_urls(claim, max_results=3)
    return urls

In [46]:
def load_image_safe(image_source):
    if image_source is None:
        return None
    try:
        if str(image_source).startswith("http"):
            r = requests.get(image_source, timeout=10, headers=HEADERS)
            return Image.open(BytesIO(r.content)).convert("RGB")
        return Image.open(image_source).convert("RGB")
    except Exception:
        return None

Score images

In [47]:
def score_images_against_claim(claim, image_urls):
    scores = []

    for url in image_urls:
        img = load_image_from_url(url)
        if img is None:
            continue

        sim = compute_clip_score(img, claim)
        scores.append({
            "url": url,
            "score": sim
        })

    scores.sort(key=lambda x: x["score"], reverse=True)
    return scores

OCR BRANCH

In [48]:
def run_ocr(image_path: str) -> str:
    try:
        result = ocr_reader.readtext(image_path, detail=0)
        return " ".join(result).strip()
    except Exception:
        return ""

In [49]:
def ocr_text_claim_alignment_score(claim: str, ocr_text: str) -> float:
    if not ocr_text:
        return 0.0
    c_words = set(re.findall(r"\w+", claim.lower()))
    o_words = set(re.findall(r"\w+", ocr_text.lower()))
    union   = len(c_words | o_words)
    return len(c_words & o_words) / union if union > 0 else 0.0

FUSION + DECISION

In [86]:
def fuse_multimodal_scores(
    text_scores: dict,
    clip_sim:    float,
    ocr_align:   float,
    ocr_text:    str  = "",
    mode:        str  = "text_clip_ocr",
    image_was_loaded: bool = False,   # ADD THIS PARAMETER
) -> dict:
    mode     = mode.lower().strip()
    ocr_text = str(ocr_text) if ocr_text is not None else ""

    # Now uses parameter, not global
    if image_was_loaded and clip_sim != 0.0:
        clip_norm = max(0.0, min(1.0, (clip_sim + 1.0) / 2.0))
    else:
        clip_norm = 0.0

    ocr_norm        = max(0.0, min(1.0, ocr_align))
    entail          = text_scores.get("entail",  0.0)
    contra          = text_scores.get("contra",  0.0)
    neutral         = text_scores.get("neutral", 0.0)
    ocr_has_content = len(ocr_text.strip()) > 10
    mode            = mode.lower().strip()

    if mode == "text_only":
        fused_support = entail
        fused_contra  = contra
        fused_mixed   = neutral + min(entail, contra)
        weights       = {"w_text": 1.0, "w_clip": 0.0, "w_ocr": 0.0}

    elif mode == "text_clip":
        if image_was_loaded and clip_norm > 0:
            w_text, w_clip = 0.85, 0.15
        else:
            w_text, w_clip = 1.0, 0.0
        fused_support = w_text * entail + w_clip * clip_norm * entail
        fused_contra  = w_text * contra + w_clip * (1 - clip_norm) * contra
        fused_mixed   = w_text * (neutral + min(entail, contra))
        weights       = {"w_text": w_text, "w_clip": w_clip, "w_ocr": 0.0}

    else:  # text_clip_ocr
        if image_was_loaded and clip_norm > 0 and ocr_has_content:
            w_text, w_clip, w_ocr = 0.70, 0.15, 0.15
        elif image_was_loaded and clip_norm > 0:
            w_text, w_clip, w_ocr = 0.85, 0.15, 0.0
        else:
            w_text, w_clip, w_ocr = 1.0, 0.0, 0.0
            ocr_norm = 0.0

        fused_support = w_text * entail + w_clip * clip_norm * entail + w_ocr * ocr_norm * entail
        fused_contra  = w_text * contra + w_clip * (1 - clip_norm) * contra + w_ocr * (1 - ocr_norm) * contra
        fused_mixed   = w_text * (neutral + min(entail, contra))
        weights       = {"w_text": w_text, "w_clip": w_clip, "w_ocr": w_ocr}

    return {
        "fused_support": float(fused_support),
        "fused_contra":  float(fused_contra),
        "fused_mixed":   float(fused_mixed),
        "clip_norm":     float(clip_norm),
        "ocr_norm":      float(ocr_norm),
        "ocr_used":      ocr_has_content,
        "weights":       weights,
    }

In [87]:
def final_label_v2(fused, binary_dataset=True):
    support = fused["fused_support"]
    contra  = fused["fused_contra"]

    if binary_dataset:
        MIN_SIGNAL = 0.05
        if support < MIN_SIGNAL and contra < MIN_SIGNAL:
            return "FAKE"
        if support > contra * 1.4 and support >= 0.08:
            return "REAL"
        return "FAKE"

    if contra >= 0.22 and (contra - support) >= 0.05: return "FAKE"
    if support >= 0.18 and (support - contra) >= 0.05: return "REAL"
    return "MISLEADING"

In [51]:
def final_multimodal_label(
    fused:      dict,
    support_th: float = 0.30,
    contra_th:  float = 0.35,
    margin:     float = 0.08,
) -> str:
    support = fused["fused_support"]
    contra  = fused["fused_contra"]
    both_present = support > 0.12 and contra > 0.12
    if both_present and abs(support - contra) < margin * 1.5:
        return "MISLEADING"

    if contra >= contra_th and (contra - support) >= margin:
        return "FAKE"

    if support >= support_th and (support - contra) >= margin:
        return "REAL"

    return "MISLEADING"

EXPLANATION

In [52]:
def generate_explanation(claim, evidence_list, fused, label, text_scores):
    """
    Human-readable reasoning generator for thesis-quality output.
    """

    entail = text_scores.get("entail", 0.0)
    contra = text_scores.get("contra", 0.0)
    neutral = text_scores.get("neutral", 0.0)

    # -----------------------------
    # 1. Evidence summary
    # -----------------------------
    supporting = []
    contradicting = []
    neutral_ev = []

    for ev in evidence_list[:5]:
        text = ev["text"][:200]
        url = ev.get("url", "")

        # simple heuristic (you can later replace with NLI per evidence)
        if "nasa" in text.lower() or "confirms" in text.lower():
            supporting.append(f"{text} ({url})")
        elif "false" in text.lower() or "debunk" in text.lower() or "no evidence" in text.lower():
            contradicting.append(f"{text} ({url})")
        else:
            neutral_ev.append(f"{text} ({url})")

    # -----------------------------
    # 2. Build reasoning text
    # -----------------------------
    explanation = []

    explanation.append(f"Claim Analysis: {claim}\n")

    # Label reasoning
    if label == "REAL":
        explanation.append(
            "Verdict: REAL\n"
            "The evidence overall supports the claim across multiple reliable sources."
        )

    elif label == "FAKE":
        explanation.append(
            "Verdict: FAKE\n"
            "The evidence strongly contradicts the claim across multiple sources."
        )

    else:
        explanation.append(
            "Verdict: MISLEADING\n"
            "The evidence is mixed, with both supporting and contradicting signals."
        )

    # -----------------------------
    # 3. Evidence breakdown
    # -----------------------------
    explanation.append("\nEvidence Breakdown:")

    if supporting:
        explanation.append("\nSupporting Evidence:")
        for s in supporting[:3]:
            explanation.append(f"- {s}")

    if contradicting:
        explanation.append("\nContradicting Evidence:")
        for c in contradicting[:3]:
            explanation.append(f"- {c}")

    if neutral_ev:
        explanation.append("\nNeutral / Irrelevant Evidence:")
        for n in neutral_ev[:2]:
            explanation.append(f"- {n}")

    # -----------------------------
    # 4. Score interpretation
    # -----------------------------
    explanation.append("\nModel Scores:")
    explanation.append(
        f"- Entailment: {entail:.3f}\n"
        f"- Contradiction: {contra:.3f}\n"
        f"- Neutral: {neutral:.3f}"
    )

    # -----------------------------
    # 5. Final interpretation
    # -----------------------------
    explanation.append("\nFinal Interpretation:")

    if contra > entail:
        explanation.append(
            "The contradiction signal is stronger than support, "
            "leading to a FAKE classification."
        )
    elif entail > contra:
        explanation.append(
            "The support signal is stronger than contradiction, "
            "leading to a REAL classification."
        )
    else:
        explanation.append(
            "Signals are balanced, leading to a MISLEADING classification."
        )

    return "\n".join(explanation)

images from URLs

In [ ]:
import requests
from PIL import Image
from io import BytesIO

def download_image_from_url(image_url, save_path="/content/query_image.jpg"):
    r = requests.get(image_url, timeout=20)
    r.raise_for_status()
    img = Image.open(BytesIO(r.content)).convert("RGB")
    img.save(save_path)
    return save_path

In [ ]:
def normalize_claim(claim):
    if isinstance(claim, str):
        return claim
    if isinstance(claim, list):
        if not claim:
            return ""
        if isinstance(claim[0], dict):
            return claim[0].get("claim") or claim[0].get("text", "")
        return " ".join(str(x) for x in claim)
    if isinstance(claim, dict):
        return claim.get("claim") or claim.get("text") or str(claim)
    return str(claim)

MAIN MULTIMODAL PIPELINE

In [60]:
def main_pipeline_v2(
    claim:          str,
    image_path:     str  = None,
    top_k_text:     int  = 4,
    mode:           str  = "text_clip_ocr",
    use_fact_checks:bool = True,
    binary_dataset: bool = True,
) -> dict:

    # Fix 3: clean tweet noise before searching
    search_query = clean_tweet_claim(claim)

    # Text branch
    retrieved = retrieve_all_evidence(search_query, use_fact_checks=use_fact_checks)
    deduped   = deduplicate_evidence(retrieved)
    cleaned   = clean_text_evidence(deduped)
    ranked    = rank_by_overlap_and_trust(search_query, cleaned)
    top_text  = select_best_evidence_passages(search_query, ranked, top_k=top_k_text)

    if not top_text:
        return {"claim": claim, "label": "FAKE" if binary_dataset else "NO_EVIDENCE",
                "confidence": 0.0, "explanation": "No evidence retrieved.",
                "text_scores": {"entail":0.0,"contra":0.0,"neutral":1.0,"used":0},
                "fused": {"fused_support":0.0,"fused_contra":0.0,"fused_mixed":0.0,
                          "clip_norm":0.0,"ocr_norm":0.0,"ocr_used":False,"weights":{}},
                "evidence_text": []}

    # Fix 2: DeBERTa NLI + Fix 4: embedding fallback
    text_scores = nli_text_score_v2(claim, top_text, top_k=top_k_text)

    # Image branch (unchanged)
    clip_sim = 0.0
    ocr_text = "" # Initialize ocr_text as a string
    ocr_align = 0.0
    image_used = False
    if image_path:
        img_temp, local_path, _ = load_image_from_path_or_url(image_path)
        if img_temp:
            image_used = True
            clip_sim   = compute_clip_score(img_temp, claim)
            try:
                ocr_text  = run_ocr(local_path) if local_path else ""
                ocr_align = ocr_text_claim_alignment_score(claim, ocr_text)
            except Exception:
                ocr_text = ""

    fused = fuse_multimodal_scores(
        text_scores=text_scores, clip_sim=clip_sim,
        ocr_align=ocr_align, ocr_text=ocr_text, mode=mode,
    )

    # Fix 1: binary-aware label
    label      = final_label_v2(fused, binary_dataset=binary_dataset)
    confidence = round(max(fused["fused_support"], fused["fused_contra"]) * 100, 2)
    explanation = generate_explanation(
                          claim,
                          top_text,
                          fused,
                          label,
                          text_scores
                         )
    return {
        "claim": claim, "label": label, "confidence": confidence,
        "text_scores": text_scores, "fused": fused,
        "evidence_text": top_text, "explanation": explanation,
        "image_used": image_used, "search_query": search_query,
    }

TEST RUN

In [ ]:
out1 = main_pipeline_v2("NASA confirms water on Mars",
       image_path="https://mars.nasa.gov/system/resources/detail_files/25629_PIA23764-1041.jpg")
out2 = main_pipeline_v2("The Earth is flat")
out3 = main_pipeline_v2("Smoking causes lung cancer")

print(f"Test 1 (expect MISLEADING/REAL): {out1['label']}  conf={out1['confidence']}")
print(f"Test 2 (expect FAKE):            {out2['label']}  e={out2['text_scores']['entail']:.3f}  c={out2['text_scores']['contra']:.3f}")
print(f"Test 3 (expect REAL):            {out3['label']}  e={out3['text_scores']['entail']:.3f}  c={out3['text_scores']['contra']:.3f}")

  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/news/2020/12/08/galactic-federation-n
  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/news/2022/09/21/mars-is-littered-with
  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2014/mar/12/rush-limba
  NLI [FC]: e=0.001  c=0.001  src=https://www.politifact.com/factchecks/2024/feb/23/
  [FC REJECT] off-topic article: https://www.snopes.com/fact-check/17-year-old-astronaut-trai
  NLI     : e=0.151  c=0.002  src=https://www.nasa.gov/news-release/nasa-confirms-ev
  NLI     : e=0.921  c=0.006  src=https://www.reuters.com/science/nasa-rover-detects
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/2015/03/cruz-on-the-global-cooling
  NLI [FC]: e=0.002  c=0.926  src=https://fullfact.org/online/earth-is-spherical-not
  NLI [FC]: e=0.001  c=0.969  src=https://www.politifact.com/factchecks/2024/may/29/
  [FC REJECT] off-topic article: https://fullfact.org/technology/artemis-2-earth-pictures-fak
  NLI     : e=0.000  c=1.000  src=https://www.nasa.gov/earth/how-do-we-know-the-eart
  NLI     : e=0.023  c=0.000  src=https://www.cdc.gov/tobacco/campaign/tips/diseases
  NLI     : e=0.999  c=0.000  src=https://www.cdc.gov/lung-cancer/risk-factors/index
  NLI     : e=0.999  c=0.000  src=https://www.nih.gov/news-events/nih-research-matte
  NLI     : e=0.998  c=0.000  src=https://pubmed.ncbi.nlm.nih.gov/23714547/
Test 1 (expect MISLEADING/REAL): REAL  conf=32.24
Test 2 (expect FAKE):            FAKE  e=0.001  c=0.900
Test 3 (expect REAL):            REAL  e=0.681  c=0.000

In [ ]:
out = main_pipeline_v2(
    "NASA confirms water on Mars",
    image_path="https://mars.nasa.gov/system/resources/detail_files/25629_PIA23764-1041.jpg"
)
print(f"\nTest 1 (expect MISLEADING): {out['label']}  confidence={out['confidence']}")
print(f"  entail={out['text_scores']['entail']:.3f}  "
      f"contra={out['text_scores']['contra']:.3f}  "
      f"used={out['text_scores']['used']}")
print(f"  fused_support={out['fused']['fused_support']:.3f}  "
      f"fused_contra={out['fused']['fused_contra']:.3f}")
print("  Sources:")
for ev in out["evidence_text"]:
    fc = " [FC]" if ev.get("is_fact_check") else ""
    print(f"    {fc} {ev['url'][:70]}")

out2 = main_pipeline_v2("The Earth is flat")
print(f"\nTest 2 (expect FAKE):       {out2['label']}  "
      f"entail={out2['text_scores']['entail']:.3f}  "
      f"contra={out2['text_scores']['contra']:.3f}")

out3 = main_pipeline_v2("Smoking causes lung cancer")
print(f"\nTest 3 (expect REAL):       {out3['label']}  "
      f"entail={out3['text_scores']['entail']:.3f}  "
      f"contra={out3['text_scores']['contra']:.3f}")

  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/
  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/news/2020/12/08/galactic-federation-n
  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/news/2022/09/21/mars-is-littered-with
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2014/mar/12/rush-limba
  NLI [FC]: e=0.001  c=0.001  src=https://www.politifact.com/factchecks/2024/feb/23/
  [FC REJECT] off-topic article: https://www.snopes.com/fact-check/17-year-old-astronaut-trai
  NLI     : e=0.150  c=0.002  src=https://www.nasa.gov/news-release/nasa-confirms-ev
  NLI     : e=0.013  c=0.003  src=https://www.nasa.gov/missions/mars-science-laborat

Test 1 (expect MISLEADING): REAL  confidence=15.6
  entail=0.041  contra=0.002  used=4
  fused_support=0.156  fused_contra=0.001
  Sources:
     [FC] https://www.politifact.com/factchecks/2024/feb/23/instagram-posts/nasa
     [FC] https://www.snopes.com/fact-check/17-year-old-astronaut-training/
     https://www.nasa.gov/news-release/nasa-confirms-evidence-that-liquid-w
     https://www.nasa.gov/missions/mars-science-laboratory/nasas-curiosity-
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2023/jul/26/instagram-
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/2015/03/cruz-on-the-global-cooling
  NLI [FC]: e=0.002  c=0.926  src=https://fullfact.org/online/earth-is-spherical-not
  NLI [FC]: e=0.001  c=0.969  src=https://www.politifact.com/factchecks/2024/may/29/
  [FC REJECT] off-topic article: https://fullfact.org/technology/artemis-2-earth-pictures-fak
  NLI     : e=0.000  c=1.000  src=https://www.nasa.gov/earth/how-do-we-know-the-eart

Test 2 (expect FAKE):       FAKE  entail=0.001  contra=0.900
  NLI     : e=0.023  c=0.000  src=https://www.cdc.gov/tobacco/campaign/tips/diseases
  NLI     : e=0.999  c=0.000  src=https://www.cdc.gov/lung-cancer/risk-factors/index
  NLI     : e=0.999  c=0.000  src=https://www.nih.gov/news-events/nih-research-matte
  NLI     : e=0.866  c=0.001  src=https://pubmed.ncbi.nlm.nih.gov/6388830/

Test 3 (expect REAL):       REAL  entail=0.672  contra=0.001

DuckDuckGo Search

In [90]:
!pip install -q duckduckgo-search

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.5/4.5 MB 61.6 MB/s eta 0:00:00

In [98]:
!pip uninstall -y duckduckgo-search
!pip install -q ddgs

Found existing installation: duckduckgo_search 8.1.1
Uninstalling duckduckgo_search-8.1.1:
  Successfully uninstalled duckduckgo_search-8.1.1
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 67.1/67.1 kB 3.0 MB/s eta 0:00:00

In [97]:
import warnings
warnings.filterwarnings("ignore")
import logging
logging.getLogger("ddgs").setLevel(logging.ERROR)

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [99]:
from ddgs import DDGS  # changed from duckduckgo_search

In [104]:
import time

def retrieve_from_query_ddg(query: str, max_results: int = 3) -> list:
    raw = []
    try:
        time.sleep(1)  # ADD THIS — prevents rate limiting
        with DDGS() as ddgs:
            hits = list(ddgs.text(query, max_results=max_results + 3))

        for r in hits:
            url     = r.get("href", "")
            snippet = r.get("body", "")
            if not url or not is_valid_url(url):
                continue
            if "reddit.com" in url:
                continue
            if any(str(y) in url for y in ["2014", "2015", "2016", "2017", "2018"]):
                continue

            text = fetch_article_text(url)
            if not text:
                text = snippet

            if text and len(text) >= 40:
                low = text.lower()
                if "login" in low or "subscribe" in low:
                    continue
                raw.append({"text": text, "url": url, "is_fact_check": is_fact_checker(url)})

    except Exception as e:
        print(f"  DDG ERROR: {e}")

    # Same scoring as original: 50% overlap + 30% length + 20% domain trust
    scored = []
    for ev in raw:
        overlap      = compute_overlap(query, ev["text"])
        domain_boost = get_domain_boost(ev["url"])
        score        = 0.5 * overlap + 0.3 * (len(ev["text"]) / 2500) + 0.2 * domain_boost
        scored.append((score, ev))

    scored.sort(key=lambda x: x[0], reverse=True)
    return [x[1] for x in scored[:max_results]]  # fixed slice bug too


def retrieve_fact_checks_ddg(query: str, max_results: int = 2) -> list:
    STOPWORDS_LOCAL = {"the","a","an","is","are","was","were","of","on","in",
                       "at","to","for","and","or","not","do","does","can","it",
                       "that","this","be","by","from","with","will","has","have"}

    content_words = [
        w for w in re.findall(r"\w+", query.lower())
        if w not in STOPWORDS_LOCAL and len(w) > 2
    ]
    min_matches  = 1
    search_terms = " ".join(content_words[:4])
    fc_query     = (
        f"{search_terms} site:snopes.com OR site:politifact.com OR "
        f"site:factcheck.org OR site:fullfact.org"
    )

    raw = []
    try:
        with DDGS() as ddgs:
            hits = list(ddgs.text(fc_query, max_results=max_results + 4))

        for r in hits:
            url     = r.get("href", "")
            snippet = r.get("body", "")
            title   = r.get("title", "")
            if not url or not is_valid_url(url):
                continue

            # Same relevance check as original
            combined    = (snippet + " " + title).lower()
            combo_words = set(re.findall(r"\w+", combined))
            matches     = [w for w in content_words if w in combo_words]

            if len(matches) < min_matches:
                print(f"  [FC SKIP] only {len(matches)} matches (need {min_matches}): {url[:60]}")
                continue

            text = fetch_article_text(url, min_chars=80, max_chars=2000)
            if not text:
                text = snippet

            if text and len(text) >= 40:
                raw.append({
                    "text":          text,
                    "url":           url,
                    "is_fact_check": True,
                })

    except Exception as e:
        print(f"  DDG FC ERROR: {e}")

    return raw[:max_results]


def retrieve_all_evidence_ddg(query: str, use_fact_checks: bool = True) -> list:
    web_ev = retrieve_from_query_ddg(query, max_results=3)

    if not use_fact_checks or is_pure_science(query):
        print(f"  [FC SKIP] Pure science claim — using web evidence only")
        return web_ev

    if is_health_fact(query):
        # Health claims — search trusted health domains
        health_query = f"{query} site:cdc.gov OR site:nih.gov OR site:who.int OR site:mayoclinic.org"
        health_ev = []
        try:
            with DDGS() as ddgs:
                hits = list(ddgs.text(health_query, max_results=3))
            for r in hits:
                url     = r.get("href", "")
                snippet = r.get("body", "")
                if not url or not is_valid_url(url):
                    continue
                text = fetch_article_text(url, min_chars=80, max_chars=2000)
                if not text:
                    text = snippet
                if text and len(text) >= 40:
                    health_ev.append({
                        "text":          text,
                        "url":           url,
                        "is_fact_check": False,
                        "domain_boost":  3.0,
                    })
        except Exception as e:
            print(f"  DDG HEALTH ERROR: {e}")

        seen   = set()
        merged = []
        for ev in health_ev + web_ev:
            if ev["url"] not in seen:
                seen.add(ev["url"])
                merged.append(ev)
        return merged

    # General claims — use fact checkers
    fc_ev  = retrieve_fact_checks_ddg(query, max_results=2)
    seen   = set()
    merged = []
    for ev in fc_ev + web_ev:
        if ev["url"] not in seen:
            seen.add(ev["url"])
            merged.append(ev)
    return merged

In [108]:
def final_label_calibrated(fused, text_scores, evidence_list):
    support = fused["fused_support"]
    contra  = fused["fused_contra"]
    entail  = text_scores.get("entail", 0.0)
    contra_raw = text_scores.get("contra", 0.0)

    # Count how many sources have high entailment
    high_entail_count = sum(
        1 for ev in evidence_list
        if ev.get("text") and entail > 0.3
    )

    # Count trusted domains in evidence
    trusted_count = sum(
        1 for ev in evidence_list
        if get_domain_boost(ev.get("url", "")) >= 2.0
    )

    MIN_SIGNAL = 0.05

    # Strong contradiction → FAKE
    if contra >= 0.25 and (contra - support) >= 0.08:
        return "FAKE"

    # Strong support → REAL
    if support >= 0.20 and (support - contra) >= 0.08:
        return "REAL"

    # Weak signals but trusted sources lean toward entailment → REAL
    if trusted_count >= 2 and entail > contra_raw:
        return "REAL"

    # No evidence at all → FAKE
    if support < MIN_SIGNAL and contra < MIN_SIGNAL:
        return "FAKE"

    # Default: lean FAKE only if contra has any signal
    if contra_raw > 0.05:
        return "FAKE"

    return "REAL"  # changed from FAKE — benefit of doubt with no contra signal

In [106]:
import warnings
warnings.filterwarnings("ignore")
import logging
logging.getLogger("ddgs").setLevel(logging.ERROR)
logging.getLogger("urllib3").setLevel(logging.ERROR)
import shutil

modes       = ["text_only", "text_clip", "text_clip_ocr"]
summaries   = []
all_outputs = {}

for m in modes:
    df_mode, summary, cm, report = evaluate_mode_v2(
        dataset=final_eval_dataset,
        mode=m,
        top_k_text=4,
        use_fc=True,
        per_sample_timeout=90,
        verbose=True,
    )
    path = f"/content/ablation_v2_{m}.csv"
    df_mode.to_csv(path, index=False)
    print(f"Saved: {path}")
    all_outputs[m] = {"df": df_mode, "summary": summary}
    summaries.append(summary)

summary_df = (
    pd.DataFrame(summaries)
    .sort_values("f1_macro", ascending=False)
    .reset_index(drop=True)
)
print("\n" + "="*60)
print("ABLATION SUMMARY")
print(summary_df[["mode","n_valid","accuracy","precision_macro",
                   "recall_macro","f1_macro"]].to_string(index=False))
summary_df.to_csv("/content/ablation_v2_summary.csv", index=False)

# Save to Drive
for m in modes:
    try:
        shutil.copy(f"/content/ablation_v2_{m}.csv",
                    f"/content/drive/MyDrive/ablation_v2_{m}.csv")
    except: pass
try:
    shutil.copy("/content/ablation_v2_summary.csv",
                "/content/drive/MyDrive/ablation_v2_summary.csv")
    print("All saved to Drive")
except: pass

Running text_only:   0%|          | 0/99 [00:00<?, ?it/s]

  [FC REJECT] off-topic article: https://www.snopes.com/fact-check/ai-photo-missiles-tel-aviv
  NLI     : e=0.010  c=0.001  src=https://www.pbs.org/newshour/world/hezbollah-fires
  NLI [FC]: e=0.315  c=0.059  src=https://api.politifact.com/article/2023/oct/19/did

Running text_only:   1%|          | 1/99 [00:13<22:14, 13.62s/it]

  NLI     : e=0.011  c=0.906  src=https://www.timesofisrael.com/deadly-duel-photos-c
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/fake-news/

Running text_only:   2%|▏         | 2/99 [00:24<19:05, 11.81s/it]

  NLI [FC]: e=0.001  c=0.004  src=https://www.politifact.com/article/2023/oct/23/how
  [FC REJECT] off-topic article: https://fullfact.org/online/list-organisations-no-longer-pos
  NLI     : e=0.001  c=0.007  src=https://bulkoid.com/blog/can-people-see-your-twitt
  NLI     : e=0.003  c=0.164  src=https://circleboom.com/blog/can-you-see-someones-t

Running text_only:   3%|▎         | 3/99 [00:35<18:26, 11.53s/it]

  NLI [FC]: e=0.010  c=0.001  src=https://www.factcheck.org/2025/01/republicans-wron
  NLI [FC]: e=0.013  c=0.047  src=https://www.snopes.com/news/2025/01/02/new-orleans
  NLI     : e=0.005  c=0.000  src=https://www.independent.co.uk/news/world/americas/
  NLI     : e=0.716  c=0.008  src=https://www.aljazeera.com/news/2025/1/2/who-is-sha
  [FC REJECT] off-topic article: https://www.factcheck.org/2024/06/scicheck-antarctic-ice-los
  [FC REJECT] off-topic article: https://www.politifact.com/factchecks/2023/apr/25/instagram-
  NLI     : e=0.003  c=0.003  src=https://en.wikipedia.org/wiki/Terra_Nova_Expeditio

Running text_only:   4%|▍         | 4/99 [00:49<19:35, 12.38s/it]

  NLI     : e=0.003  c=0.003  src=https://en.wikipedia.org/wiki/Robert_Falcon_Scott
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/ask-factcheck/ask-us-a-question/
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/tag/donald-trump/

Running text_only:   5%|▌         | 5/99 [01:02<19:45, 12.61s/it]

  NLI     : e=0.002  c=0.039  src=https://observers.france24.com/en/europe/20240709-
  [FC REJECT] off-topic article: https://fullfact.org/conflict/woman-cigarette-burning-pictur
  NLI     : e=0.005  c=0.282  src=https://pesacheck.org/false-this-video-doesnt-show
  NLI     : e=0.000  c=0.002  src=https://www.dogrula.org/en/fact-checks/was-the-vid
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/fake-news/

Running text_only:   6%|▌         | 6/99 [01:12<18:16, 11.79s/it]

  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/location/china/
  NLI     : e=0.002  c=0.002  src=https://www.boomlive.in/fact-check/factcheck-mosqu
  NLI [FC]: e=0.004  c=0.559  src=https://checkyourfact.com/2024/02/14/fact-check-vi
  NLI     : e=0.001  c=0.001  src=https://southafrica-info.com/fact-checks/chinese-g
  [FC REJECT] off-topic article: https://fullfact.org/online/china-mosque-demolition-false/

Running text_only:   7%|▋         | 7/99 [01:27<19:33, 12.76s/it]

  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/search/?q=somali
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/search/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/askfactcheck/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/truth-o-meter/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/issue/somalia/
  NLI     : e=0.108  c=0.003  src=https://apnews.com/article/somaliland-presidential
  NLI     : e=0.228  c=0.569  src=https://allafrica.com/view/group/main/main/id/0009
  NLI     : e=0.000  c=0.009  src=https://en.wikipedia.org/wiki/2024_Somaliland_pres
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/fake-news/

Running text_only:   8%|▊         | 8/99 [01:36<17:58, 11.86s/it]

  NLI     : e=0.883  c=0.002  src=https://edition.cnn.com/2024/11/14/business/onion-
  NLI     : e=0.999  c=0.000  src=https://www.voanews.com/a/satirical-news-site-the-
  NLI     : e=0.999  c=0.000  src=https://www.nytimes.com/2024/11/14/business/media/
  [FC REJECT] off-topic article: https://www.snopes.com/tag/the-onion/

Running text_only:   9%|▉         | 9/99 [01:51<18:51, 12.58s/it]

  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/fake-news/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/askfactcheck/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/truth-o-meter/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/hot-topics/
  NLI     : e=0.026  c=0.201  src=https://www.manchestereveningnews.co.uk/sport/foot
  NLI     : e=0.020  c=0.021  src=https://www.sportbible.com/football
  NLI     : e=0.005  c=0.012  src=https://www.bbc.co.uk/sport/football
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/fake-news/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/

Running text_only:  10%|█         | 10/99 [02:11<22:14, 14.99s/it]

  NLI     : e=0.035  c=0.551  src=https://www.mysanantonio.com/news/local/article/wh
  NLI     : e=0.022  c=0.032  src=https://www.yahoo.com/news/false-claim-mcconnells-
  NLI [FC]: e=0.013  c=0.899  src=https://www.politifact.com/factchecks/2024/mar/27/
  NLI     : e=0.060  c=0.198  src=https://www.thegatewaypundit.com/2024/02/sheriff-o
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/ask-factcheck/ask-us-a-question/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/truth-o-meter/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/2020/01/trump-administrations-shif
  NLI     : e=0.045  c=0.004  src=https://www.misbar.com/en/factcheck/2024/11/26/pho
  NLI [FC]: e=0.151  c=0.015  src=https://fullfact.org/news/israeli-sniper-false/
  NLI     : e=0.000  c=0.000  src=https://www.globalresearch.ca/heres-proof-that-isr

Running text_only:  11%|█         | 11/99 [02:22<20:10, 13.76s/it]

  NLI     : e=0.003  c=0.002  src=https://en.wikipedia.org/wiki/Qassam_rocket

Running text_only:  12%|█▏        | 12/99 [02:35<19:51, 13.69s/it]

  DDG FC ERROR: No results found.
  NLI     : e=0.035  c=0.011  src=https://www.biography.com/crime/ted-bundy-childhoo
  NLI     : e=0.027  c=0.002  src=https://theconversation.com/hamas-and-hezbollah-ho
  NLI     : e=0.059  c=0.014  src=https://arvinditsolution.blogspot.com/2011/06/what
  DDG ERROR: No results found.
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/

Running text_only:  13%|█▎        | 13/99 [02:41<16:14, 11.34s/it]

  [FC REJECT] off-topic article: https://www.factcheck.org/fake-news/
  [FC REJECT] off-topic article: https://www.snopes.com/fact-check/
  [FALLBACK] Using embedding similarity
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/facebook-fact-checks/

Running text_only:  14%|█▍        | 14/99 [02:48<13:50,  9.77s/it]

  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/2020/08/social-media-posts-use-gra
  [FC REJECT] off-topic article: https://www.factcheck.org/2018/11/california-shooting-prompt
  NLI     : e=0.001  c=0.001  src=https://www.lomography.com/magazine/347736-the-hyp
  NLI     : e=0.000  c=0.000  src=https://digitalcommons.unl.edu/honorstheses/401/
  NLI     : e=0.000  c=0.000  src=https://www.sciencedirect.com/science/article/pii/
  DDG FC ERROR: No results found.
  NLI     : e=0.006  c=0.001  src=https://www.bbc.co.uk/news/articles/c24nrynq0elo
  NLI     : e=0.005  c=0.001  src=https://www.businessinsider.com/ex-prosecutors-exp

Running text_only:  15%|█▌        | 15/99 [02:58<14:10, 10.12s/it]

  NLI     : e=0.002  c=0.989  src=https://www.bbc.co.uk/news/videos/c3e37ywg8dwo

Running text_only:  16%|█▌        | 16/99 [03:08<13:46,  9.96s/it]

  DDG FC ERROR: No results found.
  NLI     : e=0.145  c=0.084  src=https://www.amnestyindia.org/we-cant-be-a-recycled
  NLI     : e=0.007  c=0.003  src=https://www.thejc.com/life/books/noughties-nazis-a
  NLI     : e=0.003  c=0.057  src=https://www.jpost.com/international/did-nazis-chan

Running text_only:  17%|█▋        | 17/99 [03:25<16:17, 11.92s/it]

  DDG FC ERROR: No results found.
  NLI     : e=0.010  c=0.004  src=https://www.lbc.co.uk/article/badger-cull-farmers-
  NLI     : e=0.015  c=0.557  src=https://www.mirror.co.uk/news/uk-news/badgers-coul
  NLI     : e=0.010  c=0.032  src=https://www.badgertrust.org.uk/post/badgers-and-bo

Running text_only:  18%|█▊        | 18/99 [03:34<15:06, 11.19s/it]

  DDG FC ERROR: No results found.
  NLI [FC]: e=0.000  c=0.000  src=https://www.politifact.com/article/2025/aug/18/tru
  NLI     : e=0.017  c=0.002  src=https://apnews.com/article/russia-ukraine-war-trum
  NLI     : e=0.692  c=0.008  src=https://www.aljazeera.com/news/2025/12/26/zelensky
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/truth-o-meter/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/california/

Running text_only:  19%|█▉        | 19/99 [03:46<15:02, 11.28s/it]

  NLI     : e=0.001  c=0.000  src=https://www.holyrood.com/editors-column/view,a-yea
  NLI     : e=0.001  c=0.002  src=https://www.theguardian.com/commentisfree/2026/apr
  [FC REJECT] off-topic article: https://www.factcheck.org/the-factcheck-wire/
  NLI [FC]: e=0.001  c=0.000  src=https://www.factcheck.org/askfactcheck/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/fake-news/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/askfactcheck/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/

Running text_only:  20%|██        | 20/99 [03:57<15:04, 11.45s/it]

  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/ask-factcheck/ask-us-a-question/
  [FC REJECT] off-topic article: https://fullfact.org/news/funerals-can-still-go-ahead-on-Mon
  NLI     : e=0.006  c=0.003  src=https://www.nps.gov/jica/carterlanding.htm
  NLI     : e=0.964  c=0.033  src=https://www.forbes.com/sites/mollybohannon/2025/01
  NLI     : e=0.872  c=0.061  src=https://www.cbtnews.com/jimmy-carter-humanitarian-

Running text_only:  21%|██        | 21/99 [04:14<16:46, 12.91s/it]

  DDG FC ERROR: No results found.
  NLI     : e=0.019  c=0.004  src=https://www.aljazeera.com/news/2026/2/28/us-and-is
  NLI     : e=0.060  c=0.046  src=https://www.cnn.com/2026/02/28/middleeast/israel-a
  NLI     : e=0.098  c=0.065  src=https://www.bbc.com/news/live/cy0dp1l57nxt

Running text_only:  22%|██▏       | 22/99 [04:22<14:37, 11.39s/it]

  DDG FC ERROR: No results found.
  NLI     : e=0.000  c=0.000  src=https://us.headtopics.com/news/jimmy-carter-feudin
  NLI     : e=0.000  c=0.001  src=https://www.foxnews.com/media/carter-feuded-succes
  NLI     : e=0.000  c=0.001  src=https://scconstables.org/2024/12/30/carter-feuded-

Running text_only:  23%|██▎       | 23/99 [04:36<15:44, 12.43s/it]

  NLI     : e=0.971  c=0.006  src=https://qthzb.com/category/columns/antisemitism-ex
  [FC REJECT] off-topic article: https://www.politifact.com/article/2022/may/19/tucker-carlso
  NLI [FC]: e=0.003  c=0.004  src=https://www.factcheck.org/2023/11/cruz-distorts-fa
  NLI     : e=0.001  c=0.004  src=https://www.foxnews.com/us/fox-news-antisemitism-e

Running text_only:  24%|██▍       | 24/99 [04:44<13:45, 11.00s/it]

  DDG FC ERROR: No results found.
  NLI     : e=0.997  c=0.001  src=https://www.linklaters.com/insights/blogs/foreigni
  NLI     : e=0.000  c=1.000  src=https://www.hunton.com/insights/legal/nippon-steel
  NLI     : e=0.000  c=0.999  src=https://abcnews.com/Business/biden-blocks-us-steel

Running text_only:  25%|██▌       | 25/99 [04:56<13:50, 11.22s/it]

  DDG FC ERROR: No results found.
  NLI     : e=0.004  c=0.001  src=https://www.theguardian.com/us-news/ng-interactive
  NLI     : e=0.024  c=0.055  src=https://en.wikipedia.org/wiki/Indictments_against_
  NLI     : e=0.180  c=0.001  src=https://www.bbc.com/news/articles/cj0jr5ypqedo

Running text_only:  26%|██▋       | 26/99 [05:06<13:22, 11.00s/it]

  DDG FC ERROR: No results found.
  NLI     : e=0.224  c=0.048  src=https://indieradiofm.net/remembering-the-man-who-b
  NLI     : e=0.994  c=0.000  src=https://www.youtube.com/watch?v=UFVK-os5eSo
  NLI     : e=0.020  c=0.001  src=https://www.bbc.com/news/articles/c2exzm9r043o?at_

Running text_only:  27%|██▋       | 27/99 [05:14<12:09, 10.13s/it]

  DDG FC ERROR: No results found.
  NLI     : e=0.019  c=0.676  src=https://www.getyarn.io/yarn-clip/c6cef0ec-6dae-471
  NLI     : e=0.001  c=0.992  src=https://myretrotvs.com/
  NLI     : e=0.015  c=0.083  src=https://www.hoopshype.com/rumors/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/fake-news/
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/collections/911-rumors-collection/
  NLI     : e=0.007  c=0.013  src=https://www.wired.com/story/walkie-talkie-explosio
  NLI     : e=0.970  c=0.001  src=https://indianaexpres.com/world/lebanon-health-min

Running text_only:  28%|██▊       | 28/99 [05:29<13:28, 11.39s/it]

  NLI     : e=0.001  c=0.002  src=https://english.elpais.com/international/2024-09-1
  [FC REJECT] off-topic article: https://www.politifact.com/factchecks/2025/dec/19/social-med
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/fake-news/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/askfactcheck/
  NLI [FC]: e=0.001  c=0.798  src=https://www.politifact.com/factchecks/2023/may/16/
  NLI [FC]: e=0.001  c=0.937  src=https://www.politifact.com/factchecks/2023/jun/05/
  NLI     : e=0.003  c=0.146  src=https://www.independent.co.uk/arts-entertainment/f

Running text_only:  29%|██▉       | 29/99 [05:39<12:50, 11.01s/it]

  NLI     : e=0.968  c=0.008  src=https://www.aol.com/jamie-foxx-hit-glass-during-10
  DDG ERROR: query is mandatory.

Running text_only:  30%|███       | 30/99 [05:42<09:59,  8.70s/it]

  DDG FC ERROR: No results found.
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/fake-news/
  NLI     : e=0.012  c=0.001  src=https://www.abc.net.au/news/2024-09-27/netanyahu-d
  NLI     : e=1.000  c=0.000  src=https://saudigazette.com.sa/article/645819/World/M
  NLI [FC]: e=0.003  c=0.008  src=https://www.politifact.com/factchecks/2026/mar/13/

Running text_only:  31%|███▏      | 31/99 [05:56<11:38, 10.27s/it]

  NLI     : e=0.028  c=0.002  src=https://www.indiatoday.in/world/story/israeli-hezb
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/scicheck/

Running text_only:  32%|███▏      | 32/99 [06:05<11:01,  9.87s/it]

  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/issues/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/article/2025/dec/29/2025-politifa
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/fact-check/
  NLI     : e=0.996  c=0.002  src=https://www.dailystar.co.uk/news/latest-news/new-d
  NLI     : e=0.996  c=0.000  src=https://www.bbc.co.uk/news/articles/clyx9nv4mleo
  NLI     : e=0.996  c=0.000  src=https://www.yodolenews.com/2025/01/02/new-bone-tes
  [FC REJECT] off-topic article: https://www.snopes.com/latest/

Running text_only:  33%|███▎      | 33/99 [06:18<12:00, 10.92s/it]

  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/issues/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/fake-news/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/truth-o-meter/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/search/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/article/
  [FC SKIP] only 0 matches (need 1): https://fullfact.org/latest/
  NLI     : e=0.000  c=0.000  src=https://archonnews.com/mayotte-grapples-with-water
  NLI     : e=0.002  c=0.001  src=https://staging.infonews.ca/news/4517609/authoriti
  NLI     : e=0.226  c=0.003  src=https://wtxnews.com/mayotte-faces-water-shortages-

Running text_only:  34%|███▍      | 34/99 [06:30<12:04, 11.14s/it]

  DDG FC ERROR: No results found.
  NLI     : e=0.008  c=0.003  src=https://www.foxnews.com/media/biden-insider-expose
  NLI     : e=0.002  c=0.001  src=https://chicagofinancialtimes.com/2025/04/15/biden
  NLI     : e=0.003  c=0.000  src=https://constitutionalrightspac.com/articles/embar
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/
  [FC REJECT] off-topic article: https://fullfact.org/online/donald-trump-shooter-misidentifi
  NLI     : e=0.116  c=0.004  src=https://www.fox5dc.com/news/person-interest-ceo-ki
  NLI     : e=0.991  c=0.001  src=https://www.indiatoday.in/world/us-news/story/unit

Running text_only:  35%|███▌      | 35/99 [06:45<13:06, 12.30s/it]

  NLI     : e=0.943  c=0.018  src=https://www.aol.com/latest-police-man-pennsylvania
  NLI     : e=0.000  c=0.001  src=https://www.theguardian.com/world/live/2025/may/31
  NLI [FC]: e=0.004  c=0.001  src=https://fullfact.org/blog/2024/oct/a-year-of-fact-
  NLI     : e=0.015  c=0.001  src=https://en.wikipedia.org/wiki/Yahya_Sinwar

Running text_only:  36%|███▋      | 36/99 [07:00<13:36, 12.96s/it]

  NLI [FC]: e=0.001  c=0.000  src=https://fullfact.org/middle-east-conflict/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/fake-news/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/list/?category=religio

Running text_only:  37%|███▋      | 37/99 [07:09<12:09, 11.76s/it]

  NLI     : e=0.977  c=0.001  src=https://nova24tv.si/video-spanija-afriski-migrant-
  [FC REJECT] off-topic article: https://www.politifact.com/article/2025/sep/30/michigan-chur
  NLI     : e=0.002  c=0.006  src=https://www.dw.com/en/nigeria-evacuating-130-citiz
  [FC REJECT] off-topic article: https://www.factcheck.org/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/list/?category=sports
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/the-factcheck-wire/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/florida/

Running text_only:  38%|███▊      | 38/99 [07:21<12:12, 12.01s/it]

  [FC REJECT] off-topic article: https://www.factcheck.org/hot-topics/
  NLI     : e=0.028  c=0.160  src=https://www.ginx.tv/en/call-of-duty/tommey-recants
  [FC REJECT] off-topic article: https://www.factcheck.org/issue/2000-presidential-election/
  NLI     : e=0.001  c=0.009  src=https://app.wertinsaat.com/viral/amerika-sus-viral
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/fake-news/
  [FC SKIP] only 0 matches (need 1): https://fullfact.org/politics/mandelson-arrest-video-edited-
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/askfactcheck/

Running text_only:  39%|███▉      | 39/99 [07:32<11:37, 11.62s/it]

  [FC REJECT] off-topic article: https://www.politifact.com/supreme-court/
  NLI [FC]: e=0.001  c=0.006  src=https://api.politifact.com/factchecks/2022/may/12/
  NLI     : e=0.002  c=0.007  src=https://www.boston.com/news/crime/2024/05/21/karen
  NLI     : e=0.002  c=0.001  src=https://cafemom.com/news/woman-sentenced-jail-thro
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/issues/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/search/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/punditfact/
  [FC SKIP] only 0 matches (need 1): https://fullfact.org/latest/
  [FC REJECT] off-topic article: https://www.factcheck.org/fake-news/
  NLI     : e=0.988  c=0.001  src=https://www.thedetroitbureau.com/today-report/roma
  NLI     : e=0.001  c=0.001  src=https://www.bbc.com/news/world-europe-17776565

Running text_only:  40%|████      | 40/99 [07:42<11:04, 11.27s/it]

  NLI     : e=0.001  c=0.001  src=https://www.bbc.co.uk/news/world-europe-17776565

Running text_only:  41%|████▏     | 41/99 [07:52<10:31, 10.88s/it]

  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/fake-news/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/askfactcheck/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/facebook-fact-checks/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/hot-topics/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/california/
  NLI     : e=0.000  c=0.000  src=https://www.bbc.co.uk/news/articles/cjdnkdg1l8do
  NLI     : e=0.001  c=0.000  src=https://www.bbc.com/news/articles/cjdnkdg1l8do
  NLI     : e=0.000  c=0.000  src=https://d33fn5lypxzr2z.cloudfront.net/news/article

Running text_only:  42%|████▏     | 42/99 [07:58<08:52,  9.33s/it]

  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/fake-news/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/askfactcheck/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/california/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/hot-topics/

Running text_only:  43%|████▎     | 43/99 [08:09<09:04,  9.72s/it]

  DDG FC ERROR: No results found.
  NLI     : e=0.005  c=0.033  src=https://dfrac.org/en/2024/02/13/fact-check-did-cap
  NLI     : e=0.046  c=0.002  src=https://tribune.com.pk/story/2469136/chris-evans-c
  NLI     : e=0.000  c=0.050  src=https://en.wikipedia.org/wiki/Captain_America:_Bra

Running text_only:  44%|████▍     | 44/99 [08:16<08:11,  8.93s/it]

  DDG FC ERROR: No results found.
  NLI     : e=0.005  c=0.001  src=https://vcorner.medium.com/5-gruesome-torture-devi
  NLI     : e=0.025  c=0.715  src=https://en.wikipedia.org/wiki/Pear_of_anguish
  NLI     : e=0.035  c=0.007  src=https://allthatsinteresting.com/pear-of-anguish
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/list/?speaker_type=SOC
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/
  NLI     : e=0.994  c=0.002  src=https://www.mixedtimes.com/news/barron-trump-is-sm
  NLI     : e=0.041  c=0.002  src=https://www.foxnews.com/travel/man-vacation-goes-v
  [FC REJECT] off-topic article: https://www.factcheck.org/fake-news/

Running text_only:  45%|████▌     | 45/99 [08:24<07:51,  8.72s/it]

  NLI     : e=0.016  c=0.009  src=https://www.euroki.org/koza/choose-between-the-pre

Running text_only:  46%|████▋     | 46/99 [08:37<08:52, 10.05s/it]

  DDG FC ERROR: No results found.
  NLI     : e=0.012  c=0.141  src=https://www.usatoday.com/story/sports/ncaab/2026/0
  NLI     : e=0.002  c=0.000  src=https://dailysportsreporter.com/athletes/dan-hurle
  NLI     : e=0.000  c=0.000  src=https://www.si.com/college/michigan/basketball/for
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/fake-news/

Running text_only:  47%|████▋     | 47/99 [08:50<09:34, 11.05s/it]

  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/
  NLI     : e=1.000  c=0.000  src=https://www.mediaite.com/tv/dont-touch-me-scott-je
  NLI     : e=0.720  c=0.002  src=https://www.the-express.com/entertainment/celebrit
  NLI     : e=0.999  c=0.000  src=https://nypost.com/2024/12/14/media/cnn-contributo
  NLI [FC]: e=0.000  c=0.001  src=https://www.politifact.com/personalities/scott-jen

Running text_only:  48%|████▊     | 48/99 [09:04<09:57, 11.72s/it]

  NLI     : e=0.001  c=0.001  src=https://www.hindustantimes.com/world-news/a-look-a
  NLI     : e=0.000  c=0.000  src=https://abc17news.com/politics/2026/04/26/trump-fi
  NLI [FC]: e=0.001  c=0.003  src=https://www.politifact.com/personalities/donald-tr
  NLI     : e=0.000  c=0.000  src=https://7news.com.au/news/us-president-donald-trum

Running text_only:  49%|████▉     | 49/99 [09:13<09:10, 11.00s/it]

  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/crime/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/truth-o-meter/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/misconceptions/conspiracy-theories
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/health-check/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/punditfact/
  NLI     : e=0.000  c=0.000  src=https://livemorescreenless.org/blog/resource/the-c
  NLI     : e=0.000  c=0.001  src=https://www.nytimes.com/2025/06/18/opinion/parents
  NLI     : e=0.000  c=0.000  src=https://www.theatlantic.com/ideas/archive/2023/06/

Running text_only:  51%|█████     | 50/99 [09:24<09:02, 11.08s/it]

  DDG FC ERROR: No results found.
  NLI     : e=0.000  c=0.000  src=https://fastguardservice.com/texas-police-arrest-9
  NLI     : e=0.964  c=0.001  src=https://www.foxnews.com/us/texas-police-arrest-9-s
  NLI     : e=0.164  c=0.001  src=https://www.fox7austin.com/news/lakeline-mall-shop
  DDG FC ERROR: No results found.
  NLI     : e=0.151  c=0.028  src=https://popculture.com/reality-tv/news/christina-h
  NLI     : e=0.998  c=0.000  src=https://www.realestate.com.au/news/sneak-peak-at-c

Running text_only:  52%|█████▏    | 51/99 [09:33<08:16, 10.35s/it]

  NLI     : e=0.997  c=0.000  src=https://www.foxnews.com/entertainment/hgtv-star-ch

Running text_only:  53%|█████▎    | 52/99 [09:48<09:06, 11.64s/it]

  DDG FC ERROR: No results found.
  NLI     : e=0.958  c=0.040  src=https://nypost.com/2025/12/07/us-news/portland-man
  NLI     : e=0.055  c=0.894  src=https://www.euroki.org/koza/task-read-the-text-bel
  NLI     : e=0.007  c=0.051  src=https://genius.com/Digital-descendant-it-doesnt-en

Running text_only:  54%|█████▎    | 53/99 [09:56<08:14, 10.75s/it]

  DDG FC ERROR: No results found.
  NLI     : e=0.028  c=0.031  src=https://www.aol.com/articles/hiker-stumbles-human-
  NLI     : e=0.999  c=0.000  src=https://usnewsper.com/2024/12/hiker-finds-body-on-
  NLI     : e=0.002  c=0.988  src=https://www.wave3.com/2025/03/13/hiker-finds-body-

Running text_only:  55%|█████▍    | 54/99 [10:06<07:47, 10.40s/it]

  DDG FC ERROR: No results found.
  NLI     : e=0.017  c=0.001  src=https://cowboystatedaily.com/2024/10/11/wyomings-h
  NLI     : e=0.003  c=0.004  src=https://www.usatoday.com/story/news/factcheck/2024
  NLI     : e=0.009  c=0.001  src=https://www.vice.com/en/article/wyoming-wildfires-

Running text_only:  56%|█████▌    | 55/99 [10:13<06:56,  9.46s/it]

  NLI [FC]: e=0.034  c=0.024  src=https://www.factcheck.org/2023/11/dozens-of-childr
  NLI     : e=0.998  c=0.001  src=https://www.theguardian.com/world/2024/nov/10/deaf
  NLI     : e=0.002  c=0.000  src=https://www.nytimes.com/2025/07/13/world/middleeas
  [FC REJECT] off-topic article: https://www.factcheck.org/issue/israel-hamas-war/
  DDG FC ERROR: No results found.
  NLI     : e=0.000  c=0.000  src=https://www.theguardian.com/us-news/2025/may/03/tr
  NLI     : e=0.003  c=0.392  src=https://www.9news.com.au/world/donald-trump-is-fac

Running text_only:  57%|█████▋    | 56/99 [10:24<06:59,  9.76s/it]

  NLI     : e=0.000  c=0.001  src=https://www.bbc.com/news/articles/crlx8w5wdl0o

Running text_only:  58%|█████▊    | 57/99 [10:39<08:05, 11.57s/it]

  DDG FC ERROR: No results found.
  NLI     : e=0.356  c=0.001  src=https://universemagazine.com/en/how-robots-and-art
  NLI     : e=0.000  c=0.000  src=https://www.diplotic.com/the-future-of-space-trave
  NLI     : e=0.993  c=0.001  src=https://www.space.com/astronomy/mars/artificial-su
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/fake-news/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/

Running text_only:  59%|█████▊    | 58/99 [10:48<07:21, 10.77s/it]

  NLI [FC]: e=0.012  c=0.001  src=https://www.snopes.com/fact-check/keanu-reeves-who
  NLI     : e=0.020  c=0.026  src=https://news.meaww.com/fact-check-did-keanu-reeves
  NLI     : e=0.772  c=0.004  src=https://www.forbes.com/sites/mattnovak/2024/02/03/
  NLI [FC]: e=0.011  c=0.409  src=https://fullfact.org/online/keanu-reeves-matrix-fa
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/

Running text_only:  60%|█████▉    | 59/99 [11:03<07:52, 11.81s/it]

  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/fake-news/
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/fact-check/
  NLI [FC]: e=0.000  c=0.001  src=https://www.politifact.com/factchecks/2024/may/21/
  NLI     : e=0.000  c=0.000  src=https://www.citizen.co.za/news/news-world/iranian-
  NLI     : e=0.000  c=0.000  src=https://www.indiatoday.in/fact-check/story/iran-pr
  [FC REJECT] off-topic article: https://fullfact.org/online/italian-trucks-coronavirus-victi
  DDG ERROR: No results found.

Running text_only:  61%|██████    | 60/99 [11:09<06:40, 10.28s/it]

  DDG FC ERROR: No results found.
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/

Running text_only:  62%|██████▏   | 61/99 [11:20<06:39, 10.52s/it]

  [FC SKIP] only 0 matches (need 1): https://fullfact.org/news/
  NLI     : e=0.326  c=0.005  src=https://dfrac.org/en/tag/elon-musk-en/
  NLI     : e=0.001  c=0.002  src=https://www.theguardian.com/technology/article/202
  [FC REJECT] off-topic article: https://www.snopes.com/collections/king-charles-iii-rumors/
  NLI [FC]: e=0.001  c=0.315  src=https://www.factcheck.org/fake-news/

Running text_only:  63%|██████▎   | 62/99 [11:36<07:29, 12.15s/it]

  DDG FC ERROR: No results found.
  NLI     : e=0.042  c=0.023  src=https://www.aa.com.tr/en/middle-east/us-deeply-con
  NLI     : e=0.014  c=0.086  src=https://en.wikipedia.org/wiki/Gaza_war
  NLI     : e=0.024  c=0.017  src=https://www.inkl.com/news/middle-east-live-55-repo
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/fake-news/

Running text_only:  64%|██████▎   | 63/99 [11:46<06:55, 11.53s/it]

  [FC SKIP] only 0 matches (need 1): https://fullfact.org/conflict/israel-iran-misinformation-cir
  NLI     : e=0.999  c=0.000  src=https://synctopic.com/article/mkAEjexn1f
  NLI     : e=0.998  c=0.000  src=https://www.mixedtimes.com/news/hezbollah-launches
  [FC REJECT] off-topic article: https://www.politifact.com/article/2026/mar/02/these-videos-
  NLI     : e=0.005  c=0.000  src=https://www.theguardian.com/world/2024/sep/24/isra
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/fake-news/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/

Running text_only:  65%|██████▍   | 64/99 [11:58<06:41, 11.47s/it]

  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/truth-o-meter/
  NLI     : e=0.008  c=0.002  src=https://www.lifezette.com/2025/01/unprotected-fren
  NLI [FC]: e=0.002  c=0.000  src=https://www.factcheck.org/2025/01/republicans-wron
  NLI [FC]: e=0.003  c=0.001  src=https://fullfact.org/online/new-orleans-police-bad
  NLI     : e=0.000  c=0.000  src=https://bklyn-ny.com/?p=7692
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/

Running text_only:  66%|██████▌   | 65/99 [12:08<06:15, 11.03s/it]

  NLI     : e=0.021  c=0.004  src=https://www.aljazeera.com/features/2026/4/28/down-
  NLI     : e=0.002  c=0.001  src=https://www.dw.com/en/as-israel-hezbollah-ceasefir
  NLI     : e=0.014  c=0.010  src=https://www.upi.com/Top_News/World-News/2025/11/26
  [FC REJECT] off-topic article: https://www.snopes.com/category/politics/

Running text_only:  67%|██████▋   | 66/99 [12:13<05:09,  9.37s/it]

  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/fake-news/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/issues/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/the-factcheck-wire/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/search/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/hot-topics/
  NLI     : e=0.043  c=0.004  src=https://www.independent.co.uk/travel/news-and-advi
  NLI     : e=0.002  c=0.981  src=https://www.inkl.com/news/no-planes-in-alaska-aren
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/

Running text_only:  68%|██████▊   | 67/99 [12:23<05:01,  9.43s/it]

  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/fake-news/
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/
  [FC REJECT] off-topic article: https://www.factcheck.org/search/
  NLI     : e=0.219  c=0.189  src=https://aish.com/my-post-october-7th-trauma-an-int
  [FC REJECT] off-topic article: https://www.snopes.com/fact-check/
  NLI     : e=0.010  c=0.022  src=https://www.bbc.com/news/world-middle-east-6795826

Running text_only:  69%|██████▊   | 68/99 [12:31<04:37,  8.94s/it]

  DDG FC ERROR: No results found.
  NLI     : e=0.005  c=0.001  src=https://dailygalaxy.com/2025/08/soviet-probe-venus
  NLI     : e=0.329  c=0.031  src=https://rarehistoricalphotos.com/venus-surface-pho
  NLI     : e=0.018  c=0.048  src=https://en.wikipedia.org/wiki/Venera_9

Running text_only:  70%|██████▉   | 69/99 [12:41<04:43,  9.44s/it]

  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/fake-news/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/askfactcheck/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/articles/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/hot-topics/
  NLI     : e=0.000  c=0.000  src=https://www.bbc.co.uk/news/articles/ce32n0eze87o
  NLI     : e=0.002  c=0.002  src=https://news.google.com/stories/CAAqNggKIjBDQklTSG
  NLI     : e=0.005  c=0.770  src=https://www.bbc.com/news/articles/ce32n0eze87o

Running text_only:  71%|███████   | 70/99 [13:01<06:06, 12.63s/it]

  NLI     : e=0.005  c=0.004  src=https://blazingpress.com/ww3-alert-israel-launches
  NLI     : e=0.018  c=0.001  src=https://www.thenationalnews.com/mena/lebanon/2024/
  NLI     : e=0.999  c=0.000  src=https://www.jpost.com/israel-hamas-war/article-786
  NLI [FC]: e=0.121  c=0.009  src=https://fullfact.org/conflict/video-compilation-ir

Running text_only:  72%|███████▏  | 71/99 [13:15<06:04, 13.02s/it]

  NLI [FC]: e=0.043  c=0.002  src=https://www.politifact.com/article/2026/mar/02/the
  NLI     : e=0.998  c=0.001  src=https://www.theguardian.com/world/2024/oct/26/idf-
  [FC REJECT] off-topic article: https://fullfact.org/conflict/video-compilation-iranian-base
  NLI     : e=0.996  c=0.001  src=https://www.youtube.com/watch?v=-8s13QS-nhc

Running text_only:  73%|███████▎  | 72/99 [13:28<05:49, 12.95s/it]

  NLI     : e=0.982  c=0.001  src=https://edition.cnn.com/2024/05/08/politics/joe-bi
  NLI     : e=0.002  c=0.056  src=https://www.goodmorningamerica.com/news/story/bide
  NLI     : e=0.995  c=0.000  src=https://whdh.com/news/biden-says-he-will-stop-send
  NLI [FC]: e=0.016  c=0.004  src=https://www.politifact.com/factchecks/2024/nov/06/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/fake-news/

Running text_only:  74%|███████▎  | 73/99 [13:46<06:14, 14.41s/it]

  NLI     : e=0.990  c=0.004  src=https://wfin.com/fox-political-news/fox-news-polit
  NLI [FC]: e=0.000  c=0.000  src=https://www.politifact.com/factchecks/2024/mar/28/
  [FC REJECT] off-topic article: https://www.factcheck.org/issue/isis/
  NLI     : e=0.003  c=0.969  src=https://www.spursfancave.com/tag/asia/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/fake-news/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/issue/mars/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/scicheck/
  NLI     : e=0.000  c=0.000  src=https://www.foxnews.com/tech/nasas-martian-helicop
  NLI     : e=0.001  c=0.002  src=https://scitechdaily.com/mechanical-engineering-st

Running text_only:  75%|███████▍  | 74/99 [14:00<06:01, 14.47s/it]

  NLI     : e=0.005  c=0.020  src=https://www.syfy.com/syfy-wire/mars-helicopter-pho
  [FC REJECT] off-topic article: https://www.politifact.com/truth-o-meter/promises/
  DDG FC ERROR: No results found.
  NLI     : e=0.002  c=0.001  src=https://www.aol.com/sports/conor-mcgregor-accused-
  NLI     : e=0.003  c=0.302  src=https://www.dailymail.com/sport/conor_mcgregor/ind

Running text_only:  76%|███████▌  | 75/99 [14:25<06:58, 17.43s/it]

  NLI     : e=0.002  c=0.004  src=https://en.wikipedia.org/wiki/Conor_McGregor
  DDG FC ERROR: ('error sending request for url (https://html.duckduckgo.com/html/)', 'https://html.duckduckgo.com/html/')
  NLI     : e=0.011  c=0.055  src=https://www.dailykos.com/stories/2025/3/26/2312632
  NLI     : e=0.285  c=0.011  src=https://www.cnn.com/2025/08/27/politics/iowa-democ

Running text_only:  77%|███████▋  | 76/99 [14:38<06:14, 16.27s/it]

  NLI     : e=0.763  c=0.019  src=https://www.fox5dc.com/news/catelin-drey-democrats

Running text_only:  78%|███████▊  | 77/99 [14:57<06:12, 16.94s/it]

  [FC REJECT] off-topic article: https://www.factcheck.org/2016/08/trumps-false-obama-isis-li
  [FC REJECT] off-topic article: https://www.politifact.com/factchecks/2024/mar/28/alex-jones
  NLI     : e=0.001  c=0.000  src=https://www.foxnews.com/us/6-times-isis-has-inspir
  NLI     : e=0.000  c=0.000  src=https://www.adl.org/resources/article/islamist-ter
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/fake-news/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/fact-check-ratings/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/

Running text_only:  79%|███████▉  | 78/99 [15:09<05:25, 15.50s/it]

  [FC REJECT] off-topic article: https://www.factcheck.org/hot-topics/
  NLI     : e=0.003  c=0.011  src=https://tech.yahoo.com/general/articles/worst-pass
  NLI     : e=0.006  c=0.514  src=https://www.linkedin.com/pulse/worst-passwords-202
  [FC REJECT] off-topic article: https://fullfact.org/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/

Running text_only:  80%|███████▉  | 79/99 [15:33<06:00, 18.04s/it]

  NLI     : e=0.001  c=0.001  src=https://www.theguardian.com/world/2026/apr/28/hezb
  NLI [FC]: e=0.001  c=0.004  src=https://www.factcheck.org/fake-news/
  NLI     : e=0.001  c=0.000  src=https://www.rt.com/news/639136-hezbollah-drone-isr
  NLI     : e=0.003  c=0.012  src=https://www.israeltoday.co.il/read/lebanon-ceasefi

Running text_only:  81%|████████  | 80/99 [15:49<05:33, 17.57s/it]

  DDG FC ERROR: ('error sending request for url (https://html.duckduckgo.com/html/)', 'https://html.duckduckgo.com/html/')
  NLI     : e=0.025  c=0.682  src=https://www.oneindia.com/fact-check/fact-check-did
  NLI     : e=0.009  c=0.005  src=https://sports.yahoo.com/live/mike-tyson-vs-jake-p
  NLI     : e=0.015  c=0.149  src=https://www.sportskeeda.com/baseball/paul-skenes-g
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/

Running text_only:  82%|████████▏ | 81/99 [16:11<05:36, 18.70s/it]

  NLI [FC]: e=0.001  c=0.001  src=https://fullfact.org/world/us-nato-contributions/
  NLI     : e=0.001  c=0.001  src=https://www.theguardian.com/us-news/2025/apr/17/na
  [FC REJECT] off-topic article: https://www.factcheck.org/issue/nato/
  NLI     : e=0.001  c=0.002  src=https://www.bbc.com/news/articles/clyz4nq91wpo
  DDG ERROR: query is mandatory.

Running text_only:  83%|████████▎ | 82/99 [16:13<03:52, 13.69s/it]

  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/fake-news/
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/top/
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/category/politics/
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/fact-check/

Running text_only:  84%|████████▍ | 83/99 [16:25<03:30, 13.15s/it]

  DDG FC ERROR: No results found.
  NLI     : e=0.008  c=0.796  src=https://www.teslarati.com/tesla-model-3-brake-fail
  NLI     : e=0.023  c=0.153  src=https://www.notebookcheck.net/Quirky-Model-3-accid
  NLI     : e=0.212  c=0.006  src=https://www.teslaownersonline.com/threads/brakes-f
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2024/may/16/instagram-
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/article/2024/may/10/the-antisemit
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/article/2025/dec/12/genocide-isra
  NLI     : e=0.007  c=0.018  src=https://truthjihad.com/2012/08/15/zionist-extremis

Running text_only:  85%|████████▍ | 84/99 [16:35<03:02, 12.19s/it]

  NLI     : e=0.004  c=0.321  src=https://thegrayzone.com/2025/09/12/charlie-kirk-ne
  [FC REJECT] off-topic article: https://www.factcheck.org/fake-news/
  NLI     : e=0.003  c=0.128  src=https://www.bbc.com/news/topics/c302m85q5ljt
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/fake-news/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/

Running text_only:  86%|████████▌ | 85/99 [16:47<02:52, 12.35s/it]

  NLI     : e=0.067  c=0.087  src=https://www.dailymotion.com/video/x9b13ro
  [FC REJECT] off-topic article: https://fullfact.org/online/miscaptioned-video-shooting-rang
  NLI     : e=0.003  c=0.000  src=https://www.bbc.co.uk/news/articles/cj90wz8weymo.a
  [FC REJECT] off-topic article: https://api.politifact.com/factchecks/2018/may/04/blog-posti

Running text_only:  87%|████████▋ | 86/99 [17:11<03:25, 15.84s/it]

  DDG FC ERROR: ('error sending request for url (https://html.duckduckgo.com/html/)', 'https://html.duckduckgo.com/html/')
  NLI     : e=0.992  c=0.001  src=https://news.meaww.com/joe-bidens-epa-granted-50-m
  NLI     : e=0.996  c=0.001  src=https://www.foxnews.com/politics/biden-epa-granted
  NLI     : e=0.057  c=0.007  src=https://www.independentsentinel.com/admin-gave-50m
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/fake-news/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/askfactcheck/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/hot-topics/

Running text_only:  88%|████████▊ | 87/99 [17:36<03:43, 18.62s/it]

  NLI     : e=0.002  c=0.014  src=https://www.daveockop.com/latest-news/exclusive-tr
  NLI     : e=0.000  c=0.003  src=https://www.nytimes.com/athletic/6035527/2025/05/0
  NLI     : e=0.000  c=0.999  src=https://www.mirror.co.uk/sport/football/news/trent
  [FC REJECT] off-topic article: https://www.factcheck.org/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/the-factcheck-wire/

Running text_only:  89%|████████▉ | 88/99 [17:49<03:05, 16.83s/it]

  NLI     : e=0.487  c=0.379  src=https://thefilibusterblog.com/azealia-banks-consid
  [FC REJECT] off-topic article: https://www.factcheck.org/fake-news/
  [FC REJECT] off-topic article: https://www.factcheck.org/askfactcheck/
  NLI     : e=0.000  c=0.001  src=https://en.wikipedia.org/wiki/Megan_Thee_Stallion

Running text_only:  90%|████████▉ | 89/99 [18:04<02:41, 16.19s/it]

  DDG FC ERROR: ('error sending request for url (https://html.duckduckgo.com/html/)', 'https://html.duckduckgo.com/html/')
  NLI     : e=0.972  c=0.007  src=https://ca.news.yahoo.com/ukrainian-troops-pull-ar
  NLI     : e=0.995  c=0.000  src=https://m.independent.ie/world-news/europe/volodym
  NLI     : e=0.000  c=0.007  src=https://www.bbc.co.uk/news/live/world-europe-69015
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2023/may/26/tiktok-pos
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/issue/illegal-immigration/

Running text_only:  91%|█████████ | 90/99 [18:20<02:26, 16.32s/it]

  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/article/2026/jan/22/ice-immigrati
  NLI     : e=0.814  c=0.021  src=https://www.techarp.com/articles/elon-musk-nyc-mig
  [FC REJECT] off-topic article: https://api.politifact.com/factchecks/2019/jan/09/blog-posti
  NLI     : e=0.003  c=0.214  src=https://www.bbc.com/news/world-us-canada-42780382
  [FC REJECT] off-topic article: https://www.factcheck.org/issue/illegal-immigrants/
  DDG FC ERROR: ('error sending request for url (https://html.duckduckgo.com/html/)', 'https://html.duckduckgo.com/html/')
  NLI     : e=0.986  c=0.002  src=https://newsaddicts.com/russia-releases-evidence-p
  NLI     : e=0.992  c=0.001  src=https://thepeoplesvoice.tv/russia-releases-2000-pa

Running text_only:  92%|█████████▏| 91/99 [18:45<02:29, 18.73s/it]

  NLI     : e=0.812  c=0.016  src=https://darrellhines.net/2024/12/01/🚨breaking-news

Running text_only:  93%|█████████▎| 92/99 [19:11<02:27, 21.03s/it]

  DDG FC ERROR: ('error sending request for url (https://html.duckduckgo.com/html/)', 'https://html.duckduckgo.com/html/')
  NLI     : e=0.910  c=0.001  src=https://mhanys.org/mh_update/mhanys-response-to-go
  NLI     : e=0.998  c=0.000  src=https://www.foxnews.com/politics/new-york-gov-kath
  NLI     : e=0.008  c=0.006  src=https://www.yahoo.com/news/amid-shocking-crimes-ny

Running text_only:  94%|█████████▍| 93/99 [19:26<01:55, 19.23s/it]

  DDG FC ERROR: No results found.
  NLI     : e=0.028  c=0.139  src=https://en.wikipedia.org/wiki/7.7×58mm_Arisaka
  NLI     : e=0.005  c=0.003  src=https://www.mariowiki.com/World_7-7_(Super_Mario_B
  NLI     : e=0.081  c=0.254  src=https://www.youtube.com/watch?v=gwyqT7rcCYk
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/fake-news/

Running text_only:  95%|█████████▍| 94/99 [19:45<01:35, 19.15s/it]

  NLI     : e=0.993  c=0.002  src=https://wfin.com/fox-national-news/fbi-verifies-te
  NLI     : e=0.999  c=0.000  src=https://www.foxnews.com/us/las-vegas-suspect-ex-gi
  NLI [FC]: e=0.000  c=0.016  src=https://www.politifact.com/article/2025/jul/30/Sha
  NLI [FC]: e=0.000  c=0.007  src=https://www.politifact.com/article/2025/sep/12/Tyl

Running text_only:  96%|█████████▌| 95/99 [20:01<01:12, 18.23s/it]

  DDG FC ERROR: ('error sending request for url (https://html.duckduckgo.com/html/)', 'https://html.duckduckgo.com/html/')
  NLI     : e=0.001  c=0.001  src=https://www.abc.net.au/news/2025-03-23/gaza-death-
  NLI     : e=0.002  c=0.001  src=https://www.dw.com/en/israel-hamas-war-5000-killed
  NLI     : e=0.000  c=0.001  src=https://www.bbc.com/news/articles/clyz4nnqgvdo

Running text_only:  97%|█████████▋| 96/99 [20:19<00:53, 17.99s/it]

  DDG FC ERROR: ('error sending request for url (https://html.duckduckgo.com/html/)', 'https://html.duckduckgo.com/html/')
  NLI [FC]: e=0.028  c=0.955  src=https://checkyourfact.com/2024/01/25/fact-check-pu
  NLI [FC]: e=0.003  c=0.004  src=https://www.snopes.com/fact-check/putin-alaska-ill
  NLI     : e=0.000  c=0.999  src=https://lerthe61.github.io/factcheck-db/articles/f

Running text_only:  98%|█████████▊| 97/99 [20:31<00:32, 16.46s/it]

  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/askfactcheck/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/hot-topics/
  NLI     : e=0.001  c=0.000  src=https://www.npr.org/2026/04/03/nx-s1-5772611/blake
  NLI     : e=0.002  c=0.000  src=https://www.usmagazine.com/celebrity-news/news/bla
  NLI     : e=0.023  c=0.009  src=https://www.nytimes.com/2026/04/02/movies/blake-li
  [FC REJECT] off-topic article: https://www.factcheck.org/fake-news/

Running text_only:  99%|█████████▉| 98/99 [20:47<00:16, 16.08s/it]

  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/search/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/askfactcheck/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/hot-topics/
  NLI     : e=0.118  c=0.005  src=https://www.usmagazine.com/entertainment/news/mich
  NLI     : e=0.002  c=0.990  src=https://www.aol.com/madison-everything-know-michel
  NLI     : e=0.699  c=0.005  src=https://variety.com/2024/tv/news/michelle-pfeiffer
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/fake-news/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/askfactcheck/

Running text_only: 100%|██████████| 99/99 [20:58<00:00, 12.71s/it]

  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/search/factcheck/?q=who+raped+Jen
  NLI     : e=0.997  c=0.001  src=https://www.themirror.com/entertainment/jay-zs-rap
  NLI     : e=0.497  c=0.025  src=https://www.foxnews.com/entertainment/jay-zs-sexua
  NLI     : e=0.751  c=0.015  src=https://www.tmz.com/2024/12/13/jay-z-diddy-rape-ac
  NLI [FC]: e=0.042  c=0.018  src=https://www.politifact.com/factchecks/2024/oct/30/

============================================================
MODE: text_only
  mode                 text_only
  n_total              99
  n_valid              99
  n_error              0
  accuracy             0.697
  precision_macro      0.7271
  recall_macro         0.6988
  f1_macro             0.6878

Prediction distribution:
pred
FAKE    67
REAL    32
Name: count, dtype: int64

              precision    recall  f1-score   support

        FAKE       0.64      0.88      0.74        49
        REAL       0.81      0.52      0.63        50

    accuracy                           0.70        99
   macro avg       0.73      0.70      0.69        99
weighted avg       0.73      0.70      0.69        99


Confusion matrix (rows=true, cols=pred):
      FAKE  REAL
FAKE    43     6
REAL    24    26

Per-class correct/total:
  FAKE         43/49  (88%)
  REAL         26/50  (52%)
Saved: /content/ablation_v2_text_only.csv

Running text_clip:   1%|          | 1/99 [00:17<29:04, 17.80s/it]

  DDG FC ERROR: ('error sending request for url (https://html.duckduckgo.com/html/)', 'https://html.duckduckgo.com/html/')
  NLI     : e=0.958  c=0.004  src=https://www.reutersconnect.com/item/a-plume-of-smo
  NLI     : e=0.199  c=0.005  src=https://www.aljazeera.com/news/2026/3/2/israel-bom
  NLI     : e=0.047  c=0.049  src=https://www.nytimes.com/2026/04/11/world/middleeas

Running text_clip:   2%|▏         | 2/99 [00:37<30:47, 19.04s/it]

  DDG FC ERROR: ('error sending request for url (https://html.duckduckgo.com/html/)', 'https://html.duckduckgo.com/html/')
  NLI     : e=0.002  c=0.057  src=https://9mod.com/x.html
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/fake-news/
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/
  [FC SKIP] only 0 matches (need 1): https://fullfact.org/latest/
  NLI [FC]: e=0.010  c=0.001  src=https://www.factcheck.org/2025/01/republicans-wron
  NLI [FC]: e=0.993  c=0.000  src=https://www.politifact.com/factchecks/2025/jan/06/
  NLI     : e=0.005  c=0.000  src=https://www.independent.co.uk/news/world/americas/
  NLI     : e=0.993  c=0.001  src=https://www.aol.com/know-suspect-orleans-attack-18

Running text_clip:   4%|▍         | 4/99 [01:09<26:34, 16.79s/it]

  NLI     : e=0.002  c=0.003  src=https://northstarnewsletter.com/2023/04/12/behind-
  [FC REJECT] off-topic article: https://www.factcheck.org/2024/06/scicheck-antarctic-ice-los
  [FC REJECT] off-topic article: https://www.politifact.com/factchecks/2023/apr/25/instagram-
  NLI     : e=0.003  c=0.003  src=https://en.wikipedia.org/wiki/Robert_Falcon_Scott
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/ask-factcheck/ask-us-a-question/
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/tag/donald-trump/

Running text_clip:   5%|▌         | 5/99 [01:20<22:43, 14.50s/it]

  NLI     : e=0.001  c=0.000  src=https://www.indiatoday.in/fact-check/story/fact-ch
  [FC REJECT] off-topic article: https://fullfact.org/conflict/woman-cigarette-burning-pictur
  NLI     : e=0.001  c=0.001  src=https://www.npr.org/2022/10/03/1126603977/iran-mah
  [FC REJECT] off-topic article: https://www.politifact.com/islam/

Running text_clip:   6%|▌         | 6/99 [01:34<22:28, 14.51s/it]

  DDG FC ERROR: No results found.
  NLI     : e=0.001  c=0.001  src=https://www.usatoday.com/in-depth/news/politics/20
  NLI     : e=0.001  c=0.003  src=https://history.state.gov/milestones/1945-1952/chi
  NLI     : e=0.000  c=0.000  src=https://www.bbc.com/news/world-asia-china-22278037

Running text_clip:   7%|▋         | 7/99 [01:58<27:02, 17.63s/it]

  DDG FC ERROR: ('error sending request for url (https://html.duckduckgo.com/html/)', 'https://html.duckduckgo.com/html/')
  NLI     : e=0.228  c=0.569  src=https://allafrica.com/view/group/main/main/id/0009
  NLI     : e=0.999  c=0.001  src=https://www.aol.com/somaliland-opposition-leader-w
  NLI     : e=0.000  c=0.009  src=https://en.wikipedia.org/wiki/2024_Somaliland_pres
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/fake-news/

Running text_clip:   8%|▊         | 8/99 [02:11<24:19, 16.03s/it]

  NLI     : e=0.883  c=0.002  src=https://edition.cnn.com/2024/11/14/business/onion-
  NLI     : e=0.999  c=0.000  src=https://www.voanews.com/a/satirical-news-site-the-
  NLI     : e=0.999  c=0.000  src=https://www.nytimes.com/2024/11/14/business/media/
  [FC REJECT] off-topic article: https://www.snopes.com/tag/the-onion/

Running text_clip:   9%|▉         | 9/99 [02:33<26:45, 17.83s/it]

  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/fake-news/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/askfactcheck/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/truth-o-meter/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/hot-topics/
  NLI     : e=0.026  c=0.201  src=https://www.manchestereveningnews.co.uk/sport/foot
  NLI     : e=0.020  c=0.021  src=https://www.sportbible.com/football
  NLI     : e=0.005  c=0.012  src=https://www.bbc.co.uk/sport/football
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/fake-news/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/
  NLI     : e=0.035  c=0.551  src=https://www.mysanantonio.com/news/local/article/wh
  NLI     : e=0.022  c=0.032  src=https://www.yahoo.com/news/false-claim-mcconnells-
  NLI [FC]: e=0.013  c=0.899  src=https://www.politifact.com/factchecks/2024/mar/27/
  NLI     : e=0.060  c=0.198  src=https://www.thegatewaypundit.com/2024/02/sheriff-o

Running text_clip:  10%|█         | 10/99 [02:52<26:56, 18.16s/it]

  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/ask-factcheck/ask-us-a-question/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/truth-o-meter/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/2020/01/trump-administrations-shif
  NLI     : e=0.045  c=0.004  src=https://www.misbar.com/en/factcheck/2024/11/26/pho
  NLI [FC]: e=0.151  c=0.015  src=https://fullfact.org/news/israeli-sniper-false/
  NLI     : e=0.000  c=0.000  src=https://www.globalresearch.ca/heres-proof-that-isr

Running text_clip:  11%|█         | 11/99 [03:07<25:21, 17.29s/it]

  NLI     : e=0.003  c=0.002  src=https://en.wikipedia.org/wiki/Qassam_rocket
  DDG FC ERROR: ('error sending request for url (https://html.duckduckgo.com/html/)', 'https://html.duckduckgo.com/html/')
  NLI     : e=0.035  c=0.011  src=https://www.biography.com/crime/ted-bundy-childhoo
  NLI     : e=0.120  c=0.060  src=https://www.bbc.com/news/articles/c0r1xl5wgnko
  NLI     : e=0.027  c=0.002  src=https://theconversation.com/hamas-and-hezbollah-ho

Running text_clip:  12%|█▏        | 12/99 [03:31<28:18, 19.53s/it]

  DDG ERROR: ('error sending request for url (https://html.duckduckgo.com/html/)', 'https://html.duckduckgo.com/html/')

Running text_clip:  13%|█▎        | 13/99 [03:47<26:08, 18.24s/it]

  DDG FC ERROR: ('error sending request for url (https://html.duckduckgo.com/html/)', 'https://html.duckduckgo.com/html/')
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/facebook-fact-checks/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/2020/08/social-media-posts-use-gra
  [FC REJECT] off-topic article: https://www.factcheck.org/2018/11/california-shooting-prompt

Running text_clip:  14%|█▍        | 14/99 [04:08<26:55, 19.01s/it]

  NLI     : e=0.005  c=0.001  src=https://www.bellaonline.com/articles/art37257.asp
  NLI     : e=0.002  c=0.010  src=https://theconversation.com/why-women-including-fe
  NLI     : e=0.010  c=0.021  src=https://www.bbc.com/future/article/20260213-are-wo
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/fake-news/

Running text_clip:  15%|█▌        | 15/99 [04:26<26:35, 18.99s/it]

  NLI [FC]: e=0.042  c=0.022  src=https://fullfact.org/online/new-york-times-fake-he
  NLI [FC]: e=0.004  c=0.001  src=https://www.politifact.com/factchecks/2024/dec/11/
  NLI     : e=0.006  c=0.001  src=https://abc7news.com/post/unitedhealthcare-ceo-kil
  NLI     : e=0.002  c=0.001  src=https://www.aol.com/news/manhunt-underway-unitedhe

Running text_clip:  16%|█▌        | 16/99 [04:42<24:39, 17.83s/it]

  DDG FC ERROR: ('error sending request for url (https://html.duckduckgo.com/html/)', 'https://html.duckduckgo.com/html/')
  NLI     : e=0.145  c=0.084  src=https://www.amnestyindia.org/we-cant-be-a-recycled
  NLI     : e=0.007  c=0.003  src=https://www.thejc.com/life/books/noughties-nazis-a
  NLI     : e=0.003  c=0.057  src=https://www.jpost.com/international/did-nazis-chan
  DDG ERROR: ('error sending request for url (https://html.duckduckgo.com/html/)', 'https://html.duckduckgo.com/html/')
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/fake-news/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/
  [FC SKIP] only 0 matches (need 1): https://fullfact.org/environment/does-badger-culling-work/
  [FC REJECT] off-topic article: https://www.factcheck.org/
  [FC REJECT] off-topic article: https://www.snopes.com/fact-check/
  [FALLBACK] Using embedding similarity

Running text_clip:  18%|█▊        | 18/99 [05:13<23:05, 17.10s/it]

  DDG FC ERROR: ('error sending request for url (https://html.duckduckgo.com/html/)', 'https://html.duckduckgo.com/html/')
  NLI     : e=0.999  c=0.000  src=https://www.voanews.com/a/zelenskyy-says-trump-cou
  NLI     : e=0.209  c=0.002  src=https://www.aljazeera.com/news/2024/12/10/ukraines
  NLI     : e=0.004  c=0.002  src=https://www.aa.com.tr/en/russia-ukraine-war/zelens

Running text_clip:  19%|█▉        | 19/99 [05:30<22:49, 17.12s/it]

  DDG FC ERROR: ('error sending request for url (https://html.duckduckgo.com/html/)', 'https://html.duckduckgo.com/html/')
  NLI     : e=0.008  c=0.013  src=https://onceinabluemoon.ca/the-meaning-behind-oran
  NLI     : e=0.001  c=0.000  src=https://knowyourmeme.com/memes/orange-man-bad
  NLI     : e=0.004  c=0.001  src=https://meme.com/memes/orange-man-bad
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/fake-news/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/askfactcheck/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/

Running text_clip:  20%|██        | 20/99 [05:42<20:26, 15.52s/it]

  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/ask-factcheck/ask-us-a-question/
  [FC REJECT] off-topic article: https://fullfact.org/news/funerals-can-still-go-ahead-on-Mon
  NLI     : e=0.997  c=0.000  src=https://www.nytimes.com/2025/01/06/us/politics/jim
  NLI     : e=0.006  c=0.003  src=https://www.nps.gov/jica/carterlanding.htm
  NLI     : e=0.964  c=0.033  src=https://www.forbes.com/sites/mollybohannon/2025/01

Running text_clip:  21%|██        | 21/99 [05:51<17:39, 13.59s/it]

  NLI     : e=0.313  c=0.071  src=https://apnews.com/article/iran-explosions-israel-
  NLI     : e=0.045  c=0.002  src=https://www.aljazeera.com/news/2026/2/28/mapping-u
  NLI     : e=0.134  c=0.011  src=https://www.reuters.com/world/middle-east/israel-i
  [FC REJECT] off-topic article: https://www.factcheck.org/issue/israel-hamas-war/

Running text_clip:  22%|██▏       | 22/99 [06:10<19:17, 15.03s/it]

  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/elections/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/askfactcheck/
  NLI     : e=0.991  c=0.000  src=https://brutalist.report/topic/news?before=2024-12
  NLI     : e=0.979  c=0.001  src=https://texags.com/forums/16/topics/3520247
  [FC REJECT] off-topic article: https://www.politifact.com/article/2024/dec/30/fact-check-ex
  [FC REJECT] off-topic article: https://www.factcheck.org/person/jimmy-carter/
  DDG FC ERROR: ('error sending request for url (https://html.duckduckgo.com/html/)', 'https://html.duckduckgo.com/html/')
  NLI     : e=0.032  c=0.008  src=https://www.foxnews.com/us/fox-news-antisemitism-e
  NLI     : e=0.197  c=0.048  src=https://totalnews.com/fox-news-antisemitism-expose
  NLI     : e=0.002  c=0.009  src=https://www.foxnews.com/us/fox-news-antisemitism-e

Running text_clip:  24%|██▍       | 24/99 [06:45<20:46, 16.63s/it]

  DDG FC ERROR: ('error sending request for url (https://html.duckduckgo.com/html/)', 'https://html.duckduckgo.com/html/')
  NLI     : e=0.999  c=0.000  src=https://www.dw.com/en/biden-blocks-sale-of-us-stee
  NLI     : e=0.018  c=0.198  src=https://news.google.com/stories/CAAqNggKIjBDQklTSG
  NLI     : e=0.999  c=0.000  src=https://www.linkedin.com/pulse/us-president-biden-

Running text_clip:  25%|██▌       | 25/99 [06:58<19:27, 15.77s/it]

  DDG FC ERROR: ('error sending request for url (https://html.duckduckgo.com/html/)', 'https://html.duckduckgo.com/html/')
  NLI     : e=0.004  c=0.001  src=https://www.theguardian.com/us-news/ng-interactive
  NLI     : e=0.024  c=0.055  src=https://en.wikipedia.org/wiki/Indictments_against_
  NLI     : e=0.180  c=0.001  src=https://www.bbc.com/news/articles/cj0jr5ypqedo

Running text_clip:  26%|██▋       | 26/99 [07:11<18:07, 14.90s/it]

  DDG FC ERROR: No results found.
  NLI     : e=0.245  c=0.203  src=https://en.wikipedia.org/wiki/The_Ambassadors_(Hol
  NLI     : e=0.367  c=0.205  src=https://www.thehindu.com/entertainment/movies/anan
  NLI     : e=0.057  c=0.002  src=https://www.quora.com/

Running text_clip:  27%|██▋       | 27/99 [07:21<16:06, 13.42s/it]

  DDG FC ERROR: ('error sending request for url (https://html.duckduckgo.com/html/)', 'https://html.duckduckgo.com/html/')
  NLI     : e=0.043  c=0.244  src=https://www.distractify.com/p/these-people-arent-r
  NLI     : e=0.030  c=0.386  src=https://knowyourmeme.com/memes/chat-is-this-real
  NLI     : e=0.006  c=0.026  src=https://genius.com/Eazy-e-real-muthaphuckkin-gs-ly
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/fake-news/
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/collections/911-rumors-collection/
  NLI     : e=0.966  c=0.028  src=https://www.gbnews.com/news/world/lebanon-hand-hel
  [FC REJECT] off-topic article: https://www.politifact.com/factchecks/2025/dec/19/social-med
  NLI     : e=0.000  c=0.001  src=https://en.wikipedia.org/wiki/2024_Lebanon_electro
  [FC REJECT] off-topic article: https://www.factcheck.org/2021/11/how-many-died-as-a-result-

Running text_clip:  29%|██▉       | 29/99 [07:44<14:53, 12.77s/it]

  DDG FC ERROR: ('error sending request for url (https://html.duckduckgo.com/html/)', 'https://html.duckduckgo.com/html/')
  NLI     : e=0.968  c=0.008  src=https://www.aol.com/jamie-foxx-hit-glass-during-10
  NLI     : e=0.990  c=0.003  src=https://www.lbc.co.uk/article/jamie-foxx-glass-hea
  NLI     : e=0.001  c=0.001  src=https://www.bbc.co.uk/news/articles/c140e0pym6lo
  DDG ERROR: query is mandatory.

Running text_clip:  30%|███       | 30/99 [07:52<13:09, 11.44s/it]

  DDG FC ERROR: ('error sending request for url (https://html.duckduckgo.com/html/)', 'https://html.duckduckgo.com/html/')
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/fake-news/

Running text_clip:  31%|███▏      | 31/99 [08:09<14:50, 13.09s/it]

  NLI [FC]: e=0.003  c=0.008  src=https://www.politifact.com/factchecks/2026/mar/13/
  NLI     : e=0.994  c=0.001  src=https://www.theguardian.com/world/2026/apr/09/isra
  NLI [FC]: e=0.002  c=0.602  src=https://www.politifact.com/article/2026/mar/17/net
  NLI     : e=0.116  c=0.072  src=https://www.aljazeera.com/news/2026/4/8/netanyahu-
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/scicheck/

Running text_clip:  32%|███▏      | 32/99 [08:28<16:21, 14.65s/it]

  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/issues/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/article/2025/dec/29/2025-politifa
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/fact-check/
  NLI     : e=0.996  c=0.002  src=https://www.dailystar.co.uk/news/latest-news/new-d
  NLI     : e=0.996  c=0.000  src=https://www.bbc.co.uk/news/articles/clyx9nv4mleo
  NLI     : e=0.996  c=0.000  src=https://www.yodolenews.com/2025/01/02/new-bone-tes
  [FC REJECT] off-topic article: https://www.snopes.com/latest/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/issues/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/fake-news/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/truth-o-meter/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/search/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/article/
  [FC SKIP] only 0 matches (need 1): https://fullfact.org/latest/
  NLI     : e=0.000  c=0.000  src=https://archonnews.com/mayotte-grapples-with-water
  NLI     : e=0.002  c=0.001  src=https://staging.infonews.ca/news/4517609/authoriti
  NLI     : e=0.000  c=0.000  src=https://www.bbc.com/news/articles/c89x0j1le4lo

Running text_clip:  33%|███▎      | 33/99 [08:45<17:04, 15.52s/it]

  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/article/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/truth-o-meter/
  [FC SKIP] only 0 matches (need 1): https://fullfact.org/latest/
  NLI     : e=0.008  c=0.003  src=https://www.foxnews.com/media/biden-insider-expose
  NLI     : e=0.002  c=0.001  src=https://chicagofinancialtimes.com/2025/04/15/biden

Running text_clip:  34%|███▍      | 34/99 [08:59<16:21, 15.11s/it]

  NLI     : e=0.003  c=0.000  src=https://constitutionalrightspac.com/articles/embar
  [FC REJECT] off-topic article: https://www.factcheck.org/fake-news/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/
  [FC REJECT] off-topic article: https://fullfact.org/online/donald-trump-shooter-misidentifi

Running text_clip:  35%|███▌      | 35/99 [09:16<16:40, 15.63s/it]

  NLI     : e=0.116  c=0.004  src=https://www.fox5dc.com/news/person-interest-ceo-ki
  NLI     : e=0.132  c=0.204  src=https://www.fox5ny.com/news/luigi-mangione-ceo-sho
  NLI [FC]: e=0.001  c=0.012  src=https://www.politifact.com/factchecks/2024/jul/16/

Running text_clip:  36%|███▋      | 36/99 [09:43<19:49, 18.88s/it]

  NLI [FC]: e=0.004  c=0.001  src=https://fullfact.org/blog/2024/oct/a-year-of-fact-
  NLI     : e=0.010  c=0.689  src=https://www.nzherald.co.nz/world/israel-military-s
  NLI     : e=0.015  c=0.001  src=https://en.wikipedia.org/wiki/Yahya_Sinwar
  NLI     : e=0.002  c=0.008  src=https://au.news.yahoo.com/israel-says-may-killed-h
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/fake-news/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/list/?category=religio
  [FC REJECT] off-topic article: https://www.politifact.com/article/2025/sep/30/michigan-chur
  NLI     : e=0.002  c=0.006  src=https://www.dw.com/en/nigeria-evacuating-130-citiz
  [FC REJECT] off-topic article: https://www.factcheck.org/
  NLI     : e=0.001  c=0.000  src=https://www.aljazeera.com/news/2026/5/1/greek-orth

Running text_clip:  37%|███▋      | 37/99 [10:01<19:25, 18.80s/it]

  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/list/?category=sports
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/the-factcheck-wire/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/florida/
  [FC REJECT] off-topic article: https://www.factcheck.org/hot-topics/
  [FC REJECT] off-topic article: https://www.factcheck.org/issue/2000-presidential-election/
  NLI     : e=0.006  c=0.081  src=https://www.mixvale.com.br/2026/02/01/proof-of-ins

Running text_clip:  38%|███▊      | 38/99 [10:28<21:36, 21.25s/it]

  NLI     : e=0.004  c=0.509  src=https://www.talkie-ai.com/chat/sus-sprunki-1949251
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/fake-news/
  [FC SKIP] only 0 matches (need 1): https://fullfact.org/politics/mandelson-arrest-video-edited-
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/askfactcheck/

Running text_clip:  39%|███▉      | 39/99 [10:47<20:34, 20.58s/it]

  [FC REJECT] off-topic article: https://www.politifact.com/supreme-court/
  NLI [FC]: e=0.001  c=0.006  src=https://api.politifact.com/factchecks/2022/may/12/
  NLI     : e=0.001  c=0.000  src=https://relocateeurope.com/the-modern-judicial-sys
  NLI     : e=0.004  c=0.952  src=https://allaboutromance.com/presentation-at-court/

Running text_clip:  40%|████      | 40/99 [11:08<20:16, 20.62s/it]

  DDG FC ERROR: ('error sending request for url (https://html.duckduckgo.com/html/)', 'https://html.duckduckgo.com/html/')
  NLI     : e=0.988  c=0.001  src=https://www.thedetroitbureau.com/today-report/roma
  NLI     : e=0.001  c=0.001  src=https://www.bbc.com/news/world-europe-17776565
  NLI     : e=0.001  c=0.001  src=https://www.bbc.co.uk/news/world-europe-17776565

Running text_clip:  41%|████▏     | 41/99 [11:35<21:49, 22.57s/it]

  DDG FC ERROR: ('error sending request for url (https://html.duckduckgo.com/html/)', 'https://html.duckduckgo.com/html/')
  NLI     : e=0.000  c=0.000  src=https://www.bbc.co.uk/news/articles/cjdnkdg1l8do
  NLI     : e=0.727  c=0.000  src=https://sg.news.yahoo.com/chlamydia-starving-koala
  NLI     : e=0.001  c=0.000  src=https://www.bbc.com/news/articles/cjdnkdg1l8do

Running text_clip:  42%|████▏     | 42/99 [11:59<21:50, 22.99s/it]

  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/fake-news/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/askfactcheck/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/california/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/hot-topics/
  DDG FC ERROR: ('error sending request for url (https://html.duckduckgo.com/html/)', 'https://html.duckduckgo.com/html/')
  NLI     : e=0.005  c=0.033  src=https://dfrac.org/en/2024/02/13/fact-check-did-cap
  NLI     : e=0.046  c=0.002  src=https://tribune.com.pk/story/2469136/chris-evans-c
  NLI     : e=0.001  c=0.108  src=https://en.wikipedia.org/wiki/Captain_America

Running text_clip:  44%|████▍     | 44/99 [12:42<20:17, 22.14s/it]

  DDG FC ERROR: No results found.
  NLI     : e=0.216  c=0.019  src=https://www.medievalchronicles.com/medieval-tortur
  NLI     : e=0.025  c=0.715  src=https://en.wikipedia.org/wiki/Pear_of_anguish
  NLI     : e=0.002  c=0.004  src=https://allthatsinteresting.com/iron-maiden-device
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/list/?speaker_type=SOC
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/
  NLI     : e=0.994  c=0.002  src=https://www.mixedtimes.com/news/barron-trump-is-sm

Running text_clip:  45%|████▌     | 45/99 [12:51<16:20, 18.16s/it]

  NLI     : e=0.041  c=0.002  src=https://www.foxnews.com/travel/man-vacation-goes-v
  [FC REJECT] off-topic article: https://www.factcheck.org/fake-news/
  NLI     : e=0.016  c=0.009  src=https://www.euroki.org/koza/choose-between-the-pre
  DDG FC ERROR: No results found.
  NLI     : e=0.001  c=0.001  src=https://www.ctinsider.com/sports/uconn-mens-basket
  NLI     : e=0.002  c=0.006  src=https://www.foxnews.com/sports/uconns-dan-hurley-t
  NLI     : e=0.001  c=0.011  src=https://www.on3.com/news/seth-greenberg-criticizes

Running text_clip:  46%|████▋     | 46/99 [13:06<15:15, 17.28s/it]

  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/fake-news/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/
  NLI     : e=0.999  c=0.000  src=https://www.newsbreak.com/news/3713945766246-don-t
  NLI     : e=0.000  c=0.002  src=https://www.yahoo.com/entertainment/tv/articles/bo

Running text_clip:  47%|████▋     | 47/99 [13:23<14:49, 17.11s/it]

  NLI     : e=0.996  c=0.001  src=https://www.foxnews.com/media/scott-jennings-bakar
  NLI [FC]: e=0.000  c=0.001  src=https://www.politifact.com/personalities/scott-jen
  NLI     : e=0.000  c=0.001  src=https://www.theguardian.com/commentisfree/2026/apr
  NLI [FC]: e=0.001  c=0.003  src=https://www.politifact.com/personalities/donald-tr
  NLI     : e=0.010  c=0.014  src=https://en.wikipedia.org/wiki/List_of_United_State
  NLI     : e=0.000  c=0.001  src=https://theconversation.com/trump-survived-another

Running text_clip:  49%|████▉     | 49/99 [13:53<13:24, 16.09s/it]

  DDG FC ERROR: ('error sending request for url (https://html.duckduckgo.com/html/)', 'https://html.duckduckgo.com/html/')
  NLI     : e=0.000  c=0.000  src=https://livemorescreenless.org/blog/resource/the-c
  NLI     : e=0.000  c=0.001  src=https://www.nytimes.com/2025/06/18/opinion/parents
  NLI     : e=0.000  c=0.000  src=https://www.theatlantic.com/ideas/archive/2023/06/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/fake-news/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/

Running text_clip:  51%|█████     | 50/99 [14:18<15:08, 18.54s/it]

  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/hot-topics/
  NLI     : e=0.000  c=0.000  src=https://fastguardservice.com/texas-police-arrest-9
  NLI     : e=0.964  c=0.001  src=https://www.foxnews.com/us/texas-police-arrest-9-s
  NLI     : e=0.164  c=0.001  src=https://www.fox7austin.com/news/lakeline-mall-shop
  [FC REJECT] off-topic article: https://www.politifact.com/texas/

Running text_clip:  52%|█████▏    | 51/99 [14:39<15:25, 19.28s/it]

  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/search/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/truth-o-meter/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/fake-news/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/askfactcheck/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/hot-topics/
  NLI     : e=0.004  c=0.002  src=https://www.thelist.com/1755074/christina-haack-jo
  NLI     : e=0.998  c=0.000  src=https://www.realestate.com.au/news/sneak-peak-at-c
  NLI     : e=0.997  c=0.000  src=https://www.foxnews.com/entertainment/hgtv-star-ch
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/fake-news/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/california/
  [FC SKIP] only 0 matches (need 1): https://fullfact.org/latest/
  NLI [FC]: e=0.001  c=0.002  src=https://www.factcheck.org/hot-topics/

Running text_clip:  53%|█████▎    | 52/99 [14:55<14:22, 18.34s/it]

  NLI     : e=0.958  c=0.040  src=https://nypost.com/2025/12/07/us-news/portland-man
  NLI     : e=0.002  c=0.970  src=https://www.dailymail.com/news/article-4569638/Car
  NLI     : e=0.007  c=0.051  src=https://genius.com/Digital-descendant-it-doesnt-en

Running text_clip:  54%|█████▎    | 53/99 [15:21<15:50, 20.66s/it]

  DDG FC ERROR: ('error sending request for url (https://html.duckduckgo.com/html/)', 'https://html.duckduckgo.com/html/')
  NLI     : e=0.013  c=0.097  src=https://www.foxnews.com/us/hiker-stumbles-human-sk
  NLI     : e=0.998  c=0.001  src=https://www.wrganews.com/2026/04/23/hiker-stumbles
  NLI     : e=0.999  c=0.000  src=https://www.breakingnownews.com/mysterious-discove
  DDG FC ERROR: ('error sending request for url (https://html.duckduckgo.com/html/)', 'https://html.duckduckgo.com/html/')
  NLI     : e=0.017  c=0.001  src=https://cowboystatedaily.com/2024/10/11/wyomings-h
  NLI     : e=0.003  c=0.004  src=https://www.usatoday.com/story/news/factcheck/2024
  NLI     : e=0.009  c=0.001  src=https://www.vice.com/en/article/wyoming-wildfires-

Running text_clip:  56%|█████▌    | 55/99 [15:49<12:37, 17.22s/it]

  NLI [FC]: e=0.034  c=0.024  src=https://www.factcheck.org/2023/11/dozens-of-childr
  NLI     : e=0.998  c=0.001  src=https://www.theguardian.com/world/2024/nov/10/deaf
  NLI     : e=0.002  c=0.000  src=https://www.nytimes.com/2025/07/13/world/middleeas
  [FC REJECT] off-topic article: https://www.factcheck.org/issue/israel-hamas-war/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/fake-news/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/askfactcheck/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2021/aug/30/facebook-p
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/covid-misconceptions/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/article/2026/may/04/hantavirus-cr
  [FC REJECT] off-topic article: https://www.factcheck.org/hot-topics/
  NLI     : e=0.000  c=0.003  src=https://www.forbes.com/sites/maryroeloffs/2026/04/
  NLI     : e=0.000  c=0.002  src=https://factcheck.afp.com/doc.afp.com.34MA6NY

Running text_clip:  57%|█████▋    | 56/99 [16:00<10:58, 15.32s/it]

  NLI     : e=0.000  c=0.015  src=https://trumpstruth.org/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/askfactcheck/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/ask-factcheck/ask-us-a-question/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/artificial-intelligence/
  NLI [FC]: e=0.005  c=0.005  src=https://fullfact.org/economy/robots-and-your-job/
  NLI     : e=0.935  c=0.008  src=https://www.strategicstudyindia.com/2025/01/could-
  NLI     : e=0.001  c=0.000  src=https://www.bbc.co.uk/news/articles/cy7keddnj31o
  NLI     : e=0.001  c=0.000  src=https://www.linkedin.com/pulse/journey-closer-sun-

Running text_clip:  58%|█████▊    | 57/99 [16:23<12:31, 17.88s/it]

  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/fake-news/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/

Running text_clip:  59%|█████▊    | 58/99 [16:39<11:39, 17.06s/it]

  NLI [FC]: e=0.012  c=0.001  src=https://www.snopes.com/fact-check/keanu-reeves-who
  NLI     : e=0.020  c=0.026  src=https://news.meaww.com/fact-check-did-keanu-reeves
  NLI     : e=0.772  c=0.004  src=https://www.forbes.com/sites/mattnovak/2024/02/03/
  NLI [FC]: e=0.011  c=0.409  src=https://fullfact.org/online/keanu-reeves-matrix-fa
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/

Running text_clip:  60%|█████▉    | 59/99 [16:51<10:31, 15.79s/it]

  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/fake-news/
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/fact-check/
  NLI [FC]: e=0.000  c=0.001  src=https://www.politifact.com/factchecks/2024/may/21/
  NLI     : e=0.394  c=0.006  src=https://m-english.webdunia.com/article/deutsche-we
  NLI     : e=0.000  c=0.000  src=https://www.indiatoday.in/fact-check/story/iran-pr
  [FC REJECT] off-topic article: https://fullfact.org/online/italian-trucks-coronavirus-victi
  DDG ERROR: ('error sending request for url (https://html.duckduckgo.com/html/)', 'https://html.duckduckgo.com/html/')

Running text_clip:  61%|██████    | 60/99 [17:06<10:01, 15.43s/it]

  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/fake-news/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/the-factcheck-wire/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/askfactcheck/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/hot-topics/
  DDG FC ERROR: ('error sending request for url (https://html.duckduckgo.com/html/)', 'https://html.duckduckgo.com/html/')
  NLI     : e=0.326  c=0.005  src=https://dfrac.org/en/tag/elon-musk-en/
  NLI     : e=0.001  c=0.002  src=https://www.theguardian.com/technology/article/202

Running text_clip:  62%|██████▏   | 61/99 [17:22<09:48, 15.50s/it]

  NLI     : e=0.043  c=0.011  src=https://justthenews.com/world/europe/uk-police-chi
  NLI     : e=0.064  c=0.822  src=https://www.theguardian.com/world/live/2024/oct/29
  NLI     : e=0.897  c=0.007  src=https://www.gmanetwork.com/news/topstories/world/9
  NLI [FC]: e=0.022  c=0.005  src=https://www.politifact.com/article/2026/mar/02/the

Running text_clip:  63%|██████▎   | 62/99 [17:35<09:05, 14.75s/it]

  NLI [FC]: e=0.002  c=0.001  src=https://fullfact.org/blog/2024/oct/a-year-of-fact-

Running text_clip:  64%|██████▎   | 63/99 [17:47<08:28, 14.12s/it]

  DDG FC ERROR: ('error sending request for url (https://html.duckduckgo.com/html/)', 'https://html.duckduckgo.com/html/')
  NLI     : e=0.999  c=0.000  src=https://synctopic.com/article/mkAEjexn1f
  NLI     : e=0.998  c=0.000  src=https://www.mixedtimes.com/news/hezbollah-launches
  NLI     : e=0.003  c=0.613  src=https://www.bbc.com/news/articles/cdd560nvqqdo
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/fake-news/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/truth-o-meter/
  NLI     : e=0.008  c=0.002  src=https://www.lifezette.com/2025/01/unprotected-fren
  NLI [FC]: e=0.002  c=0.000  src=https://www.factcheck.org/2025/01/republicans-wron
  NLI [FC]: e=0.003  c=0.001  src=https://fullfact.org/online/new-orleans-police-bad
  NLI     : e=0.000  c=0.000  src=https://bklyn-ny.com/?p=7692

Running text_clip:  65%|██████▍   | 64/99 [18:04<08:36, 14.76s/it]

  DDG FC ERROR: ('error sending request for url (https://html.duckduckgo.com/html/)', 'https://html.duckduckgo.com/html/')
  NLI     : e=0.006  c=0.062  src=https://theconversation.com/hamas-and-hezbollah-ho
  NLI     : e=0.240  c=0.005  src=https://en.dailypakistan.com.pk/27-Nov-2024/israel
  NLI     : e=0.000  c=0.989  src=https://responsiblestatecraft.org/hamas-israel-war

Running text_clip:  67%|██████▋   | 66/99 [18:32<07:36, 13.82s/it]

  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/fake-news/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/issues/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/the-factcheck-wire/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/search/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/hot-topics/
  NLI     : e=0.001  c=0.000  src=https://www.bbc.com/news/world-us-canada-67915771
  NLI     : e=0.001  c=0.010  src=https://ifunny.co/picture/custom-jackets-are-used-
  NLI     : e=0.001  c=0.000  src=https://www.alaskaair.com/content/travel-info/bagg
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/

Running text_clip:  68%|██████▊   | 67/99 [18:44<07:11, 13.49s/it]

  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/fake-news/
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/
  [FC REJECT] off-topic article: https://www.factcheck.org/search/
  NLI     : e=0.219  c=0.189  src=https://aish.com/my-post-october-7th-trauma-an-int
  [FC REJECT] off-topic article: https://www.snopes.com/fact-check/
  NLI     : e=0.010  c=0.022  src=https://www.bbc.com/news/world-middle-east-6795826

Running text_clip:  69%|██████▊   | 68/99 [19:03<07:47, 15.06s/it]

  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/fake-news/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/askfactcheck/
  NLI     : e=0.923  c=0.005  src=https://9gag.com/gag/aBymp91
  NLI     : e=0.001  c=0.001  src=https://en.wikipedia.org/wiki/Venus
  NLI     : e=0.001  c=0.001  src=https://www.planetary.org/articles/every-picture-f

Running text_clip:  70%|██████▉   | 69/99 [19:25<08:29, 16.99s/it]

  DDG FC ERROR: ('error sending request for url (https://html.duckduckgo.com/html/)', 'https://html.duckduckgo.com/html/')
  NLI     : e=0.000  c=0.000  src=https://www.bbc.co.uk/news/articles/ce32n0eze87o
  NLI     : e=0.000  c=0.001  src=https://news.google.com/stories/CAAqNggKIjBDQklTSG
  NLI     : e=0.462  c=0.010  src=https://www.mirror.co.uk/news/uk-news/prince-andre

Running text_clip:  71%|███████   | 70/99 [19:45<08:38, 17.89s/it]

  DDG FC ERROR: ('error sending request for url (https://html.duckduckgo.com/html/)', 'https://html.duckduckgo.com/html/')
  NLI     : e=0.009  c=0.001  src=https://halifax.citynews.ca/2026/05/01/israel-stri
  NLI     : e=0.009  c=0.001  src=https://www.thenationalherald.com/israel-strikes-i
  NLI     : e=0.001  c=0.001  src=https://www.reuters.com/world/middle-east/hezbolla

Running text_clip:  72%|███████▏  | 71/99 [20:06<08:51, 19.00s/it]

  NLI [FC]: e=0.043  c=0.002  src=https://www.politifact.com/article/2026/mar/02/the
  NLI     : e=0.998  c=0.001  src=https://www.theguardian.com/world/2024/oct/26/idf-
  [FC REJECT] off-topic article: https://fullfact.org/conflict/video-compilation-iranian-base
  NLI     : e=0.012  c=0.273  src=https://www.reuters.com/graphics/IRAN-NUCLEAR/ISRA

Running text_clip:  73%|███████▎  | 72/99 [20:15<07:10, 15.94s/it]

  NLI     : e=0.086  c=0.013  src=https://apnews.com/article/israel-weapons-shipment
  NLI     : e=0.001  c=0.002  src=https://www.yahoo.com/news/biden-says-us-won-t-030
  NLI     : e=0.000  c=0.000  src=https://www.theyeshivaworld.com/news/israel-news/2
  NLI [FC]: e=0.016  c=0.004  src=https://www.politifact.com/factchecks/2024/nov/06/
  DDG FC ERROR: ('error sending request for url (https://html.duckduckgo.com/html/)', 'https://html.duckduckgo.com/html/')
  NLI     : e=0.991  c=0.004  src=https://www.mixedtimes.com/politics/fox-news-polit
  NLI     : e=0.003  c=0.969  src=https://www.spursfancave.com/tag/asia/
  NLI     : e=0.001  c=0.001  src=https://news.google.com/stories/CAAqNggKIjBDQklTSG

Running text_clip:  75%|███████▍  | 74/99 [20:58<07:38, 18.33s/it]

  DDG FC ERROR: ('error sending request for url (https://html.duckduckgo.com/html/)', 'https://html.duckduckgo.com/html/')
  NLI     : e=0.000  c=0.000  src=https://www.foxnews.com/tech/nasas-martian-helicop
  NLI     : e=0.000  c=0.000  src=https://www.nextgov.com/emerging-tech/2021/04/nasa
  NLI     : e=0.001  c=0.000  src=https://inews.co.uk/news/world/nasa-fly-helicopter

Running text_clip:  76%|███████▌  | 75/99 [21:10<06:36, 16.52s/it]

  DDG FC ERROR: ('error sending request for url (https://html.duckduckgo.com/html/)', 'https://html.duckduckgo.com/html/')
  NLI     : e=0.964  c=0.001  src=https://www.24vids.com/video/so-were-all-just-gonn
  NLI     : e=0.003  c=0.044  src=https://www.foxnews.com/sports/conor-mcgregor-lash
  NLI     : e=0.000  c=0.001  src=https://www.bbc.com/news/articles/cn5w50pw65yo

Running text_clip:  77%|███████▋  | 76/99 [21:26<06:12, 16.20s/it]

  DDG FC ERROR: No results found.
  NLI     : e=0.028  c=0.404  src=https://www.yahoo.com/news/articles/desantis-help-
  NLI     : e=0.088  c=0.057  src=https://www.usatoday.com/story/news/politics/2026/
  NLI     : e=0.016  c=0.891  src=https://trendingpoliticsnews.com/new-trump-republi

Running text_clip:  78%|███████▊  | 77/99 [21:43<06:07, 16.71s/it]

  [FC REJECT] off-topic article: https://www.factcheck.org/2016/08/trumps-false-obama-isis-li
  [FC REJECT] off-topic article: https://www.politifact.com/factchecks/2024/mar/28/alex-jones
  NLI     : e=0.001  c=0.000  src=https://www.foxnews.com/us/6-times-isis-has-inspir
  NLI     : e=0.000  c=0.000  src=https://www.adl.org/resources/article/islamist-ter
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/fake-news/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/fact-check-ratings/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/

Running text_clip:  79%|███████▉  | 78/99 [22:00<05:48, 16.60s/it]

  [FC REJECT] off-topic article: https://www.factcheck.org/hot-topics/
  NLI     : e=0.006  c=0.001  src=https://www.codemotion.com/magazine/cybersecurity/
  NLI     : e=0.000  c=0.002  src=https://www.foxnews.com/tech/revealed-10-most-popu
  [FC REJECT] off-topic article: https://fullfact.org/

Running text_clip:  80%|███████▉  | 79/99 [22:17<05:33, 16.67s/it]

  DDG FC ERROR: ('error sending request for url (https://html.duckduckgo.com/html/)', 'https://html.duckduckgo.com/html/')
  NLI     : e=0.004  c=0.025  src=https://www.nytimes.com/live/2024/09/23/world/gaza
  NLI     : e=0.000  c=0.997  src=https://www.youtube.com/watch?v=yEHTyY9nFrs
  NLI     : e=0.005  c=0.099  src=https://www.middleeasteye.net/live-blog/live-blog-
  DDG ERROR: ('error sending request for url (https://html.duckduckgo.com/html/)', 'https://html.duckduckgo.com/html/')

Running text_clip:  81%|████████  | 80/99 [22:37<05:36, 17.73s/it]

  NLI [FC]: e=0.001  c=0.016  src=https://www.snopes.com/collections/musk-rumors-col
  NLI [FC]: e=0.004  c=0.009  src=https://www.politifact.com/personalities/elon-musk
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/
  NLI [FC]: e=0.001  c=0.001  src=https://fullfact.org/world/us-nato-contributions/
  NLI     : e=0.001  c=0.001  src=https://www.theguardian.com/us-news/2025/apr/17/na
  [FC REJECT] off-topic article: https://www.factcheck.org/issue/nato/
  NLI     : e=0.001  c=0.002  src=https://www.bbc.com/news/articles/clyz4nq91wpo

Running text_clip:  82%|████████▏ | 81/99 [22:48<04:43, 15.77s/it]

  DDG ERROR: query is mandatory.

Running text_clip:  83%|████████▎ | 82/99 [22:56<03:49, 13.51s/it]

  DDG FC ERROR: ('error sending request for url (https://html.duckduckgo.com/html/)', 'https://html.duckduckgo.com/html/')
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/fake-news/

Running text_clip:  84%|████████▍ | 83/99 [23:12<03:45, 14.08s/it]

  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/doge/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/hot-topics/
  [FC REJECT] off-topic article: https://fullfact.org/us/donald-trump-ban-tesla-ai/
  [FC REJECT] off-topic article: https://www.politifact.com/personalities/elon-musk/
  NLI     : e=0.067  c=0.007  src=https://www.jalopnik.com/tesla-model-y-crash-in-ch
  NLI     : e=0.008  c=0.796  src=https://www.teslarati.com/tesla-model-3-brake-fail

Running text_clip:  85%|████████▍ | 84/99 [23:29<03:45, 15.05s/it]

  DDG FC ERROR: ('error sending request for url (https://html.duckduckgo.com/html/)', 'https://html.duckduckgo.com/html/')
  NLI     : e=0.004  c=0.321  src=https://thegrayzone.com/2025/09/12/charlie-kirk-ne
  NLI     : e=0.014  c=0.281  src=https://www.morgothsreview.com/p/the-anti-zionist-
  NLI     : e=0.003  c=0.128  src=https://www.bbc.com/news/topics/c302m85q5ljt

Running text_clip:  86%|████████▌ | 85/99 [23:48<03:45, 16.09s/it]

  DDG FC ERROR: ('error sending request for url (https://html.duckduckgo.com/html/)', 'https://html.duckduckgo.com/html/')
  NLI     : e=0.012  c=0.001  src=https://news.google.com/stories/CAAqNggKIjBDQklTSG
  NLI     : e=0.003  c=0.000  src=https://www.bbc.co.uk/news/articles/cj90wz8weymo.a
  NLI     : e=0.074  c=0.001  src=https://www.nytimes.com/2025/11/21/world/middleeas

Running text_clip:  87%|████████▋ | 86/99 [24:23<04:43, 21.78s/it]

  DDG FC ERROR: ('error sending request for url (https://html.duckduckgo.com/html/)', 'https://html.duckduckgo.com/html/')
  NLI     : e=0.992  c=0.001  src=https://news.meaww.com/joe-bidens-epa-granted-50-m
  NLI     : e=0.996  c=0.001  src=https://www.foxnews.com/politics/biden-epa-granted
  NLI     : e=0.057  c=0.007  src=https://www.independentsentinel.com/admin-gave-50m

Running text_clip:  88%|████████▊ | 87/99 [24:38<03:57, 19.82s/it]

  DDG FC ERROR: ('error sending request for url (https://html.duckduckgo.com/html/)', 'https://html.duckduckgo.com/html/')
  NLI     : e=0.002  c=0.014  src=https://www.daveockop.com/latest-news/exclusive-tr
  NLI     : e=0.000  c=0.003  src=https://www.nytimes.com/athletic/6035527/2025/05/0
  NLI     : e=0.000  c=0.999  src=https://www.mirror.co.uk/sport/football/news/trent
  DDG ERROR: ('error sending request for url (https://html.duckduckgo.com/html/)', 'https://html.duckduckgo.com/html/')

Running text_clip:  89%|████████▉ | 88/99 [24:54<03:25, 18.73s/it]

  DDG FC ERROR: No results found.

Running text_clip:  90%|████████▉ | 89/99 [25:08<02:53, 17.33s/it]

  DDG FC ERROR: ('error sending request for url (https://html.duckduckgo.com/html/)', 'https://html.duckduckgo.com/html/')
  NLI     : e=0.021  c=0.004  src=https://www.mirror.co.uk/news/world-news/breaking-
  NLI     : e=0.011  c=0.046  src=https://www.independent.co.uk/news/world/europe/uk
  NLI     : e=0.001  c=0.001  src=https://www.businessinsider.com/zelenskyy-cancels-

Running text_clip:  91%|█████████ | 90/99 [25:23<02:30, 16.68s/it]

  DDG FC ERROR: No results found.
  NLI     : e=0.196  c=0.043  src=https://www.usatoday.com/story/news/factcheck/2024
  NLI     : e=0.012  c=0.001  src=https://www.thecentersquare.com/california/article
  NLI     : e=0.000  c=0.003  src=https://www.foxnews.com/us/illegal-migrant-involve
  DDG FC ERROR: ('error sending request for url (https://html.duckduckgo.com/html/)', 'https://html.duckduckgo.com/html/')
  NLI     : e=0.986  c=0.002  src=https://newsaddicts.com/russia-releases-evidence-p
  NLI     : e=0.992  c=0.001  src=https://thepeoplesvoice.tv/russia-releases-2000-pa

Running text_clip:  92%|█████████▏| 91/99 [26:00<03:02, 22.81s/it]

  NLI     : e=0.945  c=0.004  src=https://www.healthhighroad.com/uncategorized/russi

Running text_clip:  93%|█████████▎| 92/99 [26:19<02:31, 21.63s/it]

  DDG FC ERROR: ('error sending request for url (https://html.duckduckgo.com/html/)', 'https://html.duckduckgo.com/html/')
  NLI     : e=0.910  c=0.001  src=https://mhanys.org/mh_update/mhanys-response-to-go
  NLI     : e=0.998  c=0.000  src=https://www.foxnews.com/politics/new-york-gov-kath
  NLI     : e=0.008  c=0.006  src=https://www.yahoo.com/news/amid-shocking-crimes-ny
  DDG FC ERROR: ('error sending request for url (https://html.duckduckgo.com/html/)', 'https://html.duckduckgo.com/html/')
  NLI     : e=0.028  c=0.139  src=https://en.wikipedia.org/wiki/7.7×58mm_Arisaka
  NLI     : e=0.005  c=0.003  src=https://www.mariowiki.com/World_7-7_(Super_Mario_B
  NLI     : e=0.081  c=0.254  src=https://www.youtube.com/watch?v=gwyqT7rcCYk

Running text_clip:  94%|█████████▍| 93/99 [26:33<01:56, 19.39s/it]

  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/fake-news/
  NLI     : e=0.993  c=0.002  src=https://wfin.com/fox-national-news/fbi-verifies-te
  NLI     : e=0.999  c=0.000  src=https://www.foxnews.com/us/las-vegas-suspect-ex-gi
  NLI [FC]: e=0.000  c=0.016  src=https://www.politifact.com/article/2025/jul/30/Sha
  NLI [FC]: e=0.000  c=0.007  src=https://www.politifact.com/article/2025/sep/12/Tyl

Running text_clip:  96%|█████████▌| 95/99 [27:05<01:10, 17.74s/it]

  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/
  NLI     : e=0.000  c=0.000  src=https://www.nytimes.com/2025/05/15/world/middleeas
  NLI     : e=0.002  c=0.001  src=https://www.dw.com/en/israel-hamas-war-5000-killed
  [FC REJECT] off-topic article: https://www.factcheck.org/issue/israel-hamas-war/
  NLI [FC]: e=0.001  c=0.000  src=https://fullfact.org/israel-gaza-conflict/

Running text_clip:  97%|█████████▋| 96/99 [27:23<00:53, 17.76s/it]

  DDG FC ERROR: ('error sending request for url (https://html.duckduckgo.com/html/)', 'https://html.duckduckgo.com/html/')
  NLI [FC]: e=0.028  c=0.955  src=https://checkyourfact.com/2024/01/25/fact-check-pu
  NLI [FC]: e=0.003  c=0.004  src=https://www.snopes.com/fact-check/putin-alaska-ill
  NLI     : e=0.000  c=0.999  src=https://lerthe61.github.io/factcheck-db/articles/f

Running text_clip:  98%|█████████▊| 97/99 [27:32<00:30, 15.03s/it]

  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/askfactcheck/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/hot-topics/
  NLI     : e=0.000  c=0.021  src=https://www.bbc.co.uk/news/articles/c9q7pxnr4g2o
  NLI     : e=0.523  c=0.005  src=https://news.google.com/stories/CAAqNggKIjBDQklTSG
  NLI     : e=0.000  c=0.003  src=https://saudigazette.com.sa/article/648126
  [FC REJECT] off-topic article: https://www.factcheck.org/fake-news/

Running text_clip:  99%|█████████▉| 98/99 [27:45<00:14, 14.70s/it]

  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/search/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/askfactcheck/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/hot-topics/
  NLI     : e=0.981  c=0.002  src=https://www.aol.com/madison-michelle-pfeiffer-star
  NLI     : e=0.118  c=0.005  src=https://www.usmagazine.com/entertainment/news/mich
  NLI     : e=0.001  c=0.986  src=https://www.yahoo.com/entertainment/tv/articles/ma
  DDG FC ERROR: ('error sending request for url (https://html.duckduckgo.com/html/)', 'https://html.duckduckgo.com/html/')
  NLI     : e=0.997  c=0.001  src=https://www.themirror.com/entertainment/jay-zs-rap
  NLI     : e=0.497  c=0.025  src=https://www.foxnews.com/entertainment/jay-zs-sexua
  NLI     : e=0.751  c=0.015  src=https://www.tmz.com/2024/12/13/jay-z-diddy-rape-ac

Running text_clip: 100%|██████████| 99/99 [28:00<00:00, 16.97s/it]

============================================================
MODE: text_clip
  mode                 text_clip
  n_total              99
  n_valid              99
  n_error              0
  accuracy             0.7071
  precision_macro      0.7281
  recall_macro         0.7086
  f1_macro             0.7011

Prediction distribution:
pred
FAKE    64
REAL    35
Name: count, dtype: int64

              precision    recall  f1-score   support

        FAKE       0.66      0.86      0.74        49
        REAL       0.80      0.56      0.66        50

    accuracy                           0.71        99
   macro avg       0.73      0.71      0.70        99
weighted avg       0.73      0.71      0.70        99


Confusion matrix (rows=true, cols=pred):
      FAKE  REAL
FAKE    42     7
REAL    22    28

Per-class correct/total:
  FAKE         42/49  (86%)
  REAL         28/50  (56%)
Saved: /content/ablation_v2_text_clip.csv

Running text_clip_ocr:   0%|          | 0/99 [00:00<?, ?it/s]

  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/article/2026/mar/02/these-videos-
  NLI [FC]: e=0.828  c=0.021  src=https://www.politifact.com/factchecks/2025/jun/23/
  NLI     : e=0.013  c=0.006  src=https://www.jpost.com/israel-news/defense-news/art
  NLI     : e=0.191  c=0.126  src=https://indianexpress.com/article/world/israel-hez
  NLI [FC]: e=0.073  c=0.006  src=https://www.factcheck.org/issue/israel-hamas-war/

Running text_clip_ocr:   1%|          | 1/99 [00:19<32:19, 19.79s/it]

  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/fake-news/

Running text_clip_ocr:   2%|▏         | 2/99 [00:29<22:32, 13.95s/it]

  NLI [FC]: e=0.001  c=0.004  src=https://www.politifact.com/article/2023/oct/23/how
  [FC REJECT] off-topic article: https://fullfact.org/online/list-organisations-no-longer-pos
  NLI     : e=0.002  c=0.057  src=https://9mod.com/x.html
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/fake-news/
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/
  [FC SKIP] only 0 matches (need 1): https://fullfact.org/latest/
  NLI [FC]: e=0.010  c=0.001  src=https://www.factcheck.org/2025/01/republicans-wron
  NLI [FC]: e=0.993  c=0.000  src=https://www.politifact.com/factchecks/2025/jan/06/
  NLI     : e=0.005  c=0.000  src=https://www.independent.co.uk/news/world/americas/
  NLI     : e=0.993  c=0.001  src=https://www.aol.com/know-suspect-orleans-attack-18

Running text_clip_ocr:   3%|▎         | 3/99 [00:39<18:59, 11.87s/it]

  DDG FC ERROR: ('error sending request for url (https://html.duckduckgo.com/html/)', 'https://html.duckduckgo.com/html/')
  NLI     : e=0.002  c=0.003  src=https://northstarnewsletter.com/2023/04/12/behind-
  NLI     : e=0.003  c=0.003  src=https://en.wikipedia.org/wiki/Robert_Falcon_Scott
  NLI     : e=0.016  c=0.011  src=https://www.bbc.com/news/magazine-15384729

Running text_clip_ocr:   4%|▍         | 4/99 [00:51<19:25, 12.27s/it]

  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/ask-factcheck/ask-us-a-question/
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/tag/donald-trump/

Running text_clip_ocr:   5%|▌         | 5/99 [01:14<25:17, 16.14s/it]

  NLI     : e=0.002  c=0.039  src=https://observers.france24.com/en/europe/20240709-
  [FC REJECT] off-topic article: https://fullfact.org/conflict/woman-cigarette-burning-pictur
  NLI     : e=0.005  c=0.282  src=https://pesacheck.org/false-this-video-doesnt-show
  NLI     : e=0.000  c=0.002  src=https://www.dogrula.org/en/fact-checks/was-the-vid
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/fake-news/

Running text_clip_ocr:   6%|▌         | 6/99 [01:23<20:56, 13.51s/it]

  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/location/china/
  NLI     : e=0.002  c=0.002  src=https://www.boomlive.in/fact-check/factcheck-mosqu
  NLI [FC]: e=0.004  c=0.559  src=https://checkyourfact.com/2024/02/14/fact-check-vi
  NLI     : e=0.001  c=0.001  src=https://southafrica-info.com/fact-checks/chinese-g
  [FC REJECT] off-topic article: https://fullfact.org/online/china-mosque-demolition-false/

Running text_clip_ocr:   7%|▋         | 7/99 [01:42<23:20, 15.23s/it]

  DDG FC ERROR: No results found.
  NLI     : e=0.108  c=0.003  src=https://apnews.com/article/somaliland-presidential
  NLI     : e=0.999  c=0.000  src=https://ghanaiantimes.com.gh/somaliland-opposition
  NLI     : e=0.000  c=0.009  src=https://en.wikipedia.org/wiki/2024_Somaliland_pres

Running text_clip_ocr:   8%|▊         | 8/99 [02:00<24:24, 16.09s/it]

  DDG FC ERROR: ('error sending request for url (https://html.duckduckgo.com/html/)', 'https://html.duckduckgo.com/html/')
  NLI     : e=0.883  c=0.002  src=https://edition.cnn.com/2024/11/14/business/onion-
  NLI     : e=0.999  c=0.000  src=https://www.voanews.com/a/satirical-news-site-the-
  NLI     : e=0.999  c=0.000  src=https://www.nytimes.com/2024/11/14/business/media/
  DDG ERROR: ('error sending request for url (https://html.duckduckgo.com/html/)', 'https://html.duckduckgo.com/html/')

Running text_clip_ocr:   9%|▉         | 9/99 [02:14<23:30, 15.67s/it]

  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/fake-news/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/askfactcheck/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/truth-o-meter/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/hot-topics/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/fake-news/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/
  NLI     : e=0.035  c=0.551  src=https://www.mysanantonio.com/news/local/article/wh
  NLI     : e=0.022  c=0.032  src=https://www.yahoo.com/news/false-claim-mcconnells-
  NLI [FC]: e=0.013  c=0.899  src=https://www.politifact.com/factchecks/2024/mar/27/

Running text_clip_ocr:  10%|█         | 10/99 [02:45<30:06, 20.30s/it]

  NLI     : e=0.060  c=0.198  src=https://www.thegatewaypundit.com/2024/02/sheriff-o
  DDG FC ERROR: ('error sending request for url (https://html.duckduckgo.com/html/)', 'https://html.duckduckgo.com/html/')
  NLI     : e=0.045  c=0.004  src=https://www.misbar.com/en/factcheck/2024/11/26/pho
  NLI     : e=0.000  c=0.000  src=https://www.globalresearch.ca/heres-proof-that-isr
  NLI     : e=0.003  c=0.002  src=https://en.wikipedia.org/wiki/Qassam_rocket

Running text_clip_ocr:  11%|█         | 11/99 [02:59<27:01, 18.42s/it]

  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/fake-news/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/crime/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/askfactcheck/

Running text_clip_ocr:  12%|█▏        | 12/99 [03:21<28:25, 19.61s/it]

  [FC REJECT] off-topic article: https://www.politifact.com/article/2016/dec/31/hillary-clint
  [FC REJECT] off-topic article: https://fullfact.org/hoaxes/baby-killer-on-run-hoaxes/
  NLI     : e=0.006  c=0.001  src=https://jodasgreat.github.io/harpy/0260
  NLI     : e=0.035  c=0.011  src=https://www.biography.com/crime/ted-bundy-childhoo
  DDG ERROR: ('error sending request for url (https://html.duckduckgo.com/html/)', 'https://html.duckduckgo.com/html/')
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/

Running text_clip_ocr:  13%|█▎        | 13/99 [03:38<26:51, 18.74s/it]

  [FC REJECT] off-topic article: https://www.factcheck.org/fake-news/
  [FC REJECT] off-topic article: https://www.snopes.com/fact-check/
  [FALLBACK] Using embedding similarity
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/facebook-fact-checks/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/2020/08/social-media-posts-use-gra
  [FC REJECT] off-topic article: https://www.factcheck.org/2018/11/california-shooting-prompt
  NLI     : e=0.005  c=0.001  src=https://www.bellaonline.com/articles/art37257.asp
  NLI     : e=0.010  c=0.021  src=https://www.bbc.com/future/article/20260213-are-wo

Running text_clip_ocr:  14%|█▍        | 14/99 [03:55<25:42, 18.14s/it]

  NLI     : e=0.000  c=0.001  src=https://www.familyeducation.com/naming-trends/102-

Running text_clip_ocr:  15%|█▌        | 15/99 [04:07<22:55, 16.38s/it]

  DDG FC ERROR: ('error sending request for url (https://html.duckduckgo.com/html/)', 'https://html.duckduckgo.com/html/')
  NLI     : e=0.006  c=0.001  src=https://www.bbc.co.uk/news/articles/c24nrynq0elo
  NLI     : e=0.005  c=0.001  src=https://www.businessinsider.com/ex-prosecutors-exp
  NLI     : e=0.002  c=0.989  src=https://www.bbc.co.uk/news/videos/c3e37ywg8dwo

Running text_clip_ocr:  16%|█▌        | 16/99 [04:22<21:51, 15.80s/it]

  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/fake-news/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/article/
  [FC SKIP] only 0 matches (need 1): https://fullfact.org/online/nazi-dissolved-parliament/
  NLI     : e=0.145  c=0.084  src=https://www.amnestyindia.org/we-cant-be-a-recycled
  NLI     : e=0.013  c=0.008  src=https://news-pravda.com/world/2026/01/02/1966179.h
  NLI     : e=0.022  c=0.071  src=https://www.academia.edu/37302420/Bones_of_Content
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/fake-news/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/
  [FC SKIP] only 0 matches (need 1): https://fullfact.org/environment/does-badger-culling-work/
  [FC REJECT] off-topic article: https://www.factcheck.org/
  [FC REJECT] off-topic article: https://www.snopes.com/fact-check/
  NLI     : e=0.146  c=0.090  src=https://shotkit.com/aftershoot-review/
  NLI     : e=0.018  c=0.200  src=https://aftershoot.com/

Running text_clip_ocr:  17%|█▋        | 17/99 [04:39<22:19, 16.33s/it]

  DDG FC ERROR: ('error sending request for url (https://html.duckduckgo.com/html/)', 'https://html.duckduckgo.com/html/')
  NLI [FC]: e=0.000  c=0.000  src=https://www.politifact.com/article/2025/aug/18/tru
  NLI     : e=0.017  c=0.002  src=https://apnews.com/article/russia-ukraine-war-trum

Running text_clip_ocr:  18%|█▊        | 18/99 [04:53<21:02, 15.58s/it]

  NLI     : e=0.692  c=0.008  src=https://www.aljazeera.com/news/2025/12/26/zelensky
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/truth-o-meter/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/california/

Running text_clip_ocr:  19%|█▉        | 19/99 [05:02<17:56, 13.45s/it]

  NLI     : e=0.002  c=0.003  src=https://www.yahoo.com/news/open-mic-night-supreme-
  NLI     : e=0.001  c=0.002  src=https://www.theguardian.com/commentisfree/2026/apr
  [FC REJECT] off-topic article: https://www.factcheck.org/the-factcheck-wire/
  NLI [FC]: e=0.001  c=0.000  src=https://www.factcheck.org/askfactcheck/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/fake-news/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/askfactcheck/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/

Running text_clip_ocr:  20%|██        | 20/99 [05:15<17:30, 13.30s/it]

  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/ask-factcheck/ask-us-a-question/
  [FC REJECT] off-topic article: https://fullfact.org/news/funerals-can-still-go-ahead-on-Mon
  NLI     : e=0.006  c=0.003  src=https://www.nps.gov/jica/carterlanding.htm
  NLI     : e=0.964  c=0.033  src=https://www.forbes.com/sites/mollybohannon/2025/01
  NLI     : e=0.957  c=0.006  src=https://www.archives.gov/press/press-releases/2025

Running text_clip_ocr:  21%|██        | 21/99 [05:33<19:13, 14.79s/it]

  NLI     : e=0.117  c=0.009  src=https://www.latimes.com/world-nation/story/2025-06
  NLI     : e=0.019  c=0.004  src=https://www.aljazeera.com/news/2026/2/28/us-and-is
  NLI     : e=0.006  c=0.003  src=https://www.bbc.com/news/articles/crr7gdr82e0o
  [FC REJECT] off-topic article: https://www.factcheck.org/issue/israel-hamas-war/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/elections/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/askfactcheck/
  NLI     : e=0.000  c=0.001  src=https://www.foxnews.com/media/carter-feuded-succes
  NLI     : e=0.000  c=0.001  src=https://scconstables.org/2024/12/30/carter-feuded-

Running text_clip_ocr:  22%|██▏       | 22/99 [05:41<16:33, 12.90s/it]

  NLI     : e=0.000  c=0.001  src=https://investor.wedbush.com/wedbush/news/read/444
  [FC REJECT] off-topic article: https://www.politifact.com/article/2024/dec/30/fact-check-ex

Running text_clip_ocr:  23%|██▎       | 23/99 [05:51<15:11, 12.00s/it]

  NLI     : e=0.971  c=0.006  src=https://qthzb.com/category/columns/antisemitism-ex
  [FC REJECT] off-topic article: https://www.politifact.com/article/2022/may/19/tucker-carlso
  NLI [FC]: e=0.003  c=0.004  src=https://www.factcheck.org/2023/11/cruz-distorts-fa
  NLI     : e=0.001  c=0.004  src=https://www.foxnews.com/us/fox-news-antisemitism-e

Running text_clip_ocr:  24%|██▍       | 24/99 [06:11<17:47, 14.24s/it]

  DDG FC ERROR: ('error sending request for url (https://html.duckduckgo.com/html/)', 'https://html.duckduckgo.com/html/')
  NLI     : e=0.999  c=0.000  src=https://www.theguardian.com/us-news/2025/jan/03/us
  NLI     : e=0.999  c=0.000  src=https://www.dw.com/en/biden-blocks-sale-of-us-stee
  NLI     : e=0.999  c=0.000  src=https://www.linkedin.com/pulse/us-president-biden-

Running text_clip_ocr:  25%|██▌       | 25/99 [06:31<19:39, 15.94s/it]

  NLI [FC]: e=0.678  c=0.163  src=https://www.politifact.com/factchecks/2025/jan/07/
  NLI [FC]: e=0.066  c=0.017  src=https://www.factcheck.org/2024/11/trump-won-the-po
  NLI     : e=0.004  c=0.001  src=https://www.theguardian.com/us-news/ng-interactive
  NLI     : e=0.024  c=0.055  src=https://en.wikipedia.org/wiki/Indictments_against_

Running text_clip_ocr:  26%|██▋       | 26/99 [06:52<21:15, 17.47s/it]

  DDG FC ERROR: ('error sending request for url (https://html.duckduckgo.com/html/)', 'https://html.duckduckgo.com/html/')
  NLI     : e=0.994  c=0.000  src=https://www.youtube.com/watch?v=UFVK-os5eSo
  NLI     : e=0.997  c=0.001  src=https://nz.news.yahoo.com/remembering-man-became-i
  NLI     : e=0.020  c=0.001  src=https://www.bbc.com/news/articles/c2exzm9r043o?at_

Running text_clip_ocr:  27%|██▋       | 27/99 [07:09<20:58, 17.48s/it]

  DDG FC ERROR: ('error sending request for url (https://html.duckduckgo.com/html/)', 'https://html.duckduckgo.com/html/')
  NLI     : e=0.019  c=0.676  src=https://www.getyarn.io/yarn-clip/c6cef0ec-6dae-471
  NLI     : e=0.000  c=0.000  src=https://james.cridland.net/blog/2020/hey-com-email
  NLI     : e=0.010  c=0.774  src=https://grammarkup.vercel.app/learn/beginner/demon
  DDG FC ERROR: ('error sending request for url (https://html.duckduckgo.com/html/)', 'https://html.duckduckgo.com/html/')
  NLI     : e=0.966  c=0.028  src=https://www.gbnews.com/news/world/lebanon-hand-hel
  NLI     : e=0.000  c=0.001  src=https://en.wikipedia.org/wiki/2024_Lebanon_electro

Running text_clip_ocr:  28%|██▊       | 28/99 [07:24<19:44, 16.68s/it]

  NLI     : e=0.000  c=0.001  src=https://www.bbc.com/news/articles/cz04m913m49o
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/fake-news/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/askfactcheck/
  NLI [FC]: e=0.001  c=0.798  src=https://www.politifact.com/factchecks/2023/may/16/
  NLI [FC]: e=0.001  c=0.937  src=https://www.politifact.com/factchecks/2023/jun/05/
  NLI     : e=0.003  c=0.146  src=https://www.independent.co.uk/arts-entertainment/f
  NLI     : e=0.968  c=0.008  src=https://www.aol.com/jamie-foxx-hit-glass-during-10

Running text_clip_ocr:  29%|██▉       | 29/99 [07:32<16:28, 14.12s/it]

  DDG ERROR: query is mandatory.

Running text_clip_ocr:  30%|███       | 30/99 [07:34<12:00, 10.44s/it]

  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/fake-news/
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/top/
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/category/politics/
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/fact-check/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/fake-news/

Running text_clip_ocr:  31%|███▏      | 31/99 [07:58<16:37, 14.68s/it]

  NLI     : e=0.012  c=0.001  src=https://www.abc.net.au/news/2024-09-27/netanyahu-d
  NLI     : e=0.999  c=0.000  src=https://cloudflare.egyptindependent.com/netanyahu-
  NLI [FC]: e=0.003  c=0.008  src=https://www.politifact.com/factchecks/2026/mar/13/
  NLI [FC]: e=0.002  c=0.602  src=https://www.politifact.com/article/2026/mar/17/net
  DDG FC ERROR: ('error sending request for url (https://html.duckduckgo.com/html/)', 'https://html.duckduckgo.com/html/')
  NLI     : e=0.996  c=0.002  src=https://www.dailystar.co.uk/news/latest-news/new-d
  NLI     : e=0.986  c=0.002  src=https://www.youtube.com/watch?v=5eErDIRHC3g
  NLI     : e=0.996  c=0.000  src=https://www.bbc.co.uk/news/articles/clyx9nv4mleo

Running text_clip_ocr:  32%|███▏      | 32/99 [08:14<16:42, 14.96s/it]

  DDG FC ERROR: ('error sending request for url (https://html.duckduckgo.com/html/)', 'https://html.duckduckgo.com/html/')
  NLI     : e=0.000  c=0.001  src=https://usnn.com/mayotte-imposes-curfew-and-rushes
  NLI     : e=0.000  c=0.000  src=https://www.bbc.com/news/articles/c89x0j1le4lo
  NLI     : e=0.001  c=0.000  src=https://btw.co/node/5213795/mayotte-cyclone/

Running text_clip_ocr:  33%|███▎      | 33/99 [08:26<15:26, 14.04s/it]

  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/article/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/truth-o-meter/
  [FC SKIP] only 0 matches (need 1): https://fullfact.org/latest/
  NLI     : e=0.001  c=0.000  src=https://planetchronicle.net/media/liberal-media-fi
  NLI     : e=0.007  c=0.001  src=https://www.foxnews.com/media/embarrassingly-wrong

Running text_clip_ocr:  34%|███▍      | 34/99 [08:34<13:21, 12.34s/it]

  NLI     : e=0.002  c=0.022  src=https://satoji.com/embarrassingly-wrong-liberal-me
  [FC REJECT] off-topic article: https://www.factcheck.org/fake-news/

Running text_clip_ocr:  35%|███▌      | 35/99 [08:54<15:29, 14.53s/it]

  DDG FC ERROR: ('error sending request for url (https://html.duckduckgo.com/html/)', 'https://html.duckduckgo.com/html/')
  NLI     : e=0.116  c=0.004  src=https://www.fox5dc.com/news/person-interest-ceo-ki
  NLI     : e=0.132  c=0.204  src=https://www.fox5ny.com/news/luigi-mangione-ceo-sho
  NLI     : e=0.938  c=0.002  src=https://www.newsweek.com/luigi-mangione-five-unans
  DDG FC ERROR: ('error sending request for url (https://html.duckduckgo.com/html/)', 'https://html.duckduckgo.com/html/')
  NLI     : e=0.000  c=0.001  src=https://www.theguardian.com/world/live/2025/may/31
  NLI     : e=0.015  c=0.001  src=https://en.wikipedia.org/wiki/Yahya_Sinwar
  NLI     : e=0.000  c=0.000  src=https://apnews.com/hub/israel-hamas-war

Running text_clip_ocr:  37%|███▋      | 37/99 [09:21<14:16, 13.82s/it]

  DDG FC ERROR: ('error sending request for url (https://html.duckduckgo.com/html/)', 'https://html.duckduckgo.com/html/')
  NLI     : e=0.000  c=0.002  src=https://www.christianpost.com/news/violent-attacks
  NLI     : e=0.005  c=0.003  src=https://www.newsweek.com/christians-extreme-persec
  NLI     : e=0.001  c=0.001  src=https://zenit.org/2025/09/06/a-global-surge-in-ant

Running text_clip_ocr:  38%|███▊      | 38/99 [09:36<14:27, 14.22s/it]

  DDG FC ERROR: No results found.
  NLI     : e=0.001  c=0.004  src=https://app.wertinsaat.com/viral/jepang-sus/
  NLI     : e=0.006  c=0.081  src=https://www.mixvale.com.br/2026/02/01/proof-of-ins
  NLI     : e=0.004  c=0.293  src=https://aplikasi.mendatica.com/viral/jepang-sus/pa

Running text_clip_ocr:  39%|███▉      | 39/99 [09:49<13:50, 13.85s/it]

  DDG FC ERROR: ('error sending request for url (https://html.duckduckgo.com/html/)', 'https://html.duckduckgo.com/html/')
  NLI     : e=0.005  c=0.001  src=https://www.clevelandart.org/articles/women-court
  NLI     : e=0.001  c=0.000  src=https://relocateeurope.com/the-modern-judicial-sys
  NLI     : e=0.003  c=0.005  src=https://www.aiease.ai/ai-replace/ai-clothes-change
  DDG FC ERROR: ('error sending request for url (https://html.duckduckgo.com/html/)', 'https://html.duckduckgo.com/html/')
  NLI     : e=0.988  c=0.001  src=https://www.thedetroitbureau.com/today-report/roma
  NLI     : e=0.001  c=0.001  src=https://www.bbc.com/news/world-europe-17776565
  NLI     : e=0.001  c=0.001  src=https://www.bbc.co.uk/news/world-europe-17776565

Running text_clip_ocr:  41%|████▏     | 41/99 [10:21<14:23, 14.88s/it]

  DDG FC ERROR: ('error sending request for url (https://html.duckduckgo.com/html/)', 'https://html.duckduckgo.com/html/')
  NLI     : e=0.997  c=0.000  src=https://lunaticoutpost.com/thread-397838.html
  NLI     : e=0.000  c=0.000  src=https://www.bbc.co.uk/news/articles/cjdnkdg1l8do
  NLI     : e=0.001  c=0.000  src=https://www.bbc.com/news/articles/cjdnkdg1l8do
  DDG ERROR: ('error sending request for url (https://html.duckduckgo.com/html/)', 'https://html.duckduckgo.com/html/')

Running text_clip_ocr:  42%|████▏     | 42/99 [10:37<14:25, 15.19s/it]

  DDG FC ERROR: No results found.
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/nuclear/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/hot-topics/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/california/
  NLI     : e=0.046  c=0.002  src=https://tribune.com.pk/story/2469136/chris-evans-c
  NLI     : e=0.021  c=0.008  src=https://dfrac.org/en/2024/02/13/fact-check-did-cap
  NLI     : e=0.000  c=0.050  src=https://en.wikipedia.org/wiki/Captain_America:_Bra

Running text_clip_ocr:  44%|████▍     | 44/99 [11:05<13:15, 14.46s/it]

  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/fake-news/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/askfactcheck/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/hot-topics/
  NLI     : e=0.216  c=0.019  src=https://www.medievalchronicles.com/medieval-tortur
  NLI     : e=0.025  c=0.715  src=https://en.wikipedia.org/wiki/Pear_of_anguish
  NLI     : e=0.002  c=0.004  src=https://allthatsinteresting.com/iron-maiden-device
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/list/?speaker_type=SOC
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/
  NLI     : e=0.041  c=0.002  src=https://www.foxnews.com/travel/man-vacation-goes-v
  NLI     : e=0.972  c=0.002  src=https://totalnews.com/man-on-vacation-goes-viral-f

Running text_clip_ocr:  45%|████▌     | 45/99 [11:12<10:54, 12.13s/it]

  NLI     : e=0.028  c=0.001  src=https://www.newsbreak.com/news/3736816681957-trave
  [FC REJECT] off-topic article: https://www.factcheck.org/fake-news/

Running text_clip_ocr:  46%|████▋     | 46/99 [11:25<11:00, 12.47s/it]

  DDG FC ERROR: ('error sending request for url (https://html.duckduckgo.com/html/)', 'https://html.duckduckgo.com/html/')
  NLI     : e=0.001  c=0.001  src=https://www.ctinsider.com/sports/uconn-mens-basket
  NLI     : e=0.002  c=0.006  src=https://www.foxnews.com/sports/uconns-dan-hurley-t
  NLI     : e=0.001  c=0.011  src=https://www.on3.com/news/seth-greenberg-criticizes

Running text_clip_ocr:  47%|████▋     | 47/99 [11:38<10:58, 12.66s/it]

  DDG FC ERROR: ('error sending request for url (https://html.duckduckgo.com/html/)', 'https://html.duckduckgo.com/html/')
  NLI     : e=1.000  c=0.000  src=https://www.mediaite.com/media/tv/dont-touch-me-sc
  NLI     : e=0.500  c=0.324  src=https://www.rvmnews.com/2024/12/tensions-explode-o
  NLI     : e=0.999  c=0.000  src=https://nypost.com/2024/12/14/media/cnn-contributo

Running text_clip_ocr:  48%|████▊     | 48/99 [11:54<11:32, 13.57s/it]

  NLI     : e=0.000  c=0.001  src=https://www.theguardian.com/commentisfree/2026/apr
  NLI [FC]: e=0.001  c=0.003  src=https://www.politifact.com/personalities/donald-tr
  NLI     : e=0.010  c=0.014  src=https://en.wikipedia.org/wiki/List_of_United_State
  [FC REJECT] off-topic article: https://www.factcheck.org/person/donald-trump/

Running text_clip_ocr:  49%|████▉     | 49/99 [12:05<10:46, 12.92s/it]

  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/crime/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/truth-o-meter/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/misconceptions/conspiracy-theories
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/health-check/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/punditfact/
  NLI     : e=0.017  c=0.001  src=https://www.foxnews.com/media/psychologist-jonatha
  NLI     : e=0.000  c=0.000  src=https://pjmedia.com/rick-moran/2024/12/31/how-jona
  NLI     : e=0.007  c=0.018  src=https://www.govtech.com/education/k-12/how-schools
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/fake-news/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/

Running text_clip_ocr:  51%|█████     | 50/99 [12:18<10:28, 12.82s/it]

  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/hot-topics/
  NLI     : e=0.000  c=0.000  src=https://fastguardservice.com/texas-police-arrest-9
  NLI     : e=0.964  c=0.001  src=https://www.foxnews.com/us/texas-police-arrest-9-s
  NLI     : e=0.164  c=0.001  src=https://www.fox7austin.com/news/lakeline-mall-shop
  [FC REJECT] off-topic article: https://www.politifact.com/texas/

Running text_clip_ocr:  52%|█████▏    | 51/99 [12:40<12:34, 15.71s/it]

  DDG FC ERROR: ('error sending request for url (https://html.duckduckgo.com/html/)', 'https://html.duckduckgo.com/html/')
  NLI     : e=0.004  c=0.002  src=https://www.thelist.com/1755074/christina-haack-jo
  NLI     : e=0.998  c=0.000  src=https://www.realestate.com.au/news/sneak-peak-at-c
  NLI     : e=0.997  c=0.000  src=https://www.foxnews.com/entertainment/hgtv-star-ch
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/fake-news/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/california/
  [FC SKIP] only 0 matches (need 1): https://fullfact.org/latest/
  NLI     : e=0.067  c=0.244  src=https://www.independent.co.uk/news/uk/home-news/lo
  NLI [FC]: e=0.001  c=0.002  src=https://www.factcheck.org/hot-topics/
  NLI     : e=0.007  c=0.051  src=https://genius.com/Digital-descendant-it-doesnt-en
  NLI     : e=0.000  c=0.994  src=https://www.bbc.com/news/articles/c5y3en5yv21o

Running text_clip_ocr:  53%|█████▎    | 52/99 [13:02<13:39, 17.44s/it]

  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/fake-news/

Running text_clip_ocr:  54%|█████▎    | 53/99 [13:22<13:57, 18.21s/it]

  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/search/
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/
  NLI     : e=0.028  c=0.031  src=https://www.aol.com/articles/hiker-stumbles-human-
  NLI     : e=0.999  c=0.000  src=https://usnewsper.com/2024/12/hiker-finds-body-on-
  [FC REJECT] off-topic article: https://www.politifact.com/crime/
  [FC REJECT] off-topic article: https://www.snopes.com/fact-check/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/issue/wildfire/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/issues/
  NLI     : e=0.986  c=0.002  src=https://www.pacificpundit.com/2024/10/10/meanwhile
  NLI     : e=0.002  c=0.001  src=https://www.thetrumpet.com/28042-america-under-att
  [FC REJECT] off-topic article: https://www.factcheck.org/2017/10/warming-blame-western-wild
  [FC REJECT] off-topic article: https://www.factcheck.org/fake-news/

Running text_clip_ocr:  56%|█████▌    | 55/99 [13:55<12:29, 17.02s/it]

  DDG FC ERROR: ('error sending request for url (https://html.duckduckgo.com/html/)', 'https://html.duckduckgo.com/html/')
  NLI     : e=0.982  c=0.003  src=https://www.nytimes.com/2025/07/13/world/middleeas
  NLI     : e=0.991  c=0.001  src=https://apnews.com/article/gaza-israel-palestinian
  NLI     : e=0.997  c=0.002  src=https://www.cnn.com/2025/05/06/middleeast/israel-g
  DDG ERROR: ('error sending request for url (https://html.duckduckgo.com/html/)', 'https://html.duckduckgo.com/html/')

Running text_clip_ocr:  57%|█████▋    | 56/99 [14:12<12:05, 16.86s/it]

  DDG FC ERROR: ('error sending request for url (https://html.duckduckgo.com/html/)', 'https://html.duckduckgo.com/html/')
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/askfactcheck/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/ask-factcheck/ask-us-a-question/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/artificial-intelligence/
  NLI [FC]: e=0.005  c=0.005  src=https://fullfact.org/economy/robots-and-your-job/
  NLI     : e=0.935  c=0.008  src=https://www.strategicstudyindia.com/2025/01/could-

Running text_clip_ocr:  58%|█████▊    | 57/99 [14:30<12:04, 17.24s/it]

  NLI     : e=0.000  c=0.000  src=https://www.diplotic.com/the-future-of-space-trave
  NLI     : e=0.001  c=0.000  src=https://www.linkedin.com/pulse/journey-closer-sun-

Running text_clip_ocr:  59%|█████▊    | 58/99 [14:42<10:45, 15.75s/it]

  DDG FC ERROR: ('error sending request for url (https://html.duckduckgo.com/html/)', 'https://html.duckduckgo.com/html/')
  NLI [FC]: e=0.012  c=0.001  src=https://www.snopes.com/fact-check/keanu-reeves-who
  NLI     : e=0.020  c=0.026  src=https://news.meaww.com/fact-check-did-keanu-reeves
  NLI     : e=0.772  c=0.004  src=https://www.forbes.com/sites/mattnovak/2024/02/03/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/

Running text_clip_ocr:  60%|█████▉    | 59/99 [15:00<11:01, 16.53s/it]

  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/fake-news/
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/fact-check/
  NLI     : e=0.000  c=0.000  src=https://www.citizen.co.za/news/news-world/iranian-
  NLI     : e=0.008  c=0.427  src=https://www.europereloaded.com/iran-raisi-amir-abd
  NLI     : e=0.000  c=0.000  src=https://www.indiatoday.in/fact-check/story/iran-pr
  [FC REJECT] off-topic article: https://fullfact.org/online/italian-trucks-coronavirus-victi
  DDG ERROR: ('error sending request for url (https://html.duckduckgo.com/html/)', 'https://html.duckduckgo.com/html/')

Running text_clip_ocr:  61%|██████    | 60/99 [15:11<09:28, 14.59s/it]

  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/fake-news/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/the-factcheck-wire/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/askfactcheck/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/hot-topics/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/
  [FC SKIP] only 0 matches (need 1): https://fullfact.org/news/
  NLI     : e=0.326  c=0.005  src=https://dfrac.org/en/tag/elon-musk-en/
  NLI     : e=0.001  c=0.002  src=https://www.theguardian.com/technology/article/202
  [FC REJECT] off-topic article: https://www.snopes.com/collections/king-charles-iii-rumors/
  NLI [FC]: e=0.001  c=0.315  src=https://www.factcheck.org/fake-news/

Running text_clip_ocr:  62%|██████▏   | 61/99 [15:31<10:19, 16.30s/it]

  NLI     : e=0.042  c=0.016  src=https://www.aa.com.tr/en/middle-east/us-deeply-con
  NLI [FC]: e=0.022  c=0.005  src=https://www.politifact.com/article/2026/mar/02/the
  NLI     : e=0.014  c=0.086  src=https://en.wikipedia.org/wiki/Gaza_war
  NLI     : e=0.024  c=0.017  src=https://www.inkl.com/news/middle-east-live-55-repo

Running text_clip_ocr:  63%|██████▎   | 62/99 [15:50<10:37, 17.24s/it]

  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/fake-news/
  [FC SKIP] only 0 matches (need 1): https://fullfact.org/conflict/israel-iran-misinformation-cir

Running text_clip_ocr:  64%|██████▎   | 63/99 [16:09<10:40, 17.78s/it]

  NLI     : e=0.015  c=0.005  src=https://www.voiceofemirates.com/en/news/2026/04/25
  NLI     : e=0.681  c=0.002  src=https://www.ynetnews.com/article/hjqbtrnwgl
  [FC REJECT] off-topic article: https://www.politifact.com/article/2026/mar/02/these-videos-
  NLI     : e=0.038  c=0.003  src=https://telanganatoday.com/idf-strikes-120-hezboll
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/fake-news/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/truth-o-meter/
  NLI     : e=0.008  c=0.002  src=https://www.lifezette.com/2025/01/unprotected-fren
  NLI [FC]: e=0.002  c=0.000  src=https://www.factcheck.org/2025/01/republicans-wron
  NLI [FC]: e=0.003  c=0.001  src=https://fullfact.org/online/new-orleans-police-bad
  NLI     : e=0.000  c=0.000  src=https://bklyn-ny.com/?p=7692

Running text_clip_ocr:  65%|██████▍   | 64/99 [16:19<09:01, 15.46s/it]

  DDG FC ERROR: ('error sending request for url (https://html.duckduckgo.com/html/)', 'https://html.duckduckgo.com/html/')
  NLI     : e=0.874  c=0.002  src=https://www.nytimes.com/2024/11/27/world/middleeas
  NLI     : e=0.006  c=0.062  src=https://theconversation.com/hamas-and-hezbollah-ho
  NLI     : e=0.240  c=0.005  src=https://en.dailypakistan.com.pk/27-Nov-2024/israel

Running text_clip_ocr:  67%|██████▋   | 66/99 [16:44<07:35, 13.79s/it]

  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/fake-news/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/issues/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/the-factcheck-wire/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/search/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/hot-topics/
  NLI     : e=0.043  c=0.004  src=https://www.independent.co.uk/travel/news-and-advi
  NLI     : e=0.002  c=0.981  src=https://www.inkl.com/news/no-planes-in-alaska-aren
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/

Running text_clip_ocr:  68%|██████▊   | 67/99 [16:52<06:18, 11.83s/it]

  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/fake-news/
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/
  [FC REJECT] off-topic article: https://www.factcheck.org/search/
  [FC REJECT] off-topic article: https://www.snopes.com/fact-check/
  NLI     : e=0.010  c=0.022  src=https://www.bbc.com/news/world-middle-east-6795826
  NLI     : e=0.005  c=0.020  src=https://www.bitchute.com/video/I7sG86aH5TZ4/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/fake-news/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/askfactcheck/
  NLI     : e=0.923  c=0.005  src=https://9gag.com/gag/aBymp91
  NLI     : e=0.001  c=0.009  src=https://www.newsweek.com/fact-check-viral-post-sur
  NLI     : e=0.001  c=0.001  src=https://www.planetary.org/articles/every-picture-f

Running text_clip_ocr:  70%|██████▉   | 69/99 [17:23<07:10, 14.34s/it]

  DDG FC ERROR: ('error sending request for url (https://html.duckduckgo.com/html/)', 'https://html.duckduckgo.com/html/')
  NLI     : e=0.000  c=0.000  src=https://www.bbc.co.uk/news/articles/ce32n0eze87o
  NLI     : e=0.010  c=0.001  src=https://news.google.com/stories/CAAqNggKIjBDQklTSG
  NLI     : e=0.005  c=0.770  src=https://www.bbc.com/news/articles/ce32n0eze87o
  DDG ERROR: ('error sending request for url (https://html.duckduckgo.com/html/)', 'https://html.duckduckgo.com/html/')

Running text_clip_ocr:  71%|███████   | 70/99 [17:39<07:07, 14.75s/it]

  DDG FC ERROR: No results found.

Running text_clip_ocr:  72%|███████▏  | 71/99 [17:58<07:25, 15.90s/it]

  DDG FC ERROR: No results found.
  NLI     : e=0.007  c=0.990  src=https://www.theguardian.com/world/2026/feb/28/iran
  NLI     : e=0.002  c=0.000  src=https://en.wikipedia.org/wiki/October_2024_Israeli
  NLI     : e=0.024  c=0.002  src=https://abcnews.com/International/us-israeli-strik

Running text_clip_ocr:  73%|███████▎  | 72/99 [18:09<06:28, 14.38s/it]

  NLI     : e=0.086  c=0.013  src=https://apnews.com/article/israel-weapons-shipment
  NLI     : e=0.000  c=0.001  src=https://www.theguardian.com/us-news/article/2024/m
  NLI [FC]: e=0.016  c=0.004  src=https://www.politifact.com/factchecks/2024/nov/06/
  [FC REJECT] off-topic article: https://www.factcheck.org/2024/11/both_sides_distort_incompl

Running text_clip_ocr:  74%|███████▎  | 73/99 [18:22<06:08, 14.16s/it]

  DDG FC ERROR: ('error sending request for url (https://html.duckduckgo.com/html/)', 'https://html.duckduckgo.com/html/')
  NLI     : e=0.991  c=0.004  src=https://www.mixedtimes.com/politics/fox-news-polit
  NLI     : e=0.001  c=0.004  src=https://www.youtube.com/watch?v=OQlNSDbcGeQ
  NLI     : e=0.001  c=0.001  src=https://news.google.com/stories/CAAqNggKIjBDQklTSG
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/fake-news/

Running text_clip_ocr:  75%|███████▍  | 74/99 [18:35<05:43, 13.75s/it]

  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/truth-o-meter/promises/list/?prom
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/issue/mars/
  NLI     : e=0.000  c=0.000  src=https://opentools.ai/news/nasas-ingenuity-helicopt
  NLI     : e=0.000  c=0.000  src=https://mashable.com/article/nasa-mars-helicopter-
  NLI     : e=0.000  c=0.001  src=https://gizmodo.com/next-gen-mars-mission-plans-to
  [FC REJECT] off-topic article: https://www.politifact.com/truth-o-meter/promises/

Running text_clip_ocr:  76%|███████▌  | 75/99 [18:46<05:11, 12.99s/it]

  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/fake-news/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/article/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/fact-check/
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/
  NLI     : e=0.964  c=0.001  src=https://www.24vids.com/video/so-were-all-just-gonn
  NLI     : e=0.003  c=0.044  src=https://www.foxnews.com/sports/conor-mcgregor-lash
  NLI     : e=0.000  c=0.001  src=https://www.bbc.com/news/articles/cn5w50pw65yo
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/congress/

Running text_clip_ocr:  77%|███████▋  | 76/99 [19:02<05:17, 13.81s/it]

  [FC REJECT] off-topic article: https://www.politifact.com/article/2026/may/04/political-vio
  NLI     : e=0.028  c=0.404  src=https://www.yahoo.com/news/articles/desantis-help-
  NLI     : e=0.088  c=0.057  src=https://www.usatoday.com/story/news/politics/2026/
  [FC REJECT] off-topic article: https://www.factcheck.org/
  [FC REJECT] off-topic article: https://www.factcheck.org/2016/08/trumps-false-obama-isis-li
  [FC REJECT] off-topic article: https://www.politifact.com/factchecks/2024/mar/28/alex-jones
  NLI     : e=0.001  c=0.000  src=https://www.foxnews.com/us/6-times-isis-has-inspir
  NLI     : e=0.000  c=0.000  src=https://www.nytimes.com/2025/01/01/world/middleeas

Running text_clip_ocr:  78%|███████▊  | 77/99 [19:24<05:56, 16.21s/it]

  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/fake-news/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/

Running text_clip_ocr:  79%|███████▉  | 78/99 [19:33<04:56, 14.12s/it]

  [FC REJECT] off-topic article: https://www.politifact.com/article/2025/dec/15/history-lie-o
  [FC REJECT] off-topic article: https://www.factcheck.org/hot-topics/
  NLI     : e=0.003  c=0.011  src=https://tech.yahoo.com/general/articles/worst-pass
  NLI     : e=0.006  c=0.514  src=https://www.linkedin.com/pulse/worst-passwords-202
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/

Running text_clip_ocr:  80%|███████▉  | 79/99 [19:54<05:22, 16.15s/it]

  NLI     : e=0.001  c=0.001  src=https://www.theguardian.com/world/2026/apr/28/hezb
  NLI [FC]: e=0.001  c=0.004  src=https://www.factcheck.org/fake-news/
  NLI     : e=0.001  c=0.000  src=https://www.rt.com/news/639136-hezbollah-drone-isr
  NLI     : e=0.003  c=0.012  src=https://www.israeltoday.co.il/read/lebanon-ceasefi

Running text_clip_ocr:  81%|████████  | 80/99 [20:07<04:51, 15.36s/it]

  NLI     : e=0.025  c=0.682  src=https://www.oneindia.com/fact-check/fact-check-did
  NLI [FC]: e=0.001  c=0.016  src=https://www.snopes.com/collections/musk-rumors-col
  NLI     : e=0.015  c=0.149  src=https://www.sportskeeda.com/baseball/paul-skenes-g
  NLI [FC]: e=0.004  c=0.009  src=https://www.politifact.com/personalities/elon-musk
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/

Running text_clip_ocr:  82%|████████▏ | 81/99 [20:22<04:34, 15.24s/it]

  NLI [FC]: e=0.001  c=0.001  src=https://fullfact.org/world/us-nato-contributions/
  [FC REJECT] off-topic article: https://www.factcheck.org/issue/nato/
  NLI     : e=0.001  c=0.002  src=https://www.bbc.com/news/articles/clyz4nq91wpo
  NLI     : e=0.005  c=0.001  src=https://www.nato.int/en/about-us/organization/nato
  DDG ERROR: query is mandatory.

Running text_clip_ocr:  83%|████████▎ | 82/99 [20:30<03:42, 13.11s/it]

  DDG FC ERROR: ('error sending request for url (https://html.duckduckgo.com/html/)', 'https://html.duckduckgo.com/html/')
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/fake-news/

Running text_clip_ocr:  84%|████████▍ | 83/99 [20:44<03:31, 13.22s/it]

  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/doge/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/hot-topics/
  [FC REJECT] off-topic article: https://fullfact.org/us/donald-trump-ban-tesla-ai/
  [FC REJECT] off-topic article: https://www.politifact.com/personalities/elon-musk/
  NLI     : e=0.008  c=0.796  src=https://www.teslarati.com/tesla-model-3-brake-fail
  NLI     : e=0.023  c=0.153  src=https://www.notebookcheck.net/Quirky-Model-3-accid

Running text_clip_ocr:  85%|████████▍ | 84/99 [20:57<03:17, 13.14s/it]

  DDG FC ERROR: ('error sending request for url (https://html.duckduckgo.com/html/)', 'https://html.duckduckgo.com/html/')
  NLI     : e=0.004  c=0.054  src=https://skwawkbox.org/2025/06/17/video-former-isra
  NLI     : e=0.004  c=0.321  src=https://thegrayzone.com/2025/09/12/charlie-kirk-ne
  NLI     : e=0.003  c=0.128  src=https://www.bbc.com/news/topics/c302m85q5ljt
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/fake-news/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/

Running text_clip_ocr:  86%|████████▌ | 85/99 [21:23<03:59, 17.11s/it]

  [FC REJECT] off-topic article: https://fullfact.org/online/miscaptioned-video-shooting-rang
  NLI     : e=0.020  c=0.001  src=https://syriadirect.org/in-search-of-closure-syria
  [FC REJECT] off-topic article: https://api.politifact.com/factchecks/2018/may/04/blog-posti
  NLI     : e=0.001  c=0.000  src=https://en.wikipedia.org/wiki/Mass_graves_in_Syria
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/list/?speaker=joe-bide

Running text_clip_ocr:  87%|████████▋ | 86/99 [21:45<03:58, 18.38s/it]

  NLI     : e=0.992  c=0.001  src=https://news.meaww.com/joe-bidens-epa-granted-50-m
  NLI     : e=0.996  c=0.001  src=https://www.foxnews.com/politics/biden-epa-granted
  NLI     : e=0.057  c=0.007  src=https://www.independentsentinel.com/admin-gave-50m
  [FC REJECT] off-topic article: https://www.factcheck.org/issue/environment/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/fake-news/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/askfactcheck/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/hot-topics/
  NLI     : e=0.000  c=0.001  src=https://www.anfieldwatch.co.uk/liverpool-fc/news/l

Running text_clip_ocr:  88%|████████▊ | 87/99 [22:00<03:28, 17.35s/it]

  NLI     : e=0.001  c=0.006  src=https://www.nytimes.com/athletic/5779177/2025/05/0
  NLI     : e=0.002  c=0.004  src=https://www.footballtransfers.com/en/transfer-news
  [FC REJECT] off-topic article: https://www.factcheck.org/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/the-factcheck-wire/

Running text_clip_ocr:  89%|████████▉ | 88/99 [22:16<03:08, 17.16s/it]

  NLI     : e=0.487  c=0.379  src=https://thefilibusterblog.com/azealia-banks-consid
  [FC REJECT] off-topic article: https://www.factcheck.org/fake-news/
  [FC REJECT] off-topic article: https://www.factcheck.org/askfactcheck/
  NLI     : e=0.000  c=0.001  src=https://en.wikipedia.org/wiki/Megan_Thee_Stallion
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/fake-news/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/ukraine/
  NLI     : e=0.021  c=0.004  src=https://www.mirror.co.uk/news/world-news/breaking-
  NLI [FC]: e=0.000  c=0.001  src=https://www.factcheck.org/person/volodymyr-zelensk
  NLI     : e=0.011  c=0.046  src=https://www.independent.co.uk/news/world/europe/uk
  NLI     : e=0.001  c=0.001  src=https://www.businessinsider.com/zelenskyy-cancels-

Running text_clip_ocr:  90%|████████▉ | 89/99 [22:30<02:42, 16.23s/it]

  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2023/may/26/tiktok-pos
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/issue/illegal-immigration/

Running text_clip_ocr:  91%|█████████ | 90/99 [22:38<02:02, 13.62s/it]

  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/article/2026/jan/22/ice-immigrati
  NLI     : e=0.196  c=0.043  src=https://www.usatoday.com/story/news/factcheck/2024
  NLI     : e=0.012  c=0.001  src=https://www.thecentersquare.com/california/article
  NLI     : e=0.000  c=0.003  src=https://www.foxnews.com/us/illegal-migrant-involve
  [FC REJECT] off-topic article: https://api.politifact.com/factchecks/2019/jan/09/blog-posti
  NLI     : e=0.986  c=0.002  src=https://newsaddicts.com/russia-releases-evidence-p
  NLI     : e=0.992  c=0.001  src=https://thepeoplesvoice.tv/russia-releases-2000-pa
  NLI     : e=0.872  c=0.026  src=https://www.planet-today.com/2023/08/russia-releas

Running text_clip_ocr:  92%|█████████▏| 91/99 [23:16<02:48, 21.04s/it]

  NLI [FC]: e=0.033  c=0.010  src=https://www.factcheck.org/location/russia/

Running text_clip_ocr:  93%|█████████▎| 92/99 [23:38<02:28, 21.20s/it]

  DDG FC ERROR: ('error sending request for url (https://html.duckduckgo.com/html/)', 'https://html.duckduckgo.com/html/')
  NLI     : e=0.910  c=0.001  src=https://mhanys.org/mh_update/mhanys-response-to-go
  NLI     : e=0.998  c=0.000  src=https://www.foxnews.com/politics/new-york-gov-kath
  NLI     : e=0.001  c=0.001  src=https://capitolpressroom.org/2025/05/23/mental-hea
  DDG FC ERROR: ('error sending request for url (https://html.duckduckgo.com/html/)', 'https://html.duckduckgo.com/html/')
  NLI     : e=0.028  c=0.139  src=https://en.wikipedia.org/wiki/7.7×58mm_Arisaka
  NLI     : e=0.046  c=0.020  src=https://inchesonaruler.com/7.7inches
  NLI     : e=0.074  c=0.395  src=https://www.ballisticstudies.com/Knowledgebase/7.7

Running text_clip_ocr:  94%|█████████▍| 93/99 [23:54<01:57, 19.57s/it]

  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/fake-news/

Running text_clip_ocr:  95%|█████████▍| 94/99 [24:10<01:32, 18.58s/it]

  NLI     : e=0.997  c=0.001  src=https://newsupdates24.com/cybertruck-explosion-liv
  NLI     : e=0.999  c=0.000  src=https://www.foxnews.com/us/las-vegas-suspect-ex-gi
  NLI [FC]: e=0.000  c=0.016  src=https://www.politifact.com/article/2025/jul/30/Sha
  NLI     : e=0.016  c=0.010  src=https://news.google.com/stories/CAAqNggKIjBDQklTSG
  DDG FC ERROR: ('error sending request for url (https://html.duckduckgo.com/html/)', 'https://html.duckduckgo.com/html/')
  NLI     : e=0.001  c=0.002  src=https://www.genocidewatch.com/single-post/hamas-he
  NLI     : e=0.002  c=0.001  src=https://www.dw.com/en/israel-hamas-war-5000-killed

Running text_clip_ocr:  96%|█████████▌| 95/99 [24:25<01:09, 17.47s/it]

  NLI     : e=0.003  c=0.002  src=https://www.bbc.com/news/articles/c0rnvy1zn10o
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/fake-news/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/ukraine/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/

Running text_clip_ocr:  97%|█████████▋| 96/99 [24:43<00:52, 17.60s/it]

  NLI [FC]: e=0.028  c=0.955  src=https://checkyourfact.com/2024/01/25/fact-check-pu
  NLI [FC]: e=0.006  c=0.912  src=https://www.factcheck.org/person/vladimir-putin/
  NLI     : e=0.011  c=0.091  src=https://www.greekradiofl.com/en/history-that-they-
  NLI     : e=0.213  c=0.028  src=https://english.pravda.ru/news/world/164407-modi-p

Running text_clip_ocr:  98%|█████████▊| 97/99 [24:54<00:31, 15.88s/it]

  DDG FC ERROR: ('error sending request for url (https://html.duckduckgo.com/html/)', 'https://html.duckduckgo.com/html/')
  NLI     : e=0.001  c=0.000  src=https://www.npr.org/2026/04/03/nx-s1-5772611/blake
  NLI     : e=0.002  c=0.000  src=https://www.latimes.com/entertainment-arts/movies/
  NLI     : e=0.009  c=0.000  src=https://variety.com/2026/film/news/blake-lively-la

Running text_clip_ocr:  99%|█████████▉| 98/99 [25:08<00:15, 15.27s/it]

  DDG FC ERROR: No results found.
  NLI     : e=0.002  c=0.990  src=https://www.aol.com/madison-everything-know-michel
  NLI     : e=0.699  c=0.005  src=https://variety.com/2024/tv/news/michelle-pfeiffer
  NLI     : e=0.172  c=0.007  src=https://deadline.com/2024/08/michelle-pfeiffer-con

Running text_clip_ocr: 100%|██████████| 99/99 [25:26<00:00, 15.42s/it]

  DDG FC ERROR: ('error sending request for url (https://html.duckduckgo.com/html/)', 'https://html.duckduckgo.com/html/')
  NLI     : e=0.997  c=0.001  src=https://www.themirror.com/entertainment/jay-zs-rap
  NLI     : e=0.497  c=0.025  src=https://www.foxnews.com/entertainment/jay-zs-sexua
  NLI     : e=0.751  c=0.015  src=https://www.tmz.com/2024/12/13/jay-z-diddy-rape-ac
============================================================
MODE: text_clip_ocr
  mode                 text_clip_ocr
  n_total              99
  n_valid              99
  n_error              0
  accuracy             0.7172
  precision_macro      0.7425
  recall_macro         0.7188
  f1_macro             0.7105

Prediction distribution:
pred
FAKE    65
REAL    34
Name: count, dtype: int64

              precision    recall  f1-score   support

        FAKE       0.66      0.88      0.75        49
        REAL       0.82      0.56      0.67        50

    accuracy                           0.72        99
   macro avg       0.74      0.72      0.71        99
weighted avg       0.74      0.72      0.71        99


Confusion matrix (rows=true, cols=pred):
      FAKE  REAL
FAKE    43     6
REAL    22    28

Per-class correct/total:
  FAKE         43/49  (88%)
  REAL         28/50  (56%)
Saved: /content/ablation_v2_text_clip_ocr.csv

============================================================
ABLATION SUMMARY
         mode  n_valid  accuracy  precision_macro  recall_macro  f1_macro
text_clip_ocr       99    0.7172           0.7425        0.7188    0.7105
    text_clip       99    0.7071           0.7281        0.7086    0.7011
    text_only       99    0.6970           0.7271        0.6988    0.6878
All saved to Drive

In [107]:
import numpy as np
from sklearn.metrics import accuracy_score
import pandas as pd

df_valid = pd.read_csv("/content/drive/MyDrive/ablation_v2_text_clip_ocr.csv")
df_valid = df_valid[df_valid["pred"] != "ERROR"].copy()

best_acc, best_ratio = 0, 1.4

for ratio in np.arange(0.8, 2.5, 0.1):
    def predict_with_ratio(row, r):
        s, c = row["fused_support"], row["fused_contra"]
        if s < 0.05 and c < 0.05: return "FAKE"
        if s > c * r and s >= 0.08: return "REAL"
        return "FAKE"
    df_valid["pred_tuned"] = df_valid.apply(lambda r: predict_with_ratio(r, ratio), axis=1)
    acc = accuracy_score(df_valid["true"], df_valid["pred_tuned"])
    if acc > best_acc:
        best_acc, best_ratio = acc, ratio

print(f"Best ratio: {best_ratio:.1f}")
print(f"Tuned accuracy: {best_acc:.4f}")
print(f"Current accuracy: 0.7172")
print(f"Improvement: +{round(best_acc - 0.7172, 4)}")

Best ratio: 0.8
Tuned accuracy: 0.7172
Current accuracy: 0.7172
Improvement: +-0.0

In [110]:
import pandas as pd
import numpy as np
from sklearn.metrics import accuracy_score, classification_report

df = pd.read_csv("/content/drive/MyDrive/ablation_v2_text_clip_ocr.csv")
df = df[df["pred"] != "ERROR"].copy()

def predict_calibrated(row):
    support = row["fused_support"]
    contra  = row["fused_contra"]
    entail  = row["text_entail"]
    contra_raw = row["text_contra"]

    if contra >= 0.25 and (contra - support) >= 0.08:
        return "FAKE"
    if support >= 0.20 and (support - contra) >= 0.08:
        return "REAL"
    if support < 0.05 and contra < 0.05:
        if contra_raw > 0.05:
            return "FAKE"
        return "REAL"  # no signal, no contra → benefit of doubt
    if contra_raw > 0.05:
        return "FAKE"
    return "REAL"

df["pred_calibrated"] = df.apply(predict_calibrated, axis=1)

acc = accuracy_score(df["true"], df["pred_calibrated"])
print(f"Calibrated accuracy: {acc:.4f}  (was 0.7172)")
print(classification_report(df["true"], df["pred_calibrated"], labels=["FAKE","REAL"]))

# Confusion matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(df["true"], df["pred_calibrated"], labels=["FAKE","REAL"])
print(pd.DataFrame(cm, index=["FAKE","REAL"], columns=["FAKE","REAL"]))

Calibrated accuracy: 0.6364  (was 0.7172)
              precision    recall  f1-score   support

        FAKE       0.74      0.41      0.53        49
        REAL       0.60      0.86      0.70        50

    accuracy                           0.64        99
   macro avg       0.67      0.63      0.62        99
weighted avg       0.67      0.64      0.62        99

      FAKE  REAL
FAKE    20    29
REAL     7    43

### V2 EVALUATION LOOP WITH ABLATIONS

In [61]:
import os
import time
import pandas as pd
from tqdm import tqdm
from sklearn.metrics import (
    accuracy_score,
    precision_recall_fscore_support,
    classification_report,
)

LABEL_ORDER = ["FAKE", "MISLEADING", "REAL"]

In [62]:
import threading

def run_with_timeout(fn, args=(), kwargs={}, timeout_sec=30, fallback=None):
    result = [fallback]
    exc = [None]

    def target():
        try:
            result[0] = fn(*args, **kwargs)
        except Exception as e:
            exc[0] = e

    t = threading.Thread(target=target, daemon=True)
    t.start()
    t.join(timeout_sec)

    if t.is_alive():
        print(f"  Per-sample timeout ({timeout_sec}s)")
        return fallback, True

    if exc[0] is not None:
        raise exc[0]

    return result[0], False

MAIN SAMPLE RUNNER

In [63]:
def run_one_sample(item, mode="text_clip_ocr", top_k_text=4, use_fc=True):
    claim    = item["claim"]
    img_path = item.get("image_path", None)

    # TEXT branch
    try:
        search_query = clean_tweet_claim(claim)
        retrieved    = retrieve_all_evidence(search_query, use_fact_checks=use_fc)
        cleaned      = clean_text_evidence(retrieved)
        ranked       = rank_by_overlap_and_trust(search_query, cleaned)
        top_text     = select_best_evidence_passages(search_query, ranked, top_k=top_k_text)
        text_scores  = nli_text_score(claim, top_text, top_k=top_k_text)
    except Exception as e:
        print(f"  TEXT ERROR: {e}")
        top_text    = []
        text_scores = {"entail": 0.0, "contra": 0.0, "neutral": 1.0, "used": 0}

    # IMAGE branch
    clip_sim        = 0.0
    ocr_text        = ""
    ocr_align       = 0.0
    image_was_loaded = False

    if img_path and mode in {"text_clip", "text_clip_ocr"}:
        try:
            img_temp, local_path, status = load_image_from_path_or_url(img_path)
            if img_temp is not None:
                image_was_loaded = True
                clip_sim         = compute_clip_score(img_temp, claim)
                if mode == "text_clip_ocr" and local_path:
                    try:
                        ocr_text  = run_ocr(local_path)
                        ocr_align = ocr_text_claim_alignment_score(claim, ocr_text)
                    except:
                        ocr_text = ""
        except Exception as e:
            print(f"  IMAGE ERROR: {e}")

    # FUSION — now correctly knows if image was loaded
    fused = fuse_multimodal_scores(
        text_scores     = text_scores,
        clip_sim        = clip_sim,
        ocr_align       = ocr_align,
        ocr_text        = ocr_text,
        mode            = mode,
        image_was_loaded = image_was_loaded,
    )

    pred       = final_label(fused, binary_dataset=True)
    confidence = round(max(fused["fused_support"], fused["fused_contra"]) * 100, 2)

    return {
        "claim":          claim,
        "true":           item["label"],
        "pred":           pred,
        "mode":           mode,
        "confidence":     confidence,
        "image_was_loaded": image_was_loaded,
        "clip_sim":       clip_sim,
        "text_entail":    text_scores["entail"],
        "text_contra":    text_scores["contra"],
        "fused_support":  fused["fused_support"],
        "fused_contra":   fused["fused_contra"],
        "weights":        fused["weights"],
    }

In [109]:
def run_one_sample_ablation(
    item:        dict,
    mode:        str  = "text_clip_ocr",
    top_k_text:  int  = 4,          # changed from 2 → 4
    use_fc:      bool = True,
    binary_dataset: bool = True,    # XFactA is binary
) -> dict:

    claim      = item["claim"]
    true_label = item["label"]
    img_path   = item.get("image_path", None)

    # TEXT BRANCH — now uses clean_tweet_claim + v2 NLI
    try:
        search_query = clean_tweet_claim(claim)
        #retrieved    = retrieve_all_evidence(search_query, use_fact_checks=use_fc)
        retrieved = retrieve_all_evidence_ddg(search_query, use_fact_checks=use_fc)
        cleaned      = clean_text_evidence(retrieved)
        ranked       = rank_by_overlap_and_trust(search_query, cleaned)
        top_text     = select_best_evidence_passages(search_query, ranked, top_k=top_k_text)
        text_scores  = nli_text_score_v2(claim, top_text, top_k=top_k_text)
    except Exception as e:
        print(f"  TEXT ERROR [{claim[:40]}]: {e}")
        top_text    = []
        text_scores = {"entail": 0.0, "contra": 0.0, "neutral": 1.0, "used": 0}

    # IMAGE BRANCH — unchanged
    clip_sim = 0.0; ocr_text = ""; ocr_align = 0.0
    image_used = False; actual_image_source = None; ocr_local_path = None
    image_status = "no_image_input"

    use_clip = mode in {"text_clip", "text_clip_ocr"}
    use_ocr  = mode == "text_clip_ocr"

    if img_path and (use_clip or use_ocr):
        try:
            img_temp, local_path, status = load_image_from_path_or_url(img_path)
            image_status = status
            if img_temp is not None:
                image_used = True; actual_image_source = img_path
                ocr_local_path = local_path
                if use_clip:
                    clip_sim = compute_clip_score(img_temp, claim)
                if use_ocr and ocr_local_path:
                    try:    ocr_text = run_ocr(ocr_local_path)
                    except: ocr_text = ""
                    ocr_align = ocr_text_claim_alignment_score(claim, ocr_text)
        except Exception as e:
            print(f"  IMAGE ERROR [{claim[:40]}]: {e}")

    # FUSION
    fused = fuse_multimodal_scores(
        text_scores=text_scores, clip_sim=clip_sim,
        ocr_align=ocr_align, ocr_text=ocr_text, mode=mode,
    )

    # v2 label — binary-aware, never wastes a prediction on MISLEADING
    #pred       = final_label_v2(fused, binary_dataset=binary_dataset)
    pred = final_label_calibrated(fused, text_scores, top_text)
    confidence = round(max(fused["fused_support"], fused["fused_contra"]) * 100, 2)

    try:
        explanation = generate_multimodal_explanation(
            claim, top_text, clip_sim, ocr_text, fused, pred
        )
    except Exception:
        explanation = "Explanation unavailable"

    return {
        "claim":          claim,
        "true":           true_label,
        "pred":           pred,
        "mode":           mode,
        "confidence":     confidence,
        "evidence_texts": [ev["text"] for ev in top_text],
        "evidence_urls":  [ev["url"]  for ev in top_text],
        "fc_sources":     [ev["url"]  for ev in top_text if ev.get("is_fact_check")],
        "explanation":    explanation,
        "text_entail":    text_scores["entail"],
        "text_contra":    text_scores["contra"],
        "text_neutral":   text_scores["neutral"],
        "clip_sim":       clip_sim,
        "ocr_text_len":   len(ocr_text),
        "ocr_used":       fused.get("ocr_used", False),
        "fused_support":  fused["fused_support"],
        "fused_contra":   fused["fused_contra"],
        "fused_mixed":    fused.get("fused_mixed", 0.0),
        "image_used":     image_used,
        "image_source":   actual_image_source,
        "image_status":   image_status,
        "evidence_count": len(top_text),
        "clip_norm":      fused["clip_norm"],
        "ocr_norm":       fused["ocr_norm"],
        "weights":        fused["weights"],
        "search_query":   search_query if 'search_query' in dir() else claim,
    }

RUN ALL ABLATIONS + COMPARE

In [65]:
def run_ablation_suite(dataset, top_k_text=3, per_sample_timeout=60, use_fc=True):
    modes       = ["text_only", "text_clip", "text_clip_ocr"]
    all_outputs = {}
    summaries   = []

    for m in modes:
        df_mode, summary, cm, report = evaluate_mode(
            dataset=dataset,
            mode=m,
            top_k_text=top_k_text,
            use_fc=use_fc,
            per_sample_timeout=per_sample_timeout,
            verbose=True,
        )
        out_path = f"/content/ablation_{m}_full_outputs.csv"
        df_mode.to_csv(out_path, index=False)
        print(f"  Saved: {out_path}")
        all_outputs[m] = {"df": df_mode, "summary": summary}
        summaries.append(summary)

    summary_df = (
        pd.DataFrame(summaries)
        .sort_values("f1_macro", ascending=False)
        .reset_index(drop=True)
    )
    print("\n" + "#" * 70)
    print("ABLATION SUMMARY (sorted by macro-F1)")
    print(summary_df[["mode","n_valid","accuracy","precision_macro","recall_macro","f1_macro"]].to_string(index=False))
    print("#" * 70)
    summary_df.to_csv("/content/ablation_summary.csv", index=False)
    return all_outputs, summary_df

check raw NLI scores

In [ ]:
def debug_claim(claim, true_label):
    print(f"\n{'='*60}")
    print(f"Claim: {claim!r}  (true={true_label})")
    retrieved = retrieve_all_evidence(claim, use_fact_checks=True)
    cleaned   = clean_text_evidence(retrieved)
    ranked    = rank_by_overlap_and_trust(claim, cleaned)
    top_text  = select_best_evidence_passages(claim, ranked, top_k=3)

    if not top_text:
        print("  NO EVIDENCE retrieved")
        return

    for i, ev in enumerate(top_text):
        fc_tag = " [FACT-CHECK]" if ev.get("is_fact_check") else ""
        print(f"  Evidence {i+1}{fc_tag}: {ev['text'][:120]}...")
        inp    = {"text": ev["text"], "text_pair": claim}
        out    = nli(inp, top_k=None)
        if isinstance(out[0], list):
            out = out[0]
        scores = {d["label"].upper(): round(d["score"], 3) for d in out}
        print(f"  NLI scores: {scores}")

    ts = nli_text_score(claim, top_text)
    print(f"  Averaged → entail={ts['entail']:.3f}  contra={ts['contra']:.3f}  neutral={ts['neutral']:.3f}")
    print(f"  used={ts['used']}")

    fused = fuse_multimodal_scores(ts, 0.0, 0.0, mode="text_only")
    label = final_multimodal_label(fused)
    print(f"  → Predicted: {label}  (fused_support={fused['fused_support']:.3f}  fused_contra={fused['fused_contra']:.3f}  mixed={fused['fused_mixed']:.3f})")

debug_claim("NASA confirms water on Mars", "MISLEADING")
debug_claim("The Earth is flat",           "FAKE")
debug_claim("Smoking causes lung cancer",  "REAL")

============================================================
Claim: 'NASA confirms water on Mars'  (true=MISLEADING)
  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/
  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/news/2020/12/08/galactic-federation-n
  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/news/2022/09/21/mars-is-littered-with
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2014/mar/12/rush-limba
  Evidence 1 [FACT-CHECK]: No, NASA is not editing images from Canada and passing them off as photos of Mars. Similar claims have been debunked num...
  NLI scores: {'NEUTRAL': 0.999, 'CONTRADICTION': 0.0, 'ENTAILMENT': 0.0}
  Evidence 2 [FACT-CHECK]: Claim: A 17-year-old girl named Alyssa Carson is being trained by NASA to become an astronaut. Rating: About this rating...
  NLI scores: {'CONTRADICTION': 0.904, 'NEUTRAL': 0.093, 'ENTAILMENT': 0.003}
  Evidence 3: These dark, narrow, 100 meter-long streaks called recurring slope lineae flowing downhill on Mars are inferred to have b...
  NLI scores: {'NEUTRAL': 0.848, 'ENTAILMENT': 0.15, 'CONTRADICTION': 0.002}
  NLI [FC]: entail=0.001  contra=0.001  neutral=0.998  src=https://www.politifact.com/factchecks/2024/feb/23/insta
  NLI [FC]: entail=0.001  contra=0.997  neutral=0.003  src=https://www.snopes.com/fact-check/17-year-old-astronaut
  NLI     : entail=0.150  contra=0.002  neutral=0.848  src=https://www.nasa.gov/news-release/nasa-confirms-evidenc
  Averaged → entail=0.031  contra=0.399  neutral=0.570
  used=5
  → Predicted: FAKE  (fused_support=0.031  fused_contra=0.399  mixed=0.601)

============================================================
Claim: 'The Earth is flat'  (true=FAKE)
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2023/jul/26/instagram-
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/2015/03/cruz-on-the-global-cooling
  Evidence 1 [FACT-CHECK]: We have abundant evidence going back thousands of years that the Earth is roughly spherical. There are many man-made sat...
  NLI scores: {'CONTRADICTION': 1.0, 'NEUTRAL': 0.0, 'ENTAILMENT': 0.0}
  Evidence 2 [FACT-CHECK]: The Earth is not flat, and that is a fact roundly agreed upon by scientists. But a video on Facebook claims to show othe...
  NLI scores: {'CONTRADICTION': 0.999, 'NEUTRAL': 0.001, 'ENTAILMENT': 0.0}
  Evidence 3 [FACT-CHECK]: This image is fake and was almost certainly created using AI. It contains Google AI’s SynthID watermark, and does not ma...
  NLI scores: {'CONTRADICTION': 0.999, 'NEUTRAL': 0.001, 'ENTAILMENT': 0.0}
  NLI [FC]: entail=0.002  contra=0.926  neutral=0.072  src=https://fullfact.org/online/earth-is-spherical-not-flat
  NLI [FC]: entail=0.001  contra=0.969  neutral=0.030  src=https://www.politifact.com/factchecks/2024/may/29/faceb
  NLI [FC]: entail=0.000  contra=0.999  neutral=0.001  src=https://fullfact.org/technology/artemis-2-earth-picture
  Averaged → entail=0.001  contra=0.965  neutral=0.035
  used=6
  → Predicted: FAKE  (fused_support=0.001  fused_contra=0.965  mixed=0.035)

============================================================
Claim: 'Smoking causes lung cancer'  (true=REAL)
  Evidence 1: How Is Smoking Related to Cancer? Smoking can cause cancer and then block your body from fighting it:4 Poisons in cigare...
  NLI scores: {'ENTAILMENT': 0.999, 'NEUTRAL': 0.0, 'CONTRADICTION': 0.0}
  Evidence 2: Smoking Cigarette smoking is the number one risk factor for lung cancer. In the United States, cigarette smoking is link...
  NLI scores: {'ENTAILMENT': 1.0, 'NEUTRAL': 0.0, 'CONTRADICTION': 0.0}
  Evidence 3: July 15, 2025 Factors linked to lung cancer in never-smokers At a Glance A study linked fine-particle air pollution and ...
  NLI scores: {'ENTAILMENT': 0.999, 'CONTRADICTION': 0.0, 'NEUTRAL': 0.0}
  NLI     : entail=0.023  contra=0.000  neutral=0.977  src=https://www.cdc.gov/tobacco/campaign/tips/diseases/canc
  NLI     : entail=0.999  contra=0.000  neutral=0.000  src=https://www.cdc.gov/lung-cancer/risk-factors/index.html
  NLI     : entail=0.999  contra=0.000  neutral=0.001  src=https://www.nih.gov/news-events/nih-research-matters/fa
  Averaged → entail=0.674  contra=0.000  neutral=0.326
  used=3
  → Predicted: REAL  (fused_support=0.674  fused_contra=0.000  mixed=0.326)

In [93]:
item = final_eval_dataset[0]
row  = run_one_sample_ablation(
    item, mode="text_only",
    top_k_text=4, use_fc=True, binary_dataset=True,
)
print("Pred:", row["pred"])
print("True:", row["true"])
print("Confidence:", row["confidence"])

/tmp/ipykernel_2349/2161664455.py:6: RuntimeWarning: This package (`duckduckgo_search`) has been renamed to `ddgs`! Use `pip install ddgs` instead.
  with DDGS() as ddgs:
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/tmp/ipykernel_2349/2161664455.py:62: RuntimeWarning: This package (`duckduckgo_search`) has been renamed to `ddgs`! Use `pip install ddgs` instead.
  with DDGS() as ddgs:
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

  NLI     : e=0.204  c=0.178  src=https://emojis.wiki/high-voltage/
  NLI     : e=0.040  c=0.019  src=https://www.emojiall.com/en/emoji/⚡️
  NLI     : e=0.012  c=0.016  src=https://emojiguide.org/high-voltage
Pred: FAKE
True: FAKE
Confidence: 8.55

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [94]:
import re

def clean_tweet_claim(claim: str) -> str:
    # Remove emojis
    claim = re.sub(r'[^\x00-\x7F]+', ' ', claim)
    # Remove URLs
    claim = re.sub(r'http\S+', '', claim)
    # Remove mentions and hashtags
    claim = re.sub(r'[@#]\w+', '', claim)
    # Remove RT prefix
    claim = re.sub(r'^RT\s+', '', claim)
    # Clean extra spaces
    claim = re.sub(r'\s+', ' ', claim).strip()
    return claim if len(claim) > 15 else claim

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [95]:
# Test clean_tweet_claim first
claim = "⚡️A picture of war in the sky of Israel. A Hezbollah rocket while being approached by an interceptor missile."
print("Cleaned:", clean_tweet_claim(claim))

Cleaned: A picture of war in the sky of Israel. A Hezbollah rocket while being approached by an interceptor missile.

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [96]:
item = final_eval_dataset[0]
row  = run_one_sample_ablation(
    item, mode="text_only",
    top_k_text=4, use_fc=True, binary_dataset=True,
)
print("Pred:", row["pred"])
print("True:", row["true"])
print("Confidence:", row["confidence"])

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/tmp/ipykernel_2349/2161664455.py:6: RuntimeWarning: This package (`duckduckgo_search`) has been renamed to `ddgs`! Use `pip install ddgs` instead.
  with DDGS() as ddgs:
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/tmp/ipykernel_2349/2161664455.py:62: RuntimeWarning: This package (`duckduckgo_search`) has been renamed to `ddgs`! Use `pip install ddgs` instead.
  with DDGS() as ddgs:
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

Pred: FAKE
True: FAKE
Confidence: 0.0

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)


Find the best threshold on your results

In [89]:
import shutil

all_outputs = {}
summaries   = []

df_mode, summary, cm, report = evaluate_mode_v2(
    dataset=final_eval_dataset,
    mode="text_only",      # ONE MODE ONLY
    top_k_text=4,
    use_fc=True,
    per_sample_timeout=90,
    verbose=True,
)
all_outputs["text_only"] = {"df": df_mode, "summary": summary}
summaries.append(summary)

df_mode.to_csv("/content/ablation_v2_text_only.csv", index=False)

# Save to Drive immediately
try:
    shutil.copy("/content/ablation_v2_text_only.csv",
                "/content/drive/MyDrive/ablation_v2_text_only.csv")
    print("Saved to Drive")
except Exception as e:
    print(f"Drive save failed: {e}")

Running text_only:   0%|          | 0/99 [00:00<?, ?it/s]

  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/fact-check/hamas-wedding-girls/
  [FC SKIP] only 0 matches (need 1): https://fullfact.org/conflict/
  NLI [FC]: e=0.285  c=0.532  src=https://www.snopes.com/fact-check/photograph-rafah

Running text_only:   1%|          | 1/99 [00:06<11:07,  6.81s/it]

  NLI [FC]: e=0.199  c=0.056  src=https://fullfact.org/news/iran-missile-drone-attac
  [FC REJECT] off-topic article: https://www.snopes.com/news/2024/01/22/israel-hamas-what-is-
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/fact-check/close-up-bees-face/
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/news/2022/04/08/mayim-bialik-allegati
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/2012/10/factchecking-the-hofstra-d
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/2017/05/trump-not-deporting-native
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/author/jordan/?pagenum=86

Running text_only:   2%|▏         | 2/99 [00:14<12:13,  7.56s/it]

  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/article/2025/mar/31/anonymous-x-a
  NLI [FC]: e=0.001  c=0.004  src=https://www.politifact.com/article/2023/oct/23/how
  [FC REJECT] off-topic article: https://www.snopes.com/fact-check/x-post-2023-cole-allen/
  [FC REJECT] off-topic article: https://www.snopes.com/news/2023/11/13/video-palestinian-man

Running text_only:   3%|▎         | 3/99 [00:28<16:43, 10.45s/it]

  NLI [FC]: e=0.010  c=0.001  src=https://www.factcheck.org/2025/01/republicans-wron
  NLI [FC]: e=0.864  c=0.005  src=https://www.politifact.com/article/2025/jan/02/how
  NLI [FC]: e=0.013  c=0.047  src=https://www.snopes.com/news/2025/01/02/new-orleans
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2022/jul/26/instagram-
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2023/jul/14/instagram-
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/fact-check/antarctica-seen-from-space
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2022/aug/30/facebook-p

Running text_only:   4%|▍         | 4/99 [00:37<15:16,  9.65s/it]

  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2022/sep/14/instagram-
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2022/aug/23/facebook-p
  [FC REJECT] off-topic article: https://www.politifact.com/factchecks/2022/oct/10/facebook-p
  [FC REJECT] off-topic article: https://www.politifact.com/factchecks/2023/apr/25/instagram-
  [FC REJECT] off-topic article: https://www.politifact.com/factchecks/2021/mar/02/facebook-p
  [FALLBACK] Using embedding similarity
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/category/photos/?pagenum=81
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2015/jul/16/chain-emai

Running text_only:   5%|▌         | 5/99 [00:46<14:56,  9.54s/it]

  [FC REJECT] off-topic article: https://www.snopes.com/fact-check/samira-ibrahim/
  [FC REJECT] off-topic article: https://www.snopes.com/fact-check/did-you-know-this/
  [FC REJECT] off-topic article: https://www.snopes.com/tag/the-new-york-evening/
  [FALLBACK] Using embedding similarity

Running text_only:   6%|▌         | 6/99 [00:53<13:14,  8.55s/it]

  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2016/feb/05/marco-rubi
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2018/aug/14/jeff-denha
  [FC SKIP] only 0 matches (need 1): https://fullfact.org/online/arma-3-footage-china-us-tensions
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2026/mar/10/donald-tru
  [FC REJECT] off-topic article: https://fullfact.org/online/china-mosque-demolition-false/
  NLI [FC]: e=0.002  c=0.044  src=https://www.politifact.com/article/2024/apr/29/are
  NLI [FC]: e=0.018  c=0.009  src=https://fullfact.org/online/video-mosque-demolitio

Running text_only:   8%|▊         | 8/99 [01:08<12:39,  8.35s/it]

  NLI [FC]: e=0.001  c=0.005  src=https://www.snopes.com/news/2019/08/16/readers-thi
  NLI [FC]: e=0.002  c=0.008  src=https://www.snopes.com/news/2019/01/24/yahoo-news-
  [FC REJECT] off-topic article: https://www.snopes.com/tag/the-onion/

Running text_only:  11%|█         | 11/99 [01:15<06:17,  4.29s/it]

  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/fact-check/ronald-mcdonald-1892/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/2019/10/the-facts-on-mental-illnes
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/fact-check/
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/fact-check/antonio-west-shooting-deat
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/fact-check/school-shooters-death-pena
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/fact-check/girl-solved-murder-heart-t
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/news/2019/09/04/the-psychology-behind
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2020/feb/14/blog-posti

Running text_only:  12%|█▏        | 12/99 [01:16<04:37,  3.19s/it]

  [FC SKIP] only 0 matches (need 1): https://fullfact.org/online/serial-killer-roaming-england/
  [FC REJECT] off-topic article: https://www.politifact.com/factchecks/2022/may/25/chris-murp
  [FALLBACK] Using embedding similarity
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2018/apr/20/yournewswi
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/article/2019/mar/18/wikileaks-rus
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/misconceptions/the-origins-of-covi
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/article/2018/aug/02/fact-checking
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/article/2021/oct/28/ask-politifac

Running text_only:  13%|█▎        | 13/99 [01:17<03:43,  2.60s/it]

  NLI [FC]: e=0.070  c=0.094  src=https://www.snopes.com/fact-check/funvax/
  [FC REJECT] off-topic article: https://www.factcheck.org/2019/06/falsehood-swirls-about-bid
  [FC REJECT] off-topic article: https://www.factcheck.org/2020/05/the-falsehoods-of-the-plan

Running text_only:  14%|█▍        | 14/99 [01:21<04:14,  2.99s/it]

  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/fact-check/goldfinger-actress-death/
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/news/2022/10/25/reepy-clown-history-h
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/fact-check/fauci-villain-dallas-buyer
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/fact-check/first-full-cgi-character/

Running text_only:  15%|█▌        | 15/99 [01:28<05:55,  4.24s/it]

  NLI [FC]: e=0.002  c=0.003  src=https://www.snopes.com/fact-check/luigi-beanie-ama
  [FC REJECT] off-topic article: https://www.snopes.com/fact-check/nintendo-free-him-luigi-po
  NLI [FC]: e=0.001  c=0.001  src=https://www.snopes.com/fact-check/uhc-shooter-mug-
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2018/aug/03/donald-tru

Running text_only:  16%|█▌        | 16/99 [01:32<05:47,  4.18s/it]

  [FC REJECT] off-topic article: https://www.factcheck.org/2020/02/trump-has-condemned-white-
  NLI [FC]: e=0.069  c=0.002  src=https://www.snopes.com/fact-check/war-games/
  [FC REJECT] off-topic article: https://www.politifact.com/article/2020/sep/10/ad-watch-what

Running text_only:  17%|█▋        | 17/99 [01:34<04:55,  3.60s/it]

  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/fact-check/using-regular-people/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2014/jan/26/richard-au
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/tag/usda/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2021/sep/16/facebook-p
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/fact-check/dod-pages-dei-holocaust/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/2025/05/rfk-jr-denies-cuts-to-scie
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2025/jan/30/karoline-l
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2012/feb/23/frank-nice
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2024/feb/02/instagram-
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/person/peter-mccullough/

Running text_only:  18%|█▊        | 18/99 [01:40<05:45,  4.27s/it]

  NLI [FC]: e=0.001  c=0.001  src=https://www.snopes.com/fact-check/trump-zelenskyy-
  [FC REJECT] off-topic article: https://www.factcheck.org/2019/12/zelenskys-remarks-about-tr
  NLI [FC]: e=0.001  c=0.015  src=https://www.snopes.com/fact-check/zelenskyy-us-ukr

Running text_only:  19%|█▉        | 19/99 [01:45<05:46,  4.33s/it]

  [FC REJECT] off-topic article: https://www.politifact.com/factchecks/2026/feb/09/social-med
  [FALLBACK] Using embedding similarity
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/fact-check/thanksgiving-massacre-pequ
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/article/2015/jul/22/half-truths-w

Running text_only:  20%|██        | 20/99 [01:52<06:43,  5.11s/it]

  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/2015/11/trump-carson-on-911-celebr
  [FC REJECT] off-topic article: https://www.snopes.com/fact-check/dec-11-memorial/
  NLI [FC]: e=0.022  c=0.005  src=https://www.snopes.com/news/2017/01/23/trump-patri
  [FC REJECT] off-topic article: https://www.snopes.com/fact-check/jest-in-time/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2025/jul/30/donald-tru
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2023/nov/02/vivek-rama
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/hot-topics/

Running text_only:  21%|██        | 21/99 [01:57<06:43,  5.18s/it]

  [FC REJECT] off-topic article: https://www.politifact.com/factchecks/2024/may/15/donald-tru
  NLI [FC]: e=0.013  c=0.002  src=https://www.politifact.com/article/2026/apr/02/fac
  [FC REJECT] off-topic article: https://www.politifact.com/factchecks/2025/jul/29/benjamin-n
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2024/mar/01/facebook-p
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/article/2025/nov/06/nancy-pelosi-
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/article/2019/aug/01/donald-trump-
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2020/jun/09/j-christia
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2023/aug/31/travis-tri
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/article/2026/mar/06/Markwayne-Mul
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2014/mar/03/florida-de

Running text_only:  22%|██▏       | 22/99 [02:04<07:18,  5.69s/it]

  [FC REJECT] off-topic article: https://www.politifact.com/article/2025/jun/06/jeffrey-epste
  [FC REJECT] off-topic article: https://www.politifact.com/factchecks/2023/nov/01/maga-inc/r
  [FC REJECT] off-topic article: https://www.politifact.com/factchecks/2018/jun/27/twentyeigh
  [FALLBACK] Using embedding similarity

Running text_only:  23%|██▎       | 23/99 [02:10<07:13,  5.70s/it]

  [FC REJECT] off-topic article: https://www.snopes.com/news/2018/09/06/many-daily-caller-wri
  [FC REJECT] off-topic article: https://www.snopes.com/
  [FALLBACK] Using embedding similarity

Running text_only:  24%|██▍       | 24/99 [02:15<06:51,  5.49s/it]

  [FC REJECT] off-topic article: https://www.snopes.com/tracker/trump-executive-orders-list/
  [FALLBACK] Using embedding similarity
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/2008/03/presidents-winning-without

Running text_only:  25%|██▌       | 25/99 [02:25<08:32,  6.92s/it]

  [FC REJECT] off-topic article: https://www.politifact.com/article/2024/nov/22/how-big-was-d
  NLI [FC]: e=0.066  c=0.017  src=https://www.factcheck.org/2024/11/trump-won-the-po
  NLI [FC]: e=0.004  c=0.013  src=https://www.factcheck.org/issue/presidential-elect
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/fact-check/spousal-success-story/
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/fact-check/corpus-crispy/
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/fact-check/still-the-queen/
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/fact-check/alix-idrache-west-point-gr
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/fact-check/dr-seuss-affair-wife-suici
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/2004/08/republican-funded-group-at

Running text_only:  26%|██▋       | 26/99 [02:32<08:26,  6.93s/it]

  [FC REJECT] off-topic article: https://www.snopes.com/fact-check/press-your-luck/
  [FC REJECT] off-topic article: https://www.snopes.com/fact-check/man-without-a-face/
  NLI [FC]: e=0.002  c=0.979  src=https://www.politifact.com/article/2018/aug/26/rem
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/fact-check/facebook-rule-photos-tv/
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/fact-check/facebook-bypass-system-hoa
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/fact-check/facebook-to-regain-friends
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/fact-check/new-facebook-rule-meta/

Running text_only:  27%|██▋       | 27/99 [02:35<07:03,  5.89s/it]

  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/fact-check/new-york-ceo-lamborghini/
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/fact-check/social-media-hacker-warnin
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/fact-check/bridezilla/
  [FC REJECT] off-topic article: https://www.snopes.com/fact-check/trump-volcanoes-concrete-p
  [FC REJECT] off-topic article: https://www.snopes.com/fact-check/
  [FALLBACK] Using embedding similarity
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/2017/02/trumps-bogus-terrorist-cla

Running text_only:  28%|██▊       | 28/99 [02:45<08:13,  6.94s/it]

  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/2019/10/the-facts-on-mental-illnes
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/2015/10/gun-laws-deaths-and-crimes
  [FC REJECT] off-topic article: https://www.politifact.com/embassyattacks/
  NLI [FC]: e=0.002  c=0.005  src=https://www.factcheck.org/2019/08/mass-killings-ac
  [FC REJECT] off-topic article: https://www.factcheck.org/2021/11/how-many-died-as-a-result-
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2020/jan/15/facebook-p
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2022/may/16/facebook-p

Running text_only:  29%|██▉       | 29/99 [02:50<07:41,  6.59s/it]

  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2023/aug/10/facebook-p
  [FC REJECT] off-topic article: https://www.politifact.com/article/2024/sep/27/has-a-venezue
  [FC REJECT] off-topic article: https://www.politifact.com/article/2024/oct/02/vp-debate-fac
  [FC REJECT] off-topic article: https://www.politifact.com/factchecks/2018/feb/23/philip-lev
  [FALLBACK] Using embedding similarity

Running text_only:  30%|███       | 30/99 [02:52<05:52,  5.11s/it]

  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/fact-check/film-crew-footage-gaza/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/article/2024/may/24/the-un-adjust
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2024/dec/06/instagram-

Running text_only:  31%|███▏      | 31/99 [02:55<05:11,  4.58s/it]

  NLI [FC]: e=0.003  c=0.043  src=https://www.politifact.com/factchecks/2025/jul/29/
  NLI [FC]: e=0.002  c=0.005  src=https://www.snopes.com/news/2024/05/02/netanyahu-h
  [FC REJECT] off-topic article: https://www.politifact.com/archive-beheaded-babies-israel-ha
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/2025/05/trump-allies-spread-unfoun
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2020/may/28/facebook-p

Running text_only:  32%|███▏      | 32/99 [03:37<17:23, 15.57s/it]

  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/2019/07/unpacking-bidens-and-trump
  [FC REJECT] off-topic article: https://www.politifact.com/article/2026/mar/26/covid-19-vari
  [FC REJECT] off-topic article: https://www.politifact.com/factchecks/2022/feb/23/instagram-
  [FC REJECT] off-topic article: https://www.snopes.com/fact-check/germany-gel-joint-cartilag
  [FALLBACK] Using embedding similarity

Running text_only:  34%|███▍      | 34/99 [04:00<14:41, 13.56s/it]

  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/2024/07/false-claim-about-fake-sec
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/2025/01/trump-justifies-j6-pardons

Running text_only:  35%|███▌      | 35/99 [04:11<13:36, 12.76s/it]

  NLI [FC]: e=0.010  c=0.932  src=https://www.factcheck.org/2021/04/posts-falsely-id
  NLI [FC]: e=0.001  c=0.012  src=https://www.politifact.com/factchecks/2024/jul/16/
  [FC REJECT] off-topic article: https://www.snopes.com/fact-check/derek-mullins-jasmine-cart

Running text_only:  36%|███▋      | 36/99 [04:19<11:48, 11.24s/it]

  [FC SKIP] only 0 matches (need 1): https://fullfact.org/online/lebanese-citizens-celebrating-Ha
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/fact-check/fire-tel-aviv-israel-iran-
  [FC SKIP] only 0 matches (need 1): https://fullfact.org/news/altered-audio-CNN-border-footage-s
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2014/jul/24/rula-jebre
  [FC SKIP] only 0 matches (need 1): https://fullfact.org/world/burj-khalifa-ai-iran/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/article/2026/mar/11/trump-iran-sc
  [FC REJECT] off-topic article: https://www.factcheck.org/2023/10/what-we-know-about-three-w
  [FC REJECT] off-topic article: https://www.snopes.com/fact-check/anti-netanyahu-protest-isr
  NLI [FC]: e=0.011  c=0.012  src=https://www.snopes.com/fact-check/crisis-actors-is
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/fact-check/hegseth-iran-war-christian
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/2012/10/false-claims-in-final-deba
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/fact-check/pope-leo-trump-insult-jesu
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/fact-check/pope-leo-xiv-iran-war/

Running text_only:  37%|███▋      | 37/99 [04:29<11:22, 11.00s/it]

  [FC REJECT] off-topic article: https://www.factcheck.org/2015/06/cruz-cherry-picks-terroris
  [FC REJECT] off-topic article: https://www.politifact.com/factchecks/2020/feb/29/facebook-p
  [FC REJECT] off-topic article: https://mail.snopes.com/p/new-post-0c67
  [FALLBACK] Using embedding similarity

Running text_only:  38%|███▊      | 38/99 [04:29<07:53,  7.76s/it]

  [FC SKIP] only 0 matches (need 1): https://staging.politifact.com/article/2019/jan/25/photo-cov

Running text_only:  39%|███▉      | 39/99 [04:32<06:07,  6.12s/it]

  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/collections/epstein-maxwell-clintons-
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/latest/?pagenum=798
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/fact-check/erika-kirk-tyler-robinson-
  NLI [FC]: e=0.028  c=0.698  src=https://www.snopes.com/fact-check/woman-jail-weari
  [FC REJECT] off-topic article: https://www.factcheck.org/2008/10/court-fight-in-the-heart-o
  [FC REJECT] off-topic article: https://www.factcheck.org/2008/11/2008-factcheck-awards/
  [FC SKIP] only 0 matches (need 1): https://fullfact.org/policy/reports/full-fact-report-2025/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/corrections-and-updates/

Running text_only:  40%|████      | 40/99 [04:47<08:47,  8.94s/it]

  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/article/2026/feb/18/dietary-prote
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/article/2026/feb/04/washington-DC
  [FC SKIP] only 0 matches (need 1): https://fullfact.org/policy/reports/full-fact-report-2024/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/article/2025/apr/24/RFK-jr-enviro
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/article/2026/mar/23/march-madness
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/article/2025/nov/13/biologics-bio
  [FC REJECT] off-topic article: https://www.politifact.com/article/2026/apr/07/choosing-best
  [FC REJECT] off-topic article: https://www.politifact.com/article/2026/mar/06/TrumpRx-presc
  [FALLBACK] Using embedding similarity

Running text_only:  41%|████▏     | 41/99 [04:53<07:43,  7.99s/it]

  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2025/jul/11/jon-favrea
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/article/2025/jun/06/jeffrey-epste
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2014/dec/03/jeb-bush/t
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2021/mar/02/donald-tru

Running text_only:  42%|████▏     | 42/99 [04:55<06:00,  6.32s/it]

  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2025/jul/28/markwayne-
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/article/2022/jun/09/political-ext
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2022/apr/28/facebook-p
  [FC REJECT] off-topic article: https://www.politifact.com/factchecks/2025/jul/18/donald-tru
  [FC REJECT] off-topic article: https://www.factcheck.org/2013/08/the-messy-facts-in-virgini
  [FC REJECT] off-topic article: https://www.politifact.com/factchecks/2026/jan/14/mehmet-oz/
  [FALLBACK] Using embedding similarity

Running text_only:  43%|████▎     | 43/99 [05:03<06:12,  6.65s/it]

  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/article/2018/feb/26/dunkirk-fact-
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2020/jan/15/facebook-p
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2025/mar/26/pete-hegse
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2024/sep/26/sam-brown/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/2024/08/misleading-democratic-ad-i
  [FC REJECT] off-topic article: https://www.politifact.com/factchecks/2024/jun/21/facebook-p
  [FC REJECT] off-topic article: https://www.snopes.com/fact-check/chris-evans-signing-bomb/
  [FC REJECT] off-topic article: https://www.snopes.com/tag/marvel/
  [FALLBACK] Using embedding similarity

Running text_only:  44%|████▍     | 44/99 [05:13<07:11,  7.85s/it]

  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/2010/09/bos-private-plane/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/2009/06/more-birther-nonsense-obam

Running text_only:  45%|████▌     | 45/99 [05:17<05:56,  6.60s/it]

  NLI [FC]: e=0.010  c=0.239  src=https://www.snopes.com/news/2021/06/21/mama-bear-g
  [FC REJECT] off-topic article: https://www.snopes.com/news/2016/04/10/spring-break-nightmar
  NLI [FC]: e=0.007  c=0.022  src=https://www.snopes.com/fact-check/man-stuck-2055-f

Running text_only:  46%|████▋     | 46/99 [05:19<04:40,  5.28s/it]

  NLI [FC]: e=0.001  c=0.016  src=https://www.politifact.com/factchecks/2024/jul/03/
  [FC REJECT] off-topic article: https://www.politifact.com/factchecks/2023/may/05/instagram-

Running text_only:  47%|████▋     | 47/99 [05:29<05:46,  6.67s/it]

  NLI [FC]: e=0.000  c=0.002  src=https://www.politifact.com/factchecks/2025/jul/09/
  NLI [FC]: e=0.000  c=0.001  src=https://www.politifact.com/personalities/scott-jen
  NLI [FC]: e=0.003  c=0.006  src=https://www.politifact.com/article/2026/apr/10/tru

Running text_only:  48%|████▊     | 48/99 [05:37<05:54,  6.94s/it]

  NLI [FC]: e=0.000  c=0.001  src=https://www.snopes.com/fact-check/trump-president-
  NLI [FC]: e=0.000  c=0.001  src=https://www.snopes.com/fact-check/trump-veterans-d
  NLI [FC]: e=0.011  c=0.047  src=https://www.snopes.com/fact-check/donald-tump-ffa-

Running text_only:  49%|████▉     | 49/99 [05:43<05:30,  6.61s/it]

  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/fact-check/karmelo-anthony-donations-
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/2020/06/meme-spreads-wrong-photo-d

Running text_only:  51%|█████     | 50/99 [05:49<05:18,  6.51s/it]

  [FC REJECT] off-topic article: https://www.snopes.com/fact-check/tiger-houston-neighborhood
  [FC REJECT] off-topic article: https://www.snopes.com/fact-check/texas-ice-raid-birthday-pa
  [FC REJECT] off-topic article: https://www.factcheck.org/2021/04/posts-falsely-identify-sus
  [FALLBACK] Using embedding similarity

Running text_only:  52%|█████▏    | 51/99 [05:59<05:56,  7.43s/it]

  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2022/dec/16/instagram-
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2024/dec/13/facebook-p
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/article/2022/mar/15/zuckerbucks-2
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2018/dec/04/blog-posti
  [FC SKIP] only 0 matches (need 1): https://fullfact.org/policy/reports/full-fact-report-2024/
  [FC SKIP] only 0 matches (need 1): https://fullfact.org/policy/reports/full-fact-report-2025/
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/author/snopes/?pagenum=45
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2019/jul/02/kamala-har

Running text_only:  53%|█████▎    | 52/99 [06:06<05:54,  7.55s/it]

  NLI [FC]: e=0.004  c=0.007  src=https://www.politifact.com/factchecks/2018/aug/07/
  [FC REJECT] off-topic article: https://www.politifact.com/factchecks/2018/dec/20/blog-posti
  [FC REJECT] off-topic article: https://www.politifact.com/factchecks/2017/nov/10/michael-mc
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/fact-check/missing-alaska-hikers-stor
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/fact-check/eric-langford-missing-boy-
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/fact-check/vacation-holiday-photo-vir

Running text_only:  54%|█████▎    | 53/99 [06:21<07:26,  9.71s/it]

  [FC REJECT] off-topic article: https://www.politifact.com/factchecks/2021/apr/19/facebook-p
  [FC REJECT] off-topic article: https://www.snopes.com/fact-check/log-pile-missing/
  [FC REJECT] off-topic article: https://www.politifact.com/factchecks/2025/apr/04/facebook-p
  [FALLBACK] Using embedding similarity
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/fact-check/yellowstone-animals-fleein
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/truth-o-meter/promises/obameter/p
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/article/2023/aug/08/you-and-your-

Running text_only:  55%|█████▍    | 54/99 [06:28<06:37,  8.83s/it]

  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2020/oct/01/joe-biden/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2012/feb/24/newt-gingr
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2024/nov/26/donald-tru
  [FC REJECT] off-topic article: https://www.factcheck.org/2023/01/its-too-soon-to-attribute-
  [FC REJECT] off-topic article: https://www.politifact.com/factchecks/2015/sep/29/mike-hucka
  [FALLBACK] Using embedding similarity
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/fact-check/american-three-terrorist-a

Running text_only:  56%|█████▌    | 55/99 [06:34<05:51,  7.99s/it]

  NLI [FC]: e=0.034  c=0.024  src=https://www.factcheck.org/2023/11/dozens-of-childr
  [FC REJECT] off-topic article: https://www.politifact.com/factchecks/2019/mar/04/blog-posti
  [FC REJECT] off-topic article: https://www.snopes.com/fact-check/ronald-mcdonald-1892/
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/fact-check/italy-doctor-corona-not-fl
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/fact-check/heart-attack-symptoms/
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/fact-check/onions-fight-flu-myth/
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/fact-check/call-police-new-guinea-fla

Running text_only:  57%|█████▋    | 56/99 [06:39<04:59,  6.98s/it]

  [FC REJECT] off-topic article: https://www.snopes.com/fact-check/hair-grooming-syncope/
  [FC REJECT] off-topic article: https://www.snopes.com/fact-check/swedes-called-in-gay-class
  [FC REJECT] off-topic article: https://www.snopes.com/fact-check/pfizer-covid-vaccine-adver
  [FALLBACK] Using embedding similarity
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/tag/artificial-intelligence/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/article/2019/oct/16/both-trade-an
  [FC SKIP] only 0 matches (need 1): https://fullfact.org/online/WEF-animal-charities/

Running text_only:  58%|█████▊    | 57/99 [06:44<04:34,  6.53s/it]

  [FC REJECT] off-topic article: https://www.politifact.com/article/2023/may/30/can-chatgpt-f
  [FC REJECT] off-topic article: https://www.snopes.com/category/science/?pagenum=46
  [FC REJECT] off-topic article: https://www.snopes.com/news/2015/07/29/mcdonalds-kiosks-mini
  [FALLBACK] Using embedding similarity

Running text_only:  59%|█████▊    | 58/99 [06:49<04:10,  6.12s/it]

  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/article/2019/mar/13/did-donald-tr
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/2005/08/here-we-go-again-distorted
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/2006/10/accusations-without-eviden

Running text_only:  60%|█████▉    | 59/99 [06:52<03:25,  5.13s/it]

  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/fact-check/alex-pretti-gun-video/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2014/may/05/laura-ingr
  [FC REJECT] off-topic article: https://www.politifact.com/article/2019/sep/11/fact-checking
  [FC REJECT] off-topic article: https://www.snopes.com/news/2015/09/23/fidel-lopez/
  [FC REJECT] off-topic article: https://www.snopes.com/fact-check/trump-marines-la-texas/
  [FALLBACK] Using embedding similarity

Running text_only:  61%|██████    | 60/99 [06:52<02:22,  3.64s/it]

  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/fact-check/jfk-palestine-britain/

Running text_only:  62%|██████▏   | 61/99 [06:59<02:56,  4.63s/it]

  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2015/mar/03/bill-oreil
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/2008/09/factchecking-mccain/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2014/jul/17/facebook-p
  [FC REJECT] off-topic article: https://www.factcheck.org/2020/02/trump-repeats-falsehoods-i
  [FC REJECT] off-topic article: https://www.snopes.com/news/2018/06/13/lawsuit-brexit-backer
  NLI [FC]: e=0.004  c=0.014  src=https://www.snopes.com/tag/united-kingdom/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/2026/03/how-iran-blocking-the-stra
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/2016/04/trumps-foreign-policy-spee
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/2016/05/rep-jones-didnt-empower-ob
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/2026/03/trump-links-bidens-ukraine
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/2016/06/trump-wrong-on-iraqi-oil/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/article/2026/feb/27/iran-economic
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/article/2023/oct/09/fact-check-tr
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2015/jul/23/jon-stewar

Running text_only:  63%|██████▎   | 62/99 [07:10<03:59,  6.47s/it]

  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2016/mar/17/donald-tru
  [FC REJECT] off-topic article: https://www.politifact.com/factchecks/2009/jul/14/republican
  [FALLBACK] Using embedding similarity
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/2023/10/what-we-know-about-three-w

Running text_only:  64%|██████▎   | 63/99 [07:18<04:05,  6.83s/it]

  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/news/2025/08/11/al-jazeera-anas-al-sh
  [FC REJECT] off-topic article: https://www.snopes.com/news/2021/05/25/tom-cotton-associated
  [FC REJECT] off-topic article: https://www.snopes.com/newsletter-archive/snopes-digest-116-
  [FC REJECT] off-topic article: https://www.snopes.com/news/2025/10/28/hamas-ceasefire-viola
  [FALLBACK] Using embedding similarity

Running text_only:  65%|██████▍   | 64/99 [07:28<04:37,  7.94s/it]

  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/2026/04/trumps-numbers-april-2026-

Running text_only:  66%|██████▌   | 65/99 [07:41<05:24,  9.54s/it]

  [FC REJECT] off-topic article: https://www.politifact.com/article/2024/dec/26/a-month-by-mo
  [FC REJECT] off-topic article: https://www.politifact.com/
  [FC REJECT] off-topic article: https://www.snopes.com/
  [FALLBACK] Using embedding similarity

Running text_only:  67%|██████▋   | 66/99 [07:47<04:34,  8.31s/it]

  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2025/jan/15/instagram-
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/2015/07/clinton-spins-immigration-
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/2016/07/factchecking-clintons-big-
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/2020/02/trump-has-condemned-white-

Running text_only:  68%|██████▊   | 67/99 [07:49<03:25,  6.41s/it]

  NLI [FC]: e=0.209  c=0.006  src=https://www.factcheck.org/2015/11/bogus-meme-targe
  [FC REJECT] off-topic article: https://www.factcheck.org/2008/10/lying-about-being-liberal/
  [FC REJECT] off-topic article: https://www.factcheck.org/2019/04/what-kissinger-has-said-ab

Running text_only:  69%|██████▊   | 68/99 [07:50<02:30,  4.84s/it]

  [FC REJECT] off-topic article: https://www.snopes.com/tag/astronomy/
  [FC REJECT] off-topic article: https://www.snopes.com/tag/space/?pagenum=2
  [FALLBACK] Using embedding similarity

Running text_only:  70%|██████▉   | 69/99 [07:58<02:53,  5.77s/it]

  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/fact-check/revocation-of-independence
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/news/2020/12/23/what-history-really-t
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/article/2024/mar/12/princess-kate
  [FC SKIP] only 0 matches (need 1): https://fullfact.org/policy/reports/full-fact-report-2021/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2022/feb/21/facebook-p
  [FC REJECT] off-topic article: https://www.snopes.com/fact-check/royal-family-play-monopoly
  [FC REJECT] off-topic article: https://www.snopes.com/news/2022/09/08/queen-elizabeth-ii-a-
  [FALLBACK] Using embedding similarity
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/fact-check/tunnel-between-rafah-egypt

Running text_only:  71%|███████   | 70/99 [08:03<02:39,  5.49s/it]

  NLI [FC]: e=0.381  c=0.161  src=https://www.politifact.com/factchecks/2024/apr/22/
  [FC REJECT] off-topic article: https://www.politifact.com/factchecks/2014/jul/24/rula-jebre
  NLI [FC]: e=0.019  c=0.162  src=https://www.politifact.com/article/2026/apr/02/fac

Running text_only:  72%|███████▏  | 71/99 [08:15<03:29,  7.47s/it]

  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/2026/03/without-providing-evidence
  NLI [FC]: e=0.001  c=0.005  src=https://www.snopes.com/collections/us-israel-war-i
  [FC REJECT] off-topic article: https://fullfact.org/conflict/footage-tel-aviv-destroyed-bui
  NLI [FC]: e=0.008  c=0.721  src=https://www.factcheck.org/2023/11/social-media-pos

Running text_only:  73%|███████▎  | 72/99 [08:22<03:20,  7.42s/it]

  NLI [FC]: e=0.001  c=0.003  src=https://www.factcheck.org/2021/07/factchecking-bid
  NLI [FC]: e=0.000  c=0.001  src=https://www.factcheck.org/2019/09/bidens-record-on
  NLI [FC]: e=0.001  c=0.001  src=https://www.factcheck.org/2020/09/factchecking-bid

Running text_only:  75%|███████▍  | 74/99 [08:35<02:58,  7.14s/it]

  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2023/apr/18/facebook-p
  [FC REJECT] off-topic article: https://www.politifact.com/factchecks/list/?page=44&speaker=
  [FC REJECT] off-topic article: https://www.politifact.com/factchecks/list/?page=95&category
  [FALLBACK] Using embedding similarity

Running text_only:  76%|███████▌  | 75/99 [08:40<02:35,  6.47s/it]

  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/2005/12/rnc-web-ad-are-democrats-w
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/fact-check/rashida-tlaib-bring-jihad/
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/fact-check/vance-trump-hitler-quote/
  [FC REJECT] off-topic article: https://www.snopes.com/fact-check/sydney-sweeney-ben-shapiro
  [FC REJECT] off-topic article: https://www.snopes.com/tag/ben-shapiro/
  [FC REJECT] off-topic article: https://www.snopes.com/tag/sydney_sweeney/
  [FALLBACK] Using embedding similarity
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/list/?category&ruling=
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/article/2026/apr/06/Trump-Iran-Tr

Running text_only:  77%|███████▋  | 76/99 [08:47<02:31,  6.59s/it]

  [FC REJECT] off-topic article: https://www.politifact.com/article/2026/jan/29/DHS-governmen
  [FC REJECT] off-topic article: https://www.politifact.com/personalities/democrats/
  [FC REJECT] off-topic article: https://www.politifact.com/factchecks/list/?category=&ruling
  [FALLBACK] Using embedding similarity

Running text_only:  78%|███████▊  | 77/99 [08:55<02:34,  7.03s/it]

  [FC REJECT] off-topic article: https://www.politifact.com/factchecks/2017/nov/10/michael-mc
  NLI [FC]: e=0.001  c=0.001  src=https://www.politifact.com/article/2015/dec/11/war
  [FC REJECT] off-topic article: https://www.factcheck.org/2016/08/trumps-false-obama-isis-li

Running text_only:  79%|███████▉  | 78/99 [09:06<02:56,  8.40s/it]

  [FC REJECT] off-topic article: https://www.factcheck.org/2011/12/the-whoppers-of-2011/
  [FC REJECT] off-topic article: https://www.factcheck.org/2005/10/no-death-penalty-for-hitle
  [FC REJECT] off-topic article: https://www.factcheck.org/2012/05/soft-glove-same-gps-fist/
  [FALLBACK] Using embedding similarity
  [FC SKIP] only 0 matches (need 1): https://fullfact.org/environment/haarp-not-behind-northern-l

Running text_only:  80%|███████▉  | 79/99 [09:19<03:15,  9.78s/it]

  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2021/apr/06/greg-abbot
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2025/aug/05/donald-tru
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/article/2026/mar/26/covid-19-vari
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2023/oct/06/joe-biden/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2016/jul/01/bonnie-rei
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2022/jun/04/charles-sc
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2024/jul/24/republican
  [FC REJECT] off-topic article: https://fullfact.org/news/hindu-festival-london-not-anti-imm
  [FC REJECT] off-topic article: https://fullfact.org/online/miscaptioned-video-child-syria-n
  [FALLBACK] Using embedding similarity

Running text_only:  81%|████████  | 80/99 [09:27<02:53,  9.16s/it]

  NLI [FC]: e=0.002  c=0.024  src=https://www.snopes.com/fact-check/musk-add-pop-sou
  NLI [FC]: e=0.010  c=0.036  src=https://www.snopes.com/fact-check/twitter-logo-tit
  NLI [FC]: e=0.003  c=0.010  src=https://www.snopes.com/fact-check/twitter-employee
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/2019/05/trump-17-repeats-in-17-hou
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/2011/03/obama-on-war-then-and-now/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/2018/08/a-rally-filled-with-repeat
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/article/2019/nov/14/obamas-hot-mi
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/2020/08/final-night-of-the-republi
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/2016/10/factchecking-the-vp-debate

Running text_only:  82%|████████▏ | 81/99 [09:39<03:02, 10.16s/it]

  [FC REJECT] off-topic article: https://www.politifact.com/factchecks/2018/jul/12/donald-tru
  [FC REJECT] off-topic article: https://www.politifact.com/article/2024/feb/14/fact-check-tr
  NLI [FC]: e=0.001  c=0.000  src=https://www.politifact.com/factchecks/2018/jul/12/

Running text_only:  83%|████████▎ | 82/99 [09:40<02:02,  7.19s/it]

  [FC SKIP] only 0 matches (need 1): https://fullfact.org/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/
  [FC SKIP] only 0 matches (need 1): https://fullfact.org/latest/
  [FC SKIP] only 0 matches (need 1): https://fullfact.org/vaccines/
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/
  [FC SKIP] only 0 matches (need 1): https://fullfact.org/immigration/
  [FC SKIP] only 0 matches (need 1): https://fullfact.org/online/onions/
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/top/
  [FC SKIP] only 0 matches (need 1): https://fullfact.org/fact-checks/

Running text_only:  84%|████████▍ | 83/99 [09:44<01:41,  6.34s/it]

  [FC REJECT] off-topic article: https://www.politifact.com/factchecks/2016/dec/28/jeff-brand
  [FALLBACK] Using embedding similarity
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/fact-check/israelis-absent-911/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2024/apr/30/tweets/pho
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2015/oct/09/ben-carson
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/article/2024/may/10/the-antisemit
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2026/mar/02/tweets/Ira

Running text_only:  85%|████████▍ | 84/99 [09:50<01:34,  6.31s/it]

  [FC REJECT] off-topic article: https://www.politifact.com/factchecks/2013/nov/27/marco-rubi
  [FC REJECT] off-topic article: https://www.politifact.com/factchecks/2011/sep/04/kinky-frie
  NLI [FC]: e=0.024  c=0.481  src=https://www.politifact.com/article/2025/oct/13/Tru

Running text_only:  86%|████████▌ | 85/99 [10:02<01:49,  7.80s/it]

  NLI [FC]: e=0.002  c=0.001  src=https://www.politifact.com/factchecks/2019/mar/04/

Running text_only:  87%|████████▋ | 86/99 [10:05<01:24,  6.50s/it]

  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/list/?category=&ruling
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2022/aug/11/kevin-mcca

Running text_only:  88%|████████▊ | 87/99 [10:14<01:28,  7.37s/it]

  NLI [FC]: e=0.184  c=0.003  src=https://www.politifact.com/factchecks/2026/feb/17/
  NLI [FC]: e=0.001  c=0.001  src=https://www.politifact.com/factchecks/2026/feb/13/
  NLI [FC]: e=0.008  c=0.027  src=https://www.politifact.com/factchecks/2025/feb/14/

Running text_only:  89%|████████▉ | 88/99 [10:15<00:57,  5.24s/it]

  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/article/2025/aug/18/trump-zelensk

Running text_only:  90%|████████▉ | 89/99 [10:22<00:59,  5.91s/it]

  NLI [FC]: e=0.000  c=0.015  src=https://www.snopes.com/news/2025/02/21/ukraine-ele
  [FC REJECT] off-topic article: https://www.snopes.com/fact-check/us-trump-trip-world-leader
  NLI [FC]: e=0.000  c=0.000  src=https://www.snopes.com/fact-check/zelenskyy-say-no

Running text_only:  91%|█████████ | 90/99 [10:27<00:51,  5.71s/it]

  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/article/2018/jul/05/fact-checking

Running text_only:  92%|█████████▏| 91/99 [10:35<00:50,  6.29s/it]

  NLI [FC]: e=0.012  c=0.007  src=https://www.politifact.com/factchecks/2019/nov/15/
  NLI [FC]: e=0.068  c=0.005  src=https://www.politifact.com/factchecks/2024/aug/23/
  NLI [FC]: e=0.047  c=0.017  src=https://www.politifact.com/factchecks/list/?catego
  NLI [FC]: e=0.005  c=0.012  src=https://www.factcheck.org/person/kathy-hochul/
  NLI [FC]: e=0.000  c=0.001  src=https://www.politifact.com/personalities/kathy-hoc

Running text_only:  93%|█████████▎| 92/99 [10:43<00:47,  6.74s/it]

  NLI [FC]: e=0.001  c=0.000  src=https://www.politifact.com/factchecks/list/?speake

Running text_only:  94%|█████████▍| 93/99 [10:48<00:37,  6.28s/it]

  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2025/jan/31/facebook-p
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/list/?page=8&category=
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/fact-check/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2022/apr/28/facebook-p
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/article/2023/apr/13/state-legisla

Running text_only:  95%|█████████▍| 94/99 [10:58<00:36,  7.38s/it]

  NLI [FC]: e=0.001  c=0.000  src=https://www.politifact.com/factchecks/2022/oct/21/
  [FC REJECT] off-topic article: https://www.politifact.com/factchecks/2024/feb/16/instagram-
  [FC REJECT] off-topic article: https://www.politifact.com/factchecks/2019/jan/23/facebook-p
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/2023/11/social-media-posts-misrepr

Running text_only:  96%|█████████▌| 95/99 [11:05<00:29,  7.39s/it]

  NLI [FC]: e=0.000  c=0.007  src=https://www.snopes.com/news/2025/10/28/hamas-cease
  NLI [FC]: e=0.058  c=0.012  src=https://www.snopes.com/articles/465623/oct-7-hamas
  NLI [FC]: e=0.000  c=0.003  src=https://www.snopes.com/news/2026/02/11/israel-stri
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/hot-topics/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/2018/10/factchecking-trumps-60-min

Running text_only:  97%|█████████▋| 96/99 [11:14<00:23,  7.68s/it]

  NLI [FC]: e=0.026  c=0.271  src=https://www.factcheck.org/2018/07/factchecking-rus
  [FC REJECT] off-topic article: https://www.politifact.com/factchecks/2018/mar/16/viralpolit
  [FC REJECT] off-topic article: https://www.factcheck.org/2018/02/words-trump-russian-meddli
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/fact-check/michelle-obama-harvey-wein
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/article/2013/feb/15/government-jo
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/article/2016/jan/22/iowa-gantlet-

Running text_only:  98%|█████████▊| 97/99 [11:22<00:15,  7.77s/it]

  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2011/sep/05/barack-oba
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/article/2010/jan/13/announcing-po
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2011/oct/06/critics-wa
  NLI [FC]: e=0.013  c=0.003  src=https://www.politifact.com/article/2012/oct/19/fac
  [FC REJECT] off-topic article: https://www.politifact.com/factchecks/2011/jan/31/sameh-shou
  [FC REJECT] off-topic article: https://www.politifact.com/factchecks/?page=709&
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2014/feb/11/hugh-fitzs

Running text_only:  99%|█████████▉| 98/99 [11:29<00:07,  7.66s/it]

  [FC REJECT] off-topic article: https://www.politifact.com/factchecks/2021/jun/04/tiktok-pos
  [FC REJECT] off-topic article: https://www.politifact.com/factchecks/2025/aug/07/tiktok-pos
  [FALLBACK] Using embedding similarity

Running text_only: 100%|██████████| 99/99 [11:42<00:00,  7.10s/it]

  NLI [FC]: e=0.028  c=0.367  src=https://www.politifact.com/factchecks/2020/jun/03/
  [FC REJECT] off-topic article: https://www.snopes.com/news/2026/03/13/katie-johnson-arreste
  [FC REJECT] off-topic article: https://www.politifact.com/factchecks/2024/jul/12/threads-po
============================================================
MODE: text_only
  mode                 text_only
  n_total              99
  n_valid              99
  n_error              0
  accuracy             0.4949
  precision_macro      0.4974
  recall_macro         0.4998
  f1_macro             0.348

Prediction distribution:
pred
FAKE    97
REAL     2
Name: count, dtype: int64

              precision    recall  f1-score   support

        FAKE       0.49      0.98      0.66        49
        REAL       0.50      0.02      0.04        50

    accuracy                           0.49        99
   macro avg       0.50      0.50      0.35        99
weighted avg       0.50      0.49      0.34        99


Confusion matrix (rows=true, cols=pred):
      FAKE  REAL
FAKE    48     1
REAL    49     1

Per-class correct/total:
  FAKE         48/49  (98%)
  REAL         1/50  (2%)
Saved to Drive

EVALUATION LOOP (CLEAN)

In [82]:
import pandas as pd
from tqdm import tqdm
from sklearn.metrics import (
    accuracy_score, precision_recall_fscore_support,
    classification_report, confusion_matrix
)

LABEL_ORDER = ["FAKE", "MISLEADING", "REAL"]

def evaluate_mode_v2(
    dataset,
    mode="text_only",
    top_k_text=4,
    use_fc=True,
    per_sample_timeout=90,
    verbose=True,
):
    LABEL_ORDER = ["FAKE", "REAL"]

    results = []
    for item in tqdm(dataset, desc=f"Running {mode}"):
        try:
            row = run_one_sample_ablation(
                item, mode=mode, top_k_text=top_k_text,
                use_fc=use_fc, binary_dataset=True,
            )
        except Exception as e:
            row = {"claim": item.get("claim",""), "true": item.get("label",""),
                   "pred": "ERROR", "mode": mode, "confidence": 0.0}
        results.append(row)

    df    = pd.DataFrame(results)
    valid = df[df["pred"].astype(str) != "ERROR"].copy()
    y_true = valid["true"].astype(str)
    y_pred = valid["pred"].astype(str)

    acc         = accuracy_score(y_true, y_pred)
    p, r, f1, _ = precision_recall_fscore_support(
        y_true, y_pred, labels=LABEL_ORDER, average=None, zero_division=0
    )
    summary = {
        "mode":            mode,
        "n_total":         len(df),
        "n_valid":         len(valid),
        "n_error":         len(df) - len(valid),
        "accuracy":        round(acc, 4),
        "precision_macro": round(float(p.mean()), 4),
        "recall_macro":    round(float(r.mean()), 4),
        "f1_macro":        round(float(f1.mean()), 4),
    }
    cm     = confusion_matrix(y_true, y_pred, labels=LABEL_ORDER)
    report = classification_report(y_true, y_pred, labels=LABEL_ORDER, zero_division=0)

    if verbose:
        print("=" * 60)
        print(f"MODE: {mode}")
        for k, v in summary.items():
            print(f"  {k:<20} {v}")
        print(f"\nPrediction distribution:\n{valid['pred'].value_counts()}")
        print(f"\n{report}")
        print("\nConfusion matrix (rows=true, cols=pred):")
        print(pd.DataFrame(cm, index=LABEL_ORDER, columns=LABEL_ORDER))
        print("\nPer-class correct/total:")
        for lab in LABEL_ORDER:
            sub = valid[valid["true"] == lab]
            correct = (sub["pred"] == lab).sum()
            print(f"  {lab:<12} {correct}/{len(sub)}  ({100*correct/max(len(sub),1):.0f}%)")

    return df, summary, cm, report


# ── RUN ALL THREE MODES ───────────────────────────────────────────────────────
modes       = ["text_only", "text_clip", "text_clip_ocr"]
summaries   = []
all_outputs = {}

for m in modes:
    df_mode, summary, cm, report = evaluate_mode_v2(
        dataset=final_eval_dataset,
        mode=m,
        top_k_text=4,
        use_fc=True,
        per_sample_timeout=90,
        verbose=True,
    )
    path = f"/content/ablation_v2_{m}.csv"
    df_mode.to_csv(path, index=False)
    print(f"  Saved: {path}")
    all_outputs[m] = {"df": df_mode, "summary": summary}
    summaries.append(summary)

summary_df = (
    pd.DataFrame(summaries)
    .sort_values("f1_macro", ascending=False)
    .reset_index(drop=True)
)
print("\n" + "="*60)
print("ABLATION SUMMARY (sorted by macro-F1)")
print(summary_df[["mode","n_valid","accuracy","precision_macro",
                   "recall_macro","f1_macro"]].to_string(index=False))
summary_df.to_csv("/content/ablation_v2_summary.csv", index=False)
print("\nSaved: /content/ablation_v2_summary.csv")

# ── SAVE TO GOOGLE DRIVE SO FILES SURVIVE RESTART ────────────────────────────
import shutil
files_to_save = [
    "/content/ablation_v2_text_only.csv",
    "/content/ablation_v2_text_clip.csv",
    "/content/ablation_v2_text_clip_ocr.csv",
    "/content/ablation_v2_summary.csv",
]
for f in files_to_save:
    try:
        dest = f.replace("/content/", "/content/drive/MyDrive/")
        shutil.copy(f, dest)
        print(f"Saved to Drive: {dest}")
    except Exception as e:
        print(f"Failed: {f} — {e}")

Running text_only:   0%|          | 0/99 [00:00<?, ?it/s]

  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/fact-check/hamas-wedding-girls/
  [FC SKIP] only 0 matches (need 1): https://fullfact.org/conflict/
  NLI [FC]: e=0.285  c=0.532  src=https://www.snopes.com/fact-check/photograph-rafah

Running text_only:   1%|          | 1/99 [00:21<35:06, 21.49s/it]

  NLI [FC]: e=0.199  c=0.056  src=https://fullfact.org/news/iran-missile-drone-attac
  [FC REJECT] off-topic article: https://www.snopes.com/news/2024/01/22/israel-hamas-what-is-
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/fact-check/close-up-bees-face/
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/news/2022/04/08/mayim-bialik-allegati
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/2012/10/factchecking-the-hofstra-d
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/2017/05/trump-not-deporting-native
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/author/jordan/?pagenum=86

Running text_only:   2%|▏         | 2/99 [00:39<31:31, 19.50s/it]

  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/article/2025/mar/31/anonymous-x-a
  NLI [FC]: e=0.001  c=0.004  src=https://www.politifact.com/article/2023/oct/23/how
  [FC REJECT] off-topic article: https://www.snopes.com/fact-check/x-post-2023-cole-allen/
  [FC REJECT] off-topic article: https://www.snopes.com/news/2023/11/13/video-palestinian-man

Running text_only:   3%|▎         | 3/99 [00:58<30:55, 19.32s/it]

  NLI [FC]: e=0.010  c=0.001  src=https://www.factcheck.org/2025/01/republicans-wron
  NLI [FC]: e=0.864  c=0.005  src=https://www.politifact.com/article/2025/jan/02/how
  NLI [FC]: e=0.013  c=0.047  src=https://www.snopes.com/news/2025/01/02/new-orleans
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2022/jul/26/instagram-
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2023/jul/14/instagram-
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/fact-check/antarctica-seen-from-space
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2022/aug/30/facebook-p
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2022/sep/14/instagram-
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2022/aug/23/facebook-p
  [FC REJECT] off-topic article: https://www.politifact.com/factchecks/2022/oct/10/facebook-p
  [FC REJECT] off-topic article: https://www.politifact.com/factchecks/2023/apr/25/instagram-
  [FC REJECT] off-topic article: https://www.politifact.com/factchecks/2021/mar/02/facebook-p
  [FALLBACK] Using embedding similarity

Running text_only:   4%|▍         | 4/99 [01:16<29:54, 18.89s/it]

  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/category/photos/?pagenum=81
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2015/jul/16/chain-emai

Running text_only:   5%|▌         | 5/99 [01:34<28:33, 18.23s/it]

  [FC REJECT] off-topic article: https://www.snopes.com/fact-check/samira-ibrahim/
  [FC REJECT] off-topic article: https://www.snopes.com/fact-check/did-you-know-this/
  [FC REJECT] off-topic article: https://www.snopes.com/tag/the-new-york-evening/
  [FALLBACK] Using embedding similarity
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2016/feb/05/marco-rubi
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2018/aug/14/jeff-denha
  [FC SKIP] only 0 matches (need 1): https://fullfact.org/online/arma-3-footage-china-us-tensions
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2026/mar/10/donald-tru

Running text_only:   6%|▌         | 6/99 [02:03<33:59, 21.93s/it]

  [FC REJECT] off-topic article: https://fullfact.org/online/china-mosque-demolition-false/
  NLI [FC]: e=0.002  c=0.044  src=https://www.politifact.com/article/2024/apr/29/are
  NLI [FC]: e=0.018  c=0.009  src=https://fullfact.org/online/video-mosque-demolitio

Running text_only:   8%|▊         | 8/99 [02:32<27:53, 18.40s/it]

  NLI [FC]: e=0.001  c=0.005  src=https://www.snopes.com/news/2019/08/16/readers-thi
  NLI [FC]: e=0.002  c=0.008  src=https://www.snopes.com/news/2019/01/24/yahoo-news-
  [FC REJECT] off-topic article: https://www.snopes.com/tag/the-onion/

Running text_only:  11%|█         | 11/99 [02:52<15:50, 10.80s/it]

  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/fact-check/ronald-mcdonald-1892/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/2019/10/the-facts-on-mental-illnes
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/fact-check/
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/fact-check/antonio-west-shooting-deat
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/fact-check/school-shooters-death-pena
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/fact-check/girl-solved-murder-heart-t
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/news/2019/09/04/the-psychology-behind
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2020/feb/14/blog-posti

Running text_only:  12%|█▏        | 12/99 [02:55<12:05,  8.33s/it]

  [FC SKIP] only 0 matches (need 1): https://fullfact.org/online/serial-killer-roaming-england/
  [FC REJECT] off-topic article: https://www.politifact.com/factchecks/2022/may/25/chris-murp
  [FALLBACK] Using embedding similarity
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2018/apr/20/yournewswi
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/article/2019/mar/18/wikileaks-rus
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/misconceptions/the-origins-of-covi
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/article/2018/aug/02/fact-checking
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/article/2021/oct/28/ask-politifac

You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
Running text_only:  13%|█▎        | 13/99 [03:01<11:02,  7.70s/it]

  NLI [FC]: e=0.070  c=0.094  src=https://www.snopes.com/fact-check/funvax/
  [FC REJECT] off-topic article: https://www.factcheck.org/2019/06/falsehood-swirls-about-bid
  [FC REJECT] off-topic article: https://www.factcheck.org/2020/05/the-falsehoods-of-the-plan

Running text_only:  14%|█▍        | 14/99 [03:10<11:21,  8.01s/it]

  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/fact-check/goldfinger-actress-death/
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/news/2022/10/25/reepy-clown-history-h
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/fact-check/fauci-villain-dallas-buyer
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/fact-check/first-full-cgi-character/

Running text_only:  15%|█▌        | 15/99 [03:24<13:46,  9.84s/it]

  NLI [FC]: e=0.002  c=0.003  src=https://www.snopes.com/fact-check/luigi-beanie-ama
  [FC REJECT] off-topic article: https://www.snopes.com/fact-check/nintendo-free-him-luigi-po
  NLI [FC]: e=0.001  c=0.001  src=https://www.snopes.com/fact-check/uhc-shooter-mug-
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2018/aug/03/donald-tru

Running text_only:  16%|█▌        | 16/99 [03:40<15:56, 11.53s/it]

  [FC REJECT] off-topic article: https://www.factcheck.org/2020/02/trump-has-condemned-white-
  NLI [FC]: e=0.069  c=0.002  src=https://www.snopes.com/fact-check/war-games/
  [FC REJECT] off-topic article: https://www.politifact.com/article/2020/sep/10/ad-watch-what

Running text_only:  17%|█▋        | 17/99 [03:49<14:50, 10.86s/it]

  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/fact-check/using-regular-people/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2014/jan/26/richard-au
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/tag/usda/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2021/sep/16/facebook-p
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/fact-check/dod-pages-dei-holocaust/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/2025/05/rfk-jr-denies-cuts-to-scie
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2025/jan/30/karoline-l
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2012/feb/23/frank-nice
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2024/feb/02/instagram-
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/person/peter-mccullough/

Running text_only:  18%|█▊        | 18/99 [04:06<17:01, 12.61s/it]

  NLI [FC]: e=0.001  c=0.001  src=https://www.snopes.com/fact-check/trump-zelenskyy-
  [FC REJECT] off-topic article: https://www.factcheck.org/2019/12/zelenskys-remarks-about-tr
  NLI [FC]: e=0.001  c=0.015  src=https://www.snopes.com/fact-check/zelenskyy-us-ukr

Running text_only:  19%|█▉        | 19/99 [04:14<15:09, 11.37s/it]

  [FC REJECT] off-topic article: https://www.politifact.com/factchecks/2026/feb/09/social-med
  [FALLBACK] Using embedding similarity
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/fact-check/thanksgiving-massacre-pequ
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/article/2015/jul/22/half-truths-w

Running text_only:  20%|██        | 20/99 [04:26<15:04, 11.45s/it]

  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/2015/11/trump-carson-on-911-celebr
  [FC REJECT] off-topic article: https://www.snopes.com/fact-check/dec-11-memorial/
  NLI [FC]: e=0.022  c=0.005  src=https://www.snopes.com/news/2017/01/23/trump-patri
  [FC REJECT] off-topic article: https://www.snopes.com/fact-check/jest-in-time/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2025/jul/30/donald-tru
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2023/nov/02/vivek-rama
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/hot-topics/

Running text_only:  21%|██        | 21/99 [04:34<13:29, 10.37s/it]

  [FC REJECT] off-topic article: https://www.politifact.com/factchecks/2024/may/15/donald-tru
  NLI [FC]: e=0.013  c=0.002  src=https://www.politifact.com/article/2026/apr/02/fac
  [FC REJECT] off-topic article: https://www.politifact.com/factchecks/2025/jul/29/benjamin-n
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2024/mar/01/facebook-p
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/article/2025/nov/06/nancy-pelosi-
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/article/2019/aug/01/donald-trump-
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2020/jun/09/j-christia
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2023/aug/31/travis-tri
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/article/2026/mar/06/Markwayne-Mul
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2014/mar/03/florida-de

Running text_only:  22%|██▏       | 22/99 [04:43<13:03, 10.17s/it]

  [FC REJECT] off-topic article: https://www.politifact.com/article/2025/jun/06/jeffrey-epste
  [FC REJECT] off-topic article: https://www.politifact.com/factchecks/2023/nov/01/maga-inc/r
  [FC REJECT] off-topic article: https://www.politifact.com/factchecks/2018/jun/27/twentyeigh
  [FALLBACK] Using embedding similarity

Running text_only:  23%|██▎       | 23/99 [04:53<12:52, 10.17s/it]

  [FC REJECT] off-topic article: https://www.snopes.com/news/2018/09/06/many-daily-caller-wri
  [FC REJECT] off-topic article: https://www.snopes.com/
  [FALLBACK] Using embedding similarity

Running text_only:  24%|██▍       | 24/99 [05:02<12:13,  9.78s/it]

  [FC REJECT] off-topic article: https://www.snopes.com/tracker/trump-executive-orders-list/
  [FALLBACK] Using embedding similarity
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/2008/03/presidents-winning-without

Running text_only:  25%|██▌       | 25/99 [05:16<13:33, 10.99s/it]

  [FC REJECT] off-topic article: https://www.politifact.com/article/2024/nov/22/how-big-was-d
  NLI [FC]: e=0.066  c=0.017  src=https://www.factcheck.org/2024/11/trump-won-the-po
  NLI [FC]: e=0.004  c=0.013  src=https://www.factcheck.org/issue/presidential-elect
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/fact-check/spousal-success-story/
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/fact-check/corpus-crispy/
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/fact-check/still-the-queen/
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/fact-check/alix-idrache-west-point-gr
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/fact-check/dr-seuss-affair-wife-suici
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/2004/08/republican-funded-group-at

Running text_only:  26%|██▋       | 26/99 [05:37<16:49, 13.83s/it]

  [FC REJECT] off-topic article: https://www.snopes.com/fact-check/press-your-luck/
  [FC REJECT] off-topic article: https://www.snopes.com/fact-check/man-without-a-face/
  NLI [FC]: e=0.002  c=0.979  src=https://www.politifact.com/article/2018/aug/26/rem
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/fact-check/facebook-rule-photos-tv/
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/fact-check/facebook-bypass-system-hoa
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/fact-check/facebook-to-regain-friends
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/fact-check/new-facebook-rule-meta/

Running text_only:  27%|██▋       | 27/99 [05:43<13:56, 11.62s/it]

  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/fact-check/new-york-ceo-lamborghini/
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/fact-check/social-media-hacker-warnin
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/fact-check/bridezilla/
  [FC REJECT] off-topic article: https://www.snopes.com/fact-check/trump-volcanoes-concrete-p
  [FC REJECT] off-topic article: https://www.snopes.com/fact-check/
  [FALLBACK] Using embedding similarity
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/2017/02/trumps-bogus-terrorist-cla

Running text_only:  28%|██▊       | 28/99 [05:56<14:17, 12.08s/it]

  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/2019/10/the-facts-on-mental-illnes
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/2015/10/gun-laws-deaths-and-crimes
  [FC REJECT] off-topic article: https://www.politifact.com/embassyattacks/
  NLI [FC]: e=0.002  c=0.005  src=https://www.factcheck.org/2019/08/mass-killings-ac
  [FC REJECT] off-topic article: https://www.factcheck.org/2021/11/how-many-died-as-a-result-
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2020/jan/15/facebook-p
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2022/may/16/facebook-p

Running text_only:  29%|██▉       | 29/99 [06:24<19:26, 16.66s/it]

  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2023/aug/10/facebook-p
  [FC REJECT] off-topic article: https://www.politifact.com/article/2024/sep/27/has-a-venezue
  [FC REJECT] off-topic article: https://www.politifact.com/article/2024/oct/02/vp-debate-fac
  [FC REJECT] off-topic article: https://www.politifact.com/factchecks/2018/feb/23/philip-lev
  [FALLBACK] Using embedding similarity

Running text_only:  30%|███       | 30/99 [06:28<14:47, 12.87s/it]

  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/fact-check/film-crew-footage-gaza/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/article/2024/may/24/the-un-adjust
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2024/dec/06/instagram-

Running text_only:  31%|███▏      | 31/99 [06:36<13:13, 11.67s/it]

  NLI [FC]: e=0.003  c=0.043  src=https://www.politifact.com/factchecks/2025/jul/29/
  NLI [FC]: e=0.002  c=0.005  src=https://www.snopes.com/news/2024/05/02/netanyahu-h
  [FC REJECT] off-topic article: https://www.politifact.com/archive-beheaded-babies-israel-ha
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/2025/05/trump-allies-spread-unfoun
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2020/may/28/facebook-p

Running text_only:  32%|███▏      | 32/99 [07:40<30:32, 27.36s/it]

  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/2019/07/unpacking-bidens-and-trump
  [FC REJECT] off-topic article: https://www.politifact.com/article/2026/mar/26/covid-19-vari
  [FC REJECT] off-topic article: https://www.politifact.com/factchecks/2022/feb/23/instagram-
  [FC REJECT] off-topic article: https://www.snopes.com/fact-check/germany-gel-joint-cartilag
  [FALLBACK] Using embedding similarity

Running text_only:  34%|███▍      | 34/99 [08:08<21:51, 20.17s/it]

  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/2024/07/false-claim-about-fake-sec
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/2025/01/trump-justifies-j6-pardons

Running text_only:  35%|███▌      | 35/99 [08:28<21:39, 20.31s/it]

  NLI [FC]: e=0.010  c=0.932  src=https://www.factcheck.org/2021/04/posts-falsely-id
  NLI [FC]: e=0.001  c=0.012  src=https://www.politifact.com/factchecks/2024/jul/16/
  [FC REJECT] off-topic article: https://www.snopes.com/fact-check/derek-mullins-jasmine-cart
  [FC SKIP] only 0 matches (need 1): https://fullfact.org/online/lebanese-citizens-celebrating-Ha
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/fact-check/fire-tel-aviv-israel-iran-
  [FC SKIP] only 0 matches (need 1): https://fullfact.org/news/altered-audio-CNN-border-footage-s
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2014/jul/24/rula-jebre

Running text_only:  36%|███▋      | 36/99 [08:41<18:55, 18.03s/it]

  [FC SKIP] only 0 matches (need 1): https://fullfact.org/world/burj-khalifa-ai-iran/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/article/2026/mar/11/trump-iran-sc
  [FC REJECT] off-topic article: https://www.factcheck.org/2023/10/what-we-know-about-three-w
  [FC REJECT] off-topic article: https://www.snopes.com/fact-check/anti-netanyahu-protest-isr
  NLI [FC]: e=0.011  c=0.012  src=https://www.snopes.com/fact-check/crisis-actors-is
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/fact-check/hegseth-iran-war-christian
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/2012/10/false-claims-in-final-deba
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/fact-check/pope-leo-trump-insult-jesu
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/fact-check/pope-leo-xiv-iran-war/

Running text_only:  37%|███▋      | 37/99 [08:55<17:27, 16.89s/it]

  [FC REJECT] off-topic article: https://www.factcheck.org/2015/06/cruz-cherry-picks-terroris
  [FC REJECT] off-topic article: https://www.politifact.com/factchecks/2020/feb/29/facebook-p
  [FC REJECT] off-topic article: https://mail.snopes.com/p/new-post-0c67
  [FALLBACK] Using embedding similarity

Running text_only:  38%|███▊      | 38/99 [09:01<13:40, 13.45s/it]

  [FC SKIP] only 0 matches (need 1): https://staging.politifact.com/article/2019/jan/25/photo-cov

Running text_only:  39%|███▉      | 39/99 [09:11<12:29, 12.50s/it]

  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/collections/epstein-maxwell-clintons-
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/latest/?pagenum=798
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/fact-check/erika-kirk-tyler-robinson-
  NLI [FC]: e=0.028  c=0.698  src=https://www.snopes.com/fact-check/woman-jail-weari
  [FC REJECT] off-topic article: https://www.factcheck.org/2008/10/court-fight-in-the-heart-o
  [FC REJECT] off-topic article: https://www.factcheck.org/2008/11/2008-factcheck-awards/
  [FC SKIP] only 0 matches (need 1): https://fullfact.org/policy/reports/full-fact-report-2025/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/corrections-and-updates/

Running text_only:  40%|████      | 40/99 [09:40<17:14, 17.54s/it]

  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/article/2026/feb/18/dietary-prote
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/article/2026/feb/04/washington-DC
  [FC SKIP] only 0 matches (need 1): https://fullfact.org/policy/reports/full-fact-report-2024/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/article/2025/apr/24/RFK-jr-enviro
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/article/2026/mar/23/march-madness
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/article/2025/nov/13/biologics-bio
  [FC REJECT] off-topic article: https://www.politifact.com/article/2026/apr/07/choosing-best
  [FC REJECT] off-topic article: https://www.politifact.com/article/2026/mar/06/TrumpRx-presc
  [FALLBACK] Using embedding similarity

Running text_only:  41%|████▏     | 41/99 [09:56<16:24, 16.98s/it]

  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2025/jul/11/jon-favrea
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/article/2025/jun/06/jeffrey-epste
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2014/dec/03/jeb-bush/t
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2021/mar/02/donald-tru

Running text_only:  42%|████▏     | 42/99 [10:13<16:06, 16.96s/it]

  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2025/jul/28/markwayne-
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/article/2022/jun/09/political-ext
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2022/apr/28/facebook-p
  [FC REJECT] off-topic article: https://www.politifact.com/factchecks/2025/jul/18/donald-tru
  [FC REJECT] off-topic article: https://www.factcheck.org/2013/08/the-messy-facts-in-virgini
  [FC REJECT] off-topic article: https://www.politifact.com/factchecks/2026/jan/14/mehmet-oz/
  [FALLBACK] Using embedding similarity

Running text_only:  43%|████▎     | 43/99 [10:32<16:23, 17.56s/it]

  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/article/2018/feb/26/dunkirk-fact-
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2020/jan/15/facebook-p
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2025/mar/26/pete-hegse
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2024/sep/26/sam-brown/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/2024/08/misleading-democratic-ad-i
  [FC REJECT] off-topic article: https://www.politifact.com/factchecks/2024/jun/21/facebook-p
  [FC REJECT] off-topic article: https://www.snopes.com/fact-check/chris-evans-signing-bomb/
  [FC REJECT] off-topic article: https://www.snopes.com/tag/marvel/
  [FALLBACK] Using embedding similarity

Running text_only:  44%|████▍     | 44/99 [10:42<14:07, 15.41s/it]

  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/2010/09/bos-private-plane/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/2009/06/more-birther-nonsense-obam

Running text_only:  45%|████▌     | 45/99 [11:04<15:25, 17.14s/it]

  NLI [FC]: e=0.010  c=0.239  src=https://www.snopes.com/news/2021/06/21/mama-bear-g
  [FC REJECT] off-topic article: https://www.snopes.com/news/2016/04/10/spring-break-nightmar
  NLI [FC]: e=0.007  c=0.022  src=https://www.snopes.com/fact-check/man-stuck-2055-f

Running text_only:  46%|████▋     | 46/99 [11:08<11:52, 13.44s/it]

  NLI [FC]: e=0.001  c=0.016  src=https://www.politifact.com/factchecks/2024/jul/03/
  [FC REJECT] off-topic article: https://www.politifact.com/factchecks/2023/may/05/instagram-

Running text_only:  47%|████▋     | 47/99 [11:25<12:21, 14.26s/it]

  NLI [FC]: e=0.000  c=0.002  src=https://www.politifact.com/factchecks/2025/jul/09/
  NLI [FC]: e=0.000  c=0.001  src=https://www.politifact.com/personalities/scott-jen
  NLI [FC]: e=0.003  c=0.006  src=https://www.politifact.com/article/2026/apr/10/tru

Running text_only:  48%|████▊     | 48/99 [11:40<12:22, 14.56s/it]

  NLI [FC]: e=0.000  c=0.001  src=https://www.snopes.com/fact-check/trump-president-
  NLI [FC]: e=0.000  c=0.001  src=https://www.snopes.com/fact-check/trump-veterans-d
  NLI [FC]: e=0.011  c=0.047  src=https://www.snopes.com/fact-check/donald-tump-ffa-

Running text_only:  49%|████▉     | 49/99 [11:54<11:55, 14.31s/it]

  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/fact-check/karmelo-anthony-donations-
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/2020/06/meme-spreads-wrong-photo-d

Running text_only:  51%|█████     | 50/99 [12:03<10:31, 12.89s/it]

  [FC REJECT] off-topic article: https://www.snopes.com/fact-check/tiger-houston-neighborhood
  [FC REJECT] off-topic article: https://www.snopes.com/fact-check/texas-ice-raid-birthday-pa
  [FC REJECT] off-topic article: https://www.factcheck.org/2021/04/posts-falsely-identify-sus
  [FALLBACK] Using embedding similarity

Running text_only:  52%|█████▏    | 51/99 [12:20<11:21, 14.21s/it]

  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2022/dec/16/instagram-
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2024/dec/13/facebook-p
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/article/2022/mar/15/zuckerbucks-2
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2018/dec/04/blog-posti
  [FC SKIP] only 0 matches (need 1): https://fullfact.org/policy/reports/full-fact-report-2024/
  [FC SKIP] only 0 matches (need 1): https://fullfact.org/policy/reports/full-fact-report-2025/
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/author/snopes/?pagenum=45
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2019/jul/02/kamala-har

Running text_only:  53%|█████▎    | 52/99 [12:32<10:37, 13.55s/it]

  NLI [FC]: e=0.004  c=0.007  src=https://www.politifact.com/factchecks/2018/aug/07/
  [FC REJECT] off-topic article: https://www.politifact.com/factchecks/2018/dec/20/blog-posti
  [FC REJECT] off-topic article: https://www.politifact.com/factchecks/2017/nov/10/michael-mc
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/fact-check/missing-alaska-hikers-stor
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/fact-check/eric-langford-missing-boy-
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/fact-check/vacation-holiday-photo-vir

Running text_only:  54%|█████▎    | 53/99 [12:54<12:09, 15.87s/it]

  [FC REJECT] off-topic article: https://www.politifact.com/factchecks/2021/apr/19/facebook-p
  [FC REJECT] off-topic article: https://www.snopes.com/fact-check/log-pile-missing/
  [FC REJECT] off-topic article: https://www.politifact.com/factchecks/2025/apr/04/facebook-p
  [FALLBACK] Using embedding similarity
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/fact-check/yellowstone-animals-fleein
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/truth-o-meter/promises/obameter/p
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/article/2023/aug/08/you-and-your-

Running text_only:  55%|█████▍    | 54/99 [13:18<13:53, 18.52s/it]

  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2020/oct/01/joe-biden/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2012/feb/24/newt-gingr
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2024/nov/26/donald-tru
  [FC REJECT] off-topic article: https://www.factcheck.org/2023/01/its-too-soon-to-attribute-
  [FC REJECT] off-topic article: https://www.politifact.com/factchecks/2015/sep/29/mike-hucka
  [FALLBACK] Using embedding similarity
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/fact-check/american-three-terrorist-a

Running text_only:  56%|█████▌    | 55/99 [13:30<12:08, 16.56s/it]

  NLI [FC]: e=0.034  c=0.024  src=https://www.factcheck.org/2023/11/dozens-of-childr
  [FC REJECT] off-topic article: https://www.politifact.com/factchecks/2019/mar/04/blog-posti
  [FC REJECT] off-topic article: https://www.snopes.com/fact-check/ronald-mcdonald-1892/
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/fact-check/italy-doctor-corona-not-fl
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/fact-check/heart-attack-symptoms/
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/fact-check/onions-fight-flu-myth/
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/fact-check/call-police-new-guinea-fla

Running text_only:  57%|█████▋    | 56/99 [13:41<10:36, 14.81s/it]

  [FC REJECT] off-topic article: https://www.snopes.com/fact-check/hair-grooming-syncope/
  [FC REJECT] off-topic article: https://www.snopes.com/fact-check/swedes-called-in-gay-class
  [FC REJECT] off-topic article: https://www.snopes.com/fact-check/pfizer-covid-vaccine-adver
  [FALLBACK] Using embedding similarity
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/tag/artificial-intelligence/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/article/2019/oct/16/both-trade-an
  [FC SKIP] only 0 matches (need 1): https://fullfact.org/online/WEF-animal-charities/

Running text_only:  58%|█████▊    | 57/99 [13:50<09:09, 13.08s/it]

  [FC REJECT] off-topic article: https://www.politifact.com/article/2023/may/30/can-chatgpt-f
  [FC REJECT] off-topic article: https://www.snopes.com/category/science/?pagenum=46
  [FC REJECT] off-topic article: https://www.snopes.com/news/2015/07/29/mcdonalds-kiosks-mini
  [FALLBACK] Using embedding similarity

Running text_only:  59%|█████▊    | 58/99 [13:56<07:26, 10.89s/it]

  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/article/2019/mar/13/did-donald-tr
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/2005/08/here-we-go-again-distorted
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/2006/10/accusations-without-eviden
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/fact-check/alex-pretti-gun-video/

Running text_only:  60%|█████▉    | 59/99 [14:04<06:39,  9.98s/it]

  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2014/may/05/laura-ingr
  [FC REJECT] off-topic article: https://www.politifact.com/article/2019/sep/11/fact-checking
  [FC REJECT] off-topic article: https://www.snopes.com/news/2015/09/23/fidel-lopez/
  [FC REJECT] off-topic article: https://www.snopes.com/fact-check/trump-marines-la-texas/
  [FALLBACK] Using embedding similarity

Running text_only:  61%|██████    | 60/99 [14:06<04:53,  7.53s/it]

  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/fact-check/jfk-palestine-britain/

Running text_only:  62%|██████▏   | 61/99 [14:18<05:41,  8.97s/it]

  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2015/mar/03/bill-oreil
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/2008/09/factchecking-mccain/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2014/jul/17/facebook-p
  [FC REJECT] off-topic article: https://www.factcheck.org/2020/02/trump-repeats-falsehoods-i
  [FC REJECT] off-topic article: https://www.snopes.com/news/2018/06/13/lawsuit-brexit-backer
  NLI [FC]: e=0.004  c=0.014  src=https://www.snopes.com/tag/united-kingdom/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/2026/03/how-iran-blocking-the-stra
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/2016/04/trumps-foreign-policy-spee
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/2016/05/rep-jones-didnt-empower-ob
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/2026/03/trump-links-bidens-ukraine
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/2016/06/trump-wrong-on-iraqi-oil/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/article/2026/feb/27/iran-economic
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/article/2023/oct/09/fact-check-tr
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2015/jul/23/jon-stewar

Running text_only:  63%|██████▎   | 62/99 [14:37<07:22, 11.97s/it]

  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2016/mar/17/donald-tru
  [FC REJECT] off-topic article: https://www.politifact.com/factchecks/2009/jul/14/republican
  [FALLBACK] Using embedding similarity
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/2023/10/what-we-know-about-three-w

Running text_only:  64%|██████▎   | 63/99 [14:51<07:32, 12.57s/it]

  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/news/2025/08/11/al-jazeera-anas-al-sh
  [FC REJECT] off-topic article: https://www.snopes.com/news/2021/05/25/tom-cotton-associated
  [FC REJECT] off-topic article: https://www.snopes.com/newsletter-archive/snopes-digest-116-
  [FC REJECT] off-topic article: https://www.snopes.com/news/2025/10/28/hamas-ceasefire-viola
  [FALLBACK] Using embedding similarity

Running text_only:  65%|██████▍   | 64/99 [15:20<10:09, 17.42s/it]

  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/2026/04/trumps-numbers-april-2026-

Running text_only:  66%|██████▌   | 65/99 [15:38<10:00, 17.67s/it]

  [FC REJECT] off-topic article: https://www.politifact.com/article/2024/dec/26/a-month-by-mo
  [FC REJECT] off-topic article: https://www.politifact.com/
  [FC REJECT] off-topic article: https://www.snopes.com/
  [FALLBACK] Using embedding similarity

Running text_only:  67%|██████▋   | 66/99 [15:48<08:23, 15.26s/it]

  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2025/jan/15/instagram-
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/2015/07/clinton-spins-immigration-
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/2016/07/factchecking-clintons-big-
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/2020/02/trump-has-condemned-white-

Running text_only:  68%|██████▊   | 67/99 [15:55<06:58, 13.08s/it]

  NLI [FC]: e=0.209  c=0.006  src=https://www.factcheck.org/2015/11/bogus-meme-targe
  [FC REJECT] off-topic article: https://www.factcheck.org/2008/10/lying-about-being-liberal/
  [FC REJECT] off-topic article: https://www.factcheck.org/2019/04/what-kissinger-has-said-ab

Running text_only:  69%|██████▊   | 68/99 [16:12<07:18, 14.16s/it]

  [FC REJECT] off-topic article: https://www.snopes.com/tag/astronomy/
  [FC REJECT] off-topic article: https://www.snopes.com/tag/space/?pagenum=2
  [FALLBACK] Using embedding similarity

Running text_only:  70%|██████▉   | 69/99 [16:34<08:14, 16.49s/it]

  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/fact-check/revocation-of-independence
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/news/2020/12/23/what-history-really-t
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/article/2024/mar/12/princess-kate
  [FC SKIP] only 0 matches (need 1): https://fullfact.org/policy/reports/full-fact-report-2021/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2022/feb/21/facebook-p
  [FC REJECT] off-topic article: https://www.snopes.com/fact-check/royal-family-play-monopoly
  [FC REJECT] off-topic article: https://www.snopes.com/news/2022/09/08/queen-elizabeth-ii-a-
  [FALLBACK] Using embedding similarity
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/fact-check/tunnel-between-rafah-egypt

Running text_only:  71%|███████   | 70/99 [16:41<06:34, 13.61s/it]

  NLI [FC]: e=0.381  c=0.161  src=https://www.politifact.com/factchecks/2024/apr/22/
  [FC REJECT] off-topic article: https://www.politifact.com/factchecks/2014/jul/24/rula-jebre
  NLI [FC]: e=0.019  c=0.162  src=https://www.politifact.com/article/2026/apr/02/fac
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/2026/03/without-providing-evidence

Running text_only:  72%|███████▏  | 71/99 [17:01<07:15, 15.54s/it]

  NLI [FC]: e=0.001  c=0.005  src=https://www.snopes.com/collections/us-israel-war-i
  [FC REJECT] off-topic article: https://fullfact.org/conflict/footage-tel-aviv-destroyed-bui
  NLI [FC]: e=0.008  c=0.721  src=https://www.factcheck.org/2023/11/social-media-pos

Running text_only:  73%|███████▎  | 72/99 [17:17<06:59, 15.53s/it]

  NLI [FC]: e=0.001  c=0.003  src=https://www.factcheck.org/2021/07/factchecking-bid
  NLI [FC]: e=0.000  c=0.001  src=https://www.factcheck.org/2019/09/bidens-record-on
  NLI [FC]: e=0.001  c=0.001  src=https://www.factcheck.org/2020/09/factchecking-bid

Running text_only:  75%|███████▍  | 74/99 [17:43<05:56, 14.24s/it]

  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2023/apr/18/facebook-p
  [FC REJECT] off-topic article: https://www.politifact.com/factchecks/list/?page=44&speaker=
  [FC REJECT] off-topic article: https://www.politifact.com/factchecks/list/?page=95&category
  [FALLBACK] Using embedding similarity

Running text_only:  76%|███████▌  | 75/99 [17:55<05:27, 13.66s/it]

  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/2005/12/rnc-web-ad-are-democrats-w
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/fact-check/rashida-tlaib-bring-jihad/
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/fact-check/vance-trump-hitler-quote/
  [FC REJECT] off-topic article: https://www.snopes.com/fact-check/sydney-sweeney-ben-shapiro
  [FC REJECT] off-topic article: https://www.snopes.com/tag/ben-shapiro/
  [FC REJECT] off-topic article: https://www.snopes.com/tag/sydney_sweeney/
  [FALLBACK] Using embedding similarity
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/list/?category&ruling=
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/article/2026/apr/06/Trump-Iran-Tr

Running text_only:  77%|███████▋  | 76/99 [18:07<04:57, 12.92s/it]

  [FC REJECT] off-topic article: https://www.politifact.com/article/2026/jan/29/DHS-governmen
  [FC REJECT] off-topic article: https://www.politifact.com/personalities/democrats/
  [FC REJECT] off-topic article: https://www.politifact.com/factchecks/list/?category=&ruling
  [FALLBACK] Using embedding similarity

Running text_only:  78%|███████▊  | 77/99 [18:20<04:44, 12.95s/it]

  [FC REJECT] off-topic article: https://www.politifact.com/factchecks/2017/nov/10/michael-mc
  NLI [FC]: e=0.001  c=0.001  src=https://www.politifact.com/article/2015/dec/11/war
  [FC REJECT] off-topic article: https://www.factcheck.org/2016/08/trumps-false-obama-isis-li

Running text_only:  79%|███████▉  | 78/99 [18:40<05:21, 15.29s/it]

  [FC REJECT] off-topic article: https://www.factcheck.org/2011/12/the-whoppers-of-2011/
  [FC REJECT] off-topic article: https://www.factcheck.org/2005/10/no-death-penalty-for-hitle
  [FC REJECT] off-topic article: https://www.factcheck.org/2012/05/soft-glove-same-gps-fist/
  [FALLBACK] Using embedding similarity
  [FC SKIP] only 0 matches (need 1): https://fullfact.org/environment/haarp-not-behind-northern-l

Running text_only:  80%|███████▉  | 79/99 [18:56<05:05, 15.27s/it]

  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2021/apr/06/greg-abbot
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2025/aug/05/donald-tru
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/article/2026/mar/26/covid-19-vari
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2023/oct/06/joe-biden/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2016/jul/01/bonnie-rei
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2022/jun/04/charles-sc
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2024/jul/24/republican
  [FC REJECT] off-topic article: https://fullfact.org/news/hindu-festival-london-not-anti-imm
  [FC REJECT] off-topic article: https://fullfact.org/online/miscaptioned-video-child-syria-n
  [FALLBACK] Using embedding similarity

Running text_only:  81%|████████  | 80/99 [19:08<04:32, 14.33s/it]

  NLI [FC]: e=0.002  c=0.024  src=https://www.snopes.com/fact-check/musk-add-pop-sou
  NLI [FC]: e=0.010  c=0.036  src=https://www.snopes.com/fact-check/twitter-logo-tit
  NLI [FC]: e=0.003  c=0.010  src=https://www.snopes.com/fact-check/twitter-employee
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/2019/05/trump-17-repeats-in-17-hou
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/2011/03/obama-on-war-then-and-now/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/2018/08/a-rally-filled-with-repeat
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/article/2019/nov/14/obamas-hot-mi
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/2020/08/final-night-of-the-republi
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/2016/10/factchecking-the-vp-debate

Running text_only:  82%|████████▏ | 81/99 [19:23<04:22, 14.61s/it]

  [FC REJECT] off-topic article: https://www.politifact.com/factchecks/2018/jul/12/donald-tru
  [FC REJECT] off-topic article: https://www.politifact.com/article/2024/feb/14/fact-check-tr
  NLI [FC]: e=0.001  c=0.000  src=https://www.politifact.com/factchecks/2018/jul/12/

Running text_only:  83%|████████▎ | 82/99 [19:24<03:01, 10.68s/it]

  [FC SKIP] only 0 matches (need 1): https://fullfact.org/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/
  [FC SKIP] only 0 matches (need 1): https://fullfact.org/latest/
  [FC SKIP] only 0 matches (need 1): https://fullfact.org/vaccines/
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/
  [FC SKIP] only 0 matches (need 1): https://fullfact.org/immigration/
  [FC SKIP] only 0 matches (need 1): https://fullfact.org/online/onions/
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/top/
  [FC SKIP] only 0 matches (need 1): https://fullfact.org/fact-checks/

Running text_only:  84%|████████▍ | 83/99 [19:33<02:42, 10.17s/it]

  [FC REJECT] off-topic article: https://www.politifact.com/factchecks/2016/dec/28/jeff-brand
  [FALLBACK] Using embedding similarity
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/fact-check/israelis-absent-911/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2024/apr/30/tweets/pho
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2015/oct/09/ben-carson
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/article/2024/may/10/the-antisemit
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2026/mar/02/tweets/Ira

Running text_only:  85%|████████▍ | 84/99 [19:46<02:43, 10.93s/it]

  [FC REJECT] off-topic article: https://www.politifact.com/factchecks/2013/nov/27/marco-rubi
  [FC REJECT] off-topic article: https://www.politifact.com/factchecks/2011/sep/04/kinky-frie
  NLI [FC]: e=0.024  c=0.481  src=https://www.politifact.com/article/2025/oct/13/Tru

Running text_only:  86%|████████▌ | 85/99 [19:57<02:34, 11.04s/it]

  NLI [FC]: e=0.002  c=0.001  src=https://www.politifact.com/factchecks/2019/mar/04/

Running text_only:  87%|████████▋ | 86/99 [20:07<02:16, 10.47s/it]

  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/list/?category=&ruling
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2022/aug/11/kevin-mcca

Running text_only:  88%|████████▊ | 87/99 [20:28<02:44, 13.72s/it]

  NLI [FC]: e=0.184  c=0.003  src=https://www.politifact.com/factchecks/2026/feb/17/
  NLI [FC]: e=0.001  c=0.001  src=https://www.politifact.com/factchecks/2026/feb/13/
  NLI [FC]: e=0.008  c=0.027  src=https://www.politifact.com/factchecks/2025/feb/14/

Running text_only:  89%|████████▉ | 88/99 [20:31<01:57, 10.65s/it]

  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/article/2025/aug/18/trump-zelensk

Running text_only:  90%|████████▉ | 89/99 [20:43<01:49, 10.90s/it]

  NLI [FC]: e=0.000  c=0.015  src=https://www.snopes.com/news/2025/02/21/ukraine-ele
  [FC REJECT] off-topic article: https://www.snopes.com/fact-check/us-trump-trip-world-leader
  NLI [FC]: e=0.000  c=0.000  src=https://www.snopes.com/fact-check/zelenskyy-say-no

Running text_only:  91%|█████████ | 90/99 [21:10<02:20, 15.64s/it]

  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/article/2018/jul/05/fact-checking

Running text_only:  92%|█████████▏| 91/99 [21:23<02:00, 15.02s/it]

  NLI [FC]: e=0.012  c=0.007  src=https://www.politifact.com/factchecks/2019/nov/15/
  NLI [FC]: e=0.068  c=0.005  src=https://www.politifact.com/factchecks/2024/aug/23/
  NLI [FC]: e=0.306  c=0.081  src=https://www.politifact.com/factchecks/list/?catego

Running text_only:  93%|█████████▎| 92/99 [21:38<01:45, 15.07s/it]

  NLI [FC]: e=0.005  c=0.012  src=https://www.factcheck.org/person/kathy-hochul/
  NLI [FC]: e=0.000  c=0.001  src=https://www.politifact.com/personalities/kathy-hoc
  NLI [FC]: e=0.001  c=0.000  src=https://www.politifact.com/factchecks/list/?speake

Building prefix dict from /usr/local/lib/python3.12/dist-packages/jieba/dict.txt ...
DEBUG:jieba:Building prefix dict from /usr/local/lib/python3.12/dist-packages/jieba/dict.txt ...
Dumping model to file cache /tmp/jieba.cache
DEBUG:jieba:Dumping model to file cache /tmp/jieba.cache
Loading model cost 1.9831280708312988 seconds.
DEBUG:jieba:Loading model cost 1.9831280708312988 seconds.
Prefix dict has been built succesfully.
DEBUG:jieba:Prefix dict has been built succesfully.
Running text_only:  94%|█████████▍| 93/99 [21:56<01:35, 15.97s/it]

  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2025/jan/31/facebook-p
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/list/?page=8&category=
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/fact-check/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2022/apr/28/facebook-p
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/article/2023/apr/13/state-legisla

Running text_only:  95%|█████████▍| 94/99 [22:12<01:18, 15.73s/it]

  NLI [FC]: e=0.001  c=0.000  src=https://www.politifact.com/factchecks/2022/oct/21/
  [FC REJECT] off-topic article: https://www.politifact.com/factchecks/2024/feb/16/instagram-
  [FC REJECT] off-topic article: https://www.politifact.com/factchecks/2019/jan/23/facebook-p
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/2023/11/social-media-posts-misrepr

Running text_only:  96%|█████████▌| 95/99 [22:25<01:00, 15.06s/it]

  NLI [FC]: e=0.000  c=0.007  src=https://www.snopes.com/news/2025/10/28/hamas-cease
  NLI [FC]: e=0.058  c=0.012  src=https://www.snopes.com/articles/465623/oct-7-hamas
  NLI [FC]: e=0.000  c=0.003  src=https://www.snopes.com/news/2026/02/11/israel-stri
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/hot-topics/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/2018/10/factchecking-trumps-60-min

Running text_only:  97%|█████████▋| 96/99 [22:44<00:48, 16.09s/it]

  NLI [FC]: e=0.026  c=0.271  src=https://www.factcheck.org/2018/07/factchecking-rus
  [FC REJECT] off-topic article: https://www.politifact.com/factchecks/2018/mar/16/viralpolit
  [FC REJECT] off-topic article: https://www.factcheck.org/2018/02/words-trump-russian-meddli
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/fact-check/michelle-obama-harvey-wein
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/article/2013/feb/15/government-jo
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/article/2016/jan/22/iowa-gantlet-

Running text_only:  98%|█████████▊| 97/99 [22:55<00:29, 14.58s/it]

  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2011/sep/05/barack-oba
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/article/2010/jan/13/announcing-po
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2011/oct/06/critics-wa
  NLI [FC]: e=0.013  c=0.003  src=https://www.politifact.com/article/2012/oct/19/fac
  [FC REJECT] off-topic article: https://www.politifact.com/factchecks/2011/jan/31/sameh-shou
  [FC REJECT] off-topic article: https://www.politifact.com/factchecks/?page=709&
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2014/feb/11/hugh-fitzs

Running text_only:  99%|█████████▉| 98/99 [23:12<00:15, 15.28s/it]

  [FC REJECT] off-topic article: https://www.politifact.com/factchecks/2021/jun/04/tiktok-pos
  [FC REJECT] off-topic article: https://www.politifact.com/factchecks/2025/aug/07/tiktok-pos
  [FALLBACK] Using embedding similarity

Running text_only: 100%|██████████| 99/99 [23:26<00:00, 14.21s/it]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:557: RuntimeWarning: Mean of empty slice.
  avg = a.mean(axis, **keepdims_kw)
/usr/local/lib/python3.12/dist-packages/numpy/_core/_methods.py:138: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

  NLI [FC]: e=0.028  c=0.367  src=https://www.politifact.com/factchecks/2020/jun/03/
  [FC REJECT] off-topic article: https://www.snopes.com/news/2026/03/13/katie-johnson-arreste
  [FC REJECT] off-topic article: https://www.politifact.com/factchecks/2024/jul/12/threads-po
============================================================
MODE: text_only
  mode                 text_only
  n_total              99
  n_valid              0
  n_error              99
  accuracy             nan
  precision_macro      0.0
  recall_macro         0.0
  f1_macro             0.0

Prediction distribution:
Series([], Name: count, dtype: int64)

              precision    recall  f1-score   support

        FAKE       0.00      0.00      0.00       0.0
        REAL       0.00      0.00      0.00       0.0

    accuracy                           0.00       0.0
   macro avg       0.00      0.00      0.00       0.0
weighted avg       0.00      0.00      0.00       0.0


Confusion matrix (rows=true, cols=pred):
      FAKE  REAL
FAKE     0     0
REAL     0     0

Per-class correct/total:
  FAKE         0/0  (0%)
  REAL         0/0  (0%)
  Saved: /content/ablation_v2_text_only.csv

Running text_clip:   0%|          | 0/99 [00:00<?, ?it/s]

  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/fact-check/hamas-wedding-girls/
  [FC SKIP] only 0 matches (need 1): https://fullfact.org/conflict/
  NLI [FC]: e=0.285  c=0.532  src=https://www.snopes.com/fact-check/photograph-rafah
  NLI [FC]: e=0.199  c=0.056  src=https://fullfact.org/news/iran-missile-drone-attac
  [FC REJECT] off-topic article: https://www.snopes.com/news/2024/01/22/israel-hamas-what-is-

Running text_clip:   1%|          | 1/99 [00:05<09:26,  5.78s/it]

  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/fact-check/close-up-bees-face/
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/news/2022/04/08/mayim-bialik-allegati
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/2012/10/factchecking-the-hofstra-d
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/2017/05/trump-not-deporting-native
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/author/jordan/?pagenum=86

Running text_clip:   2%|▏         | 2/99 [00:13<11:14,  6.96s/it]

  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/article/2025/mar/31/anonymous-x-a
  NLI [FC]: e=0.001  c=0.004  src=https://www.politifact.com/article/2023/oct/23/how
  [FC REJECT] off-topic article: https://www.snopes.com/fact-check/x-post-2023-cole-allen/
  [FC REJECT] off-topic article: https://www.snopes.com/news/2023/11/13/video-palestinian-man

Running text_clip:   2%|▏         | 2/99 [00:14<11:58,  7.41s/it]

KeyboardInterrupt:

In [88]:
item = final_eval_dataset[0]
row = run_one_sample_ablation(
    item,
    mode="text_only",
    top_k_text=4,
    use_fc=True,
    binary_dataset=True,
)
print("Pred:", row["pred"])
print("True:", row["true"])
print("Confidence:", row["confidence"])

  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/fact-check/hamas-wedding-girls/
  [FC SKIP] only 0 matches (need 1): https://fullfact.org/conflict/
  NLI [FC]: e=0.285  c=0.532  src=https://www.snopes.com/fact-check/photograph-rafah
  NLI [FC]: e=0.199  c=0.056  src=https://fullfact.org/news/iran-missile-drone-attac
  [FC REJECT] off-topic article: https://www.snopes.com/news/2024/01/22/israel-hamas-what-is-
Pred: FAKE
True: FAKE
Confidence: 29.42

In [ ]:
import pandas as pd
from tqdm import tqdm
from sklearn.metrics import (
    accuracy_score, precision_recall_fscore_support,
    classification_report, confusion_matrix
)

LABEL_ORDER = ["FAKE", "MISLEADING", "REAL"]

def evaluate_mode_v2(
    dataset,
    mode="text_only",
    top_k_text=4,
    use_fc=True,
    per_sample_timeout=90,   # DeBERTa is slower than distilbert — give it time
    verbose=True,
):
    LABEL_ORDER = ["FAKE", "REAL"]   # binary — no MISLEADING

    results = []
    for item in tqdm(dataset, desc=f"Running {mode}"):
        try:
            row = run_one_sample_ablation(
                item, mode=mode, top_k_text=top_k_text,
                use_fc=use_fc, binary_dataset=True,
            )
        except Exception as e:
            row = {"claim": item.get("claim",""), "true": item.get("label",""),
                   "pred": "ERROR", "mode": mode, "confidence": 0.0}
        results.append(row)

    df    = pd.DataFrame(results)
    valid = df[df["pred"].astype(str) != "ERROR"].copy()
    y_true = valid["true"].astype(str)
    y_pred = valid["pred"].astype(str)

    acc         = accuracy_score(y_true, y_pred)
    p, r, f1, _ = precision_recall_fscore_support(
        y_true, y_pred, labels=LABEL_ORDER, average=None, zero_division=0
    )
    summary = {
        "mode":            mode,
        "n_total":         len(df),
        "n_valid":         len(valid),
        "n_error":         len(df) - len(valid),
        "accuracy":        round(acc, 4),
        "precision_macro": round(float(p.mean()), 4),
        "recall_macro":    round(float(r.mean()), 4),
        "f1_macro":        round(float(f1.mean()), 4),
    }
    cm     = confusion_matrix(y_true, y_pred, labels=LABEL_ORDER)
    report = classification_report(y_true, y_pred, labels=LABEL_ORDER, zero_division=0)

    if verbose:
        print("=" * 60)
        print(f"MODE: {mode}")
        for k, v in summary.items():
            print(f"  {k:<20} {v}")
        print(f"\nPrediction distribution:\n{valid['pred'].value_counts()}")
        print(f"\n{report}")
        print("\nConfusion matrix (rows=true, cols=pred):")
        print(pd.DataFrame(cm, index=LABEL_ORDER, columns=LABEL_ORDER))
        print("\nPer-class correct/total:")
        for lab in LABEL_ORDER:
            sub = valid[valid["true"] == lab]
            correct = (sub["pred"] == lab).sum()
            print(f"  {lab:<12} {correct}/{len(sub)}  ({100*correct/max(len(sub),1):.0f}%)")

    return df, summary, cm, report


# ── NOW RUN IT ────────────────────────────────────────────────────────────────
modes     = ["text_only", "text_clip", "text_clip_ocr"]
summaries = []
all_outputs = {}

for m in modes:
    df_mode, summary, cm, report = evaluate_mode_v2(
        dataset=final_eval_dataset,
        mode=m,
        top_k_text=4,
        use_fc=True,
        per_sample_timeout=90,
        verbose=True,
    )
    path = f"/content/ablation_v2_{m}.csv"
    df_mode.to_csv(path, index=False)
    print(f"  Saved: {path}")
    all_outputs[m] = {"df": df_mode, "summary": summary}
    summaries.append(summary)

summary_df = (
    pd.DataFrame(summaries)
    .sort_values("f1_macro", ascending=False)
    .reset_index(drop=True)
)
print("\n" + "="*60)
print("ABLATION SUMMARY (sorted by macro-F1)")
print(summary_df[["mode","n_valid","accuracy","precision_macro",
                   "recall_macro","f1_macro"]].to_string(index=False))
summary_df.to_csv("/content/ablation_v2_summary.csv", index=False)
print("\nSaved: /content/ablation_v2_summary.csv")

Running text_only:   0%|          | 0/99 [00:00<?, ?it/s]

  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/fact-check/hamas-wedding-girls/

You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset

  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/news/2023/10/13/idf-white-phosphorus-
  [FC SKIP] only 0 matches (need 2): https://fullfact.org/conflict/
  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/fact-check/ai-photo-missiles-tel-aviv
  NLI [FC]: e=0.285  c=0.532  src=https://www.snopes.com/fact-check/photograph-rafah
  NLI [FC]: e=0.199  c=0.056  src=https://fullfact.org/news/iran-missile-drone-attac
  NLI [FC]: e=0.676  c=0.026  src=https://www.snopes.com/fact-check/richard-engel-is

Running text_only:   1%|          | 1/99 [00:08<13:35,  8.33s/it]

  NLI     : e=0.002  c=0.994  src=https://www.timesofisrael.com/liveblog_entry/idf-i
  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/2012/10/factchecking-the-hofstra-d
  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/2017/05/trump-not-deporting-native

Running text_only:   2%|▏         | 2/99 [00:16<13:19,  8.25s/it]

  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2025/10/competing-claims-on-who-be
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/article/2025/mar/31/anonymous-x-a
  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/fact-check/close-up-bees-face/
  NLI [FC]: e=0.001  c=0.004  src=https://www.politifact.com/article/2023/oct/23/how
  [FC REJECT] off-topic article: https://www.snopes.com/fact-check/x-post-2023-cole-allen/
  NLI     : e=0.000  c=0.002  src=https://tweetdelete.net/resources/are-twitter-book
  [FC REJECT] off-topic article: https://www.snopes.com/news/2023/11/13/video-palestinian-man

Running text_only:   3%|▎         | 3/99 [00:38<22:56, 14.34s/it]

  NLI [FC]: e=0.010  c=0.001  src=https://www.factcheck.org/2025/01/republicans-wron
  NLI [FC]: e=0.864  c=0.005  src=https://www.politifact.com/article/2025/jan/02/how
  NLI [FC]: e=0.013  c=0.047  src=https://www.snopes.com/news/2025/01/02/new-orleans
  NLI     : e=0.988  c=0.003  src=https://abc7.com/post/what-know-shamsud-din-jabbar
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2022/jul/26/instagram-
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2023/jul/14/instagram-
  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/fact-check/antarctica-seen-from-space
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2023/apr/25/instagram-
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2022/aug/30/facebook-p
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2022/oct/10/facebook-p
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2022/sep/14/instagram-
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2021/mar/02/facebook-p
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2022/aug/23/facebook-p
  NLI     : e=0.009  c=0.005  src=https://www.outsideonline.com/outdoor-adventure/ex
  NLI     : e=0.009  c=0.319  src=https://www.history.co.uk/articles/reasons-captain
  NLI     : e=0.110  c=0.108  src=https://www.coolantarctica.com/Antarctica%20fact%2

Running text_only:   4%|▍         | 4/99 [00:48<19:58, 12.61s/it]

  NLI     : e=0.002  c=0.960  src=https://www.quora.com/What-do-the-people-who-belie
  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/fact-check/samira-ibrahim/
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2023/oct/13/instagram-
  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/fact-check/a-farewell-to-arms/
  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/category/photos/?pagenum=81
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2015/jul/16/chain-emai
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/article/2015/jul/22/half-truths-w
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/list/?page=209&speaker
  NLI     : e=0.001  c=0.000  src=https://www.indiatoday.in/fact-check/story/fact-ch
  NLI     : e=0.002  c=0.000  src=https://www.reuters.com/fact-check/video-shows-fre
  NLI     : e=0.000  c=0.002  src=https://www.dogrula.org/en/fact-checks/was-the-vid

Running text_only:   5%|▌         | 5/99 [01:00<19:50, 12.66s/it]

  NLI     : e=0.001  c=0.000  src=https://www.misbar.com/amp/en/factcheck/2024/06/26

Running text_only:   6%|▌         | 6/99 [01:12<19:04, 12.31s/it]

  NLI     : e=0.002  c=0.002  src=https://www.boomlive.in/fact-check/factcheck-mosqu
  NLI     : e=0.000  c=0.002  src=https://www.reuters.com/fact-check/video-shows-dem
  NLI     : e=0.001  c=0.004  src=https://africacheck.org/fact-checks/meta-programme
  NLI     : e=0.018  c=0.002  src=https://www.bbc.com/news/world-asia-china-67483202
  NLI     : e=0.108  c=0.003  src=https://apnews.com/article/somaliland-presidential
  NLI     : e=0.997  c=0.000  src=https://www.reuters.com/world/africa/somaliland-op
  NLI     : e=0.000  c=0.009  src=https://en.wikipedia.org/wiki/2024_Somaliland_pres

Running text_only:   7%|▋         | 7/99 [01:26<19:43, 12.87s/it]

  NLI     : e=0.002  c=0.001  src=https://www.yahoo.com/news/somaliland-opposition-l
  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/notes/why-we-include-humor-and-satire

Running text_only:   8%|▊         | 8/99 [01:43<21:28, 14.16s/it]

  NLI     : e=0.010  c=0.040  src=https://apnews.com/article/onion-satire-alex-jones
  NLI     : e=0.001  c=0.004  src=https://www.cnn.com/2026/04/20/media/the-onion-ale
  NLI [FC]: e=0.001  c=0.005  src=https://www.snopes.com/news/2019/08/16/readers-thi
  NLI     : e=0.999  c=0.000  src=https://www.pbs.org/video/the-onion-is-adding-cont

Running text_only:   9%|▉         | 9/99 [01:49<17:33, 11.70s/it]

  NLI     : e=0.002  c=0.002  src=https://www.threads.com/@based.angxl_/post/DC8W638

Running text_only:  10%|█         | 10/99 [02:00<17:08, 11.55s/it]

  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/article/2020/oct/19/fact-checking
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/article/2020/may/22/hunter-biden-
  NLI     : e=0.120  c=0.180  src=https://apnews.com/article/fact-check-dali-ship-ba
  NLI     : e=0.119  c=0.173  src=https://www.usatoday.com/story/news/factcheck/2024
  NLI [FC]: e=0.013  c=0.899  src=https://www.politifact.com/factchecks/2024/mar/27/
  NLI     : e=0.074  c=0.603  src=https://www.fox8live.com/2024/03/12/angela-chao-sh

Running text_only:  12%|█▏        | 12/99 [02:10<12:13,  8.43s/it]

  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/fact-check/lost-child-rape-lure/
  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/fact-check/ronald-mcdonald-1892/
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2022/05/tv-ads-about-cheri-beasley
  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/fact-check/
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2019/05/meme-inflates-school-shoot
  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/news/2020/06/24/rayshard-brooks-crimi
  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/fact-check/school-shooters-death-pena
  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/2019/10/the-facts-on-mental-illnes
  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/ap/2018/11/14/authorities-prosecuting
  NLI [FC]: e=0.181  c=0.097  src=https://www.snopes.com/news/2019/09/04/the-psychol

Running text_only:  13%|█▎        | 13/99 [02:16<10:43,  7.48s/it]

  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2019/06/falsehood-swirls-about-bid
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2018/apr/20/yournewswi
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2020/05/the-falsehoods-of-the-plan
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/article/2019/mar/18/wikileaks-rus
  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/misconceptions/the-origins-of-covi
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/article/2020/apr/17/what-we-know-
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2023/06/video-distorts-early-coron
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/article/2018/aug/02/fact-checking
  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/fact-check/queen-elizabeth-gorilla-bl
  NLI [FC]: e=0.070  c=0.094  src=https://www.snopes.com/fact-check/funvax/
  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/fact-check/goldfinger-actress-death/
  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/news/2022/10/25/reepy-clown-history-h
  NLI     : e=0.000  c=0.000  src=https://www.flavorwire.com/509157/lets-stop-tellin
  NLI     : e=0.001  c=0.003  src=https://kotaku.com/sexism-character-design-and-the
  NLI     : e=0.003  c=0.000  src=https://medium.com/@mirandasalinger/the-villinizat

Running text_only:  14%|█▍        | 14/99 [02:36<15:54, 11.23s/it]

  NLI     : e=0.000  c=0.000  src=https://www.quora.com/The-guy-I-m-dating-treats-me

Running text_only:  15%|█▌        | 15/99 [02:47<15:54, 11.36s/it]

  NLI [FC]: e=0.002  c=0.003  src=https://www.snopes.com/fact-check/luigi-beanie-ama
  [FC REJECT] off-topic article: https://www.snopes.com/fact-check/nintendo-free-him-luigi-po
  NLI [FC]: e=0.001  c=0.001  src=https://www.snopes.com/fact-check/uhc-shooter-mug-
  NLI     : e=0.004  c=0.004  src=https://www.nbcnewyork.com/news/local/crime-and-co

Running text_only:  16%|█▌        | 16/99 [02:57<15:09, 10.96s/it]

  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2020/02/trump-has-condemned-white-
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2018/aug/03/donald-tru
  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/fact-check/war-games/
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2022/03/the-facts-on-de-nazifying-
  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/2017/04/100-days-whoppers/
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/article/2020/sep/10/ad-watch-what
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2015/oct/16/jason-vill
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2018/mar/06/david-simm
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2024/may/14/instagram-
  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/fact-check/trump-very-fine-people/

Running text_only:  17%|█▋        | 17/99 [03:11<16:15, 11.90s/it]

  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/fact-check/using-regular-people/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/2025/03/rfk-jr-s-faulty-advice-on-
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/2021/03/scicheck-video-targets-gat
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/person/peter-mccullough/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2021/sep/16/facebook-p
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/2025/05/rfk-jr-denies-cuts-to-scie
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2024/feb/02/instagram-
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2022/jul/27/instagram-
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2014/jan/26/richard-au
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/tag/usda/
  NLI     : e=0.018  c=0.104  src=https://americancattlemen.com/to-cull-or-not-to-cu
  NLI     : e=0.007  c=0.004  src=https://www.bbc.com/news/articles/c4gzl9d759po
  NLI     : e=0.015  c=0.007  src=https://en.wikipedia.org/wiki/Culling
  NLI     : e=0.006  c=0.020  src=https://www.backyardchickens.com/threads/culling-w
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2019/12/zelenskys-remarks-about-tr
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2023/03/social-media-posts-misrepr
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/person/volodymyr-zelenskyy/
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2019/11/discrepancy-in-white-house
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/issue/ukraine/

Running text_only:  18%|█▊        | 18/99 [03:23<15:45, 11.67s/it]

  NLI [FC]: e=0.025  c=0.571  src=https://www.factcheck.org/2025/02/trumps-false-and
  NLI [FC]: e=0.000  c=0.000  src=https://www.politifact.com/article/2025/aug/18/tru
  NLI [FC]: e=0.001  c=0.015  src=https://www.snopes.com/fact-check/zelenskyy-us-ukr
  NLI     : e=0.999  c=0.000  src=https://www.foxnews.com/world/zelenskyy-says-trump

Running text_only:  19%|█▉        | 19/99 [03:29<13:23, 10.05s/it]

  NLI     : e=0.005  c=0.004  src=https://www.nytimes.com/live/2024/01/30/opinion/th
  NLI     : e=0.015  c=0.004  src=https://www.taxnotes.com/research/federal/legislat
  NLI     : e=0.004  c=0.000  src=https://www.govinfo.gov/content/pkg/CHRG-116hhrg39
  NLI     : e=0.004  c=0.004  src=https://www.theodorerooseveltcenter.org/quotes/pag
  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/fact-check/dec-11-memorial/
  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/2013/01/anti-nra-groups-shameless-
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/article/2016/jul/29/backstory-mus
  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/2017/06/trumps-tweets-twist-facts/

Running text_only:  20%|██        | 20/99 [03:42<14:21, 10.91s/it]

  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2004/10/media-fund-twists-the-trut
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/article/2015/jul/22/half-truths-w
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/article/2016/oct/08/context-donal
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2018/01/response-iranian-protests-
  [FC REJECT] off-topic article: https://www.politifact.com/factchecks/2014/dec/02/facebook-p
  [FALLBACK] Using embedding similarity
  TEXT ERROR [US to hold national day of mourning for ]: name 'embedding_stance_fallback' is not defined
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2023/10/what-we-know-about-three-w
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/article/2024/may/16/how-unprecede

Running text_only:  21%|██        | 21/99 [04:02<17:41, 13.61s/it]

  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/collections/israel-hamas-ceasefire/
  [FC REJECT] off-topic article: https://www.politifact.com/factchecks/2023/oct/13/instagram-
  NLI [FC]: e=0.013  c=0.002  src=https://www.politifact.com/article/2026/apr/02/fac
  NLI [FC]: e=0.060  c=0.036  src=https://www.factcheck.org/2026/03/legality-of-late
  NLI     : e=0.359  c=0.031  src=https://www.aa.com.tr/en/middle-east/explosions-he
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2024/mar/01/facebook-p
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/article/2025/nov/06/nancy-pelosi-
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/article/2019/aug/01/donald-trump-
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2018/jun/27/twentyeigh
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2023/aug/31/travis-tri
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/article/2017/jan/27/heres-what-do
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/article/2026/mar/06/Markwayne-Mul
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2014/mar/03/florida-de

Running text_only:  22%|██▏       | 22/99 [04:16<17:40, 13.77s/it]

  [FC REJECT] off-topic article: https://www.politifact.com/article/2025/jun/06/jeffrey-epste
  [FC REJECT] off-topic article: https://www.politifact.com/factchecks/2023/nov/01/maga-inc/r
  NLI     : e=0.000  c=0.001  src=https://www.foxnews.com/media/carter-feuded-succes
  NLI     : e=0.000  c=0.001  src=https://ground.news/article/carter-feuded-with-suc

Running text_only:  23%|██▎       | 23/99 [04:28<16:56, 13.37s/it]

  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/news/2018/09/06/many-daily-caller-wri
  NLI     : e=0.032  c=0.008  src=https://www.foxnews.com/us/fox-news-antisemitism-e
  NLI     : e=0.001  c=0.004  src=https://www.foxnews.com/us/fox-news-antisemitism-e
  NLI     : e=0.005  c=0.005  src=https://www.foxnews.com/world/global-rise-antisemi
  NLI     : e=0.003  c=0.015  src=https://www.foxnews.com/world/antisemitism-spiking

Running text_only:  24%|██▍       | 24/99 [04:48<19:17, 15.43s/it]

  NLI     : e=0.997  c=0.000  src=https://www.reuters.com/markets/deals/us-steel-nip
  [FC REJECT] off-topic article: https://www.snopes.com/tracker/trump-executive-orders-list/
  NLI     : e=0.999  c=0.000  src=https://www.cnn.com/2025/01/06/business/us-steel-b
  NLI     : e=0.999  c=0.000  src=https://www.pbs.org/newshour/politics/biden-reject
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2024/11/both_sides_distort_incompl
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2024/nov/08/instagram-

Running text_only:  25%|██▌       | 25/99 [05:00<17:32, 14.23s/it]

  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/2008/03/presidents-winning-without
  [FC REJECT] off-topic article: https://www.politifact.com/factchecks/2021/jan/07/donald-tru
  [FC REJECT] off-topic article: https://www.politifact.com/article/2024/nov/22/how-big-was-d
  NLI [FC]: e=0.066  c=0.017  src=https://www.factcheck.org/2024/11/trump-won-the-po
  NLI     : e=0.997  c=0.000  src=https://news.syr.edu/2024/11/06/what-happens-to-th
  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/2010/07/shirley-sherrods-contextua
  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/news/2015/11/23/clock-kid-ahmed-moham
  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/2004/08/republican-funded-group-at
  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/fact-check/still-the-queen/
  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/fact-check/cesar-sayoc-obama-supporti
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/article/2018/jul/05/fact-checking
  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/news/2016/07/11/black-officer-jay-sta
  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/fact-check/the-day-i-met-daniel/
  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/fact-check/spousal-success-story/
  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/fact-check/the-last-of-the-kennedy-dy
  NLI     : e=1.000  c=0.000  src=https://www.voanews.com/a/india-reflects-on-ravi-s
  NLI     : e=0.989  c=0.000  src=https://indiacurrents.com/the-global-ambassador-of

Running text_only:  26%|██▋       | 26/99 [05:15<17:44, 14.58s/it]

  NLI     : e=0.003  c=0.000  src=https://www.elsewhere.co.nz/world-music/332/ravi-s
  NLI     : e=0.973  c=0.001  src=https://www.bbc.com/news/articles/cwype77kwyjo
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/fact-check/oregon-ballot-omits-donald
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/fact-check/marine-wedding/
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/fact-check/facebook-rule-photos-tv/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/2010/01/clueless-columbo/
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/fact-check/prayer-request-child-shot-

Running text_only:  27%|██▋       | 27/99 [05:39<20:45, 17.29s/it]

  [FC REJECT] off-topic article: https://www.snopes.com/fact-check/report-from-a-paramedic/
  [FC REJECT] off-topic article: https://www.snopes.com/fact-check/maryland-billboard-guns-tr
  [FC REJECT] off-topic article: https://www.snopes.com/fact-check/trump-volcanoes-concrete-p
  NLI     : e=0.014  c=0.089  src=https://scottrobinsonhonda.com/video-reels/?wchann
  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/2017/02/trumps-bogus-terrorist-cla
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2015/jun/22/barack-oba
  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/2015/10/gun-laws-deaths-and-crimes

Running text_only:  28%|██▊       | 28/99 [05:59<21:24, 18.09s/it]

  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/2019/10/the-facts-on-mental-illnes
  NLI     : e=0.983  c=0.003  src=https://www.threads.com/@cnn/post/DAEOXX6KH7r
  [FC REJECT] off-topic article: https://www.politifact.com/embassyattacks/
  NLI     : e=0.007  c=0.237  src=https://apnews.com/live/lebanon-syria-pagers-hezbo
  NLI     : e=0.701  c=0.001  src=https://www.timesofisrael.com/liveblog_entry/leban
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2018/nov/04/blog-posti
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2018/feb/23/philip-lev
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/article/2024/oct/02/vp-debate-fac

Running text_only:  29%|██▉       | 29/99 [06:17<21:17, 18.26s/it]

  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2022/may/16/facebook-p
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2023/aug/10/facebook-p
  NLI     : e=0.968  c=0.008  src=https://www.today.com/news/news/jamie-foxx-injured
  NLI     : e=0.997  c=0.002  src=https://www.tmz.com/2024/12/14/jamie-foxx-fight-mr
  [FC REJECT] off-topic article: https://www.politifact.com/article/2024/sep/27/has-a-venezue
  NLI     : e=0.999  c=0.000  src=https://www.nbclosangeles.com/entertainment/entert

Running text_only:  30%|███       | 30/99 [06:32<19:50, 17.25s/it]

  NLI     : e=0.088  c=0.460  src=https://t.me/s/MojahdeenMN?after=55418
  NLI     : e=0.217  c=0.208  src=https://t.me/s/auem_yemen/46872
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2025/jul/29/benjamin-n
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/archive-beheaded-babies-israel-ha
  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/fact-check/film-crew-footage-gaza/
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/article/2025/dec/12/genocide-isra
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/article/2024/may/24/the-un-adjust
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/article/2025/dec/15/lie-of-the-ye
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2024/dec/06/instagram-
  NLI [FC]: e=0.002  c=0.005  src=https://www.snopes.com/news/2024/05/02/netanyahu-h
  NLI [FC]: e=0.003  c=0.003  src=https://www.politifact.com/factchecks/2015/mar/22/

Running text_only:  31%|███▏      | 31/99 [06:44<17:32, 15.47s/it]

  NLI     : e=0.013  c=0.001  src=https://transcripts.cnn.com/show/cnc/date/2024-09-

Running text_only:  32%|███▏      | 32/99 [06:51<14:42, 13.17s/it]

  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/2019/07/unpacking-bidens-and-trump
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2020/may/28/facebook-p
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2024/dec/30/instagram-
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2022/feb/23/instagram-
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2025/05/trump-allies-spread-unfoun
  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/collections/barron-trump-rumors-colle
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2020/08/covid-19-nasal-swab-test-d
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/issue/government-run-health-care/f
  NLI     : e=0.996  c=0.002  src=https://www.dailystar.co.uk/news/latest-news/new-d
  [FC REJECT] off-topic article: https://www.snopes.com/fact-check/germany-gel-joint-cartilag
  NLI     : e=0.002  c=0.002  src=https://www.bbc.com/news/articles/clyx9nv4mleo
  NLI     : e=0.072  c=0.025  src=https://www.cnn.com/2025/12/19/science/beachy-head

Running text_only:  33%|███▎      | 33/99 [07:04<14:17, 12.99s/it]

  NLI     : e=0.995  c=0.000  src=https://www.chazakrescue.org/news-updates/mayotte-
  NLI     : e=0.019  c=0.002  src=https://www.pbs.org/newshour/world/mayotte-imposes
  NLI     : e=0.000  c=0.000  src=https://www.bbc.com/news/articles/c89x0j1le4lo
  NLI     : e=0.001  c=0.001  src=https://www.columbian.com/news/2024/dec/17/authori

Running text_only:  34%|███▍      | 34/99 [07:29<17:57, 16.58s/it]

  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/news/2016/06/19/daily-caller-error-fi
  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/2008/03/wisconsin-judgment-day-the
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/article/2015/sep/22/fact-checking
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/article/2016/dec/13/2016-lie-year
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2024/nov/21/threads-po
  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/2009/02/who-is-linda-panetta/
  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/fact-check/huckabee-sanders-red-hen-p
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/article/2015/jan/22/ernsts-bread-
  NLI     : e=0.007  c=0.001  src=https://www.foxnews.com/media/embarrassingly-wrong
  NLI     : e=0.004  c=0.001  src=https://abc3340.com/news/nation-world/questions-em
  NLI     : e=0.026  c=0.007  src=https://www.yahoo.com/news/gullible-wrong-journali
  NLI     : e=0.001  c=0.000  src=https://www.newyorker.com/news/fault-lines/whos-to
  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/2020/05/baseless-conspiracy-theory
  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/fact-check/derek-mullins-jasmine-cart

Running text_only:  35%|███▌      | 35/99 [07:41<16:08, 15.13s/it]

  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2024/09/posts-misrepresent-police-
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2019/03/social-posts-spin-sanders-
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2024/jul/16/threads-po
  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/person/george-floyd/
  NLI     : e=0.992  c=0.005  src=https://www.12onyourside.com/2024/12/09/key-detail
  NLI [FC]: e=0.010  c=0.932  src=https://www.factcheck.org/2021/04/posts-falsely-id
  NLI [FC]: e=0.005  c=0.027  src=https://www.factcheck.org/2020/05/falsehoods-follo
  NLI     : e=0.997  c=0.001  src=https://6abc.com/15622805/
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2023/10/what-we-know-about-three-w
  [FC SKIP] only 0 matches (need 2): https://fullfact.org/news/altered-audio-CNN-border-footage-s
  [FC SKIP] only 0 matches (need 2): https://fullfact.org/world/arab-fact-checking-lessons-from-p

Running text_only:  36%|███▋      | 36/99 [07:55<15:38, 14.90s/it]

  [FC SKIP] only 0 matches (need 2): https://fullfact.org/world/burj-khalifa-ai-iran/
  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/2023/11/online-video-misrepresents
  [FC SKIP] only 0 matches (need 2): https://fullfact.org/online/lebanese-citizens-celebrating-Ha
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/article/2026/mar/11/trump-iran-sc
  [FC REJECT] off-topic article: https://www.snopes.com/fact-check/anti-netanyahu-protest-isr
  NLI [FC]: e=0.021  c=0.023  src=https://www.factcheck.org/2023/12/post-misrepresen
  NLI [FC]: e=0.011  c=0.012  src=https://www.snopes.com/fact-check/crisis-actors-is
  NLI     : e=0.013  c=0.007  src=https://www.bbc.com/news/videos/ce9jeev2grro
  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/fact-check/hegseth-iran-war-christian
  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/news/2025/02/24/congo-70-christians-b
  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/fact-check/pope-leo-xiv-iran-war/
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2015/06/cruz-cherry-picks-terroris
  [FC SKIP] only 1 matches (need 2): https://mail.snopes.com/p/new-post-0c67
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2021/aug/19/facebook-p
  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/fact-check/saved-by-humility/

Running text_only:  37%|███▋      | 37/99 [08:14<16:39, 16.12s/it]

  NLI     : e=0.000  c=0.001  src=https://www.ewtnnews.com/world/europe/7-catholic-c
  [FC REJECT] off-topic article: https://www.politifact.com/factchecks/2011/feb/07/ron-paul/r
  [FC REJECT] off-topic article: https://www.politifact.com/factchecks/2014/aug/01/georgiacar
  [FC REJECT] off-topic article: https://www.politifact.com/factchecks/2020/feb/29/facebook-p

Running text_only:  38%|███▊      | 38/99 [08:16<11:59, 11.80s/it]

  [FC SKIP] only 0 matches (need 2): https://staging.politifact.com/article/2019/jan/25/photo-cov
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2008/11/2008-factcheck-awards/
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2008/10/court-fight-in-the-heart-o
  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/collections/epstein-maxwell-clintons-
  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/fact-check/pam-bondi-cross-necklace/

Running text_only:  39%|███▉      | 39/99 [08:23<10:21, 10.35s/it]

  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/article/2016/oct/18/allegations-a
  NLI [FC]: e=0.028  c=0.698  src=https://www.snopes.com/fact-check/woman-jail-weari
  [FC REJECT] off-topic article: https://www.politifact.com/factchecks/2010/oct/22/roy-barnes
  NLI     : e=0.020  c=0.034  src=https://www.yahoo.com/entertainment/celebrity/arti
  NLI     : e=0.016  c=0.419  src=https://www.yahoo.com/entertainment/celebrity/arti
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/corrections-and-updates/
  [FC SKIP] only 0 matches (need 1): https://fullfact.org/policy/reports/full-fact-report-2024/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/article/2026/feb/18/dietary-prote
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/article/2026/feb/04/washington-DC

Running text_only:  40%|████      | 40/99 [08:58<17:39, 17.96s/it]

  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/article/2026/mar/23/march-madness
  [FC REJECT] off-topic article: https://www.snopes.com/fact-check/dracula-live-transylvanian
  [FC REJECT] off-topic article: https://www.politifact.com/article/2026/apr/07/choosing-best
  [FC REJECT] off-topic article: https://www.politifact.com/article/2026/mar/06/TrumpRx-presc
  NLI     : e=0.001  c=0.001  src=https://www.bbc.com/news/world-europe-17776565

Running text_only:  41%|████▏     | 41/99 [09:16<17:13, 17.81s/it]

  NLI     : e=0.070  c=0.000  src=https://apnews.com/article/koala-chlamydia-vaccina
  NLI     : e=0.001  c=0.000  src=https://www.bbc.com/news/articles/cjdnkdg1l8do
  NLI     : e=0.004  c=0.000  src=https://www.reuters.com/business/healthcare-pharma
  NLI     : e=0.159  c=0.000  src=https://www.euronews.com/2025/09/12/new-vaccine-ai

Running text_only:  42%|████▏     | 42/99 [09:26<14:47, 15.57s/it]

  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2013/08/the-messy-facts-in-virgini
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2019/aug/09/pete-butti
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2025/jul/11/jon-favrea
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2021/mar/02/donald-tru
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/article/2025/jun/06/jeffrey-epste
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2013/jul/03/debbie-was
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/article/2022/jun/09/political-ext
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2014/dec/03/jeb-bush/t
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2025/jul/18/donald-tru
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/article/2022/jan/28/what-you-need
  NLI     : e=0.001  c=0.002  src=http://archive.is/duYni
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2020/jan/15/facebook-p
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/article/2018/feb/26/dunkirk-fact-
  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/2024/08/misleading-democratic-ad-i
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2024/sep/26/sam-brown/

Running text_only:  43%|████▎     | 43/99 [09:37<13:04, 14.01s/it]

  [FC REJECT] off-topic article: https://www.politifact.com/factchecks/2025/mar/26/pete-hegse
  [FC REJECT] off-topic article: https://www.snopes.com/fact-check/chris-evans-signing-bomb/
  NLI     : e=0.009  c=0.009  src=https://www.yahoo.com/entertainment/chris-evans-cl
  NLI     : e=0.000  c=0.995  src=https://okmagazine.com/p/captain-america-chris-eva

Running text_only:  44%|████▍     | 44/99 [09:49<12:19, 13.45s/it]

  NLI     : e=0.025  c=0.715  src=https://en.wikipedia.org/wiki/Pear_of_anguish
  NLI     : e=0.070  c=0.024  src=https://medievaltorturemuseum.com/blog/pear-anguis
  NLI     : e=0.035  c=0.007  src=https://allthatsinteresting.com/pear-of-anguish
  NLI     : e=0.043  c=0.008  src=https://medievalbritain.com/type/medieval-life/tor
  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/news/2016/04/10/spring-break-nightmar
  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/fact-check/man-stuck-2055-france/
  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/2010/09/bos-private-plane/
  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/news/2026/02/25/kash-patel-olympic-ho
  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/category/viral-phenomena/?pagenum=18
  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/fact-check/yusra-mardini-flee-syria-s
  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/fact-check/racist-carnival-game/
  NLI     : e=0.041  c=0.002  src=https://www.foxnews.com/travel/man-vacation-goes-v
  NLI     : e=0.028  c=0.001  src=https://nypost.com/2024/12/31/lifestyle/man-on-vac
  NLI [FC]: e=0.010  c=0.239  src=https://www.snopes.com/news/2021/06/21/mama-bear-g

Running text_only:  45%|████▌     | 45/99 [10:00<11:22, 12.64s/it]

  NLI [FC]: e=0.017  c=0.443  src=https://www.snopes.com/fact-check/kentucky-snow-fl

Running text_only:  46%|████▋     | 46/99 [10:11<10:47, 12.22s/it]

  NLI [FC]: e=0.001  c=0.016  src=https://www.politifact.com/factchecks/2024/jul/03/
  NLI     : e=0.001  c=0.000  src=https://forums.dukebasketballreport.com/index.php?
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2025/jul/09/scott-jenn
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/article/2022/sep/29/united-facts-
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/article/2026/jan/03/trump-maduro-
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/article/2016/apr/06/we-fact-check
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/article/2026/feb/25/democrats-sta
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/article/2025/nov/03/trump-60-minu

Running text_only:  47%|████▋     | 47/99 [10:20<09:52, 11.40s/it]

  NLI     : e=0.884  c=0.013  src=https://www.foxnews.com/video/6365955471112
  NLI     : e=1.000  c=0.000  src=https://www.mediaite.com/media/tv/dont-touch-me-sc
  NLI     : e=0.996  c=0.001  src=https://www.foxnews.com/media/scott-jennings-bakar
  NLI     : e=0.999  c=0.000  src=https://nypost.com/2024/12/14/media/cnn-contributo
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/article/2017/may/02/whats-up-with
  NLI [FC]: e=0.000  c=0.001  src=https://www.snopes.com/fact-check/trump-veterans-d
  NLI [FC]: e=0.011  c=0.047  src=https://www.snopes.com/fact-check/donald-tump-ffa-
  NLI     : e=0.002  c=0.050  src=https://www.foxnews.com/opinion/how-trump-survives

Running text_only:  48%|████▊     | 48/99 [10:31<09:36, 11.31s/it]

  NLI     : e=0.000  c=0.000  src=https://abc17news.com/politics/2026/04/26/trump-fi

Running text_only:  49%|████▉     | 49/99 [10:46<10:16, 12.34s/it]

  NLI     : e=0.017  c=0.001  src=https://www.foxnews.com/media/psychologist-jonatha
  NLI     : e=0.000  c=0.000  src=https://cyberbullying.org/student-phones-school-ba
  NLI     : e=0.001  c=0.017  src=https://www.applerouth.com/blog/parents-phones-and
  NLI     : e=0.000  c=0.000  src=https://ground.news/article/how-jonathan-haidt-won
  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/fact-check/texas-ice-raid-birthday-pa
  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/fact-check/tiger-houston-neighborhood
  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/fact-check/texas-alien-anal-probe/
  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/fact-check/carl-twinly-cow-arrest/
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2010/nov/11/greg-abbot
  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/fact-check/karmelo-anthony-donations-
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2015/jul/30/harry-houc
  NLI     : e=0.000  c=0.000  src=https://fastguardservice.com/texas-police-arrest-9
  NLI     : e=0.000  c=0.000  src=https://www.foxnews.com/video/6365971915112
  NLI     : e=0.964  c=0.001  src=https://www.foxnews.com/us/texas-police-arrest-9-s

Running text_only:  51%|█████     | 50/99 [10:56<09:31, 11.66s/it]

  NLI     : e=0.164  c=0.001  src=https://www.fox7austin.com/news/lakeline-mall-shop
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2022/dec/16/instagram-
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/article/2022/mar/15/zuckerbucks-2
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2024/dec/13/facebook-p
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2018/dec/04/blog-posti
  NLI     : e=0.120  c=0.001  src=https://www.realtor.com/news/reality-tv/christina-
  NLI     : e=0.996  c=0.002  src=https://www.wwbl.com/2025/01/07/hgtv-star-christin
  NLI     : e=0.997  c=0.000  src=https://www.foxnews.com/entertainment/hgtv-star-ch

Running text_only:  52%|█████▏    | 51/99 [11:18<11:50, 14.80s/it]

  NLI     : e=0.998  c=0.001  src=https://www.cosmopolitan.com/entertainment/celebs/
  [FC SKIP] only 0 matches (need 2): https://fullfact.org/policy/reports/full-fact-report-2024/
  [FC SKIP] only 0 matches (need 2): https://fullfact.org/policy/reports/full-fact-report-2025/
  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/author/snopes/?pagenum=45
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2018/dec/20/blog-posti
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2018/aug/07/greg-abbot

Running text_only:  53%|█████▎    | 52/99 [11:31<11:01, 14.07s/it]

  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2015/jul/20/rick-perry
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2019/jul/02/kamala-har
  [FC REJECT] off-topic article: https://www.politifact.com/factchecks/2017/nov/10/michael-mc
  NLI     : e=0.099  c=0.439  src=https://www.express.co.uk/news/uk/1979993/westmins
  NLI     : e=0.006  c=0.860  src=https://uk.news.yahoo.com/westmister-bridge-150736
  NLI     : e=0.000  c=0.994  src=https://www.bbc.com/news/articles/c5y3en5yv21o
  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/fact-check/log-pile-missing/
  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/fact-check/eric-langford-missing-boy-
  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/fact-check/missing-alaska-hikers-stor
  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/news/2026/04/28/scientists-dead-missi

Running text_only:  54%|█████▎    | 53/99 [11:49<11:40, 15.22s/it]

  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/article/2025/aug/25/kilmar-abrego
  NLI     : e=0.028  c=0.031  src=https://www.aol.com/articles/hiker-stumbles-human-
  NLI     : e=0.995  c=0.003  src=https://abc7.com/post/severely-decomposed-human-re
  NLI     : e=0.999  c=0.000  src=https://www.foxnews.com/us/police-investigating-af
  NLI [FC]: e=0.021  c=0.376  src=https://www.politifact.com/factchecks/2023/aug/22/

Running text_only:  55%|█████▍    | 54/99 [12:14<13:48, 18.40s/it]

  NLI     : e=0.027  c=0.023  src=https://issuu.com/outlawpartners/docs/explore_big_
  NLI     : e=0.002  c=0.001  src=https://www.youtube.com/shorts/sSCIeF_wUE8
  NLI     : e=0.223  c=0.128  src=https://www.youtube.com/watch?v=dOrawfTwJPY
  NLI     : e=0.223  c=0.128  src=https://www.youtube.com/watch?v=UHdfT8TbR4c

Running text_only:  56%|█████▌    | 55/99 [12:33<13:35, 18.53s/it]

  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/fact-check/isis-crisis-2/
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/fake-news/page/16/
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2019/mar/04/blog-posti
  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/fact-check/american-three-terrorist-a
  [FC REJECT] off-topic article: https://www.politifact.com/article/2023/nov/21/israel-hamas-
  NLI [FC]: e=0.034  c=0.024  src=https://www.factcheck.org/2023/11/dozens-of-childr
  [FC REJECT] off-topic article: https://www.factcheck.org/2023/10/what-we-know-about-three-w
  NLI     : e=0.304  c=0.014  src=https://www.aa.com.tr/en/middle-east/children-amon

Running text_only:  57%|█████▋    | 56/99 [12:40<10:47, 15.06s/it]

  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/fact-check/pfizer-covid-vaccine-adver
  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/fact-check/call-police-new-guinea-fla
  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/fact-check/dangers-dihydrogen-monoxid
  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/fact-check/mayo-clinic/
  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/fact-check/hair-grooming-syncope/
  NLI     : e=0.003  c=0.001  src=https://www.yahoo.com/news/articles/trump-post-him
  NLI     : e=0.000  c=0.000  src=https://www.bbc.com/news/videos/c624dy3pgg2o
  NLI     : e=0.004  c=0.185  src=https://www.bbc.com/news/articles/c17v8y0z9z2o
  NLI     : e=0.000  c=0.005  src=https://www.courthousenews.com/i-thought-it-was-me

Running text_only:  58%|█████▊    | 57/99 [12:44<08:16, 11.81s/it]

  [FC SKIP] only 1 matches (need 2): https://www.merriam-webster.com/dictionary/could
  [FC SKIP] only 1 matches (need 2): https://dictionary.cambridge.org/us/dictionary/english/could
  [FC SKIP] only 1 matches (need 2): https://en.wiktionary.org/wiki/could
  [FC SKIP] only 1 matches (need 2): https://www.grammarly.com/blog/commonly-confused-words/can-v
  [FC SKIP] only 1 matches (need 2): https://www.dictionary.com/browse/could
  [FC SKIP] only 1 matches (need 2): https://www.youtube.com/watch?v=OiYmamqv7H0
  [FC SKIP] only 1 matches (need 2): https://www.collinsdictionary.com/us/dictionary/english/coul
  [FC SKIP] only 1 matches (need 2): https://www.youtube.com/watch?v=z_PyX-NAKEI
  NLI     : e=0.993  c=0.001  src=https://www.space.com/astronomy/mars/artificial-su
  NLI     : e=0.003  c=0.002  src=https://www.quora.com/How-can-AI-driven-robots-and
  NLI     : e=0.001  c=0.000  src=https://www.bbc.com/news/articles/cy7keddnj31o
  NLI     : e=0.010  c=0.003  src=https://news.stanford.edu/stories/2025/12/ai-robot

Running text_only:  59%|█████▊    | 58/99 [13:08<10:23, 15.22s/it]

  NLI [FC]: e=0.079  c=0.028  src=https://checkyourfact.com/2024/06/18/fact-check-ke
  NLI [FC]: e=0.012  c=0.001  src=https://www.snopes.com/fact-check/keanu-reeves-who
  NLI     : e=0.020  c=0.026  src=https://news.meaww.com/fact-check-did-keanu-reeves
  NLI     : e=0.981  c=0.003  src=https://visegrad25.quora.com/BREAKING-Keanu-Reeves

Running text_only:  60%|█████▉    | 59/99 [13:15<08:38, 12.95s/it]

  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/2016/02/factchecking-the-eighth-go
  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/2006/10/accusations-without-eviden
  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/2025/11/sorting-out-the-facts-on-e
  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/2005/08/here-we-go-again-distorted
  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/2022/11/conservative-figures-sprea
  [FC SKIP] only 1 matches (need 2): https://mail.snopes.com/p/shackled-bodies-in-spain-health-ca
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2014/may/05/laura-ingr
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2013/jan/18/facebook-p
  [FC REJECT] off-topic article: https://www.factcheck.org/2023/10/what-we-know-about-three-w
  NLI     : e=0.004  c=0.565  src=https://www.reuters.com/fact-check/photos-show-202
  NLI     : e=0.837  c=0.002  src=https://www.wionews.com/world/iran-prez-ebrahim-ra
  NLI     : e=0.000  c=0.007  src=https://www.timesofisrael.com/liveblog_entry/iran-

Running text_only:  61%|██████    | 60/99 [13:42<11:02, 16.98s/it]

  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/fact-check/jfk-palestine-britain/
  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/news/2018/06/13/lawsuit-brexit-backer
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2015/mar/03/bill-oreil
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2010/jan/22/charles-sc
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2014/jul/17/facebook-p

Running text_only:  62%|██████▏   | 61/99 [14:03<11:34, 18.29s/it]

  [FC REJECT] off-topic article: https://www.factcheck.org/2008/10/life-cycle-of-a-rumor/
  NLI     : e=0.006  c=0.030  src=https://apnews.com/article/elon-musk-britain-riots
  NLI     : e=0.000  c=0.021  src=https://foxbaltimore.com/station/share/musk-slams-
  NLI     : e=0.000  c=0.021  src=https://katv.com/news/nation-world/musk-slams-uk-a
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2026/03/how-iran-blocking-the-stra
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/article/2026/feb/27/iran-economic
  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/2016/04/trumps-foreign-policy-spee
  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/2016/05/rep-jones-didnt-empower-ob
  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/2016/06/trump-wrong-on-iraqi-oil/
  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/fact-check/netanyahu-gaza-2035-plan/
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/article/2026/apr/06/strait-hormuz
  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/2026/03/trump-links-bidens-ukraine
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/article/2023/oct/09/fact-check-tr
  NLI     : e=0.086  c=0.739  src=https://www.theguardian.com/world/live/2024/oct/29
  NLI     : e=0.042  c=0.016  src=https://www.aa.com.tr/en/middle-east/us-deeply-con
  NLI     : e=0.007  c=0.039  src=https://truthout.org/articles/israel-used-us-bomb-

Running text_only:  63%|██████▎   | 62/99 [14:29<12:41, 20.59s/it]

  NLI [FC]: e=0.006  c=0.044  src=https://www.snopes.com/fact-check/trumps-us-gaza-a
  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/news/2025/10/28/hamas-ceasefire-viola
  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/news/2021/05/25/tom-cotton-associated
  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/newsletter-archive/snopes-digest-116-
  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/fact-check/gaza-strip-photo/
  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/news/2025/08/11/al-jazeera-anas-al-sh
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2023/11/post-makes-unfounded-claim

Running text_only:  64%|██████▎   | 63/99 [14:36<09:57, 16.60s/it]

  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/fact-check/turkey-warship-gaza/
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2014/sep/18/julie-pace
  [FC REJECT] off-topic article: https://www.snopes.com/fact-check/clinton-netanyahu-satire-v
  [FC REJECT] off-topic article: https://www.snopes.com/news/2023/10/16/china-hamas-israel-ga
  NLI     : e=0.999  c=0.000  src=https://www.foxnews.com/world/israeli-airstrikes-c
  NLI     : e=0.053  c=0.001  src=https://www.longwarjournal.org/archives/2024/11/is

Running text_only:  65%|██████▍   | 64/99 [14:52<09:29, 16.28s/it]

  NLI     : e=0.005  c=0.030  src=https://www.foxnews.com/us/new-orleans-barricade-o
  NLI     : e=0.002  c=0.001  src=https://www.foxnews.com/us/new-orleans-revelers-na
  NLI     : e=0.037  c=0.007  src=https://apnews.com/article/new-orleans-car-bourbon
  NLI     : e=0.002  c=0.001  src=https://www.pbs.org/newshour/politics/watch-live-f
  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/2026/04/trumps-numbers-april-2026-
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/article/2024/dec/26/a-month-by-mo
  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/location/international/
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2026/02/trump-oversells-recent-u-s
  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/

Running text_only:  66%|██████▌   | 65/99 [15:00<07:54, 13.96s/it]

  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/2026/02/manufacturing-construction
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2025/05/democrats-exaggerate-estim
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/article/2026/jan/20/trump-inflati
  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/2026/02/a-pre-sotu-guide-to-trumps
  NLI     : e=0.007  c=0.002  src=https://www.foxnews.com/world/israel-warns-go-afte
  NLI     : e=0.006  c=0.009  src=https://www.yahoo.com/news/where-ceasefire-talks-b
  NLI     : e=0.002  c=0.000  src=https://www.ntd.com/ntdplus/israel-hezbollah-agree
  [FC REJECT] off-topic article: https://www.politifact.com/
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2025/jan/15/instagram-
  NLI     : e=0.000  c=0.000  src=https://beartrackinn.com/frequently-asked-question
  NLI     : e=0.003  c=0.001  src=https://fullsuitcase.com/kids-pack-plane/
  NLI     : e=0.061  c=0.510  src=https://www.remitly.com/blog/travel/chicago-o-hare

Running text_only:  67%|██████▋   | 66/99 [16:34<20:54, 38.01s/it]

  NLI     : e=0.027  c=0.024  src=http://www.ketchikanmuseums.org/virtual_exhibit/ve
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2012/12/firefighters-fact-checking
  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/2015/07/clinton-spins-immigration-
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2015/11/bogus-meme-targets-trump/
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2019/04/what-kissinger-has-said-ab
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2008/10/lying-about-being-liberal/
  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/2016/07/factchecking-clintons-big-
  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/2020/02/trump-has-condemned-white-
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2012/07/you-didnt-build-that-uncut
  NLI [FC]: e=0.140  c=0.033  src=https://www.factcheck.org/2009/04/here-there-be-pi
  NLI [FC]: e=0.025  c=0.012  src=https://www.factcheck.org/2012/08/factcheck-mailba
  NLI     : e=0.022  c=0.024  src=https://prospect.org/2024/03/20/2024-03-20-what-re

Running text_only:  68%|██████▊   | 67/99 [16:55<17:24, 32.63s/it]

  NLI     : e=0.002  c=0.039  src=https://www.nytimes.com/2023/12/04/podcasts/the-da

Running text_only:  69%|██████▊   | 68/99 [17:11<14:20, 27.77s/it]

  NLI     : e=0.001  c=0.001  src=https://www.planetary.org/articles/every-picture-f
  [FC REJECT] off-topic article: https://www.snopes.com/tag/astronomy/
  [FC REJECT] off-topic article: https://www.snopes.com/tag/space/?pagenum=2
  NLI     : e=0.004  c=0.101  src=https://9gag.com/gag/aBymp91
  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/fact-check/royal-family-play-monopoly
  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/fact-check/revocation-of-independence

Running text_only:  70%|██████▉   | 69/99 [17:25<11:45, 23.51s/it]

  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/article/2024/mar/12/princess-kate
  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/news/2020/12/23/what-history-really-t
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2022/feb/21/facebook-p
  [FC SKIP] only 0 matches (need 2): https://fullfact.org/policy/reports/full-fact-report-2021/
  [FC REJECT] off-topic article: https://www.snopes.com/news/2022/09/08/queen-elizabeth-ii-a-
  [FALLBACK] Using embedding similarity
  TEXT ERROR [Andrew will not join royals for Christma]: name 'embedding_stance_fallback' is not defined
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2014/jul/24/rula-jebre
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2024/apr/22/facebook-p
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2026/apr/13/commonweal
  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/news/2026/03/16/vaccine-for-pedophile
  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/fact-check/stevie-wonder-israel-epste
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/article/2015/sep/02/11-examples-h
  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/fact-check/tunnel-between-rafah-egypt

Running text_only:  71%|███████   | 70/99 [17:31<08:50, 18.28s/it]

  NLI     : e=0.002  c=0.001  src=https://www.spacewar.com/reports/Israel_attacks_He
  NLI [FC]: e=0.019  c=0.162  src=https://www.politifact.com/article/2026/apr/02/fac
  NLI [FC]: e=0.005  c=0.930  src=https://www.snopes.com/fact-check/trump-walking-no
  [FC REJECT] off-topic article: https://www.snopes.com/news/2026/04/08/trump-abandon-troops-
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/article/2026/apr/02/fact-checking
  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/news/2023/10/19/israel-warned-al-ahli
  NLI [FC]: e=0.831  c=0.048  src=https://www.snopes.com/fact-check/iran-israeli-f-3
  NLI [FC]: e=0.001  c=0.005  src=https://www.snopes.com/collections/us-israel-war-i

Running text_only:  72%|███████▏  | 71/99 [17:50<08:37, 18.47s/it]

  NLI     : e=0.998  c=0.001  src=https://www.theguardian.com/world/2024/oct/26/idf-
  NLI [FC]: e=0.008  c=0.721  src=https://www.factcheck.org/2023/11/social-media-pos
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2023/feb/28/facebook-p
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2020/12/false-claim-about-bidens-w
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2021/02/factchecking-bidens-town-h
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2020/08/bidens-greatest-hits/
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2020/03/biden-admits-he-was-stoppe
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2020/05/trumps-mysterious-claim-of
  NLI     : e=0.001  c=0.000  src=https://www.npr.org/2024/05/08/1250094064/biden-is
  NLI     : e=0.982  c=0.001  src=https://www.cnn.com/2024/05/08/politics/joe-biden-

Running text_only:  73%|███████▎  | 72/99 [18:03<07:40, 17.07s/it]

  NLI     : e=0.000  c=0.000  src=https://www.pbs.org/newshour/politics/biden-says-u
  NLI     : e=0.000  c=0.001  src=https://www.theguardian.com/us-news/article/2024/m

Running text_only:  74%|███████▎  | 73/99 [18:19<07:11, 16.58s/it]

  NLI     : e=0.000  c=0.000  src=https://www.foxnews.com/world/isis-increasingly-un
  NLI     : e=0.001  c=0.001  src=https://globalecco.org/-/the-afghan-debacle-causes
  NLI     : e=0.001  c=0.034  src=https://en.wikipedia.org/wiki/United_States_interv
  NLI     : e=0.000  c=0.001  src=http://foreignaffairs.house.gov/getting-answers-on
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/list/?page=95&category
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/list/?page=44&speaker=
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2023/apr/18/facebook-p
  NLI     : e=0.000  c=0.000  src=https://www.scientificamerican.com/article/nasa-rs
  NLI     : e=0.000  c=0.000  src=https://www.nasa.gov/centers-and-facilities/jpl/ho

Running text_only:  75%|███████▍  | 74/99 [18:31<06:21, 15.27s/it]

  NLI     : e=0.000  c=0.000  src=https://www.foxnews.com/tech/nasas-martian-helicop
  NLI     : e=0.000  c=0.000  src=https://www.space.com/ingenuity-mars-helicopter-33
  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/2005/12/rnc-web-ad-are-democrats-w
  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/fact-check/vance-trump-hitler-quote/
  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/fact-check/driver-switches-places/
  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/2016/07/trumps-press-conference/
  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/fact-check/make-the-pie-higher/

Running text_only:  76%|███████▌  | 75/99 [18:52<06:44, 16.84s/it]

  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/article/2016/may/10/context-hilla
  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/2017/04/100-days-whoppers/
  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/fact-check/rashida-tlaib-bring-jihad/
  NLI     : e=0.017  c=0.024  src=https://www.theguardian.com/world/2024/nov/05/mma-
  NLI     : e=0.013  c=0.337  src=https://nypost.com/2024/11/25/sports/conor-mcgrego
  NLI     : e=0.014  c=0.005  src=https://www.nytimes.com/athletic/6862186/2025/12/0
  NLI     : e=0.001  c=0.005  src=https://www.cbsnews.com/news/conor-mcgregor-rape-i
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/personalities/democrats/
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/article/2026/apr/06/Trump-Iran-Tr
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/list/?category=&ruling
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/article/2026/jan/29/DHS-governmen
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/article/2025/nov/04/trump-governm
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2025/10/lawmakers-health-care-gove

Running text_only:  77%|███████▋  | 76/99 [19:09<06:30, 16.97s/it]

  NLI [FC]: e=0.000  c=0.995  src=https://www.politifact.com/factchecks/2022/oct/21/
  NLI     : e=0.071  c=0.249  src=https://www.thedailybeast.com/dems-stunningly-flip
  NLI [FC]: e=0.016  c=0.221  src=https://www.politifact.com/factchecks/list/?speake
  NLI [FC]: e=0.005  c=0.540  src=https://www.politifact.com/personalities/senate-ma
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2016/08/trumps-false-obama-isis-li
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/article/2015/dec/11/war-words-fig
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2015/dec/09/greg-abbot
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2017/jun/01/national-r
  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/news/2017/04/22/counterterrorism-isis

Running text_only:  78%|███████▊  | 77/99 [19:24<06:00, 16.38s/it]

  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/fact-check/american-couple-isis-kind/
  [FC REJECT] off-topic article: https://www.politifact.com/article/2015/dec/29/what-citizens
  [FC REJECT] off-topic article: https://www.politifact.com/factchecks/2017/nov/10/michael-mc
  NLI [FC]: e=0.008  c=0.006  src=https://www.politifact.com/factchecks/2015/dec/16/
  NLI     : e=0.001  c=0.000  src=https://www.foxnews.com/us/6-times-isis-has-inspir
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2011/12/the-whoppers-of-2011/
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2012/05/soft-glove-same-gps-fist/
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/article/2025/dec/15/lie-of-the-ye
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2005/10/no-death-penalty-for-hitle
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2018/09/vying-for-veterans-votes-i
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2010/10/court-watch-mudfest-2010/
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2012/04/the-whole-truth-in-wiscons
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2021/01/what-president-biden-inher

Running text_only:  79%|███████▉  | 78/99 [19:39<05:34, 15.93s/it]

  NLI [FC]: e=0.002  c=0.016  src=https://www.politifact.com/factchecks/2025/feb/13/
  [FC REJECT] off-topic article: https://www.snopes.com/fact-check/harding-china-poker/
  NLI     : e=0.985  c=0.003  src=https://www.foxbangor.com/news/national/revealed-t
  NLI     : e=0.015  c=0.651  src=https://www.zdnet.com/article/the-10-most-popular-

Running text_only:  80%|███████▉  | 79/99 [19:52<05:04, 15.24s/it]

  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/fact-check/reopened-scottish-railway-
  [FC SKIP] only 1 matches (need 2): https://fullfact.org/online/miscaptioned-video-child-syria-n
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2014/sep/23/steve-sout
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2017/aug/17/tucker-car
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/article/2026/apr/02/Trump-Fired-P
  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/2025/07/maga-ad-distorts-how-massi
  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/2019/08/the-epstein-connections-fu
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/article/2025/jun/05/elon-musk-don
  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/2018/10/misleading-ads-from-leadin
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/article/2026/may/01/diet-soda-hea
  NLI     : e=0.002  c=0.004  src=https://www.jpost.com/israel-news/defense-news/art
  NLI     : e=0.059  c=0.344  src=https://www.youtube.com/watch?v=kEloSTe9ABg
  NLI     : e=0.059  c=0.344  src=https://www.youtube.com/watch?v=a6ZQ7_p52PQ
  NLI     : e=0.059  c=0.344  src=https://www.youtube.com/watch?v=1AKVZkRzaUQ
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2025/03/viral-posts-share-phony-le

Running text_only:  81%|████████  | 80/99 [20:05<04:33, 14.41s/it]

  NLI [FC]: e=0.002  c=0.024  src=https://www.snopes.com/fact-check/musk-add-pop-sou
  NLI [FC]: e=0.008  c=0.031  src=https://www.snopes.com/fact-check/twitter-like-but
  NLI [FC]: e=0.062  c=0.157  src=https://www.snopes.com/fact-check/elon-musk-rebran
  NLI     : e=0.027  c=0.812  src=https://www.podcastrepublic.net/podcast/1386234384
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2024/jul/12/joe-biden/
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2018/jul/12/donald-tru
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2019/05/trump-17-repeats-in-17-hou
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2018/jul/12/nicholas-b
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2016/apr/19/bernie-san
  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/2020/08/final-night-of-the-republi
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2024/03/factchecking-trumps-fact-c

Running text_only:  82%|████████▏ | 81/99 [20:16<04:03, 13.55s/it]

  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2021/aug/26/joe-biden/
  [FC REJECT] off-topic article: https://www.factcheck.org/2011/03/obama-on-war-then-and-now/
  [FC REJECT] off-topic article: https://www.factcheck.org/2018/08/a-rally-filled-with-repeat
  NLI     : e=0.004  c=0.003  src=https://www.yahoo.com/news/happened-nato-defense-b
  NLI     : e=0.003  c=0.001  src=https://www.nato.int/en/what-we-do/introduction-to

Running text_only:  83%|████████▎ | 82/99 [20:28<03:38, 12.84s/it]

  [FC SKIP] only 0 matches (need 1): https://fullfact.org/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/
  [FC SKIP] only 0 matches (need 1): https://fullfact.org/latest/
  [FC SKIP] only 0 matches (need 1): https://fullfact.org/vaccines/
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/
  [FC SKIP] only 0 matches (need 1): https://fullfact.org/immigration/
  [FC SKIP] only 0 matches (need 1): https://fullfact.org/toolkit/
  [FC SKIP] only 0 matches (need 1): https://fullfact.org/training/
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/top/

Running text_only:  84%|████████▍ | 83/99 [20:57<04:46, 17.88s/it]

  [FC REJECT] off-topic article: https://www.politifact.com/factchecks/2016/dec/28/jeff-brand
  NLI     : e=0.003  c=0.001  src=https://www.mountainpassperformance.com/avoid-brak
  NLI     : e=0.001  c=0.993  src=https://driveteslacanada.ca/model-y/tesla-exonerat
  NLI     : e=0.515  c=0.017  src=https://www.cbc.ca/news/canada/sudbury/failed-road
  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/fact-check/israelis-absent-911/
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2024/apr/30/tweets/pho

Running text_only:  85%|████████▍ | 84/99 [21:07<03:53, 15.55s/it]

  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/article/2024/sep/11/how-kamala-ha
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2013/nov/27/marco-rubi
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/article/2024/may/10/the-antisemit
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/article/2020/aug/24/ask-politifac
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2015/oct/09/ben-carson
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/article/2025/jun/17/us-israel-ira
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2026/mar/02/tweets/Ira
  NLI [FC]: e=0.024  c=0.481  src=https://www.politifact.com/article/2025/oct/13/Tru
  NLI     : e=0.004  c=0.860  src=https://www.canada.ca/en/canadian-heritage/service
  NLI     : e=0.003  c=0.018  src=https://www.youtube.com/shorts/MaGT7YGer-c
  NLI     : e=0.003  c=0.018  src=https://www.youtube.com/shorts/UHQvV7qjObM

Running text_only:  86%|████████▌ | 85/99 [21:20<03:25, 14.70s/it]

  NLI [FC]: e=0.002  c=0.001  src=https://www.politifact.com/factchecks/2019/mar/04/
  NLI     : e=0.193  c=0.010  src=https://apnews.com/article/syria-mass-graves-steph
  NLI     : e=0.003  c=0.000  src=https://www.bbc.co.uk/news/articles/cj90wz8weymo
  NLI     : e=0.001  c=0.000  src=https://en.wikipedia.org/wiki/Mass_graves_in_Syria

Running text_only:  87%|████████▋ | 86/99 [21:32<03:01, 13.96s/it]

  NLI     : e=0.992  c=0.001  src=https://news.meaww.com/joe-bidens-epa-granted-50-m
  NLI     : e=0.996  c=0.001  src=https://www.foxnews.com/politics/biden-epa-granted
  NLI     : e=0.006  c=0.970  src=https://www.theverge.com/news/613135/climate-justi
  NLI     : e=0.004  c=0.046  src=https://wordinblack.com/2025/02/epa-kills-50m-clim
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/list/?category=&ruling
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2026/feb/17/bruce-blak
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2026/feb/13/tom-omara/
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2025/feb/14/elon-musk/
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2016/oct/07/donald-tru
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2022/aug/11/kevin-mcca
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/article/2025/apr/02/elon-musks-mi
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/article/2025/aug/08/trump-new-cen
  NLI     : e=0.000  c=0.001  src=https://sports.yahoo.com/liverpool-ready-unprecede
  NLI     : e=0.000  c=0.001  src=https://www.empireofthekop.com/2025/03/25/liverpoo
  NLI     : e=0.000  c=0.092  src=https://www.sportbible.com/football/football-news/

Running text_only:  88%|████████▊ | 87/99 [21:44<02:40, 13.40s/it]

  NLI     : e=0.001  c=0.000  src=https://www.thesun.co.uk/sport/32568118/trent-alex

Running text_only:  89%|████████▉ | 88/99 [21:58<02:28, 13.54s/it]

  NLI     : e=0.688  c=0.006  src=https://azealia-banks.fandom.com/wiki/Feuds
  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/news/2025/02/21/ukraine-elections-war
  [FC SKIP] only 1 matches (need 2): https://fullfact.org/politics/trump-zelenskyy-dictator-elect
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/article/2025/aug/18/trump-zelensk

Running text_only:  90%|████████▉ | 89/99 [22:20<02:39, 15.98s/it]

  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/collections/ukraine-russia-war-annive
  [FC REJECT] off-topic article: https://www.snopes.com/fact-check/us-trump-trip-world-leader
  NLI [FC]: e=0.000  c=0.000  src=https://www.snopes.com/fact-check/zelenskyy-say-no
  NLI [FC]: e=0.000  c=0.011  src=https://www.politifact.com/article/2025/feb/28/tru
  NLI     : e=0.061  c=0.172  src=https://m.naharnet.com/stories/en/305234-zelensky-

Running text_only:  91%|█████████ | 90/99 [22:35<02:21, 15.73s/it]

  NLI     : e=0.286  c=0.021  src=https://www.washingtonexaminer.com/news/2839164/il
  NLI     : e=0.005  c=0.008  src=https://www.cbsnews.com/newyork/news/nypd-officers
  NLI     : e=0.005  c=0.005  src=https://apnews.com/article/fact-check-nypd-protest
  NLI     : e=0.001  c=0.001  src=https://www.foxnews.com/us/nyc-migrants-arrested-a
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/article/2018/jul/05/fact-checking
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/article/2026/mar/05/Kristi-Noem-m
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2025/feb/26/facebook-p
  NLI     : e=0.992  c=0.001  src=https://thepeoplesvoice.tv/russia-releases-2000-pa
  NLI     : e=0.523  c=0.031  src=https://www.linkedin.com/posts/shivam-shukla-b0484

Running text_only:  92%|█████████▏| 91/99 [22:46<01:55, 14.43s/it]

  NLI     : e=0.039  c=0.062  src=https://www.theguardian.com/world/2020/feb/22/coro
  NLI [FC]: e=0.148  c=0.065  src=https://www.factcheck.org/2024/06/factchecking-tru

Running text_only:  93%|█████████▎| 92/99 [22:58<01:36, 13.74s/it]

  NLI     : e=0.998  c=0.000  src=https://www.foxnews.com/politics/new-york-gov-kath
  NLI [FC]: e=0.001  c=0.000  src=https://www.politifact.com/factchecks/2025/dec/11/
  NLI     : e=0.000  c=0.000  src=https://abc7ny.com/post/gov-kathy-hochul-unveils-p
  NLI     : e=0.998  c=0.000  src=https://www.yahoo.com/news/ny-governor-eyes-change

Building prefix dict from /usr/local/lib/python3.12/dist-packages/jieba/dict.txt ...
DEBUG:jieba:Building prefix dict from /usr/local/lib/python3.12/dist-packages/jieba/dict.txt ...
Dumping model to file cache /tmp/jieba.cache
DEBUG:jieba:Dumping model to file cache /tmp/jieba.cache
Loading model cost 1.766087532043457 seconds.
DEBUG:jieba:Loading model cost 1.766087532043457 seconds.
Prefix dict has been built succesfully.
DEBUG:jieba:Prefix dict has been built succesfully.
Running text_only:  94%|█████████▍| 93/99 [23:06<01:10, 11.83s/it]

  NLI     : e=0.037  c=0.099  src=https://breakgfw.com/202403/74694.html
  NLI     : e=0.110  c=0.325  src=https://www.sinchew.com.my/news/20240426/nation/55
  NLI     : e=0.065  c=0.076  src=https://www.huaglad.com/zh-tw/lovecn/20240327/5504
  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/fact-check/boyfriend-corpses-medical-
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2025/jan/31/facebook-p
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2022/apr/28/facebook-p
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2019/jan/23/facebook-p
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/list/?page=8&category=
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/article/2023/apr/13/state-legisla
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2024/feb/16/instagram-
  NLI [FC]: e=0.001  c=0.000  src=https://www.politifact.com/factchecks/2022/oct/21/
  NLI     : e=0.999  c=0.000  src=https://www.foxnews.com/us/las-vegas-suspect-ex-gi
  NLI     : e=0.002  c=0.001  src=https://gazette.com/2025/01/02/what-matthew-livels

Running text_only:  95%|█████████▍| 94/99 [23:17<00:58, 11.70s/it]

  NLI     : e=0.013  c=0.016  src=https://www.dailymail.co.uk/news/article-14246183/
  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/news/2023/10/19/israel-warned-al-ahli
  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/2023/11/social-media-posts-misrepr
  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/collections/israel-conflicts-rumors-c

Running text_only:  96%|█████████▌| 95/99 [23:27<00:44, 11.09s/it]

  NLI [FC]: e=0.000  c=0.007  src=https://www.snopes.com/news/2025/10/28/hamas-cease
  NLI [FC]: e=0.058  c=0.012  src=https://www.snopes.com/articles/465623/oct-7-hamas
  NLI     : e=0.998  c=0.001  src=https://www.euronews.com/2025/04/25/at-least-50-pa
  NLI [FC]: e=0.000  c=0.003  src=https://www.snopes.com/news/2026/02/11/israel-stri
  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/hot-topics/
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2018/mar/16/viralpolit
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/article/2017/dec/12/2017-lie-year
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2018/02/words-trump-russian-meddli
  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/2018/10/factchecking-trumps-60-min

Running text_only:  97%|█████████▋| 96/99 [23:45<00:39, 13.24s/it]

  NLI [FC]: e=0.026  c=0.271  src=https://www.factcheck.org/2018/07/factchecking-rus
  NLI [FC]: e=0.002  c=0.003  src=https://www.factcheck.org/2017/07/trump-spins-puti
  [FC REJECT] off-topic article: https://www.factcheck.org/location/russia/
  NLI     : e=0.046  c=0.734  src=https://www.ukrainefactcheck.org/source/fact-check

Running text_only:  98%|█████████▊| 97/99 [24:04<00:30, 15.03s/it]

  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/fact-check/michelle-obama-harvey-wein
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2019/apr/03/donald-tru
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/article/2016/jan/22/iowa-gantlet-
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/article/2012/oct/19/fact-checking
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/article/2013/feb/15/government-jo
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2011/jan/31/sameh-shou
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2011/sep/05/barack-oba
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/article/2010/jan/13/announcing-po
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2011/oct/06/critics-wa
  NLI     : e=0.004  c=0.000  src=https://www.desertradio.fm/justin-baldoni-hits-bac
  NLI     : e=0.098  c=0.001  src=https://www.vanityfair.com/hollywood/story/blake-l
  NLI     : e=0.712  c=0.003  src=https://www.nytimes.com/2024/12/26/opinion/blake-l
  NLI     : e=0.003  c=0.001  src=https://www.bbc.com/news/articles/c9q7pxnr4g2o
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2025/aug/07/tiktok-pos
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2014/feb/11/hugh-fitzs
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2021/jun/04/tiktok-pos
  NLI     : e=0.135  c=0.006  src=https://www.foxnews.com/entertainment/michelle-pfe
  NLI     : e=0.003  c=0.010  src=https://www.elle.com/culture/movies-tv/a63196619/t
  NLI     : e=0.699  c=0.005  src=https://variety.com/2024/tv/news/michelle-pfeiffer

Running text_only:  99%|█████████▉| 98/99 [24:11<00:12, 12.64s/it]

  NLI     : e=0.001  c=0.986  src=https://www.yahoo.com/entertainment/tv/articles/ma
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2024/jul/12/threads-po
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/truth-o-meter/promises/trumpomete

Running text_only: 100%|██████████| 99/99 [24:28<00:00, 14.83s/it]

  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/article/2023/may/12/ask-politifac
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2022/apr/28/facebook-p
  NLI     : e=0.497  c=0.025  src=https://www.foxnews.com/entertainment/jay-zs-sexua
  NLI     : e=0.751  c=0.015  src=https://www.tmz.com/2024/12/13/jay-z-diddy-rape-ac
  NLI [FC]: e=0.001  c=0.001  src=https://www.politifact.com/factchecks/2017/may/05/
  NLI [FC]: e=0.028  c=0.367  src=https://www.politifact.com/factchecks/2020/jun/03/

============================================================
MODE: text_only
  mode                 text_only
  n_total              99
  n_valid              99
  n_error              0
  accuracy             0.6465
  precision_macro      0.7225
  recall_macro         0.6435
  f1_macro             0.6107

Prediction distribution:
pred
REAL    79
FAKE    20
Name: count, dtype: int64

              precision    recall  f1-score   support

        FAKE       0.85      0.35      0.49        49
        REAL       0.59      0.94      0.73        50

    accuracy                           0.65        99
   macro avg       0.72      0.64      0.61        99
weighted avg       0.72      0.65      0.61        99


Confusion matrix (rows=true, cols=pred):
      FAKE  REAL
FAKE    17    32
REAL     3    47

Per-class correct/total:
  FAKE         17/49  (35%)
  REAL         47/50  (94%)
  Saved: /content/ablation_v2_text_only.csv

Running text_clip:   0%|          | 0/99 [00:00<?, ?it/s]

  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/fact-check/hamas-wedding-girls/
  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/news/2023/10/13/idf-white-phosphorus-
  [FC SKIP] only 0 matches (need 2): https://fullfact.org/conflict/
  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/fact-check/ai-photo-missiles-tel-aviv
  NLI [FC]: e=0.285  c=0.532  src=https://www.snopes.com/fact-check/photograph-rafah
  NLI [FC]: e=0.199  c=0.056  src=https://fullfact.org/news/iran-missile-drone-attac
  NLI [FC]: e=0.676  c=0.026  src=https://www.snopes.com/fact-check/richard-engel-is
  NLI     : e=0.002  c=0.994  src=https://www.timesofisrael.com/liveblog_entry/idf-i

Running text_clip:   1%|          | 1/99 [00:06<09:58,  6.11s/it]

  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/2012/10/factchecking-the-hofstra-d
  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/2017/05/trump-not-deporting-native

Running text_clip:   2%|▏         | 2/99 [00:11<09:29,  5.88s/it]

  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2025/10/competing-claims-on-who-be
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/article/2025/mar/31/anonymous-x-a
  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/fact-check/close-up-bees-face/
  NLI [FC]: e=0.001  c=0.004  src=https://www.politifact.com/article/2023/oct/23/how
  [FC REJECT] off-topic article: https://www.snopes.com/fact-check/x-post-2023-cole-allen/
  NLI     : e=0.000  c=0.002  src=https://tweetdelete.net/resources/are-twitter-book
  [FC REJECT] off-topic article: https://www.snopes.com/news/2023/11/13/video-palestinian-man
  NLI [FC]: e=0.010  c=0.001  src=https://www.factcheck.org/2025/01/republicans-wron
  NLI [FC]: e=0.864  c=0.005  src=https://www.politifact.com/article/2025/jan/02/how
  NLI [FC]: e=0.013  c=0.047  src=https://www.snopes.com/news/2025/01/02/new-orleans

Running text_clip:   3%|▎         | 3/99 [00:23<13:18,  8.32s/it]

  NLI     : e=0.988  c=0.003  src=https://abc7.com/post/what-know-shamsud-din-jabbar
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2022/jul/26/instagram-
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2023/jul/14/instagram-
  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/fact-check/antarctica-seen-from-space
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2023/apr/25/instagram-
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2022/aug/30/facebook-p
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2022/oct/10/facebook-p
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2022/sep/14/instagram-
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2021/mar/02/facebook-p
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2022/aug/23/facebook-p
  NLI     : e=0.009  c=0.005  src=https://www.outsideonline.com/outdoor-adventure/ex
  NLI     : e=0.009  c=0.319  src=https://www.history.co.uk/articles/reasons-captain
  NLI     : e=0.110  c=0.108  src=https://www.coolantarctica.com/Antarctica%20fact%2

Running text_clip:   4%|▍         | 4/99 [00:29<12:11,  7.70s/it]

  NLI     : e=0.002  c=0.960  src=https://www.quora.com/What-do-the-people-who-belie
  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/fact-check/samira-ibrahim/
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2023/oct/13/instagram-
  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/fact-check/a-farewell-to-arms/
  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/category/photos/?pagenum=81
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2015/jul/16/chain-emai
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/article/2015/jul/22/half-truths-w
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/list/?page=209&speaker
  NLI     : e=0.001  c=0.000  src=https://www.indiatoday.in/fact-check/story/fact-ch

Running text_clip:   5%|▌         | 5/99 [00:37<11:47,  7.53s/it]

  NLI     : e=0.002  c=0.000  src=https://www.reuters.com/fact-check/video-shows-fre
  NLI     : e=0.000  c=0.002  src=https://www.dogrula.org/en/fact-checks/was-the-vid
  NLI     : e=0.001  c=0.000  src=https://www.misbar.com/amp/en/factcheck/2024/06/26

Running text_clip:   6%|▌         | 6/99 [00:39<08:52,  5.72s/it]

  NLI     : e=0.002  c=0.002  src=https://www.boomlive.in/fact-check/factcheck-mosqu
  NLI     : e=0.000  c=0.002  src=https://www.reuters.com/fact-check/video-shows-dem
  NLI     : e=0.001  c=0.004  src=https://africacheck.org/fact-checks/meta-programme
  NLI     : e=0.018  c=0.002  src=https://www.bbc.com/news/world-asia-china-67483202

Running text_clip:   7%|▋         | 7/99 [00:42<07:22,  4.81s/it]

  NLI     : e=0.108  c=0.003  src=https://apnews.com/article/somaliland-presidential
  NLI     : e=0.997  c=0.000  src=https://www.reuters.com/world/africa/somaliland-op
  NLI     : e=0.000  c=0.009  src=https://en.wikipedia.org/wiki/2024_Somaliland_pres
  NLI     : e=0.002  c=0.001  src=https://www.yahoo.com/news/somaliland-opposition-l
  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/notes/why-we-include-humor-and-satire
  NLI     : e=0.010  c=0.040  src=https://apnews.com/article/onion-satire-alex-jones
  NLI     : e=0.001  c=0.004  src=https://www.cnn.com/2026/04/20/media/the-onion-ale
  NLI [FC]: e=0.001  c=0.005  src=https://www.snopes.com/news/2019/08/16/readers-thi
  NLI     : e=0.999  c=0.000  src=https://www.pbs.org/video/the-onion-is-adding-cont

Running text_clip:   9%|▉         | 9/99 [00:49<05:51,  3.91s/it]

  NLI     : e=0.002  c=0.002  src=https://www.threads.com/@based.angxl_/post/DC8W638
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/article/2020/oct/19/fact-checking
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/article/2020/may/22/hunter-biden-
  NLI     : e=0.120  c=0.180  src=https://apnews.com/article/fact-check-dali-ship-ba
  NLI     : e=0.119  c=0.173  src=https://www.usatoday.com/story/news/factcheck/2024
  NLI [FC]: e=0.013  c=0.899  src=https://www.politifact.com/factchecks/2024/mar/27/

Running text_clip:  11%|█         | 11/99 [00:53<04:12,  2.87s/it]

  NLI     : e=0.074  c=0.603  src=https://www.fox8live.com/2024/03/12/angela-chao-sh

Running text_clip:  12%|█▏        | 12/99 [00:54<03:02,  2.10s/it]

  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/fact-check/lost-child-rape-lure/
  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/fact-check/ronald-mcdonald-1892/
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2022/05/tv-ads-about-cheri-beasley
  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/fact-check/
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2019/05/meme-inflates-school-shoot
  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/news/2020/06/24/rayshard-brooks-crimi
  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/fact-check/school-shooters-death-pena
  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/2019/10/the-facts-on-mental-illnes
  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/ap/2018/11/14/authorities-prosecuting
  NLI [FC]: e=0.181  c=0.097  src=https://www.snopes.com/news/2019/09/04/the-psychol

Running text_clip:  13%|█▎        | 13/99 [00:54<02:14,  1.57s/it]

  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2019/06/falsehood-swirls-about-bid
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2018/apr/20/yournewswi
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2020/05/the-falsehoods-of-the-plan
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/article/2019/mar/18/wikileaks-rus
  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/misconceptions/the-origins-of-covi
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/article/2020/apr/17/what-we-know-
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2023/06/video-distorts-early-coron
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/article/2018/aug/02/fact-checking
  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/fact-check/queen-elizabeth-gorilla-bl
  NLI [FC]: e=0.070  c=0.094  src=https://www.snopes.com/fact-check/funvax/
  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/fact-check/goldfinger-actress-death/
  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/news/2022/10/25/reepy-clown-history-h
  NLI     : e=0.000  c=0.000  src=https://www.flavorwire.com/509157/lets-stop-tellin
  NLI     : e=0.001  c=0.003  src=https://kotaku.com/sexism-character-design-and-the
  NLI     : e=0.003  c=0.000  src=https://medium.com/@mirandasalinger/the-villinizat
  NLI     : e=0.000  c=0.000  src=https://www.quora.com/The-guy-I-m-dating-treats-me

Running text_clip:  15%|█▌        | 15/99 [01:03<04:17,  3.07s/it]

  NLI [FC]: e=0.002  c=0.003  src=https://www.snopes.com/fact-check/luigi-beanie-ama
  [FC REJECT] off-topic article: https://www.snopes.com/fact-check/nintendo-free-him-luigi-po
  NLI [FC]: e=0.001  c=0.001  src=https://www.snopes.com/fact-check/uhc-shooter-mug-
  NLI     : e=0.004  c=0.004  src=https://www.nbcnewyork.com/news/local/crime-and-co

Running text_clip:  16%|█▌        | 16/99 [01:03<03:04,  2.23s/it]

  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2020/02/trump-has-condemned-white-
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2018/aug/03/donald-tru
  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/fact-check/war-games/
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2022/03/the-facts-on-de-nazifying-
  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/2017/04/100-days-whoppers/
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/article/2020/sep/10/ad-watch-what
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2015/oct/16/jason-vill
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2018/mar/06/david-simm
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2024/may/14/instagram-
  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/fact-check/trump-very-fine-people/
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/fact-check/using-regular-people/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/2025/03/rfk-jr-s-faulty-advice-on-
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/2021/03/scicheck-video-targets-gat
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/person/peter-mccullough/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2021/sep/16/facebook-p
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/2025/05/rfk-jr-denies-cuts-to-scie
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2024/feb/02/instagram-
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2022/jul/27/instagram-
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2014/jan/26/richard-au
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/tag/usda/
  NLI     : e=0.018  c=0.104  src=https://americancattlemen.com/to-cull-or-not-to-cu
  NLI     : e=0.007  c=0.004  src=https://www.bbc.com/news/articles/c4gzl9d759po
  NLI     : e=0.015  c=0.007  src=https://en.wikipedia.org/wiki/Culling
  NLI     : e=0.006  c=0.020  src=https://www.backyardchickens.com/threads/culling-w

Running text_clip:  17%|█▋        | 17/99 [01:08<03:55,  2.88s/it]

  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2019/12/zelenskys-remarks-about-tr
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2023/03/social-media-posts-misrepr
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/person/volodymyr-zelenskyy/
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2019/11/discrepancy-in-white-house
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/issue/ukraine/
  NLI [FC]: e=0.025  c=0.571  src=https://www.factcheck.org/2025/02/trumps-false-and
  NLI [FC]: e=0.000  c=0.000  src=https://www.politifact.com/article/2025/aug/18/tru

Running text_clip:  18%|█▊        | 18/99 [01:11<04:04,  3.02s/it]

  NLI [FC]: e=0.001  c=0.015  src=https://www.snopes.com/fact-check/zelenskyy-us-ukr
  NLI     : e=0.999  c=0.000  src=https://www.foxnews.com/world/zelenskyy-says-trump
  NLI     : e=0.005  c=0.004  src=https://www.nytimes.com/live/2024/01/30/opinion/th
  NLI     : e=0.015  c=0.004  src=https://www.taxnotes.com/research/federal/legislat
  NLI     : e=0.004  c=0.000  src=https://www.govinfo.gov/content/pkg/CHRG-116hhrg39
  NLI     : e=0.004  c=0.004  src=https://www.theodorerooseveltcenter.org/quotes/pag

Running text_clip:  19%|█▉        | 19/99 [01:13<03:38,  2.73s/it]

  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/fact-check/dec-11-memorial/
  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/2013/01/anti-nra-groups-shameless-
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/article/2016/jul/29/backstory-mus
  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/2017/06/trumps-tweets-twist-facts/

Running text_clip:  20%|██        | 20/99 [01:13<02:41,  2.05s/it]

  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2004/10/media-fund-twists-the-trut
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/article/2015/jul/22/half-truths-w
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/article/2016/oct/08/context-donal
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2018/01/response-iranian-protests-
  [FC REJECT] off-topic article: https://www.politifact.com/factchecks/2014/dec/02/facebook-p
  [FALLBACK] Using embedding similarity
  TEXT ERROR [US to hold national day of mourning for ]: name 'embedding_stance_fallback' is not defined
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2023/10/what-we-know-about-three-w
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/article/2024/may/16/how-unprecede

Running text_clip:  21%|██        | 21/99 [01:19<03:51,  2.97s/it]

  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/collections/israel-hamas-ceasefire/
  [FC REJECT] off-topic article: https://www.politifact.com/factchecks/2023/oct/13/instagram-
  NLI [FC]: e=0.013  c=0.002  src=https://www.politifact.com/article/2026/apr/02/fac
  NLI [FC]: e=0.060  c=0.036  src=https://www.factcheck.org/2026/03/legality-of-late
  NLI     : e=0.535  c=0.025  src=https://www.aa.com.tr/en/middle-east/explosions-he
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2024/mar/01/facebook-p
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/article/2025/nov/06/nancy-pelosi-
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/article/2019/aug/01/donald-trump-
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2018/jun/27/twentyeigh
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2023/aug/31/travis-tri
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/article/2017/jan/27/heres-what-do
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/article/2026/mar/06/Markwayne-Mul
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2014/mar/03/florida-de

Running text_clip:  22%|██▏       | 22/99 [01:27<06:04,  4.74s/it]

  [FC REJECT] off-topic article: https://www.politifact.com/article/2025/jun/06/jeffrey-epste
  [FC REJECT] off-topic article: https://www.politifact.com/factchecks/2023/nov/01/maga-inc/r
  NLI     : e=0.000  c=0.001  src=https://www.foxnews.com/media/carter-feuded-succes
  NLI     : e=0.000  c=0.001  src=https://ground.news/article/carter-feuded-with-suc
  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/news/2018/09/06/many-daily-caller-wri
  NLI     : e=0.032  c=0.008  src=https://www.foxnews.com/us/fox-news-antisemitism-e
  NLI     : e=0.001  c=0.004  src=https://www.foxnews.com/us/fox-news-antisemitism-e
  NLI     : e=0.005  c=0.005  src=https://www.foxnews.com/world/global-rise-antisemi
  NLI     : e=0.003  c=0.015  src=https://www.foxnews.com/world/antisemitism-spiking

Running text_clip:  24%|██▍       | 24/99 [01:37<05:52,  4.70s/it]

  NLI     : e=0.997  c=0.000  src=https://www.reuters.com/markets/deals/us-steel-nip
  [FC REJECT] off-topic article: https://www.snopes.com/tracker/trump-executive-orders-list/
  NLI     : e=0.999  c=0.000  src=https://www.cnn.com/2025/01/06/business/us-steel-b
  NLI     : e=0.999  c=0.000  src=https://www.pbs.org/newshour/politics/biden-reject
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2024/11/both_sides_distort_incompl
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2024/nov/08/instagram-

Running text_clip:  25%|██▌       | 25/99 [01:43<06:15,  5.07s/it]

  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/2008/03/presidents-winning-without
  [FC REJECT] off-topic article: https://www.politifact.com/factchecks/2021/jan/07/donald-tru
  [FC REJECT] off-topic article: https://www.politifact.com/article/2024/nov/22/how-big-was-d
  NLI [FC]: e=0.066  c=0.017  src=https://www.factcheck.org/2024/11/trump-won-the-po
  NLI     : e=0.997  c=0.000  src=https://news.syr.edu/2024/11/06/what-happens-to-th
  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/2010/07/shirley-sherrods-contextua
  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/news/2015/11/23/clock-kid-ahmed-moham
  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/2004/08/republican-funded-group-at
  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/fact-check/still-the-queen/
  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/fact-check/cesar-sayoc-obama-supporti
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/article/2018/jul/05/fact-checking
  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/news/2016/07/11/black-officer-jay-sta
  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/fact-check/the-day-i-met-daniel/
  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/fact-check/spousal-success-story/
  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/fact-check/the-last-of-the-kennedy-dy
  NLI     : e=1.000  c=0.000  src=https://www.voanews.com/a/india-reflects-on-ravi-s
  NLI     : e=0.989  c=0.000  src=https://indiacurrents.com/the-global-ambassador-of
  NLI     : e=0.003  c=0.000  src=https://www.elsewhere.co.nz/world-music/332/ravi-s
  NLI     : e=0.973  c=0.001  src=https://www.bbc.com/news/articles/cwype77kwyjo

Running text_clip:  26%|██▋       | 26/99 [01:47<06:03,  4.98s/it]

  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/fact-check/oregon-ballot-omits-donald
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/fact-check/marine-wedding/
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/fact-check/facebook-rule-photos-tv/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/2010/01/clueless-columbo/
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/fact-check/prayer-request-child-shot-

Running text_clip:  27%|██▋       | 27/99 [01:52<05:59,  4.99s/it]

  [FC REJECT] off-topic article: https://www.snopes.com/fact-check/report-from-a-paramedic/
  [FC REJECT] off-topic article: https://www.snopes.com/fact-check/maryland-billboard-guns-tr
  [FC REJECT] off-topic article: https://www.snopes.com/fact-check/trump-volcanoes-concrete-p
  NLI     : e=0.014  c=0.089  src=https://scottrobinsonhonda.com/video-reels/?wchann
  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/2017/02/trumps-bogus-terrorist-cla
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2015/jun/22/barack-oba
  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/2015/10/gun-laws-deaths-and-crimes

Running text_clip:  28%|██▊       | 28/99 [02:02<07:24,  6.26s/it]

  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/2019/10/the-facts-on-mental-illnes
  NLI     : e=0.983  c=0.003  src=https://www.threads.com/@cnn/post/DAEOXX6KH7r
  [FC REJECT] off-topic article: https://www.politifact.com/embassyattacks/
  NLI     : e=0.007  c=0.237  src=https://apnews.com/live/lebanon-syria-pagers-hezbo
  NLI     : e=0.701  c=0.001  src=https://www.timesofisrael.com/liveblog_entry/leban
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2018/nov/04/blog-posti
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2018/feb/23/philip-lev
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/article/2024/oct/02/vp-debate-fac
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2022/may/16/facebook-p
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2023/aug/10/facebook-p
  NLI     : e=0.968  c=0.008  src=https://www.today.com/news/news/jamie-foxx-injured
  NLI     : e=0.997  c=0.002  src=https://www.tmz.com/2024/12/14/jamie-foxx-fight-mr
  [FC REJECT] off-topic article: https://www.politifact.com/article/2024/sep/27/has-a-venezue
  NLI     : e=0.999  c=0.000  src=https://www.nbclosangeles.com/entertainment/entert

Running text_clip:  30%|███       | 30/99 [02:08<05:15,  4.58s/it]

  NLI     : e=0.088  c=0.460  src=https://t.me/s/MojahdeenMN?after=55418
  NLI     : e=0.217  c=0.208  src=https://t.me/s/auem_yemen/46872
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2025/jul/29/benjamin-n
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/archive-beheaded-babies-israel-ha

Running text_clip:  31%|███▏      | 31/99 [02:09<03:54,  3.44s/it]

  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/fact-check/film-crew-footage-gaza/
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/article/2025/dec/12/genocide-isra
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/article/2024/may/24/the-un-adjust
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/article/2025/dec/15/lie-of-the-ye
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2024/dec/06/instagram-
  NLI [FC]: e=0.002  c=0.005  src=https://www.snopes.com/news/2024/05/02/netanyahu-h
  NLI [FC]: e=0.003  c=0.003  src=https://www.politifact.com/factchecks/2015/mar/22/
  NLI     : e=0.013  c=0.001  src=https://transcripts.cnn.com/show/cnc/date/2024-09-
  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/2019/07/unpacking-bidens-and-trump
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2020/may/28/facebook-p
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2024/dec/30/instagram-
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2022/feb/23/instagram-
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2025/05/trump-allies-spread-unfoun
  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/collections/barron-trump-rumors-colle
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2020/08/covid-19-nasal-swab-test-d
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/issue/government-run-health-care/f
  NLI     : e=0.996  c=0.002  src=https://www.dailystar.co.uk/news/latest-news/new-d
  [FC REJECT] off-topic article: https://www.snopes.com/fact-check/germany-gel-joint-cartilag
  NLI     : e=0.002  c=0.002  src=https://www.bbc.com/news/articles/clyx9nv4mleo
  NLI     : e=0.072  c=0.025  src=https://www.cnn.com/2025/12/19/science/beachy-head

Running text_clip:  33%|███▎      | 33/99 [02:17<04:21,  3.96s/it]

  NLI     : e=0.995  c=0.000  src=https://www.chazakrescue.org/news-updates/mayotte-
  NLI     : e=0.019  c=0.002  src=https://www.pbs.org/newshour/world/mayotte-imposes
  NLI     : e=0.000  c=0.000  src=https://www.bbc.com/news/articles/c89x0j1le4lo
  NLI     : e=0.001  c=0.001  src=https://www.columbian.com/news/2024/dec/17/authori
  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/news/2016/06/19/daily-caller-error-fi
  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/2008/03/wisconsin-judgment-day-the
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/article/2015/sep/22/fact-checking
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/article/2016/dec/13/2016-lie-year
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2024/nov/21/threads-po
  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/2009/02/who-is-linda-panetta/
  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/fact-check/huckabee-sanders-red-hen-p
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/article/2015/jan/22/ernsts-bread-
  NLI     : e=0.007  c=0.001  src=https://www.foxnews.com/media/embarrassingly-wrong
  NLI     : e=0.004  c=0.001  src=https://abc3340.com/news/nation-world/questions-em
  NLI     : e=0.026  c=0.007  src=https://www.yahoo.com/news/gullible-wrong-journali
  NLI     : e=0.001  c=0.000  src=https://www.newyorker.com/news/fault-lines/whos-to

Running text_clip:  34%|███▍      | 34/99 [02:22<04:40,  4.31s/it]

  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/2020/05/baseless-conspiracy-theory
  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/fact-check/derek-mullins-jasmine-cart
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2024/09/posts-misrepresent-police-
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2019/03/social-posts-spin-sanders-
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2024/jul/16/threads-po
  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/person/george-floyd/
  NLI     : e=0.992  c=0.005  src=https://www.12onyourside.com/2024/12/09/key-detail
  NLI [FC]: e=0.010  c=0.932  src=https://www.factcheck.org/2021/04/posts-falsely-id
  NLI [FC]: e=0.005  c=0.027  src=https://www.factcheck.org/2020/05/falsehoods-follo
  NLI     : e=0.997  c=0.001  src=https://6abc.com/15622805/

Running text_clip:  35%|███▌      | 35/99 [02:28<05:07,  4.81s/it]

  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2023/10/what-we-know-about-three-w
  [FC SKIP] only 0 matches (need 2): https://fullfact.org/news/altered-audio-CNN-border-footage-s
  [FC SKIP] only 0 matches (need 2): https://fullfact.org/world/arab-fact-checking-lessons-from-p
  [FC SKIP] only 0 matches (need 2): https://fullfact.org/world/burj-khalifa-ai-iran/
  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/2023/11/online-video-misrepresents
  [FC SKIP] only 0 matches (need 2): https://fullfact.org/online/lebanese-citizens-celebrating-Ha
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/article/2026/mar/11/trump-iran-sc
  [FC REJECT] off-topic article: https://www.snopes.com/fact-check/anti-netanyahu-protest-isr
  NLI [FC]: e=0.021  c=0.023  src=https://www.factcheck.org/2023/12/post-misrepresen
  NLI [FC]: e=0.011  c=0.012  src=https://www.snopes.com/fact-check/crisis-actors-is
  NLI     : e=0.013  c=0.007  src=https://www.bbc.com/news/videos/ce9jeev2grro

Running text_clip:  36%|███▋      | 36/99 [02:34<05:12,  4.96s/it]

  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/fact-check/hegseth-iran-war-christian
  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/news/2025/02/24/congo-70-christians-b
  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/fact-check/pope-leo-xiv-iran-war/
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2015/06/cruz-cherry-picks-terroris
  [FC SKIP] only 1 matches (need 2): https://mail.snopes.com/p/new-post-0c67
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2021/aug/19/facebook-p
  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/fact-check/saved-by-humility/

Running text_clip:  38%|███▊      | 38/99 [02:37<03:07,  3.07s/it]

  NLI     : e=0.000  c=0.001  src=https://www.ewtnnews.com/world/europe/7-catholic-c
  [FC REJECT] off-topic article: https://www.politifact.com/factchecks/2011/feb/07/ron-paul/r
  [FC REJECT] off-topic article: https://www.politifact.com/factchecks/2014/aug/01/georgiacar
  [FC REJECT] off-topic article: https://www.politifact.com/factchecks/2020/feb/29/facebook-p
  [FC SKIP] only 0 matches (need 2): https://staging.politifact.com/article/2019/jan/25/photo-cov
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2008/11/2008-factcheck-awards/
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2008/10/court-fight-in-the-heart-o
  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/collections/epstein-maxwell-clintons-
  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/fact-check/pam-bondi-cross-necklace/
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/article/2016/oct/18/allegations-a
  NLI [FC]: e=0.028  c=0.698  src=https://www.snopes.com/fact-check/woman-jail-weari
  [FC REJECT] off-topic article: https://www.politifact.com/factchecks/2010/oct/22/roy-barnes
  NLI     : e=0.020  c=0.034  src=https://www.yahoo.com/entertainment/celebrity/arti
  NLI     : e=0.016  c=0.419  src=https://www.yahoo.com/entertainment/celebrity/arti

Running text_clip:  39%|███▉      | 39/99 [02:38<02:35,  2.60s/it]

  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/corrections-and-updates/
  [FC SKIP] only 0 matches (need 1): https://fullfact.org/policy/reports/full-fact-report-2024/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/article/2026/feb/18/dietary-prote
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/article/2026/feb/04/washington-DC

Running text_clip:  40%|████      | 40/99 [02:50<05:11,  5.29s/it]

  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/article/2026/mar/23/march-madness
  [FC REJECT] off-topic article: https://www.snopes.com/fact-check/dracula-live-transylvanian
  [FC REJECT] off-topic article: https://www.politifact.com/article/2026/apr/07/choosing-best
  [FC REJECT] off-topic article: https://www.politifact.com/article/2026/mar/06/TrumpRx-presc
  NLI     : e=0.001  c=0.001  src=https://www.bbc.com/news/world-europe-17776565

Running text_clip:  41%|████▏     | 41/99 [02:54<04:47,  4.96s/it]

  NLI     : e=0.070  c=0.000  src=https://apnews.com/article/koala-chlamydia-vaccina
  NLI     : e=0.001  c=0.000  src=https://www.bbc.com/news/articles/cjdnkdg1l8do
  NLI     : e=0.004  c=0.000  src=https://www.reuters.com/business/healthcare-pharma
  NLI     : e=0.159  c=0.000  src=https://www.euronews.com/2025/09/12/new-vaccine-ai

Running text_clip:  42%|████▏     | 42/99 [02:54<03:24,  3.59s/it]

  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2013/08/the-messy-facts-in-virgini
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2019/aug/09/pete-butti
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2025/jul/11/jon-favrea
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2021/mar/02/donald-tru
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/article/2025/jun/06/jeffrey-epste
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2013/jul/03/debbie-was
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/article/2022/jun/09/political-ext
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2014/dec/03/jeb-bush/t
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2025/jul/18/donald-tru
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/article/2022/jan/28/what-you-need
  NLI     : e=0.001  c=0.002  src=http://archive.is/duYni
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2020/jan/15/facebook-p
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/article/2018/feb/26/dunkirk-fact-
  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/2024/08/misleading-democratic-ad-i
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2024/sep/26/sam-brown/

Running text_clip:  43%|████▎     | 43/99 [03:01<04:15,  4.57s/it]

  [FC REJECT] off-topic article: https://www.politifact.com/factchecks/2025/mar/26/pete-hegse
  [FC REJECT] off-topic article: https://www.snopes.com/fact-check/chris-evans-signing-bomb/
  NLI     : e=0.009  c=0.009  src=https://www.yahoo.com/entertainment/chris-evans-cl
  NLI     : e=0.000  c=0.995  src=https://okmagazine.com/p/captain-america-chris-eva

Running text_clip:  44%|████▍     | 44/99 [03:07<04:36,  5.02s/it]

  NLI     : e=0.025  c=0.715  src=https://en.wikipedia.org/wiki/Pear_of_anguish
  NLI     : e=0.070  c=0.024  src=https://medievaltorturemuseum.com/blog/pear-anguis
  NLI     : e=0.035  c=0.007  src=https://allthatsinteresting.com/pear-of-anguish
  NLI     : e=0.043  c=0.008  src=https://medievalbritain.com/type/medieval-life/tor
  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/news/2016/04/10/spring-break-nightmar
  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/fact-check/man-stuck-2055-france/
  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/2010/09/bos-private-plane/
  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/news/2026/02/25/kash-patel-olympic-ho
  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/category/viral-phenomena/?pagenum=18
  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/fact-check/yusra-mardini-flee-syria-s
  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/fact-check/racist-carnival-game/

Running text_clip:  45%|████▌     | 45/99 [03:14<05:02,  5.61s/it]

  NLI     : e=0.041  c=0.002  src=https://www.foxnews.com/travel/man-vacation-goes-v
  NLI     : e=0.028  c=0.001  src=https://nypost.com/2024/12/31/lifestyle/man-on-vac
  NLI [FC]: e=0.010  c=0.239  src=https://www.snopes.com/news/2021/06/21/mama-bear-g
  NLI [FC]: e=0.017  c=0.443  src=https://www.snopes.com/fact-check/kentucky-snow-fl

Running text_clip:  46%|████▋     | 46/99 [03:16<03:53,  4.41s/it]

  NLI [FC]: e=0.001  c=0.016  src=https://www.politifact.com/factchecks/2024/jul/03/
  NLI     : e=0.001  c=0.000  src=https://forums.dukebasketballreport.com/index.php?
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2025/jul/09/scott-jenn
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/article/2022/sep/29/united-facts-
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/article/2026/jan/03/trump-maduro-
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/article/2016/apr/06/we-fact-check
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/article/2026/feb/25/democrats-sta
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/article/2025/nov/03/trump-60-minu
  NLI     : e=0.884  c=0.013  src=https://www.foxnews.com/video/6365955471112
  NLI     : e=1.000  c=0.000  src=https://www.mediaite.com/media/tv/dont-touch-me-sc
  NLI     : e=0.996  c=0.001  src=https://www.foxnews.com/media/scott-jennings-bakar
  NLI     : e=0.999  c=0.000  src=https://nypost.com/2024/12/14/media/cnn-contributo

Running text_clip:  47%|████▋     | 47/99 [03:21<03:58,  4.59s/it]

  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/article/2017/may/02/whats-up-with
  NLI [FC]: e=0.000  c=0.001  src=https://www.snopes.com/fact-check/trump-veterans-d
  NLI [FC]: e=0.011  c=0.047  src=https://www.snopes.com/fact-check/donald-tump-ffa-
  NLI     : e=0.002  c=0.050  src=https://www.foxnews.com/opinion/how-trump-survives

Running text_clip:  48%|████▊     | 48/99 [03:25<03:50,  4.51s/it]

  NLI     : e=0.000  c=0.000  src=https://abc17news.com/politics/2026/04/26/trump-fi

Running text_clip:  49%|████▉     | 49/99 [03:32<04:19,  5.19s/it]

  NLI     : e=0.017  c=0.001  src=https://www.foxnews.com/media/psychologist-jonatha
  NLI     : e=0.000  c=0.000  src=https://cyberbullying.org/student-phones-school-ba
  NLI     : e=0.001  c=0.017  src=https://www.applerouth.com/blog/parents-phones-and
  NLI     : e=0.000  c=0.000  src=https://ground.news/article/how-jonathan-haidt-won
  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/fact-check/texas-ice-raid-birthday-pa
  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/fact-check/tiger-houston-neighborhood
  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/fact-check/texas-alien-anal-probe/
  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/fact-check/carl-twinly-cow-arrest/
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2010/nov/11/greg-abbot
  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/fact-check/karmelo-anthony-donations-
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2015/jul/30/harry-houc
  NLI     : e=0.000  c=0.000  src=https://fastguardservice.com/texas-police-arrest-9
  NLI     : e=0.000  c=0.000  src=https://www.foxnews.com/video/6365971915112
  NLI     : e=0.964  c=0.001  src=https://www.foxnews.com/us/texas-police-arrest-9-s

Running text_clip:  51%|█████     | 50/99 [03:37<04:11,  5.13s/it]

  NLI     : e=0.164  c=0.001  src=https://www.fox7austin.com/news/lakeline-mall-shop
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2022/dec/16/instagram-
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/article/2022/mar/15/zuckerbucks-2
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2024/dec/13/facebook-p
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2018/dec/04/blog-posti
  NLI     : e=0.120  c=0.001  src=https://www.realtor.com/news/reality-tv/christina-
  NLI     : e=0.996  c=0.002  src=https://www.wwbl.com/2025/01/07/hgtv-star-christin
  NLI     : e=0.997  c=0.000  src=https://www.foxnews.com/entertainment/hgtv-star-ch
  NLI     : e=0.998  c=0.001  src=https://www.cosmopolitan.com/entertainment/celebs/

Running text_clip:  52%|█████▏    | 51/99 [03:43<04:17,  5.36s/it]

  [FC SKIP] only 0 matches (need 2): https://fullfact.org/policy/reports/full-fact-report-2024/
  [FC SKIP] only 0 matches (need 2): https://fullfact.org/policy/reports/full-fact-report-2025/
  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/author/snopes/?pagenum=45
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2018/dec/20/blog-posti
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2018/aug/07/greg-abbot
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2015/jul/20/rick-perry
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2019/jul/02/kamala-har
  [FC REJECT] off-topic article: https://www.politifact.com/factchecks/2017/nov/10/michael-mc
  NLI     : e=0.099  c=0.439  src=https://www.express.co.uk/news/uk/1979993/westmins
  NLI     : e=0.006  c=0.860  src=https://uk.news.yahoo.com/westmister-bridge-150736
  NLI     : e=0.000  c=0.994  src=https://www.bbc.com/news/articles/c5y3en5yv21o

Running text_clip:  53%|█████▎    | 52/99 [03:52<04:59,  6.38s/it]

  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/fact-check/log-pile-missing/
  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/fact-check/eric-langford-missing-boy-
  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/fact-check/missing-alaska-hikers-stor
  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/news/2026/04/28/scientists-dead-missi
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/article/2025/aug/25/kilmar-abrego
  NLI     : e=0.028  c=0.031  src=https://www.aol.com/articles/hiker-stumbles-human-
  NLI     : e=0.995  c=0.003  src=https://abc7.com/post/severely-decomposed-human-re
  NLI     : e=0.999  c=0.000  src=https://www.foxnews.com/us/police-investigating-af
  NLI [FC]: e=0.021  c=0.376  src=https://www.politifact.com/factchecks/2023/aug/22/

Running text_clip:  54%|█████▎    | 53/99 [03:58<04:56,  6.45s/it]

  NLI     : e=0.027  c=0.023  src=https://issuu.com/outlawpartners/docs/explore_big_
  NLI     : e=0.002  c=0.001  src=https://www.youtube.com/shorts/sSCIeF_wUE8
  NLI     : e=0.223  c=0.128  src=https://www.youtube.com/watch?v=dOrawfTwJPY
  NLI     : e=0.223  c=0.128  src=https://www.youtube.com/watch?v=UHdfT8TbR4c

Running text_clip:  56%|█████▌    | 55/99 [04:13<05:16,  7.18s/it]

  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/fact-check/isis-crisis-2/
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/fake-news/page/16/
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2019/mar/04/blog-posti
  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/fact-check/american-three-terrorist-a
  [FC REJECT] off-topic article: https://www.politifact.com/article/2023/nov/21/israel-hamas-
  NLI [FC]: e=0.034  c=0.024  src=https://www.factcheck.org/2023/11/dozens-of-childr
  [FC REJECT] off-topic article: https://www.factcheck.org/2023/10/what-we-know-about-three-w
  NLI     : e=0.488  c=0.011  src=https://www.aa.com.tr/en/middle-east/children-amon
  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/fact-check/pfizer-covid-vaccine-adver
  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/fact-check/call-police-new-guinea-fla
  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/fact-check/dangers-dihydrogen-monoxid
  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/fact-check/mayo-clinic/
  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/fact-check/hair-grooming-syncope/
  NLI     : e=0.003  c=0.001  src=https://www.yahoo.com/news/articles/trump-post-him
  NLI     : e=0.000  c=0.000  src=https://www.bbc.com/news/videos/c624dy3pgg2o
  NLI     : e=0.004  c=0.185  src=https://www.bbc.com/news/articles/c17v8y0z9z2o
  NLI     : e=0.000  c=0.005  src=https://www.courthousenews.com/i-thought-it-was-me

Running text_clip:  57%|█████▋    | 56/99 [04:14<03:51,  5.38s/it]

  [FC SKIP] only 1 matches (need 2): https://www.merriam-webster.com/dictionary/could
  [FC SKIP] only 1 matches (need 2): https://dictionary.cambridge.org/us/dictionary/english/could
  [FC SKIP] only 1 matches (need 2): https://en.wiktionary.org/wiki/could
  [FC SKIP] only 1 matches (need 2): https://www.grammarly.com/blog/commonly-confused-words/can-v
  [FC SKIP] only 1 matches (need 2): https://www.dictionary.com/browse/could
  [FC SKIP] only 1 matches (need 2): https://www.youtube.com/watch?v=OiYmamqv7H0
  [FC SKIP] only 1 matches (need 2): https://www.collinsdictionary.com/us/dictionary/english/coul
  [FC SKIP] only 1 matches (need 2): https://www.youtube.com/watch?v=z_PyX-NAKEI
  NLI     : e=0.993  c=0.001  src=https://www.space.com/astronomy/mars/artificial-su
  NLI     : e=0.995  c=0.000  src=https://spacenews.com/will-ai-redefine-human-roles

Running text_clip:  58%|█████▊    | 57/99 [04:19<03:31,  5.03s/it]

  NLI     : e=0.003  c=0.002  src=https://www.quora.com/How-can-AI-driven-robots-and
  NLI     : e=0.001  c=0.000  src=https://www.bbc.com/news/articles/cy7keddnj31o

Running text_clip:  59%|█████▊    | 58/99 [04:23<03:14,  4.74s/it]

  NLI [FC]: e=0.079  c=0.028  src=https://checkyourfact.com/2024/06/18/fact-check-ke
  NLI [FC]: e=0.012  c=0.001  src=https://www.snopes.com/fact-check/keanu-reeves-who
  NLI     : e=0.020  c=0.026  src=https://news.meaww.com/fact-check-did-keanu-reeves
  NLI     : e=0.981  c=0.003  src=https://visegrad25.quora.com/BREAKING-Keanu-Reeves

Running text_clip:  60%|█████▉    | 59/99 [04:26<02:58,  4.46s/it]

  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/2016/02/factchecking-the-eighth-go
  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/2006/10/accusations-without-eviden
  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/2025/11/sorting-out-the-facts-on-e
  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/2005/08/here-we-go-again-distorted
  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/2022/11/conservative-figures-sprea
  [FC SKIP] only 1 matches (need 2): https://mail.snopes.com/p/shackled-bodies-in-spain-health-ca
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2014/may/05/laura-ingr
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2013/jan/18/facebook-p
  [FC REJECT] off-topic article: https://www.factcheck.org/2023/10/what-we-know-about-three-w
  NLI     : e=0.004  c=0.565  src=https://www.reuters.com/fact-check/photos-show-202
  NLI     : e=0.837  c=0.002  src=https://www.wionews.com/world/iran-prez-ebrahim-ra
  NLI     : e=0.000  c=0.007  src=https://www.timesofisrael.com/liveblog_entry/iran-

Running text_clip:  61%|██████    | 60/99 [04:27<02:02,  3.15s/it]

  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/fact-check/jfk-palestine-britain/
  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/news/2018/06/13/lawsuit-brexit-backer
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2015/mar/03/bill-oreil
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2010/jan/22/charles-sc
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2014/jul/17/facebook-p
  [FC REJECT] off-topic article: https://www.factcheck.org/2008/10/life-cycle-of-a-rumor/
  NLI     : e=0.006  c=0.030  src=https://apnews.com/article/elon-musk-britain-riots
  NLI     : e=0.000  c=0.021  src=https://foxbaltimore.com/station/share/musk-slams-
  NLI     : e=0.000  c=0.021  src=https://katv.com/news/nation-world/musk-slams-uk-a

Running text_clip:  62%|██████▏   | 61/99 [04:30<02:03,  3.25s/it]

  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2026/03/how-iran-blocking-the-stra
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/article/2026/feb/27/iran-economic
  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/2016/04/trumps-foreign-policy-spee
  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/2016/05/rep-jones-didnt-empower-ob
  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/2016/06/trump-wrong-on-iraqi-oil/
  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/fact-check/netanyahu-gaza-2035-plan/
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/article/2026/apr/06/strait-hormuz
  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/2026/03/trump-links-bidens-ukraine
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/article/2023/oct/09/fact-check-tr
  NLI     : e=0.086  c=0.739  src=https://www.theguardian.com/world/live/2024/oct/29
  NLI     : e=0.042  c=0.016  src=https://www.aa.com.tr/en/middle-east/us-deeply-con
  NLI     : e=0.007  c=0.039  src=https://truthout.org/articles/israel-used-us-bomb-
  NLI [FC]: e=0.006  c=0.044  src=https://www.snopes.com/fact-check/trumps-us-gaza-a

Running text_clip:  63%|██████▎   | 62/99 [04:40<03:18,  5.37s/it]

  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/news/2025/10/28/hamas-ceasefire-viola
  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/news/2021/05/25/tom-cotton-associated
  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/newsletter-archive/snopes-digest-116-
  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/fact-check/gaza-strip-photo/
  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/news/2025/08/11/al-jazeera-anas-al-sh
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2023/11/post-makes-unfounded-claim

Running text_clip:  64%|██████▎   | 63/99 [04:42<02:38,  4.40s/it]

  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/fact-check/turkey-warship-gaza/
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2014/sep/18/julie-pace
  [FC REJECT] off-topic article: https://www.snopes.com/fact-check/clinton-netanyahu-satire-v
  [FC REJECT] off-topic article: https://www.snopes.com/news/2023/10/16/china-hamas-israel-ga
  NLI     : e=0.999  c=0.000  src=https://www.foxnews.com/world/israeli-airstrikes-c
  NLI     : e=0.053  c=0.001  src=https://www.longwarjournal.org/archives/2024/11/is

Running text_clip:  65%|██████▍   | 64/99 [04:50<03:03,  5.24s/it]

  NLI     : e=0.005  c=0.030  src=https://www.foxnews.com/us/new-orleans-barricade-o
  NLI     : e=0.002  c=0.001  src=https://www.foxnews.com/us/new-orleans-revelers-na
  NLI     : e=0.037  c=0.007  src=https://apnews.com/article/new-orleans-car-bourbon
  NLI     : e=0.002  c=0.001  src=https://www.pbs.org/newshour/politics/watch-live-f
  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/2026/04/trumps-numbers-april-2026-
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/article/2024/dec/26/a-month-by-mo
  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/location/international/
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2026/02/trump-oversells-recent-u-s
  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/
  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/2026/02/manufacturing-construction
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2025/05/democrats-exaggerate-estim
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/article/2026/jan/20/trump-inflati
  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/2026/02/a-pre-sotu-guide-to-trumps
  NLI     : e=0.007  c=0.002  src=https://www.foxnews.com/world/israel-warns-go-afte
  NLI     : e=0.006  c=0.009  src=https://www.yahoo.com/news/where-ceasefire-talks-b
  NLI     : e=0.002  c=0.000  src=https://www.ntd.com/ntdplus/israel-hezbollah-agree
  [FC REJECT] off-topic article: https://www.politifact.com/

Running text_clip:  66%|██████▌   | 65/99 [04:54<02:46,  4.91s/it]

  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2025/jan/15/instagram-
  NLI     : e=0.000  c=0.000  src=https://beartrackinn.com/frequently-asked-question
  NLI     : e=0.003  c=0.001  src=https://fullsuitcase.com/kids-pack-plane/
  NLI     : e=0.061  c=0.510  src=https://www.remitly.com/blog/travel/chicago-o-hare

Running text_clip:  67%|██████▋   | 66/99 [06:25<16:51, 30.65s/it]

  NLI     : e=0.027  c=0.024  src=http://www.ketchikanmuseums.org/virtual_exhibit/ve
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2012/12/firefighters-fact-checking
  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/2015/07/clinton-spins-immigration-
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2015/11/bogus-meme-targets-trump/
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2019/04/what-kissinger-has-said-ab
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2008/10/lying-about-being-liberal/
  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/2016/07/factchecking-clintons-big-
  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/2020/02/trump-has-condemned-white-
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2012/07/you-didnt-build-that-uncut
  NLI [FC]: e=0.140  c=0.033  src=https://www.factcheck.org/2009/04/here-there-be-pi

Running text_clip:  68%|██████▊   | 67/99 [06:32<12:37, 23.66s/it]

  NLI [FC]: e=0.025  c=0.012  src=https://www.factcheck.org/2012/08/factcheck-mailba
  NLI     : e=0.022  c=0.024  src=https://prospect.org/2024/03/20/2024-03-20-what-re
  NLI     : e=0.002  c=0.039  src=https://www.nytimes.com/2023/12/04/podcasts/the-da

Running text_clip:  69%|██████▊   | 68/99 [06:33<08:40, 16.78s/it]

  NLI     : e=0.001  c=0.001  src=https://www.planetary.org/articles/every-picture-f
  [FC REJECT] off-topic article: https://www.snopes.com/tag/astronomy/
  [FC REJECT] off-topic article: https://www.snopes.com/tag/space/?pagenum=2
  NLI     : e=0.004  c=0.101  src=https://9gag.com/gag/aBymp91
  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/fact-check/royal-family-play-monopoly
  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/fact-check/revocation-of-independence

Running text_clip:  70%|██████▉   | 69/99 [06:33<05:55, 11.84s/it]

  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/article/2024/mar/12/princess-kate
  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/news/2020/12/23/what-history-really-t
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2022/feb/21/facebook-p
  [FC SKIP] only 0 matches (need 2): https://fullfact.org/policy/reports/full-fact-report-2021/
  [FC REJECT] off-topic article: https://www.snopes.com/news/2022/09/08/queen-elizabeth-ii-a-
  [FALLBACK] Using embedding similarity
  TEXT ERROR [Andrew will not join royals for Christma]: name 'embedding_stance_fallback' is not defined
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2014/jul/24/rula-jebre
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2024/apr/22/facebook-p
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2026/apr/13/commonweal
  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/news/2026/03/16/vaccine-for-pedophile
  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/fact-check/stevie-wonder-israel-epste
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/article/2015/sep/02/11-examples-h
  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/fact-check/tunnel-between-rafah-egypt

Running text_clip:  71%|███████   | 70/99 [06:34<04:12,  8.71s/it]

  NLI     : e=0.002  c=0.001  src=https://www.spacewar.com/reports/Israel_attacks_He
  NLI [FC]: e=0.019  c=0.162  src=https://www.politifact.com/article/2026/apr/02/fac
  NLI [FC]: e=0.005  c=0.930  src=https://www.snopes.com/fact-check/trump-walking-no
  [FC REJECT] off-topic article: https://www.snopes.com/news/2026/04/08/trump-abandon-troops-
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/article/2026/apr/02/fact-checking
  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/news/2023/10/19/israel-warned-al-ahli
  NLI [FC]: e=0.831  c=0.048  src=https://www.snopes.com/fact-check/iran-israeli-f-3
  NLI [FC]: e=0.001  c=0.005  src=https://www.snopes.com/collections/us-israel-war-i
  NLI     : e=0.998  c=0.001  src=https://www.theguardian.com/world/2024/oct/26/idf-
  NLI [FC]: e=0.008  c=0.721  src=https://www.factcheck.org/2023/11/social-media-pos

Running text_clip:  72%|███████▏  | 71/99 [06:45<04:16,  9.17s/it]

  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2023/feb/28/facebook-p
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2020/12/false-claim-about-bidens-w
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2021/02/factchecking-bidens-town-h
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2020/08/bidens-greatest-hits/
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2020/03/biden-admits-he-was-stoppe
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2020/05/trumps-mysterious-claim-of
  NLI     : e=0.001  c=0.000  src=https://www.npr.org/2024/05/08/1250094064/biden-is

Running text_clip:  73%|███████▎  | 72/99 [06:50<03:37,  8.05s/it]

  NLI     : e=0.982  c=0.001  src=https://www.cnn.com/2024/05/08/politics/joe-biden-
  NLI     : e=0.000  c=0.000  src=https://www.pbs.org/newshour/politics/biden-says-u
  NLI     : e=0.000  c=0.001  src=https://www.theguardian.com/us-news/article/2024/m

Running text_clip:  74%|███████▎  | 73/99 [06:56<03:16,  7.56s/it]

  NLI     : e=0.000  c=0.000  src=https://www.foxnews.com/world/isis-increasingly-un
  NLI     : e=0.001  c=0.001  src=https://globalecco.org/-/the-afghan-debacle-causes
  NLI     : e=0.001  c=0.034  src=https://en.wikipedia.org/wiki/United_States_interv
  NLI     : e=0.000  c=0.001  src=http://foreignaffairs.house.gov/getting-answers-on
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/list/?page=95&category
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/list/?page=44&speaker=
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2023/apr/18/facebook-p
  NLI     : e=0.000  c=0.000  src=https://www.scientificamerican.com/article/nasa-rs
  NLI     : e=0.000  c=0.000  src=https://www.nasa.gov/centers-and-facilities/jpl/ho
  NLI     : e=0.000  c=0.000  src=https://www.foxnews.com/tech/nasas-martian-helicop

Running text_clip:  75%|███████▍  | 74/99 [06:59<02:33,  6.16s/it]

  NLI     : e=0.000  c=0.000  src=https://www.space.com/ingenuity-mars-helicopter-33
  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/2005/12/rnc-web-ad-are-democrats-w
  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/fact-check/vance-trump-hitler-quote/
  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/fact-check/driver-switches-places/
  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/2016/07/trumps-press-conference/
  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/fact-check/make-the-pie-higher/
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/article/2016/may/10/context-hilla
  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/2017/04/100-days-whoppers/
  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/fact-check/rashida-tlaib-bring-jihad/
  NLI     : e=0.017  c=0.024  src=https://www.theguardian.com/world/2024/nov/05/mma-
  NLI     : e=0.013  c=0.337  src=https://nypost.com/2024/11/25/sports/conor-mcgrego
  NLI     : e=0.014  c=0.005  src=https://www.nytimes.com/athletic/6862186/2025/12/0

Running text_clip:  76%|███████▌  | 75/99 [07:03<02:09,  5.41s/it]

  NLI     : e=0.001  c=0.005  src=https://www.cbsnews.com/news/conor-mcgregor-rape-i
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/personalities/democrats/
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/article/2026/apr/06/Trump-Iran-Tr
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/list/?category=&ruling
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/article/2026/jan/29/DHS-governmen
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/article/2025/nov/04/trump-governm
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2025/10/lawmakers-health-care-gove

Running text_clip:  77%|███████▋  | 76/99 [07:08<02:03,  5.38s/it]

  NLI [FC]: e=0.000  c=0.995  src=https://www.politifact.com/factchecks/2022/oct/21/
  NLI     : e=0.071  c=0.249  src=https://www.thedailybeast.com/dems-stunningly-flip
  NLI [FC]: e=0.016  c=0.221  src=https://www.politifact.com/factchecks/list/?speake
  NLI [FC]: e=0.005  c=0.540  src=https://www.politifact.com/personalities/senate-ma
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2016/08/trumps-false-obama-isis-li
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/article/2015/dec/11/war-words-fig
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2015/dec/09/greg-abbot
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2017/jun/01/national-r
  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/news/2017/04/22/counterterrorism-isis

Running text_clip:  78%|███████▊  | 77/99 [07:14<02:01,  5.52s/it]

  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/fact-check/american-couple-isis-kind/
  [FC REJECT] off-topic article: https://www.politifact.com/article/2015/dec/29/what-citizens
  [FC REJECT] off-topic article: https://www.politifact.com/factchecks/2017/nov/10/michael-mc
  NLI [FC]: e=0.008  c=0.006  src=https://www.politifact.com/factchecks/2015/dec/16/
  NLI     : e=0.001  c=0.000  src=https://www.foxnews.com/us/6-times-isis-has-inspir
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2011/12/the-whoppers-of-2011/
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2012/05/soft-glove-same-gps-fist/
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/article/2025/dec/15/lie-of-the-ye
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2005/10/no-death-penalty-for-hitle
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2018/09/vying-for-veterans-votes-i
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2010/10/court-watch-mudfest-2010/
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2012/04/the-whole-truth-in-wiscons
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2021/01/what-president-biden-inher

Running text_clip:  79%|███████▉  | 78/99 [07:22<02:13,  6.35s/it]

  NLI [FC]: e=0.002  c=0.016  src=https://www.politifact.com/factchecks/2025/feb/13/
  [FC REJECT] off-topic article: https://www.snopes.com/fact-check/harding-china-poker/
  NLI     : e=0.985  c=0.003  src=https://www.foxbangor.com/news/national/revealed-t
  NLI     : e=0.015  c=0.651  src=https://www.zdnet.com/article/the-10-most-popular-
  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/fact-check/reopened-scottish-railway-
  [FC SKIP] only 1 matches (need 2): https://fullfact.org/online/miscaptioned-video-child-syria-n
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2014/sep/23/steve-sout
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2017/aug/17/tucker-car
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/article/2026/apr/02/Trump-Fired-P
  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/2025/07/maga-ad-distorts-how-massi
  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/2019/08/the-epstein-connections-fu
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/article/2025/jun/05/elon-musk-don
  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/2018/10/misleading-ads-from-leadin
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/article/2026/may/01/diet-soda-hea
  NLI     : e=0.002  c=0.004  src=https://www.jpost.com/israel-news/defense-news/art
  NLI     : e=0.059  c=0.344  src=https://www.youtube.com/watch?v=kEloSTe9ABg
  NLI     : e=0.059  c=0.344  src=https://www.youtube.com/watch?v=a6ZQ7_p52PQ

Running text_clip:  80%|███████▉  | 79/99 [07:29<02:10,  6.55s/it]

  NLI     : e=0.059  c=0.344  src=https://www.youtube.com/watch?v=1AKVZkRzaUQ
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2025/03/viral-posts-share-phony-le

Running text_clip:  81%|████████  | 80/99 [07:36<02:03,  6.51s/it]

  NLI [FC]: e=0.002  c=0.024  src=https://www.snopes.com/fact-check/musk-add-pop-sou
  NLI [FC]: e=0.008  c=0.031  src=https://www.snopes.com/fact-check/twitter-like-but
  NLI [FC]: e=0.062  c=0.157  src=https://www.snopes.com/fact-check/elon-musk-rebran
  NLI     : e=0.027  c=0.812  src=https://www.podcastrepublic.net/podcast/1386234384
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2024/jul/12/joe-biden/
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2018/jul/12/donald-tru
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2019/05/trump-17-repeats-in-17-hou
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2018/jul/12/nicholas-b
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2016/apr/19/bernie-san
  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/2020/08/final-night-of-the-republi
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2024/03/factchecking-trumps-fact-c

Running text_clip:  82%|████████▏ | 81/99 [07:40<01:42,  5.71s/it]

  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2021/aug/26/joe-biden/
  [FC REJECT] off-topic article: https://www.factcheck.org/2011/03/obama-on-war-then-and-now/
  [FC REJECT] off-topic article: https://www.factcheck.org/2018/08/a-rally-filled-with-repeat
  NLI     : e=0.004  c=0.003  src=https://www.yahoo.com/news/happened-nato-defense-b
  NLI     : e=0.003  c=0.001  src=https://www.nato.int/en/what-we-do/introduction-to

Running text_clip:  83%|████████▎ | 82/99 [07:40<01:08,  4.06s/it]

  [FC SKIP] only 0 matches (need 1): https://fullfact.org/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/
  [FC SKIP] only 0 matches (need 1): https://fullfact.org/latest/
  [FC SKIP] only 0 matches (need 1): https://fullfact.org/vaccines/
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/
  [FC SKIP] only 0 matches (need 1): https://fullfact.org/immigration/
  [FC SKIP] only 0 matches (need 1): https://fullfact.org/toolkit/
  [FC SKIP] only 0 matches (need 1): https://fullfact.org/training/
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/top/

Running text_clip:  84%|████████▍ | 83/99 [07:49<01:28,  5.51s/it]

  [FC REJECT] off-topic article: https://www.politifact.com/factchecks/2016/dec/28/jeff-brand
  NLI     : e=0.003  c=0.001  src=https://www.mountainpassperformance.com/avoid-brak
  NLI     : e=0.001  c=0.993  src=https://driveteslacanada.ca/model-y/tesla-exonerat
  NLI     : e=0.515  c=0.017  src=https://www.cbc.ca/news/canada/sudbury/failed-road
  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/fact-check/israelis-absent-911/
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2024/apr/30/tweets/pho
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/article/2024/sep/11/how-kamala-ha
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2013/nov/27/marco-rubi
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/article/2024/may/10/the-antisemit
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/article/2020/aug/24/ask-politifac
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2015/oct/09/ben-carson
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/article/2025/jun/17/us-israel-ira
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2026/mar/02/tweets/Ira
  NLI [FC]: e=0.024  c=0.481  src=https://www.politifact.com/article/2025/oct/13/Tru
  NLI     : e=0.004  c=0.860  src=https://www.canada.ca/en/canadian-heritage/service
  NLI     : e=0.003  c=0.018  src=https://www.youtube.com/shorts/MaGT7YGer-c

Running text_clip:  85%|████████▍ | 84/99 [07:54<01:22,  5.50s/it]

  NLI     : e=0.003  c=0.018  src=https://www.youtube.com/shorts/UHQvV7qjObM
  NLI [FC]: e=0.002  c=0.001  src=https://www.politifact.com/factchecks/2019/mar/04/
  NLI     : e=0.193  c=0.010  src=https://apnews.com/article/syria-mass-graves-steph
  NLI     : e=0.003  c=0.000  src=https://www.bbc.co.uk/news/articles/cj90wz8weymo
  NLI     : e=0.001  c=0.000  src=https://en.wikipedia.org/wiki/Mass_graves_in_Syria

Running text_clip:  87%|████████▋ | 86/99 [08:04<01:04,  4.99s/it]

  NLI     : e=0.992  c=0.001  src=https://news.meaww.com/joe-bidens-epa-granted-50-m
  NLI     : e=0.996  c=0.001  src=https://www.foxnews.com/politics/biden-epa-granted
  NLI     : e=0.006  c=0.970  src=https://www.theverge.com/news/613135/climate-justi
  NLI     : e=0.004  c=0.046  src=https://wordinblack.com/2025/02/epa-kills-50m-clim
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/list/?category=&ruling
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2026/feb/17/bruce-blak
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2026/feb/13/tom-omara/
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2025/feb/14/elon-musk/
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2016/oct/07/donald-tru
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2022/aug/11/kevin-mcca
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/article/2025/apr/02/elon-musks-mi
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/article/2025/aug/08/trump-new-cen
  NLI     : e=0.000  c=0.001  src=https://sports.yahoo.com/liverpool-ready-unprecede
  NLI     : e=0.000  c=0.001  src=https://www.empireofthekop.com/2025/03/25/liverpoo
  NLI     : e=0.000  c=0.092  src=https://www.sportbible.com/football/football-news/
  NLI     : e=0.001  c=0.000  src=https://www.thesun.co.uk/sport/32568118/trent-alex

Running text_clip:  89%|████████▉ | 88/99 [08:11<00:44,  4.04s/it]

  NLI     : e=0.688  c=0.006  src=https://azealia-banks.fandom.com/wiki/Feuds
  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/news/2025/02/21/ukraine-elections-war
  [FC SKIP] only 1 matches (need 2): https://fullfact.org/politics/trump-zelenskyy-dictator-elect
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/article/2025/aug/18/trump-zelensk
  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/collections/ukraine-russia-war-annive
  [FC REJECT] off-topic article: https://www.snopes.com/fact-check/us-trump-trip-world-leader

Running text_clip:  90%|████████▉ | 89/99 [08:17<00:46,  4.65s/it]

  NLI [FC]: e=0.000  c=0.000  src=https://www.snopes.com/fact-check/zelenskyy-say-no
  NLI [FC]: e=0.000  c=0.011  src=https://www.politifact.com/article/2025/feb/28/tru
  NLI     : e=0.061  c=0.172  src=https://m.naharnet.com/stories/en/305234-zelensky-
  NLI     : e=0.286  c=0.021  src=https://www.washingtonexaminer.com/news/2839164/il
  NLI     : e=0.005  c=0.008  src=https://www.cbsnews.com/newyork/news/nypd-officers
  NLI     : e=0.005  c=0.005  src=https://apnews.com/article/fact-check-nypd-protest
  NLI     : e=0.001  c=0.001  src=https://www.foxnews.com/us/nyc-migrants-arrested-a

Running text_clip:  91%|█████████ | 90/99 [08:21<00:40,  4.47s/it]

  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/article/2018/jul/05/fact-checking
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/article/2026/mar/05/Kristi-Noem-m
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2025/feb/26/facebook-p
  NLI     : e=0.992  c=0.001  src=https://thepeoplesvoice.tv/russia-releases-2000-pa
  NLI     : e=0.523  c=0.031  src=https://www.linkedin.com/posts/shivam-shukla-b0484

Running text_clip:  92%|█████████▏| 91/99 [08:26<00:35,  4.46s/it]

  NLI     : e=0.039  c=0.062  src=https://www.theguardian.com/world/2020/feb/22/coro
  NLI [FC]: e=0.148  c=0.065  src=https://www.factcheck.org/2024/06/factchecking-tru

Running text_clip:  93%|█████████▎| 92/99 [08:30<00:30,  4.41s/it]

  NLI     : e=0.998  c=0.000  src=https://www.foxnews.com/politics/new-york-gov-kath
  NLI [FC]: e=0.001  c=0.000  src=https://www.politifact.com/factchecks/2025/dec/11/
  NLI     : e=0.000  c=0.000  src=https://abc7ny.com/post/gov-kathy-hochul-unveils-p
  NLI     : e=0.998  c=0.000  src=https://www.yahoo.com/news/ny-governor-eyes-change

Running text_clip:  94%|█████████▍| 93/99 [08:31<00:21,  3.54s/it]

  NLI     : e=0.037  c=0.099  src=https://breakgfw.com/202403/74694.html
  NLI     : e=0.110  c=0.325  src=https://www.sinchew.com.my/news/20240426/nation/55
  NLI     : e=0.065  c=0.076  src=https://www.huaglad.com/zh-tw/lovecn/20240327/5504
  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/fact-check/boyfriend-corpses-medical-
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2025/jan/31/facebook-p
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2022/apr/28/facebook-p
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2019/jan/23/facebook-p
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/list/?page=8&category=
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/article/2023/apr/13/state-legisla
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2024/feb/16/instagram-
  NLI [FC]: e=0.001  c=0.000  src=https://www.politifact.com/factchecks/2022/oct/21/
  NLI     : e=0.999  c=0.000  src=https://www.foxnews.com/us/las-vegas-suspect-ex-gi
  NLI     : e=0.002  c=0.001  src=https://gazette.com/2025/01/02/what-matthew-livels
  NLI     : e=0.013  c=0.016  src=https://www.dailymail.co.uk/news/article-14246183/

Running text_clip:  95%|█████████▍| 94/99 [08:41<00:26,  5.31s/it]

  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/news/2023/10/19/israel-warned-al-ahli
  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/2023/11/social-media-posts-misrepr
  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/collections/israel-conflicts-rumors-c

Running text_clip:  96%|█████████▌| 95/99 [08:45<00:20,  5.00s/it]

  NLI [FC]: e=0.000  c=0.007  src=https://www.snopes.com/news/2025/10/28/hamas-cease
  NLI [FC]: e=0.058  c=0.012  src=https://www.snopes.com/articles/465623/oct-7-hamas
  NLI     : e=0.998  c=0.001  src=https://www.euronews.com/2025/04/25/at-least-50-pa
  NLI [FC]: e=0.000  c=0.003  src=https://www.snopes.com/news/2026/02/11/israel-stri
  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/hot-topics/
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2018/mar/16/viralpolit
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/article/2017/dec/12/2017-lie-year
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2018/02/words-trump-russian-meddli
  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/2018/10/factchecking-trumps-60-min

Running text_clip:  97%|█████████▋| 96/99 [08:52<00:16,  5.53s/it]

  NLI [FC]: e=0.026  c=0.271  src=https://www.factcheck.org/2018/07/factchecking-rus
  NLI [FC]: e=0.002  c=0.003  src=https://www.factcheck.org/2017/07/trump-spins-puti
  [FC REJECT] off-topic article: https://www.factcheck.org/location/russia/
  NLI     : e=0.046  c=0.734  src=https://www.ukrainefactcheck.org/source/fact-check
  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/fact-check/michelle-obama-harvey-wein
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2019/apr/03/donald-tru
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/article/2016/jan/22/iowa-gantlet-
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/article/2012/oct/19/fact-checking
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/article/2013/feb/15/government-jo
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2011/jan/31/sameh-shou
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2011/sep/05/barack-oba
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/article/2010/jan/13/announcing-po
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2011/oct/06/critics-wa
  NLI     : e=0.004  c=0.000  src=https://www.desertradio.fm/justin-baldoni-hits-bac
  NLI     : e=0.098  c=0.001  src=https://www.vanityfair.com/hollywood/story/blake-l
  NLI     : e=0.712  c=0.003  src=https://www.nytimes.com/2024/12/26/opinion/blake-l
  NLI     : e=0.003  c=0.001  src=https://www.bbc.com/news/articles/c9q7pxnr4g2o

Running text_clip:  98%|█████████▊| 97/99 [08:57<00:10,  5.39s/it]

  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2025/aug/07/tiktok-pos
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2014/feb/11/hugh-fitzs
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2021/jun/04/tiktok-pos
  NLI     : e=0.135  c=0.006  src=https://www.foxnews.com/entertainment/michelle-pfe
  NLI     : e=0.003  c=0.010  src=https://www.elle.com/culture/movies-tv/a63196619/t
  NLI     : e=0.699  c=0.005  src=https://variety.com/2024/tv/news/michelle-pfeiffer
  NLI     : e=0.001  c=0.986  src=https://www.yahoo.com/entertainment/tv/articles/ma

Running text_clip:  99%|█████████▉| 98/99 [08:59<00:04,  4.38s/it]

  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2024/jul/12/threads-po
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/truth-o-meter/promises/trumpomete
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/article/2023/may/12/ask-politifac
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2022/apr/28/facebook-p
  NLI     : e=0.497  c=0.025  src=https://www.foxnews.com/entertainment/jay-zs-sexua
  NLI     : e=0.751  c=0.015  src=https://www.tmz.com/2024/12/13/jay-z-diddy-rape-ac
  NLI [FC]: e=0.001  c=0.001  src=https://www.politifact.com/factchecks/2017/may/05/
  NLI [FC]: e=0.028  c=0.367  src=https://www.politifact.com/factchecks/2020/jun/03/

Running text_clip: 100%|██████████| 99/99 [09:07<00:00,  5.53s/it]

============================================================
MODE: text_clip
  mode                 text_clip
  n_total              99
  n_valid              99
  n_error              0
  accuracy             0.5556
  precision_macro      0.766
  recall_macro         0.551
  f1_macro             0.4398

Prediction distribution:
pred
REAL    94
FAKE     5
Name: count, dtype: int64

              precision    recall  f1-score   support

        FAKE       1.00      0.10      0.19        49
        REAL       0.53      1.00      0.69        50

    accuracy                           0.56        99
   macro avg       0.77      0.55      0.44        99
weighted avg       0.76      0.56      0.44        99


Confusion matrix (rows=true, cols=pred):
      FAKE  REAL
FAKE     5    44
REAL     0    50

Per-class correct/total:
  FAKE         5/49  (10%)
  REAL         50/50  (100%)
  Saved: /content/ablation_v2_text_clip.csv

Running text_clip_ocr:   0%|          | 0/99 [00:00<?, ?it/s]

  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/fact-check/hamas-wedding-girls/
  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/news/2023/10/13/idf-white-phosphorus-
  [FC SKIP] only 0 matches (need 2): https://fullfact.org/conflict/
  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/fact-check/ai-photo-missiles-tel-aviv
  NLI [FC]: e=0.285  c=0.532  src=https://www.snopes.com/fact-check/photograph-rafah
  NLI [FC]: e=0.199  c=0.056  src=https://fullfact.org/news/iran-missile-drone-attac
  NLI [FC]: e=0.676  c=0.026  src=https://www.snopes.com/fact-check/richard-engel-is

Running text_clip_ocr:   1%|          | 1/99 [00:04<08:05,  4.95s/it]

  NLI     : e=0.002  c=0.994  src=https://www.timesofisrael.com/liveblog_entry/idf-i
  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/2012/10/factchecking-the-hofstra-d
  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/2017/05/trump-not-deporting-native

Running text_clip_ocr:   2%|▏         | 2/99 [00:10<08:56,  5.53s/it]

  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2025/10/competing-claims-on-who-be
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/article/2025/mar/31/anonymous-x-a
  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/fact-check/close-up-bees-face/
  NLI [FC]: e=0.001  c=0.004  src=https://www.politifact.com/article/2023/oct/23/how
  [FC REJECT] off-topic article: https://www.snopes.com/fact-check/x-post-2023-cole-allen/
  NLI     : e=0.000  c=0.002  src=https://tweetdelete.net/resources/are-twitter-book
  [FC REJECT] off-topic article: https://www.snopes.com/news/2023/11/13/video-palestinian-man
  NLI [FC]: e=0.010  c=0.001  src=https://www.factcheck.org/2025/01/republicans-wron
  NLI [FC]: e=0.864  c=0.005  src=https://www.politifact.com/article/2025/jan/02/how
  NLI [FC]: e=0.013  c=0.047  src=https://www.snopes.com/news/2025/01/02/new-orleans

Running text_clip_ocr:   3%|▎         | 3/99 [00:21<12:55,  8.08s/it]

  NLI     : e=0.988  c=0.003  src=https://abc7.com/post/what-know-shamsud-din-jabbar
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2022/jul/26/instagram-
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2023/jul/14/instagram-
  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/fact-check/antarctica-seen-from-space
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2023/apr/25/instagram-
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2022/aug/30/facebook-p
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2022/oct/10/facebook-p
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2022/sep/14/instagram-
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2021/mar/02/facebook-p
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2022/aug/23/facebook-p
  NLI     : e=0.009  c=0.005  src=https://www.outsideonline.com/outdoor-adventure/ex
  NLI     : e=0.009  c=0.319  src=https://www.history.co.uk/articles/reasons-captain
  NLI     : e=0.110  c=0.108  src=https://www.coolantarctica.com/Antarctica%20fact%2
  NLI     : e=0.002  c=0.960  src=https://www.quora.com/What-do-the-people-who-belie

Running text_clip_ocr:   4%|▍         | 4/99 [00:29<12:36,  7.97s/it]

  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/fact-check/samira-ibrahim/
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2023/oct/13/instagram-
  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/fact-check/a-farewell-to-arms/
  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/category/photos/?pagenum=81
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2015/jul/16/chain-emai
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/article/2015/jul/22/half-truths-w
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/list/?page=209&speaker
  NLI     : e=0.001  c=0.000  src=https://www.indiatoday.in/fact-check/story/fact-ch

Running text_clip_ocr:   5%|▌         | 5/99 [00:37<12:28,  7.96s/it]

  NLI     : e=0.002  c=0.000  src=https://www.reuters.com/fact-check/video-shows-fre
  NLI     : e=0.000  c=0.002  src=https://www.dogrula.org/en/fact-checks/was-the-vid
  NLI     : e=0.001  c=0.000  src=https://www.misbar.com/amp/en/factcheck/2024/06/26

Running text_clip_ocr:   6%|▌         | 6/99 [00:40<09:26,  6.09s/it]

  NLI     : e=0.002  c=0.002  src=https://www.boomlive.in/fact-check/factcheck-mosqu
  NLI     : e=0.000  c=0.002  src=https://www.reuters.com/fact-check/video-shows-dem
  NLI     : e=0.001  c=0.004  src=https://africacheck.org/fact-checks/meta-programme
  NLI     : e=0.018  c=0.002  src=https://www.bbc.com/news/world-asia-china-67483202

Running text_clip_ocr:   7%|▋         | 7/99 [00:43<08:04,  5.26s/it]

  NLI     : e=0.108  c=0.003  src=https://apnews.com/article/somaliland-presidential
  NLI     : e=0.997  c=0.000  src=https://www.reuters.com/world/africa/somaliland-op
  NLI     : e=0.000  c=0.009  src=https://en.wikipedia.org/wiki/2024_Somaliland_pres
  NLI     : e=0.002  c=0.001  src=https://www.yahoo.com/news/somaliland-opposition-l
  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/notes/why-we-include-humor-and-satire

Running text_clip_ocr:   8%|▊         | 8/99 [00:49<07:58,  5.26s/it]

  NLI     : e=0.010  c=0.040  src=https://apnews.com/article/onion-satire-alex-jones
  NLI     : e=0.001  c=0.004  src=https://www.cnn.com/2026/04/20/media/the-onion-ale
  NLI [FC]: e=0.001  c=0.005  src=https://www.snopes.com/news/2019/08/16/readers-thi
  NLI     : e=0.999  c=0.000  src=https://www.pbs.org/video/the-onion-is-adding-cont

Running text_clip_ocr:   9%|▉         | 9/99 [00:49<05:50,  3.90s/it]

  NLI     : e=0.002  c=0.002  src=https://www.threads.com/@based.angxl_/post/DC8W638
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/article/2020/oct/19/fact-checking
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/article/2020/may/22/hunter-biden-
  NLI     : e=0.120  c=0.180  src=https://apnews.com/article/fact-check-dali-ship-ba
  NLI     : e=0.119  c=0.173  src=https://www.usatoday.com/story/news/factcheck/2024
  NLI [FC]: e=0.013  c=0.899  src=https://www.politifact.com/factchecks/2024/mar/27/

Running text_clip_ocr:  11%|█         | 11/99 [00:52<03:27,  2.35s/it]

  NLI     : e=0.074  c=0.603  src=https://www.fox8live.com/2024/03/12/angela-chao-sh

Running text_clip_ocr:  12%|█▏        | 12/99 [00:52<02:31,  1.74s/it]

  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/fact-check/lost-child-rape-lure/
  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/fact-check/ronald-mcdonald-1892/
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2022/05/tv-ads-about-cheri-beasley
  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/fact-check/
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2019/05/meme-inflates-school-shoot
  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/news/2020/06/24/rayshard-brooks-crimi
  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/fact-check/school-shooters-death-pena
  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/2019/10/the-facts-on-mental-illnes
  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/ap/2018/11/14/authorities-prosecuting
  NLI [FC]: e=0.181  c=0.097  src=https://www.snopes.com/news/2019/09/04/the-psychol

Running text_clip_ocr:  13%|█▎        | 13/99 [00:52<01:52,  1.31s/it]

  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2019/06/falsehood-swirls-about-bid
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2018/apr/20/yournewswi
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2020/05/the-falsehoods-of-the-plan
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/article/2019/mar/18/wikileaks-rus
  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/misconceptions/the-origins-of-covi
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/article/2020/apr/17/what-we-know-
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2023/06/video-distorts-early-coron
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/article/2018/aug/02/fact-checking
  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/fact-check/queen-elizabeth-gorilla-bl
  NLI [FC]: e=0.070  c=0.094  src=https://www.snopes.com/fact-check/funvax/
  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/fact-check/goldfinger-actress-death/
  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/news/2022/10/25/reepy-clown-history-h
  NLI     : e=0.000  c=0.000  src=https://www.flavorwire.com/509157/lets-stop-tellin
  NLI     : e=0.001  c=0.003  src=https://kotaku.com/sexism-character-design-and-the
  NLI     : e=0.003  c=0.000  src=https://medium.com/@mirandasalinger/the-villinizat
  NLI     : e=0.000  c=0.000  src=https://www.quora.com/The-guy-I-m-dating-treats-me

Running text_clip_ocr:  15%|█▌        | 15/99 [01:02<04:30,  3.22s/it]

  NLI [FC]: e=0.002  c=0.003  src=https://www.snopes.com/fact-check/luigi-beanie-ama
  [FC REJECT] off-topic article: https://www.snopes.com/fact-check/nintendo-free-him-luigi-po
  NLI [FC]: e=0.001  c=0.001  src=https://www.snopes.com/fact-check/uhc-shooter-mug-
  NLI     : e=0.004  c=0.004  src=https://www.nbcnewyork.com/news/local/crime-and-co

Running text_clip_ocr:  16%|█▌        | 16/99 [01:02<03:13,  2.34s/it]

  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2020/02/trump-has-condemned-white-
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2018/aug/03/donald-tru
  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/fact-check/war-games/
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2022/03/the-facts-on-de-nazifying-
  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/2017/04/100-days-whoppers/
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/article/2020/sep/10/ad-watch-what
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2015/oct/16/jason-vill
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2018/mar/06/david-simm
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2024/may/14/instagram-
  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/fact-check/trump-very-fine-people/
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/fact-check/using-regular-people/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/2025/03/rfk-jr-s-faulty-advice-on-
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/2021/03/scicheck-video-targets-gat
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/person/peter-mccullough/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2021/sep/16/facebook-p
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/2025/05/rfk-jr-denies-cuts-to-scie
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2024/feb/02/instagram-
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2022/jul/27/instagram-
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/factchecks/2014/jan/26/richard-au
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/tag/usda/
  NLI     : e=0.018  c=0.104  src=https://americancattlemen.com/to-cull-or-not-to-cu
  NLI     : e=0.007  c=0.004  src=https://www.bbc.com/news/articles/c4gzl9d759po
  NLI     : e=0.015  c=0.007  src=https://en.wikipedia.org/wiki/Culling

Running text_clip_ocr:  17%|█▋        | 17/99 [01:06<03:48,  2.79s/it]

  NLI     : e=0.006  c=0.020  src=https://www.backyardchickens.com/threads/culling-w
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2019/12/zelenskys-remarks-about-tr
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2023/03/social-media-posts-misrepr
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/person/volodymyr-zelenskyy/
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2019/11/discrepancy-in-white-house
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/issue/ukraine/
  NLI [FC]: e=0.025  c=0.571  src=https://www.factcheck.org/2025/02/trumps-false-and
  NLI [FC]: e=0.000  c=0.000  src=https://www.politifact.com/article/2025/aug/18/tru

Running text_clip_ocr:  18%|█▊        | 18/99 [01:10<04:01,  2.98s/it]

  NLI [FC]: e=0.001  c=0.015  src=https://www.snopes.com/fact-check/zelenskyy-us-ukr
  NLI     : e=0.999  c=0.000  src=https://www.foxnews.com/world/zelenskyy-says-trump
  NLI     : e=0.005  c=0.004  src=https://www.nytimes.com/live/2024/01/30/opinion/th
  NLI     : e=0.015  c=0.004  src=https://www.taxnotes.com/research/federal/legislat
  NLI     : e=0.004  c=0.000  src=https://www.govinfo.gov/content/pkg/CHRG-116hhrg39
  NLI     : e=0.004  c=0.004  src=https://www.theodorerooseveltcenter.org/quotes/pag

Running text_clip_ocr:  19%|█▉        | 19/99 [01:11<03:26,  2.59s/it]

  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/fact-check/dec-11-memorial/
  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/2013/01/anti-nra-groups-shameless-
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/article/2016/jul/29/backstory-mus
  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/2017/06/trumps-tweets-twist-facts/

Running text_clip_ocr:  20%|██        | 20/99 [01:12<02:34,  1.95s/it]

  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2004/10/media-fund-twists-the-trut
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/article/2015/jul/22/half-truths-w
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/article/2016/oct/08/context-donal
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2018/01/response-iranian-protests-
  [FC REJECT] off-topic article: https://www.politifact.com/factchecks/2014/dec/02/facebook-p
  [FALLBACK] Using embedding similarity
  TEXT ERROR [US to hold national day of mourning for ]: name 'embedding_stance_fallback' is not defined
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2023/10/what-we-know-about-three-w
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/article/2024/may/16/how-unprecede

Running text_clip_ocr:  21%|██        | 21/99 [01:16<03:37,  2.79s/it]

  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/collections/israel-hamas-ceasefire/
  [FC REJECT] off-topic article: https://www.politifact.com/factchecks/2023/oct/13/instagram-
  NLI [FC]: e=0.013  c=0.002  src=https://www.politifact.com/article/2026/apr/02/fac
  NLI [FC]: e=0.060  c=0.036  src=https://www.factcheck.org/2026/03/legality-of-late
  NLI     : e=0.276  c=0.028  src=https://www.aa.com.tr/en/middle-east/explosions-he
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2024/mar/01/facebook-p
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/article/2025/nov/06/nancy-pelosi-
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/article/2019/aug/01/donald-trump-
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2018/jun/27/twentyeigh
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2023/aug/31/travis-tri
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/article/2017/jan/27/heres-what-do
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/article/2026/mar/06/Markwayne-Mul
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2014/mar/03/florida-de

Running text_clip_ocr:  22%|██▏       | 22/99 [01:26<06:07,  4.77s/it]

  [FC REJECT] off-topic article: https://www.politifact.com/article/2025/jun/06/jeffrey-epste
  [FC REJECT] off-topic article: https://www.politifact.com/factchecks/2023/nov/01/maga-inc/r
  NLI     : e=0.000  c=0.001  src=https://www.foxnews.com/media/carter-feuded-succes
  NLI     : e=0.000  c=0.001  src=https://ground.news/article/carter-feuded-with-suc
  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/news/2018/09/06/many-daily-caller-wri
  NLI     : e=0.032  c=0.008  src=https://www.foxnews.com/us/fox-news-antisemitism-e
  NLI     : e=0.001  c=0.004  src=https://www.foxnews.com/us/fox-news-antisemitism-e
  NLI     : e=0.005  c=0.005  src=https://www.foxnews.com/world/global-rise-antisemi
  NLI     : e=0.003  c=0.015  src=https://www.foxnews.com/world/antisemitism-spiking

Running text_clip_ocr:  24%|██▍       | 24/99 [01:34<05:45,  4.60s/it]

  NLI     : e=0.997  c=0.000  src=https://www.reuters.com/markets/deals/us-steel-nip
  [FC REJECT] off-topic article: https://www.snopes.com/tracker/trump-executive-orders-list/
  NLI     : e=0.999  c=0.000  src=https://www.cnn.com/2025/01/06/business/us-steel-b
  NLI     : e=0.999  c=0.000  src=https://www.pbs.org/newshour/politics/biden-reject
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2024/11/both_sides_distort_incompl
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2024/nov/08/instagram-
  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/2008/03/presidents-winning-without
  [FC REJECT] off-topic article: https://www.politifact.com/factchecks/2021/jan/07/donald-tru
  [FC REJECT] off-topic article: https://www.politifact.com/article/2024/nov/22/how-big-was-d
  NLI [FC]: e=0.066  c=0.017  src=https://www.factcheck.org/2024/11/trump-won-the-po
  NLI     : e=0.997  c=0.000  src=https://news.syr.edu/2024/11/06/what-happens-to-th

Running text_clip_ocr:  25%|██▌       | 25/99 [01:41<06:21,  5.16s/it]

  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/2010/07/shirley-sherrods-contextua
  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/news/2015/11/23/clock-kid-ahmed-moham
  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/2004/08/republican-funded-group-at
  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/fact-check/still-the-queen/
  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/fact-check/cesar-sayoc-obama-supporti
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/article/2018/jul/05/fact-checking
  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/news/2016/07/11/black-officer-jay-sta
  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/fact-check/the-day-i-met-daniel/
  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/fact-check/spousal-success-story/
  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/fact-check/the-last-of-the-kennedy-dy
  NLI     : e=1.000  c=0.000  src=https://www.voanews.com/a/india-reflects-on-ravi-s
  NLI     : e=0.989  c=0.000  src=https://indiacurrents.com/the-global-ambassador-of
  NLI     : e=0.003  c=0.000  src=https://www.elsewhere.co.nz/world-music/332/ravi-s
  NLI     : e=0.973  c=0.001  src=https://www.bbc.com/news/articles/cwype77kwyjo

Running text_clip_ocr:  26%|██▋       | 26/99 [01:45<06:00,  4.94s/it]

  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/fact-check/oregon-ballot-omits-donald
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/fact-check/marine-wedding/
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/fact-check/facebook-rule-photos-tv/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/2010/01/clueless-columbo/
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/fact-check/prayer-request-child-shot-
  [FC REJECT] off-topic article: https://www.snopes.com/fact-check/report-from-a-paramedic/
  [FC REJECT] off-topic article: https://www.snopes.com/fact-check/maryland-billboard-guns-tr
  [FC REJECT] off-topic article: https://www.snopes.com/fact-check/trump-volcanoes-concrete-p

Running text_clip_ocr:  27%|██▋       | 27/99 [01:50<05:52,  4.90s/it]

  NLI     : e=0.014  c=0.089  src=https://scottrobinsonhonda.com/video-reels/?wchann
  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/2017/02/trumps-bogus-terrorist-cla
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2015/jun/22/barack-oba
  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/2015/10/gun-laws-deaths-and-crimes

Running text_clip_ocr:  28%|██▊       | 28/99 [02:00<07:34,  6.40s/it]

  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/2019/10/the-facts-on-mental-illnes
  NLI     : e=0.983  c=0.003  src=https://www.threads.com/@cnn/post/DAEOXX6KH7r
  [FC REJECT] off-topic article: https://www.politifact.com/embassyattacks/
  NLI     : e=0.007  c=0.237  src=https://apnews.com/live/lebanon-syria-pagers-hezbo
  NLI     : e=0.701  c=0.001  src=https://www.timesofisrael.com/liveblog_entry/leban
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2018/nov/04/blog-posti
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2018/feb/23/philip-lev
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/article/2024/oct/02/vp-debate-fac

Running text_clip_ocr:  29%|██▉       | 29/99 [02:04<06:28,  5.55s/it]

  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2022/may/16/facebook-p
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2023/aug/10/facebook-p
  NLI     : e=0.968  c=0.008  src=https://www.today.com/news/news/jamie-foxx-injured
  NLI     : e=0.997  c=0.002  src=https://www.tmz.com/2024/12/14/jamie-foxx-fight-mr
  [FC REJECT] off-topic article: https://www.politifact.com/article/2024/sep/27/has-a-venezue
  NLI     : e=0.999  c=0.000  src=https://www.nbclosangeles.com/entertainment/entert

Running text_clip_ocr:  30%|███       | 30/99 [02:05<05:03,  4.39s/it]

  NLI     : e=0.088  c=0.460  src=https://t.me/s/MojahdeenMN?after=55418
  NLI     : e=0.217  c=0.208  src=https://t.me/s/auem_yemen/46872
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2025/jul/29/benjamin-n
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/archive-beheaded-babies-israel-ha
  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/fact-check/film-crew-footage-gaza/
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/article/2025/dec/12/genocide-isra
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/article/2024/may/24/the-un-adjust
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/article/2025/dec/15/lie-of-the-ye
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2024/dec/06/instagram-
  NLI [FC]: e=0.002  c=0.005  src=https://www.snopes.com/news/2024/05/02/netanyahu-h
  NLI [FC]: e=0.003  c=0.003  src=https://www.politifact.com/factchecks/2015/mar/22/

Running text_clip_ocr:  31%|███▏      | 31/99 [02:06<03:50,  3.38s/it]

  NLI     : e=0.013  c=0.001  src=https://transcripts.cnn.com/show/cnc/date/2024-09-

Running text_clip_ocr:  32%|███▏      | 32/99 [02:09<03:29,  3.12s/it]

  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/2019/07/unpacking-bidens-and-trump
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2020/may/28/facebook-p
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2024/dec/30/instagram-
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2022/feb/23/instagram-
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2025/05/trump-allies-spread-unfoun
  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/collections/barron-trump-rumors-colle
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2020/08/covid-19-nasal-swab-test-d
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/issue/government-run-health-care/f
  NLI     : e=0.996  c=0.002  src=https://www.dailystar.co.uk/news/latest-news/new-d
  [FC REJECT] off-topic article: https://www.snopes.com/fact-check/germany-gel-joint-cartilag
  NLI     : e=0.002  c=0.002  src=https://www.bbc.com/news/articles/clyx9nv4mleo
  NLI     : e=0.072  c=0.025  src=https://www.cnn.com/2025/12/19/science/beachy-head

Running text_clip_ocr:  33%|███▎      | 33/99 [02:15<04:19,  3.93s/it]

  NLI     : e=0.995  c=0.000  src=https://www.chazakrescue.org/news-updates/mayotte-
  NLI     : e=0.019  c=0.002  src=https://www.pbs.org/newshour/world/mayotte-imposes
  NLI     : e=0.000  c=0.000  src=https://www.bbc.com/news/articles/c89x0j1le4lo
  NLI     : e=0.001  c=0.001  src=https://www.columbian.com/news/2024/dec/17/authori
  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/news/2016/06/19/daily-caller-error-fi
  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/2008/03/wisconsin-judgment-day-the
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/article/2015/sep/22/fact-checking
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/article/2016/dec/13/2016-lie-year
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2024/nov/21/threads-po
  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/2009/02/who-is-linda-panetta/
  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/fact-check/huckabee-sanders-red-hen-p
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/article/2015/jan/22/ernsts-bread-
  NLI     : e=0.007  c=0.001  src=https://www.foxnews.com/media/embarrassingly-wrong
  NLI     : e=0.004  c=0.001  src=https://abc3340.com/news/nation-world/questions-em
  NLI     : e=0.026  c=0.007  src=https://www.yahoo.com/news/gullible-wrong-journali

Running text_clip_ocr:  34%|███▍      | 34/99 [02:19<04:23,  4.05s/it]

  NLI     : e=0.001  c=0.000  src=https://www.newyorker.com/news/fault-lines/whos-to
  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/2020/05/baseless-conspiracy-theory
  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/fact-check/derek-mullins-jasmine-cart
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2024/09/posts-misrepresent-police-
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2019/03/social-posts-spin-sanders-
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2024/jul/16/threads-po
  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/person/george-floyd/
  NLI     : e=0.992  c=0.005  src=https://www.12onyourside.com/2024/12/09/key-detail
  NLI [FC]: e=0.010  c=0.932  src=https://www.factcheck.org/2021/04/posts-falsely-id
  NLI [FC]: e=0.005  c=0.027  src=https://www.factcheck.org/2020/05/falsehoods-follo

Running text_clip_ocr:  35%|███▌      | 35/99 [02:23<04:26,  4.16s/it]

  NLI     : e=0.997  c=0.001  src=https://6abc.com/15622805/
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2023/10/what-we-know-about-three-w
  [FC SKIP] only 0 matches (need 2): https://fullfact.org/news/altered-audio-CNN-border-footage-s
  [FC SKIP] only 0 matches (need 2): https://fullfact.org/world/arab-fact-checking-lessons-from-p
  [FC SKIP] only 0 matches (need 2): https://fullfact.org/world/burj-khalifa-ai-iran/
  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/2023/11/online-video-misrepresents
  [FC SKIP] only 0 matches (need 2): https://fullfact.org/online/lebanese-citizens-celebrating-Ha
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/article/2026/mar/11/trump-iran-sc
  [FC REJECT] off-topic article: https://www.snopes.com/fact-check/anti-netanyahu-protest-isr
  NLI [FC]: e=0.021  c=0.023  src=https://www.factcheck.org/2023/12/post-misrepresen
  NLI [FC]: e=0.011  c=0.012  src=https://www.snopes.com/fact-check/crisis-actors-is

Running text_clip_ocr:  36%|███▋      | 36/99 [02:30<05:00,  4.77s/it]

  NLI     : e=0.013  c=0.007  src=https://www.bbc.com/news/videos/ce9jeev2grro
  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/fact-check/hegseth-iran-war-christian
  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/news/2025/02/24/congo-70-christians-b
  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/fact-check/pope-leo-xiv-iran-war/
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2015/06/cruz-cherry-picks-terroris
  [FC SKIP] only 1 matches (need 2): https://mail.snopes.com/p/new-post-0c67
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2021/aug/19/facebook-p
  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/fact-check/saved-by-humility/

Running text_clip_ocr:  38%|███▊      | 38/99 [02:33<03:01,  2.98s/it]

  NLI     : e=0.000  c=0.001  src=https://www.ewtnnews.com/world/europe/7-catholic-c
  [FC REJECT] off-topic article: https://www.politifact.com/factchecks/2011/feb/07/ron-paul/r
  [FC REJECT] off-topic article: https://www.politifact.com/factchecks/2014/aug/01/georgiacar
  [FC REJECT] off-topic article: https://www.politifact.com/factchecks/2020/feb/29/facebook-p
  [FC SKIP] only 0 matches (need 2): https://staging.politifact.com/article/2019/jan/25/photo-cov
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2008/11/2008-factcheck-awards/
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2008/10/court-fight-in-the-heart-o
  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/collections/epstein-maxwell-clintons-
  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/fact-check/pam-bondi-cross-necklace/

Running text_clip_ocr:  39%|███▉      | 39/99 [02:34<02:33,  2.56s/it]

  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/article/2016/oct/18/allegations-a
  NLI [FC]: e=0.028  c=0.698  src=https://www.snopes.com/fact-check/woman-jail-weari
  [FC REJECT] off-topic article: https://www.politifact.com/factchecks/2010/oct/22/roy-barnes
  NLI     : e=0.020  c=0.034  src=https://www.yahoo.com/entertainment/celebrity/arti
  NLI     : e=0.016  c=0.419  src=https://www.yahoo.com/entertainment/celebrity/arti
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/corrections-and-updates/
  [FC SKIP] only 0 matches (need 1): https://fullfact.org/policy/reports/full-fact-report-2024/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/article/2026/feb/18/dietary-prote
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/article/2026/feb/04/washington-DC
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/article/2026/mar/23/march-madness
  [FC REJECT] off-topic article: https://www.snopes.com/fact-check/dracula-live-transylvanian
  [FC REJECT] off-topic article: https://www.politifact.com/article/2026/apr/07/choosing-best
  [FC REJECT] off-topic article: https://www.politifact.com/article/2026/mar/06/TrumpRx-presc

Running text_clip_ocr:  40%|████      | 40/99 [02:48<05:58,  6.07s/it]

  NLI     : e=0.001  c=0.001  src=https://www.bbc.com/news/world-europe-17776565

Running text_clip_ocr:  41%|████▏     | 41/99 [02:52<05:10,  5.35s/it]

  NLI     : e=0.070  c=0.000  src=https://apnews.com/article/koala-chlamydia-vaccina
  NLI     : e=0.001  c=0.000  src=https://www.bbc.com/news/articles/cjdnkdg1l8do
  NLI     : e=0.004  c=0.000  src=https://www.reuters.com/business/healthcare-pharma
  NLI     : e=0.159  c=0.000  src=https://www.euronews.com/2025/09/12/new-vaccine-ai

Running text_clip_ocr:  42%|████▏     | 42/99 [02:56<04:32,  4.79s/it]

  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2013/08/the-messy-facts-in-virgini
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2019/aug/09/pete-butti
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2025/jul/11/jon-favrea
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2021/mar/02/donald-tru
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/article/2025/jun/06/jeffrey-epste
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2013/jul/03/debbie-was
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/article/2022/jun/09/political-ext
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2014/dec/03/jeb-bush/t
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2025/jul/18/donald-tru
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/article/2022/jan/28/what-you-need
  NLI     : e=0.001  c=0.002  src=http://archive.is/duYni
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2020/jan/15/facebook-p
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/article/2018/feb/26/dunkirk-fact-
  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/2024/08/misleading-democratic-ad-i
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2024/sep/26/sam-brown/

Running text_clip_ocr:  43%|████▎     | 43/99 [03:02<05:01,  5.38s/it]

  [FC REJECT] off-topic article: https://www.politifact.com/factchecks/2025/mar/26/pete-hegse
  [FC REJECT] off-topic article: https://www.snopes.com/fact-check/chris-evans-signing-bomb/
  NLI     : e=0.009  c=0.009  src=https://www.yahoo.com/entertainment/chris-evans-cl
  NLI     : e=0.000  c=0.995  src=https://okmagazine.com/p/captain-america-chris-eva

Running text_clip_ocr:  44%|████▍     | 44/99 [03:08<04:57,  5.42s/it]

  NLI     : e=0.025  c=0.715  src=https://en.wikipedia.org/wiki/Pear_of_anguish
  NLI     : e=0.070  c=0.024  src=https://medievaltorturemuseum.com/blog/pear-anguis
  NLI     : e=0.035  c=0.007  src=https://allthatsinteresting.com/pear-of-anguish
  NLI     : e=0.043  c=0.008  src=https://medievalbritain.com/type/medieval-life/tor
  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/news/2016/04/10/spring-break-nightmar
  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/fact-check/man-stuck-2055-france/
  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/2010/09/bos-private-plane/
  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/news/2026/02/25/kash-patel-olympic-ho
  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/category/viral-phenomena/?pagenum=18
  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/fact-check/yusra-mardini-flee-syria-s
  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/fact-check/racist-carnival-game/

Running text_clip_ocr:  45%|████▌     | 45/99 [03:15<05:19,  5.91s/it]

  NLI     : e=0.041  c=0.002  src=https://www.foxnews.com/travel/man-vacation-goes-v
  NLI     : e=0.028  c=0.001  src=https://nypost.com/2024/12/31/lifestyle/man-on-vac
  NLI [FC]: e=0.010  c=0.239  src=https://www.snopes.com/news/2021/06/21/mama-bear-g
  NLI [FC]: e=0.017  c=0.443  src=https://www.snopes.com/fact-check/kentucky-snow-fl

Running text_clip_ocr:  46%|████▋     | 46/99 [03:17<04:04,  4.62s/it]

  NLI [FC]: e=0.001  c=0.016  src=https://www.politifact.com/factchecks/2024/jul/03/
  NLI     : e=0.001  c=0.000  src=https://forums.dukebasketballreport.com/index.php?
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2025/jul/09/scott-jenn
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/article/2022/sep/29/united-facts-
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/article/2026/jan/03/trump-maduro-
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/article/2016/apr/06/we-fact-check
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/article/2026/feb/25/democrats-sta
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/article/2025/nov/03/trump-60-minu
  NLI     : e=0.884  c=0.013  src=https://www.foxnews.com/video/6365955471112
  NLI     : e=1.000  c=0.000  src=https://www.mediaite.com/media/tv/dont-touch-me-sc
  NLI     : e=0.996  c=0.001  src=https://www.foxnews.com/media/scott-jennings-bakar
  NLI     : e=0.999  c=0.000  src=https://nypost.com/2024/12/14/media/cnn-contributo

Running text_clip_ocr:  47%|████▋     | 47/99 [03:22<04:07,  4.75s/it]

  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/article/2017/may/02/whats-up-with
  NLI [FC]: e=0.000  c=0.001  src=https://www.snopes.com/fact-check/trump-veterans-d
  NLI [FC]: e=0.011  c=0.047  src=https://www.snopes.com/fact-check/donald-tump-ffa-
  NLI     : e=0.002  c=0.050  src=https://www.foxnews.com/opinion/how-trump-survives

Running text_clip_ocr:  48%|████▊     | 48/99 [03:27<04:11,  4.92s/it]

  NLI     : e=0.000  c=0.000  src=https://abc17news.com/politics/2026/04/26/trump-fi

Running text_clip_ocr:  49%|████▉     | 49/99 [03:34<04:37,  5.56s/it]

  NLI     : e=0.017  c=0.001  src=https://www.foxnews.com/media/psychologist-jonatha
  NLI     : e=0.000  c=0.000  src=https://cyberbullying.org/student-phones-school-ba
  NLI     : e=0.001  c=0.017  src=https://www.applerouth.com/blog/parents-phones-and
  NLI     : e=0.000  c=0.000  src=https://ground.news/article/how-jonathan-haidt-won
  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/fact-check/texas-ice-raid-birthday-pa
  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/fact-check/tiger-houston-neighborhood
  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/fact-check/texas-alien-anal-probe/
  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/fact-check/carl-twinly-cow-arrest/
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2010/nov/11/greg-abbot
  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/fact-check/karmelo-anthony-donations-
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2015/jul/30/harry-houc
  NLI     : e=0.000  c=0.000  src=https://fastguardservice.com/texas-police-arrest-9
  NLI     : e=0.000  c=0.000  src=https://www.foxnews.com/video/6365971915112

Running text_clip_ocr:  51%|█████     | 50/99 [03:41<04:47,  5.87s/it]

  NLI     : e=0.964  c=0.001  src=https://www.foxnews.com/us/texas-police-arrest-9-s
  NLI     : e=0.164  c=0.001  src=https://www.fox7austin.com/news/lakeline-mall-shop
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2022/dec/16/instagram-
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/article/2022/mar/15/zuckerbucks-2
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2024/dec/13/facebook-p
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2018/dec/04/blog-posti
  NLI     : e=0.120  c=0.001  src=https://www.realtor.com/news/reality-tv/christina-
  NLI     : e=0.996  c=0.002  src=https://www.wwbl.com/2025/01/07/hgtv-star-christin
  NLI     : e=0.997  c=0.000  src=https://www.foxnews.com/entertainment/hgtv-star-ch
  NLI     : e=0.998  c=0.001  src=https://www.cosmopolitan.com/entertainment/celebs/

Running text_clip_ocr:  52%|█████▏    | 51/99 [03:44<04:06,  5.14s/it]

  [FC SKIP] only 0 matches (need 2): https://fullfact.org/policy/reports/full-fact-report-2024/
  [FC SKIP] only 0 matches (need 2): https://fullfact.org/policy/reports/full-fact-report-2025/
  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/author/snopes/?pagenum=45
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2018/dec/20/blog-posti
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2018/aug/07/greg-abbot
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2015/jul/20/rick-perry
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2019/jul/02/kamala-har
  [FC REJECT] off-topic article: https://www.politifact.com/factchecks/2017/nov/10/michael-mc
  NLI     : e=0.099  c=0.439  src=https://www.express.co.uk/news/uk/1979993/westmins
  NLI     : e=0.006  c=0.860  src=https://uk.news.yahoo.com/westmister-bridge-150736

Running text_clip_ocr:  53%|█████▎    | 52/99 [03:52<04:41,  5.98s/it]

  NLI     : e=0.000  c=0.994  src=https://www.bbc.com/news/articles/c5y3en5yv21o
  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/fact-check/log-pile-missing/
  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/fact-check/eric-langford-missing-boy-
  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/fact-check/missing-alaska-hikers-stor
  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/news/2026/04/28/scientists-dead-missi
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/article/2025/aug/25/kilmar-abrego
  NLI     : e=0.028  c=0.031  src=https://www.aol.com/articles/hiker-stumbles-human-
  NLI     : e=0.995  c=0.003  src=https://abc7.com/post/severely-decomposed-human-re
  NLI     : e=0.999  c=0.000  src=https://www.foxnews.com/us/police-investigating-af
  NLI [FC]: e=0.021  c=0.376  src=https://www.politifact.com/factchecks/2023/aug/22/

Running text_clip_ocr:  54%|█████▎    | 53/99 [04:00<04:59,  6.50s/it]

  NLI     : e=0.027  c=0.023  src=https://issuu.com/outlawpartners/docs/explore_big_
  NLI     : e=0.002  c=0.001  src=https://www.youtube.com/shorts/sSCIeF_wUE8
  NLI     : e=0.223  c=0.128  src=https://www.youtube.com/watch?v=dOrawfTwJPY
  NLI     : e=0.223  c=0.128  src=https://www.youtube.com/watch?v=UHdfT8TbR4c

Running text_clip_ocr:  56%|█████▌    | 55/99 [04:12<04:51,  6.62s/it]

  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/fact-check/isis-crisis-2/
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/fake-news/page/16/
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2019/mar/04/blog-posti
  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/fact-check/american-three-terrorist-a
  [FC REJECT] off-topic article: https://www.politifact.com/article/2023/nov/21/israel-hamas-
  NLI [FC]: e=0.034  c=0.024  src=https://www.factcheck.org/2023/11/dozens-of-childr
  [FC REJECT] off-topic article: https://www.factcheck.org/2023/10/what-we-know-about-three-w
  NLI     : e=0.095  c=0.008  src=https://www.aa.com.tr/en/middle-east/children-amon
  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/fact-check/pfizer-covid-vaccine-adver
  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/fact-check/call-police-new-guinea-fla
  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/fact-check/dangers-dihydrogen-monoxid
  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/fact-check/mayo-clinic/
  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/fact-check/hair-grooming-syncope/
  NLI     : e=0.003  c=0.001  src=https://www.yahoo.com/news/articles/trump-post-him
  NLI     : e=0.000  c=0.000  src=https://www.bbc.com/news/videos/c624dy3pgg2o
  NLI     : e=0.004  c=0.185  src=https://www.bbc.com/news/articles/c17v8y0z9z2o

Running text_clip_ocr:  57%|█████▋    | 56/99 [04:14<03:33,  4.97s/it]

  NLI     : e=0.000  c=0.005  src=https://www.courthousenews.com/i-thought-it-was-me
  [FC SKIP] only 1 matches (need 2): https://www.merriam-webster.com/dictionary/could
  [FC SKIP] only 1 matches (need 2): https://dictionary.cambridge.org/us/dictionary/english/could
  [FC SKIP] only 1 matches (need 2): https://en.wiktionary.org/wiki/could
  [FC SKIP] only 1 matches (need 2): https://www.grammarly.com/blog/commonly-confused-words/can-v
  [FC SKIP] only 1 matches (need 2): https://www.dictionary.com/browse/could
  [FC SKIP] only 1 matches (need 2): https://www.youtube.com/watch?v=OiYmamqv7H0
  [FC SKIP] only 1 matches (need 2): https://www.collinsdictionary.com/us/dictionary/english/coul
  [FC SKIP] only 1 matches (need 2): https://www.youtube.com/watch?v=z_PyX-NAKEI
  NLI     : e=0.993  c=0.001  src=https://www.space.com/astronomy/mars/artificial-su
  NLI     : e=0.995  c=0.000  src=https://spacenews.com/will-ai-redefine-human-roles
  NLI     : e=0.003  c=0.002  src=https://www.quora.com/How-can-AI-driven-robots-and

Running text_clip_ocr:  58%|█████▊    | 57/99 [04:18<03:16,  4.67s/it]

  NLI     : e=0.001  c=0.000  src=https://www.bbc.com/news/articles/cy7keddnj31o
  NLI [FC]: e=0.079  c=0.028  src=https://checkyourfact.com/2024/06/18/fact-check-ke
  NLI [FC]: e=0.012  c=0.001  src=https://www.snopes.com/fact-check/keanu-reeves-who
  NLI     : e=0.020  c=0.026  src=https://news.meaww.com/fact-check-did-keanu-reeves
  NLI     : e=0.981  c=0.003  src=https://visegrad25.quora.com/BREAKING-Keanu-Reeves

Running text_clip_ocr:  60%|█████▉    | 59/99 [04:26<02:52,  4.32s/it]

  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/2016/02/factchecking-the-eighth-go
  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/2006/10/accusations-without-eviden
  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/2025/11/sorting-out-the-facts-on-e
  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/2005/08/here-we-go-again-distorted
  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/2022/11/conservative-figures-sprea
  [FC SKIP] only 1 matches (need 2): https://mail.snopes.com/p/shackled-bodies-in-spain-health-ca
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2014/may/05/laura-ingr
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2013/jan/18/facebook-p
  [FC REJECT] off-topic article: https://www.factcheck.org/2023/10/what-we-know-about-three-w
  NLI     : e=0.004  c=0.565  src=https://www.reuters.com/fact-check/photos-show-202
  NLI     : e=0.837  c=0.002  src=https://www.wionews.com/world/iran-prez-ebrahim-ra
  NLI     : e=0.000  c=0.007  src=https://www.timesofisrael.com/liveblog_entry/iran-

Running text_clip_ocr:  61%|██████    | 60/99 [04:26<01:59,  3.06s/it]

  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/fact-check/jfk-palestine-britain/
  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/news/2018/06/13/lawsuit-brexit-backer
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2015/mar/03/bill-oreil
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2010/jan/22/charles-sc
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2014/jul/17/facebook-p
  [FC REJECT] off-topic article: https://www.factcheck.org/2008/10/life-cycle-of-a-rumor/
  NLI     : e=0.006  c=0.030  src=https://apnews.com/article/elon-musk-britain-riots
  NLI     : e=0.000  c=0.021  src=https://foxbaltimore.com/station/share/musk-slams-
  NLI     : e=0.000  c=0.021  src=https://katv.com/news/nation-world/musk-slams-uk-a

Running text_clip_ocr:  62%|██████▏   | 61/99 [04:29<01:58,  3.12s/it]

  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2026/03/how-iran-blocking-the-stra
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/article/2026/feb/27/iran-economic
  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/2016/04/trumps-foreign-policy-spee
  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/2016/05/rep-jones-didnt-empower-ob
  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/2016/06/trump-wrong-on-iraqi-oil/
  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/fact-check/netanyahu-gaza-2035-plan/
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/article/2026/apr/06/strait-hormuz
  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/2026/03/trump-links-bidens-ukraine
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/article/2023/oct/09/fact-check-tr
  NLI     : e=0.086  c=0.739  src=https://www.theguardian.com/world/live/2024/oct/29
  NLI     : e=0.053  c=0.023  src=https://www.aa.com.tr/en/middle-east/us-deeply-con
  NLI     : e=0.007  c=0.039  src=https://truthout.org/articles/israel-used-us-bomb-
  NLI [FC]: e=0.006  c=0.044  src=https://www.snopes.com/fact-check/trumps-us-gaza-a

Running text_clip_ocr:  63%|██████▎   | 62/99 [04:36<02:35,  4.21s/it]

  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/news/2025/10/28/hamas-ceasefire-viola
  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/news/2021/05/25/tom-cotton-associated
  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/newsletter-archive/snopes-digest-116-
  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/fact-check/gaza-strip-photo/
  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/news/2025/08/11/al-jazeera-anas-al-sh
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2023/11/post-makes-unfounded-claim

Running text_clip_ocr:  64%|██████▎   | 63/99 [04:39<02:17,  3.83s/it]

  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/fact-check/turkey-warship-gaza/
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2014/sep/18/julie-pace
  [FC REJECT] off-topic article: https://www.snopes.com/fact-check/clinton-netanyahu-satire-v
  [FC REJECT] off-topic article: https://www.snopes.com/news/2023/10/16/china-hamas-israel-ga
  NLI     : e=0.999  c=0.000  src=https://www.foxnews.com/world/israeli-airstrikes-c
  NLI     : e=0.053  c=0.001  src=https://www.longwarjournal.org/archives/2024/11/is

Running text_clip_ocr:  65%|██████▍   | 64/99 [04:46<02:53,  4.96s/it]

  NLI     : e=0.005  c=0.030  src=https://www.foxnews.com/us/new-orleans-barricade-o
  NLI     : e=0.002  c=0.001  src=https://www.foxnews.com/us/new-orleans-revelers-na
  NLI     : e=0.037  c=0.007  src=https://apnews.com/article/new-orleans-car-bourbon
  NLI     : e=0.002  c=0.001  src=https://www.pbs.org/newshour/politics/watch-live-f
  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/2026/04/trumps-numbers-april-2026-
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/article/2024/dec/26/a-month-by-mo
  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/location/international/
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2026/02/trump-oversells-recent-u-s
  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/
  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/2026/02/manufacturing-construction
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2025/05/democrats-exaggerate-estim
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/article/2026/jan/20/trump-inflati
  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/2026/02/a-pre-sotu-guide-to-trumps
  NLI     : e=0.007  c=0.002  src=https://www.foxnews.com/world/israel-warns-go-afte
  NLI     : e=0.006  c=0.009  src=https://www.yahoo.com/news/where-ceasefire-talks-b
  NLI     : e=0.002  c=0.000  src=https://www.ntd.com/ntdplus/israel-hezbollah-agree
  [FC REJECT] off-topic article: https://www.politifact.com/

Running text_clip_ocr:  66%|██████▌   | 65/99 [04:50<02:32,  4.50s/it]

  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2025/jan/15/instagram-
  NLI     : e=0.000  c=0.000  src=https://beartrackinn.com/frequently-asked-question
  NLI     : e=0.003  c=0.001  src=https://fullsuitcase.com/kids-pack-plane/
  NLI     : e=0.061  c=0.510  src=https://www.remitly.com/blog/travel/chicago-o-hare
  NLI     : e=0.027  c=0.024  src=http://www.ketchikanmuseums.org/virtual_exhibit/ve

Running text_clip_ocr:  67%|██████▋   | 66/99 [06:20<16:39, 30.30s/it]

  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2012/12/firefighters-fact-checking
  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/2015/07/clinton-spins-immigration-
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2015/11/bogus-meme-targets-trump/
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2019/04/what-kissinger-has-said-ab
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2008/10/lying-about-being-liberal/
  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/2016/07/factchecking-clintons-big-
  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/2020/02/trump-has-condemned-white-
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2012/07/you-didnt-build-that-uncut
  NLI [FC]: e=0.140  c=0.033  src=https://www.factcheck.org/2009/04/here-there-be-pi

Running text_clip_ocr:  68%|██████▊   | 67/99 [06:28<12:31, 23.48s/it]

  NLI [FC]: e=0.025  c=0.012  src=https://www.factcheck.org/2012/08/factcheck-mailba
  NLI     : e=0.022  c=0.024  src=https://prospect.org/2024/03/20/2024-03-20-what-re
  NLI     : e=0.002  c=0.039  src=https://www.nytimes.com/2023/12/04/podcasts/the-da

Running text_clip_ocr:  69%|██████▊   | 68/99 [06:28<08:36, 16.66s/it]

  NLI     : e=0.001  c=0.001  src=https://www.planetary.org/articles/every-picture-f
  [FC REJECT] off-topic article: https://www.snopes.com/tag/astronomy/
  [FC REJECT] off-topic article: https://www.snopes.com/tag/space/?pagenum=2
  NLI     : e=0.004  c=0.101  src=https://9gag.com/gag/aBymp91
  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/fact-check/royal-family-play-monopoly
  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/fact-check/revocation-of-independence

Running text_clip_ocr:  70%|██████▉   | 69/99 [06:29<05:52, 11.76s/it]

  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/article/2024/mar/12/princess-kate
  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/news/2020/12/23/what-history-really-t
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2022/feb/21/facebook-p
  [FC SKIP] only 0 matches (need 2): https://fullfact.org/policy/reports/full-fact-report-2021/
  [FC REJECT] off-topic article: https://www.snopes.com/news/2022/09/08/queen-elizabeth-ii-a-
  [FALLBACK] Using embedding similarity
  TEXT ERROR [Andrew will not join royals for Christma]: name 'embedding_stance_fallback' is not defined
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2014/jul/24/rula-jebre
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2024/apr/22/facebook-p
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2026/apr/13/commonweal
  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/news/2026/03/16/vaccine-for-pedophile
  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/fact-check/stevie-wonder-israel-epste
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/article/2015/sep/02/11-examples-h
  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/fact-check/tunnel-between-rafah-egypt

Running text_clip_ocr:  71%|███████   | 70/99 [06:30<04:11,  8.68s/it]

  NLI     : e=0.002  c=0.001  src=https://www.spacewar.com/reports/Israel_attacks_He
  NLI [FC]: e=0.019  c=0.162  src=https://www.politifact.com/article/2026/apr/02/fac
  NLI [FC]: e=0.005  c=0.930  src=https://www.snopes.com/fact-check/trump-walking-no
  [FC REJECT] off-topic article: https://www.snopes.com/news/2026/04/08/trump-abandon-troops-
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/article/2026/apr/02/fact-checking
  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/news/2023/10/19/israel-warned-al-ahli
  NLI [FC]: e=0.831  c=0.048  src=https://www.snopes.com/fact-check/iran-israeli-f-3
  NLI [FC]: e=0.001  c=0.005  src=https://www.snopes.com/collections/us-israel-war-i
  NLI     : e=0.998  c=0.001  src=https://www.theguardian.com/world/2024/oct/26/idf-
  NLI [FC]: e=0.008  c=0.721  src=https://www.factcheck.org/2023/11/social-media-pos

Running text_clip_ocr:  72%|███████▏  | 71/99 [06:41<04:17,  9.21s/it]

  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2023/feb/28/facebook-p
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2020/12/false-claim-about-bidens-w
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2021/02/factchecking-bidens-town-h
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2020/08/bidens-greatest-hits/
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2020/03/biden-admits-he-was-stoppe
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2020/05/trumps-mysterious-claim-of
  NLI     : e=0.001  c=0.000  src=https://www.npr.org/2024/05/08/1250094064/biden-is
  NLI     : e=0.982  c=0.001  src=https://www.cnn.com/2024/05/08/politics/joe-biden-

Running text_clip_ocr:  73%|███████▎  | 72/99 [06:46<03:39,  8.13s/it]

  NLI     : e=0.000  c=0.000  src=https://www.pbs.org/newshour/politics/biden-says-u
  NLI     : e=0.000  c=0.001  src=https://www.theguardian.com/us-news/article/2024/m

Running text_clip_ocr:  74%|███████▎  | 73/99 [06:53<03:18,  7.63s/it]

  NLI     : e=0.000  c=0.000  src=https://www.foxnews.com/world/isis-increasingly-un
  NLI     : e=0.001  c=0.001  src=https://globalecco.org/-/the-afghan-debacle-causes
  NLI     : e=0.001  c=0.034  src=https://en.wikipedia.org/wiki/United_States_interv
  NLI     : e=0.000  c=0.001  src=http://foreignaffairs.house.gov/getting-answers-on
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/list/?page=95&category
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/list/?page=44&speaker=
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2023/apr/18/facebook-p
  NLI     : e=0.000  c=0.000  src=https://www.scientificamerican.com/article/nasa-rs
  NLI     : e=0.000  c=0.000  src=https://www.nasa.gov/centers-and-facilities/jpl/ho
  NLI     : e=0.000  c=0.000  src=https://www.foxnews.com/tech/nasas-martian-helicop

Running text_clip_ocr:  75%|███████▍  | 74/99 [06:56<02:33,  6.15s/it]

  NLI     : e=0.000  c=0.000  src=https://www.space.com/ingenuity-mars-helicopter-33
  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/2005/12/rnc-web-ad-are-democrats-w
  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/fact-check/vance-trump-hitler-quote/
  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/fact-check/driver-switches-places/
  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/2016/07/trumps-press-conference/
  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/fact-check/make-the-pie-higher/
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/article/2016/may/10/context-hilla
  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/2017/04/100-days-whoppers/
  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/fact-check/rashida-tlaib-bring-jihad/
  NLI     : e=0.017  c=0.024  src=https://www.theguardian.com/world/2024/nov/05/mma-
  NLI     : e=0.013  c=0.337  src=https://nypost.com/2024/11/25/sports/conor-mcgrego
  NLI     : e=0.014  c=0.005  src=https://www.nytimes.com/athletic/6862186/2025/12/0
  NLI     : e=0.001  c=0.005  src=https://www.cbsnews.com/news/conor-mcgregor-rape-i

Running text_clip_ocr:  76%|███████▌  | 75/99 [06:59<02:08,  5.34s/it]

  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/personalities/democrats/
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/article/2026/apr/06/Trump-Iran-Tr
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/list/?category=&ruling
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/article/2026/jan/29/DHS-governmen
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/article/2025/nov/04/trump-governm
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2025/10/lawmakers-health-care-gove

Running text_clip_ocr:  77%|███████▋  | 76/99 [07:05<02:08,  5.57s/it]

  NLI [FC]: e=0.000  c=0.995  src=https://www.politifact.com/factchecks/2022/oct/21/
  NLI     : e=0.071  c=0.249  src=https://www.thedailybeast.com/dems-stunningly-flip
  NLI [FC]: e=0.016  c=0.221  src=https://www.politifact.com/factchecks/list/?speake
  NLI [FC]: e=0.005  c=0.540  src=https://www.politifact.com/personalities/senate-ma
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2016/08/trumps-false-obama-isis-li
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/article/2015/dec/11/war-words-fig
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2015/dec/09/greg-abbot
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2017/jun/01/national-r
  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/news/2017/04/22/counterterrorism-isis

Running text_clip_ocr:  78%|███████▊  | 77/99 [07:11<02:04,  5.67s/it]

  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/fact-check/american-couple-isis-kind/
  [FC REJECT] off-topic article: https://www.politifact.com/article/2015/dec/29/what-citizens
  [FC REJECT] off-topic article: https://www.politifact.com/factchecks/2017/nov/10/michael-mc
  NLI [FC]: e=0.008  c=0.006  src=https://www.politifact.com/factchecks/2015/dec/16/
  NLI     : e=0.001  c=0.000  src=https://www.foxnews.com/us/6-times-isis-has-inspir
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2011/12/the-whoppers-of-2011/
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2012/05/soft-glove-same-gps-fist/
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/article/2025/dec/15/lie-of-the-ye
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2005/10/no-death-penalty-for-hitle
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2018/09/vying-for-veterans-votes-i
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2010/10/court-watch-mudfest-2010/
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2012/04/the-whole-truth-in-wiscons
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2021/01/what-president-biden-inher

Running text_clip_ocr:  79%|███████▉  | 78/99 [07:20<02:17,  6.55s/it]

  NLI [FC]: e=0.002  c=0.016  src=https://www.politifact.com/factchecks/2025/feb/13/
  [FC REJECT] off-topic article: https://www.snopes.com/fact-check/harding-china-poker/
  NLI     : e=0.985  c=0.003  src=https://www.foxbangor.com/news/national/revealed-t
  NLI     : e=0.015  c=0.651  src=https://www.zdnet.com/article/the-10-most-popular-
  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/fact-check/reopened-scottish-railway-
  [FC SKIP] only 1 matches (need 2): https://fullfact.org/online/miscaptioned-video-child-syria-n
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2014/sep/23/steve-sout
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2017/aug/17/tucker-car
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/article/2026/apr/02/Trump-Fired-P
  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/2025/07/maga-ad-distorts-how-massi
  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/2019/08/the-epstein-connections-fu
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/article/2025/jun/05/elon-musk-don
  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/2018/10/misleading-ads-from-leadin
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/article/2026/may/01/diet-soda-hea
  NLI     : e=0.002  c=0.004  src=https://www.jpost.com/israel-news/defense-news/art
  NLI     : e=0.059  c=0.344  src=https://www.youtube.com/watch?v=kEloSTe9ABg
  NLI     : e=0.059  c=0.344  src=https://www.youtube.com/watch?v=a6ZQ7_p52PQ

Running text_clip_ocr:  80%|███████▉  | 79/99 [07:31<02:38,  7.92s/it]

  NLI     : e=0.059  c=0.344  src=https://www.youtube.com/watch?v=1AKVZkRzaUQ
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2025/03/viral-posts-share-phony-le

Running text_clip_ocr:  81%|████████  | 80/99 [07:37<02:22,  7.52s/it]

  NLI [FC]: e=0.002  c=0.024  src=https://www.snopes.com/fact-check/musk-add-pop-sou
  NLI [FC]: e=0.008  c=0.031  src=https://www.snopes.com/fact-check/twitter-like-but
  NLI [FC]: e=0.062  c=0.157  src=https://www.snopes.com/fact-check/elon-musk-rebran
  NLI     : e=0.027  c=0.812  src=https://www.podcastrepublic.net/podcast/1386234384
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2024/jul/12/joe-biden/
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2018/jul/12/donald-tru
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2019/05/trump-17-repeats-in-17-hou
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2018/jul/12/nicholas-b
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2016/apr/19/bernie-san
  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/2020/08/final-night-of-the-republi
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2024/03/factchecking-trumps-fact-c

Running text_clip_ocr:  82%|████████▏ | 81/99 [07:44<02:09,  7.18s/it]

  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2021/aug/26/joe-biden/
  [FC REJECT] off-topic article: https://www.factcheck.org/2011/03/obama-on-war-then-and-now/
  [FC REJECT] off-topic article: https://www.factcheck.org/2018/08/a-rally-filled-with-repeat
  NLI     : e=0.004  c=0.003  src=https://www.yahoo.com/news/happened-nato-defense-b
  NLI     : e=0.003  c=0.001  src=https://www.nato.int/en/what-we-do/introduction-to

Running text_clip_ocr:  83%|████████▎ | 82/99 [07:44<01:26,  5.09s/it]

  [FC SKIP] only 0 matches (need 1): https://fullfact.org/
  [FC SKIP] only 0 matches (need 1): https://www.factcheck.org/
  [FC SKIP] only 0 matches (need 1): https://www.politifact.com/
  [FC SKIP] only 0 matches (need 1): https://fullfact.org/latest/
  [FC SKIP] only 0 matches (need 1): https://fullfact.org/vaccines/
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/
  [FC SKIP] only 0 matches (need 1): https://fullfact.org/immigration/
  [FC SKIP] only 0 matches (need 1): https://fullfact.org/toolkit/
  [FC SKIP] only 0 matches (need 1): https://fullfact.org/training/
  [FC SKIP] only 0 matches (need 1): https://www.snopes.com/top/
  [FC REJECT] off-topic article: https://www.politifact.com/factchecks/2016/dec/28/jeff-brand
  NLI     : e=0.003  c=0.001  src=https://www.mountainpassperformance.com/avoid-brak
  NLI     : e=0.001  c=0.993  src=https://driveteslacanada.ca/model-y/tesla-exonerat

Running text_clip_ocr:  84%|████████▍ | 83/99 [07:54<01:43,  6.50s/it]

  NLI     : e=0.515  c=0.017  src=https://www.cbc.ca/news/canada/sudbury/failed-road
  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/fact-check/israelis-absent-911/
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2024/apr/30/tweets/pho
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/article/2024/sep/11/how-kamala-ha
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2013/nov/27/marco-rubi
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/article/2024/may/10/the-antisemit
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/article/2020/aug/24/ask-politifac
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2015/oct/09/ben-carson
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/article/2025/jun/17/us-israel-ira
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2026/mar/02/tweets/Ira
  NLI [FC]: e=0.024  c=0.481  src=https://www.politifact.com/article/2025/oct/13/Tru
  NLI     : e=0.004  c=0.860  src=https://www.canada.ca/en/canadian-heritage/service
  NLI     : e=0.003  c=0.018  src=https://www.youtube.com/shorts/MaGT7YGer-c
  NLI     : e=0.003  c=0.018  src=https://www.youtube.com/shorts/UHQvV7qjObM

Running text_clip_ocr:  86%|████████▌ | 85/99 [08:03<01:17,  5.57s/it]

  NLI [FC]: e=0.002  c=0.001  src=https://www.politifact.com/factchecks/2019/mar/04/
  NLI     : e=0.193  c=0.010  src=https://apnews.com/article/syria-mass-graves-steph
  NLI     : e=0.003  c=0.000  src=https://www.bbc.co.uk/news/articles/cj90wz8weymo
  NLI     : e=0.001  c=0.000  src=https://en.wikipedia.org/wiki/Mass_graves_in_Syria
  NLI     : e=0.992  c=0.001  src=https://news.meaww.com/joe-bidens-epa-granted-50-m
  NLI     : e=0.996  c=0.001  src=https://www.foxnews.com/politics/biden-epa-granted
  NLI     : e=0.006  c=0.970  src=https://www.theverge.com/news/613135/climate-justi
  NLI     : e=0.004  c=0.014  src=https://wordinblack.com/2024/12/could-pro-palestin

Running text_clip_ocr:  87%|████████▋ | 86/99 [08:07<01:04,  4.97s/it]

  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/list/?category=&ruling
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2026/feb/17/bruce-blak
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2026/feb/13/tom-omara/
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2025/feb/14/elon-musk/
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2016/oct/07/donald-tru
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2022/aug/11/kevin-mcca
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/article/2025/apr/02/elon-musks-mi
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/article/2025/aug/08/trump-new-cen
  NLI     : e=0.000  c=0.001  src=https://sports.yahoo.com/liverpool-ready-unprecede
  NLI     : e=0.000  c=0.001  src=https://www.empireofthekop.com/2025/03/25/liverpoo
  NLI     : e=0.000  c=0.092  src=https://www.sportbible.com/football/football-news/

Running text_clip_ocr:  88%|████████▊ | 87/99 [08:14<01:06,  5.52s/it]

  NLI     : e=0.001  c=0.000  src=https://www.thesun.co.uk/sport/32568118/trent-alex
  NLI     : e=0.688  c=0.006  src=https://azealia-banks.fandom.com/wiki/Feuds

Running text_clip_ocr:  89%|████████▉ | 88/99 [08:14<00:43,  3.92s/it]

  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/news/2025/02/21/ukraine-elections-war
  [FC SKIP] only 1 matches (need 2): https://fullfact.org/politics/trump-zelenskyy-dictator-elect
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/article/2025/aug/18/trump-zelensk
  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/collections/ukraine-russia-war-annive
  [FC REJECT] off-topic article: https://www.snopes.com/fact-check/us-trump-trip-world-leader
  NLI [FC]: e=0.000  c=0.000  src=https://www.snopes.com/fact-check/zelenskyy-say-no
  NLI [FC]: e=0.000  c=0.011  src=https://www.politifact.com/article/2025/feb/28/tru

Running text_clip_ocr:  90%|████████▉ | 89/99 [08:21<00:50,  5.04s/it]

  NLI     : e=0.061  c=0.172  src=https://m.naharnet.com/stories/en/305234-zelensky-

Running text_clip_ocr:  91%|█████████ | 90/99 [08:25<00:41,  4.59s/it]

  NLI     : e=0.286  c=0.021  src=https://www.washingtonexaminer.com/news/2839164/il
  NLI     : e=0.005  c=0.008  src=https://www.cbsnews.com/newyork/news/nypd-officers
  NLI     : e=0.005  c=0.005  src=https://apnews.com/article/fact-check-nypd-protest
  NLI     : e=0.001  c=0.001  src=https://www.foxnews.com/us/nyc-migrants-arrested-a
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/article/2018/jul/05/fact-checking
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/article/2026/mar/05/Kristi-Noem-m
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2025/feb/26/facebook-p
  NLI     : e=0.992  c=0.001  src=https://thepeoplesvoice.tv/russia-releases-2000-pa
  NLI     : e=0.523  c=0.031  src=https://www.linkedin.com/posts/shivam-shukla-b0484

Running text_clip_ocr:  92%|█████████▏| 91/99 [08:29<00:36,  4.55s/it]

  NLI     : e=0.039  c=0.062  src=https://www.theguardian.com/world/2020/feb/22/coro
  NLI [FC]: e=0.148  c=0.065  src=https://www.factcheck.org/2024/06/factchecking-tru
  NLI     : e=0.998  c=0.000  src=https://www.foxnews.com/politics/new-york-gov-kath
  NLI [FC]: e=0.001  c=0.000  src=https://www.politifact.com/factchecks/2025/dec/11/
  NLI     : e=0.000  c=0.000  src=https://abc7ny.com/post/gov-kathy-hochul-unveils-p

Running text_clip_ocr:  93%|█████████▎| 92/99 [08:35<00:33,  4.78s/it]

  NLI     : e=0.998  c=0.000  src=https://www.yahoo.com/news/ny-governor-eyes-change

Running text_clip_ocr:  94%|█████████▍| 93/99 [08:36<00:22,  3.81s/it]

  NLI     : e=0.037  c=0.099  src=https://breakgfw.com/202403/74694.html
  NLI     : e=0.110  c=0.325  src=https://www.sinchew.com.my/news/20240426/nation/55
  NLI     : e=0.065  c=0.076  src=https://www.huaglad.com/zh-tw/lovecn/20240327/5504
  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/fact-check/boyfriend-corpses-medical-
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2025/jan/31/facebook-p
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2022/apr/28/facebook-p
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2019/jan/23/facebook-p
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/list/?page=8&category=
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/article/2023/apr/13/state-legisla
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2024/feb/16/instagram-
  NLI [FC]: e=0.001  c=0.000  src=https://www.politifact.com/factchecks/2022/oct/21/
  NLI     : e=0.999  c=0.000  src=https://www.foxnews.com/us/las-vegas-suspect-ex-gi
  NLI     : e=0.002  c=0.001  src=https://gazette.com/2025/01/02/what-matthew-livels
  NLI     : e=0.013  c=0.016  src=https://www.dailymail.co.uk/news/article-14246183/

Running text_clip_ocr:  95%|█████████▍| 94/99 [08:45<00:26,  5.33s/it]

  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/news/2023/10/19/israel-warned-al-ahli
  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/2023/11/social-media-posts-misrepr
  [FC SKIP] only 1 matches (need 2): https://www.snopes.com/collections/israel-conflicts-rumors-c

Running text_clip_ocr:  96%|█████████▌| 95/99 [08:50<00:20,  5.14s/it]

  NLI [FC]: e=0.000  c=0.007  src=https://www.snopes.com/news/2025/10/28/hamas-cease
  NLI [FC]: e=0.058  c=0.012  src=https://www.snopes.com/articles/465623/oct-7-hamas
  NLI     : e=0.998  c=0.001  src=https://www.euronews.com/2025/04/25/at-least-50-pa
  NLI [FC]: e=0.000  c=0.003  src=https://www.snopes.com/news/2026/02/11/israel-stri
  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/hot-topics/
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2018/mar/16/viralpolit
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/article/2017/dec/12/2017-lie-year
  [FC SKIP] only 1 matches (need 2): https://www.factcheck.org/2018/02/words-trump-russian-meddli
  [FC SKIP] only 0 matches (need 2): https://www.factcheck.org/2018/10/factchecking-trumps-60-min

Running text_clip_ocr:  97%|█████████▋| 96/99 [08:56<00:16,  5.36s/it]

  NLI [FC]: e=0.026  c=0.271  src=https://www.factcheck.org/2018/07/factchecking-rus
  NLI [FC]: e=0.002  c=0.003  src=https://www.factcheck.org/2017/07/trump-spins-puti
  [FC REJECT] off-topic article: https://www.factcheck.org/location/russia/
  NLI     : e=0.046  c=0.734  src=https://www.ukrainefactcheck.org/source/fact-check
  [FC SKIP] only 0 matches (need 2): https://www.snopes.com/fact-check/michelle-obama-harvey-wein
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2019/apr/03/donald-tru
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/article/2016/jan/22/iowa-gantlet-
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/article/2012/oct/19/fact-checking
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/article/2013/feb/15/government-jo
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2011/jan/31/sameh-shou
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2011/sep/05/barack-oba
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/article/2010/jan/13/announcing-po
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2011/oct/06/critics-wa
  NLI     : e=0.004  c=0.000  src=https://www.desertradio.fm/justin-baldoni-hits-bac
  NLI     : e=0.098  c=0.001  src=https://www.vanityfair.com/hollywood/story/blake-l

Running text_clip_ocr:  98%|█████████▊| 97/99 [09:01<00:10,  5.25s/it]

  NLI     : e=0.712  c=0.003  src=https://www.nytimes.com/2024/12/26/opinion/blake-l
  NLI     : e=0.003  c=0.001  src=https://www.bbc.com/news/articles/c9q7pxnr4g2o
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2025/aug/07/tiktok-pos
  [FC SKIP] only 0 matches (need 2): https://www.politifact.com/factchecks/2014/feb/11/hugh-fitzs
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2021/jun/04/tiktok-pos
  NLI     : e=0.135  c=0.006  src=https://www.foxnews.com/entertainment/michelle-pfe
  NLI     : e=0.003  c=0.010  src=https://www.elle.com/culture/movies-tv/a63196619/t
  NLI     : e=0.699  c=0.005  src=https://variety.com/2024/tv/news/michelle-pfeiffer

Running text_clip_ocr:  99%|█████████▉| 98/99 [09:03<00:04,  4.38s/it]

  NLI     : e=0.001  c=0.986  src=https://www.yahoo.com/entertainment/tv/articles/ma
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2024/jul/12/threads-po
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/truth-o-meter/promises/trumpomete
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/article/2023/may/12/ask-politifac
  [FC SKIP] only 1 matches (need 2): https://www.politifact.com/factchecks/2022/apr/28/facebook-p
  NLI     : e=0.497  c=0.025  src=https://www.foxnews.com/entertainment/jay-zs-sexua
  NLI     : e=0.751  c=0.015  src=https://www.tmz.com/2024/12/13/jay-z-diddy-rape-ac
  NLI [FC]: e=0.001  c=0.001  src=https://www.politifact.com/factchecks/2017/may/05/

Running text_clip_ocr: 100%|██████████| 99/99 [09:10<00:00,  5.56s/it]

  NLI [FC]: e=0.028  c=0.367  src=https://www.politifact.com/factchecks/2020/jun/03/
============================================================
MODE: text_clip_ocr
  mode                 text_clip_ocr
  n_total              99
  n_valid              99
  n_error              0
  accuracy             0.5556
  precision_macro      0.766
  recall_macro         0.551
  f1_macro             0.4398

Prediction distribution:
pred
REAL    94
FAKE     5
Name: count, dtype: int64

              precision    recall  f1-score   support

        FAKE       1.00      0.10      0.19        49
        REAL       0.53      1.00      0.69        50

    accuracy                           0.56        99
   macro avg       0.77      0.55      0.44        99
weighted avg       0.76      0.56      0.44        99


Confusion matrix (rows=true, cols=pred):
      FAKE  REAL
FAKE     5    44
REAL     0    50

Per-class correct/total:
  FAKE         5/49  (10%)
  REAL         50/50  (100%)
  Saved: /content/ablation_v2_text_clip_ocr.csv

============================================================
ABLATION SUMMARY (sorted by macro-F1)
         mode  n_valid  accuracy  precision_macro  recall_macro  f1_macro
    text_only       99    0.6465           0.7225        0.6435    0.6107
    text_clip       99    0.5556           0.7660        0.5510    0.4398
text_clip_ocr       99    0.5556           0.7660        0.5510    0.4398

Saved: /content/ablation_v2_summary.csv

In [ ]:
# Run in a separate cell to confirm GPU is active
import torch
print(torch.cuda.is_available())
print(torch.cuda.get_device_name(0))

False

AssertionError: Torch not compiled with CUDA enabled

In [ ]:
# ═══════════════════════════════════════════════════════════════
# FULL ACCURACY EVALUATION — run this as one cell
# ═══════════════════════════════════════════════════════════════

import pandas as pd
from sklearn.metrics import (
    accuracy_score, precision_recall_fscore_support,
    classification_report, confusion_matrix
)
from tqdm import tqdm
from collections import Counter

LABEL_ORDER = ["FAKE", "MISLEADING", "REAL"]


eval_text = [
    {"claim": x["claim"], "label": x["label"], "image_path": None}
    for x in dataset_100
]


df_result, summary, cm, report = evaluate_mode(
    eval_text,
    mode="text_only",
    top_k_text=2,
    per_sample_timeout=45,
    verbose=True,
)

print("\nConfusion matrix (rows=true, cols=pred):")
cm_df = pd.DataFrame(cm, index=LABEL_ORDER, columns=LABEL_ORDER)
print(cm_df)

print("\nPer-class correct/total:")
for lab in LABEL_ORDER:
    sub = df_result[df_result["true"] == lab]
    correct = (sub["pred"] == lab).sum()
    print(f"  {lab:<12} {correct}/{len(sub)}  "
          f"({100*correct/max(len(sub),1):.0f}%)")

df_result.to_csv("/content/eval_text_only_fixed.csv", index=False)
print("\nSaved: /content/eval_text_only_fixed.csv")

Running text_only:   0%|          | 0/100 [00:06<?, ?it/s]

KeyboardInterrupt:

dataset

In [68]:
import json
import os
from collections import Counter

ROOT = "/content/drive/MyDrive/MyFakeNewsProject/IMFND_dataset/XFACTA_extracted"

def load_xfacta():
    dataset = []

    json_files = []

    for folder in ["fake_sample", "real_sample"]:
        json_files += [
            os.path.join(ROOT, folder, f)
            for f in os.listdir(os.path.join(ROOT, folder))
            if f.endswith(".json")
        ]

    for jf in json_files:
        with open(jf, "r") as f:
            data = json.load(f)

        for item in data:
            tweet = item.get("ooc_tweet", {})
            text = tweet.get("text", "")

            label_bool = tweet.get("metadata", {}).get("label", None)

            if label_bool is True:
                label = "REAL"
            elif label_bool is False:
                label = "FAKE"
            else:
                continue

            images = tweet.get("images", [])
            img_path = images[0] if len(images) > 0 else None

            if img_path and img_path.startswith("./"):
                img_path = os.path.join(ROOT, folder, img_path.replace("./", ""))

            dataset.append({
                "claim": text,
                "image_path": img_path,
                "label": label
            })

    return dataset
dataset = load_xfacta()

print("Total:", len(dataset))
print("Labels:", Counter([d["label"] for d in dataset]))

Total: 2005
Labels: Counter({'FAKE': 1005, 'REAL': 1000})

In [69]:
import random
from collections import defaultdict
import os
from PIL import Image

def sample_100(dataset, seed=42):
    random.seed(seed)

    grouped = defaultdict(list)
    for d in dataset:
        grouped[d["label"]].append(d)

    sample = []
    sample += random.sample(grouped["FAKE"], 50)
    sample += random.sample(grouped["REAL"], 50)

    random.shuffle(sample)
    return sample

small_dataset = sample_100(dataset)

print("Selected:", len(small_dataset))

Selected: 100

In [70]:
def verify_images(data):
    valid = []
    missing = []

    for d in data:
        img_path = d["image_path"]

        if img_path and os.path.exists(img_path):
            try:
                Image.open(img_path).verify()
                valid.append(d)
            except:
                missing.append(d)
        else:
            missing.append(d)

    return valid, missing


valid_data, missing_data = verify_images(small_dataset)

print("Valid samples:", len(valid_data))
print("Missing/Corrupt images:", len(missing_data))

Valid samples: 99
Missing/Corrupt images: 1

In [71]:
from collections import Counter

print("Label distribution (VALID ONLY):")
print(Counter([d["label"] for d in valid_data]))

Label distribution (VALID ONLY):
Counter({'REAL': 50, 'FAKE': 49})

In [72]:
final_eval_set = random.sample(
    [d for d in valid_data if d["label"] == "REAL"], 49
) + \
random.sample(
    [d for d in valid_data if d["label"] == "FAKE"], 49
)

In [73]:
final_dataset = valid_data

In [74]:
import json

with open("xfacta_100_eval.json", "w") as f:
    json.dump(final_dataset, f, indent=2)

In [75]:
final_eval_dataset = [
    {
        "claim": d["claim"],
        "image_path": d["image_path"],
        "label": d["label"]
    }
    for d in valid_data
]

In [76]:
sum([1 for d in final_eval_dataset if d["claim"] == ""])

1

In [ ]:
all_outputs, summary_df = run_ablation_suite(
    final_eval_dataset,
    top_k_text=2,

    per_sample_timeout=60
)

NameError: name 'evaluate_mode' is not defined

CREATE DATASET

In [ ]:

print("\n" + "="*65)
print("ABLATION RESULTS — MULTIMODAL DATASET")
print("="*65)
print(f"{'Mode':<18} {'Accuracy':>10} {'Precision':>10} {'Recall':>10} {'F1':>10}")
print("-"*65)
for _, row in summary_df.iterrows():
    print(f"{row['mode']:<18} {row['accuracy']:>10.4f} "
          f"{row['precision_macro']:>10.4f} "
          f"{row['recall_macro']:>10.4f} "
          f"{row['f1_macro']:>10.4f}")
print("="*65)

# ── compare against text-only baseline ──────────────────────────
print("\nComparison vs text-only baseline (no images):")
print(f"  text_only  (no images): accuracy=0.61, f1=0.61")
for _, row in summary_df.iterrows():
    delta_acc = row['accuracy'] - 0.61
    delta_f1  = row['f1_macro'] - 0.61
    sign_acc  = "+" if delta_acc >= 0 else ""
    sign_f1   = "+" if delta_f1  >= 0 else ""
    print(f"  {row['mode']:<18} (with images): "
          f"acc={sign_acc}{delta_acc:+.4f}  f1={sign_f1}{delta_f1:+.4f}")

# ── save everything ──────────────────────────────────────────────
summary_df.to_csv("/content/ablation_summary_multimodal.csv", index=False)
print("\nSaved: /content/ablation_summary_multimodal.csv")

=================================================================
ABLATION RESULTS — MULTIMODAL DATASET
=================================================================
Mode                 Accuracy  Precision     Recall         F1
-----------------------------------------------------------------
text_only              0.6300     0.6394     0.6298     0.6276
text_clip              0.6000     0.6059     0.5986     0.5863
text_clip_ocr          0.5900     0.5946     0.5885     0.5735
=================================================================

Comparison vs text-only baseline (no images):
  text_only  (no images): accuracy=0.61, f1=0.61
  text_only          (with images): acc=++0.0200  f1=++0.0176
  text_clip          (with images): acc=-0.0100  f1=-0.0237
  text_clip_ocr      (with images): acc=-0.0200  f1=-0.0365

Saved: /content/ablation_summary_multimodal.csv

Run full ablation

In [ ]:
def build_chapter4_tables(modes=None, k=3):
    if modes is None:
        modes = ["text_only", "text_clip", "text_clip_ocr"]

    all_summaries, all_best, all_worst = [], [], []

    for mode in modes:
        path = f"/content/ablation_{mode}_full_outputs.csv"
        if not os.path.exists(path):
            print(f"  Missing: {path}")
            continue
        df = pd.read_csv(path)

        y_true = df["true"].astype(str)
        y_pred = df["pred"].astype(str)
        acc = accuracy_score(y_true, y_pred)
        p, r, f1, _ = precision_recall_fscore_support(
            y_true, y_pred, labels=LABEL_ORDER, average=None, zero_division=0
        )
        row = {"mode": mode, "n_valid": len(df), "accuracy": float(acc), "f1_macro": float(f1.mean())}
        for i, lab in enumerate(LABEL_ORDER):
            row[f"recall_{lab}"] = float(r[i])
        all_summaries.append(row)

        df["correct"] = y_pred == y_true
        use_cols = [c for c in ["claim", "true", "pred", "confidence", "explanation"] if c in df.columns]
        best = df[df["correct"]].sort_values("confidence", ascending=False).head(k)[use_cols].copy()
        worst = df[~df["correct"]].sort_values("confidence", ascending=False).head(k)[use_cols].copy()
        best["mode"] = worst["mode"] = mode
        all_best.append(best)
        all_worst.append(worst)

    summary_df = pd.DataFrame(all_summaries).sort_values("f1_macro", ascending=False).reset_index(drop=True)
    best_df = pd.concat(all_best, ignore_index=True) if all_best else pd.DataFrame()
    worst_df = pd.concat(all_worst, ignore_index=True) if all_worst else pd.DataFrame()

    summary_df.to_csv("/content/ch4_ablation_summary_tables.csv", index=False)
    best_df.to_csv("/content/ch4_ablation_best_examples.csv", index=False)
    worst_df.to_csv("/content/ch4_ablation_worst_examples.csv", index=False)

    print("=== Chapter 4 Summary ===")
    print(summary_df.to_string(index=False))
    return summary_df, best_df, worst_df


# ── Example usage ────────────────────────────────────────────
if __name__ == "__main__":
    eval_data = [
        {"claim": "NASA confirms water on Mars",    "label": "MISLEADING", "image_path": None},
        {"claim": "Smoking causes lung cancer",     "label": "REAL",       "image_path": None},
        {"claim": "The Earth is flat",              "label": "FAKE",       "image_path": None},
    ]

    all_outputs, summary_df = run_ablation_suite(eval_data, top_k_text=2, per_sample_timeout=45)
    print(summary_df)

In [ ]:
def best_worst_examples(df, mode, k=3):
    df = df[df["pred"].astype(str) != "ERROR"].copy()
    if len(df) == 0:
        return pd.DataFrame(), pd.DataFrame()
    df["correct"] = df["pred"].astype(str) == df["true"].astype(str)
    conf_col = "confidence" if "confidence" in df.columns else None
    use_cols = [c for c in [
        "claim", "true", "pred", "confidence",
        "evidence_texts", "explanation", "image_status", "clip_sim_raw", "ocr_len"
    ] if c in df.columns]
    # Best = correct & highest confidence
    best = df[df["correct"]].copy()
    if conf_col:
        best = best.sort_values("confidence", ascending=False)
    best = best.head(k)[use_cols].reset_index(drop=True)
    # Worst = incorrect & highest confidence
    worst = df[~df["correct"]].copy()
    if conf_col:
        worst = worst.sort_values("confidence", ascending=False)
    worst = worst.head(k)[use_cols].reset_index(drop=True)
    best["mode"] = mode
    worst["mode"] = mode
    return best, worst
all_summaries = []
all_best = []
all_worst = []
for mode in modes:
    path = f"/content/ablation_{mode}_full_outputs.csv"
    if not os.path.exists(path):
        print(f"Missing: {path}")
        continue
    df = pd.read_csv(path)
    all_summaries.append(make_summary_row(df, mode))
    best, worst = best_worst_examples(df, mode, k=3)
    all_best.append(best)
    all_worst.append(worst)
summary_df = pd.DataFrame(all_summaries).sort_values("f1_macro", ascending=False).reset_index(drop=True)
best_examples_df = pd.concat(all_best, ignore_index=True) if all_best else pd.DataFrame()
worst_examples_df = pd.concat(all_worst, ignore_index=True) if all_worst else pd.DataFrame()
# Save thesis artifacts
summary_path = "/content/ch4_ablation_summary_tables.csv"
best_path = "/content/ch4_ablation_best_examples.csv"
worst_path = "/content/ch4_ablation_worst_examples.csv"
summary_df.to_csv(summary_path, index=False)
best_examples_df.to_csv(best_path, index=False)
worst_examples_df.to_csv(worst_path, index=False)
print("=== Chapter 4 Summary Table ===")
display(summary_df)
print("\nSaved:")
print(summary_path)
print(best_path)
print(worst_path)
print("\n=== Best Examples (highest confidence, correct) ===")
display(best_examples_df.head(12))
print("\n=== Worst Examples (highest confidence, wrong) ===")
display(worst_examples_df.head(12))

=== Chapter 4 Summary Table ===

,mode,n_valid,accuracy,f1_macro,recall_FAKE,recall_MISLEADING,recall_REAL
0,text_only,3,0.333333,0.166667,0.0,1.0,0.0
1,text_clip,3,0.333333,0.166667,0.0,1.0,0.0
2,text_clip_ocr,3,0.333333,0.166667,0.0,1.0,0.0

Saved:
/content/ch4_ablation_summary_tables.csv
/content/ch4_ablation_best_examples.csv
/content/ch4_ablation_worst_examples.csv

=== Best Examples (highest confidence, correct) ===

,claim,true,pred,confidence,evidence_texts,explanation,image_status,clip_sim_raw,ocr_len,mode
0,NASA confirms water on Mars,MISLEADING,MISLEADING,0.00,"""This makes it sound like we announced that we...",Claim: NASA confirms water on Mars\n\nTop evid...,skipped,0.000000,0,text_only
1,NASA confirms water on Mars,MISLEADING,MISLEADING,15.42,"""This makes it sound like we announced that we...",Claim: NASA confirms water on Mars\n\nTop evid...,url_ok,0.233853,0,text_clip
2,NASA confirms water on Mars,MISLEADING,MISLEADING,15.42,"""This makes it sound like we announced that we...",Claim: NASA confirms water on Mars\n\nTop evid...,url_ok,0.233853,0,text_clip_ocr

=== Worst Examples (highest confidence, wrong) ===

,claim,true,pred,confidence,evidence_texts,explanation,image_status,clip_sim_raw,ocr_len,mode
0,Smoking causes lung cancer,REAL,MISLEADING,0.0,Cancer Mythbusters: Smoking and Lung Cancer Yo...,Claim: Smoking causes lung cancer\n\nTop evide...,skipped,0.0,0,text_only
1,The Earth is flat,FAKE,MISLEADING,0.0,"Experts told Reuters that the idea, which orig...",Claim: The Earth is flat\n\nTop evidence:\n1. ...,skipped,0.0,0,text_only
2,Smoking causes lung cancer,REAL,MISLEADING,12.5,Cancer Mythbusters: Smoking and Lung Cancer Yo...,Claim: Smoking causes lung cancer\n\nTop evide...,no_image,0.0,0,text_clip
3,The Earth is flat,FAKE,MISLEADING,12.5,"Experts told Reuters that the idea, which orig...",Claim: The Earth is flat\n\nTop evidence:\n1. ...,no_image,0.0,0,text_clip
4,Smoking causes lung cancer,REAL,MISLEADING,12.5,Cancer Mythbusters: Smoking and Lung Cancer Yo...,Claim: Smoking causes lung cancer\n\nTop evide...,no_image,0.0,0,text_clip_ocr
5,The Earth is flat,FAKE,MISLEADING,12.5,"Experts told Reuters that the idea, which orig...",Claim: The Earth is flat\n\nTop evidence:\n1. ...,no_image,0.0,0,text_clip_ocr

In [ ]:
# Save all outputs to Google Drive so they survive runtime restarts
import shutil

files_to_save = [
    "/content/ablation_v2_text_only.csv",
    "/content/ablation_v2_text_clip.csv",
    "/content/ablation_v2_text_clip_ocr.csv",
    "/content/ablation_v2_summary.csv",
]

for f in files_to_save:
    try:
        dest = f.replace("/content/", "/content/drive/MyDrive/")
        shutil.copy(f, dest)
        print(f"Saved to Drive: {dest}")
    except Exception as e:
        print(f"Failed: {f} — {e}")